[Draft] Nearest Neighbor module
intel-isl/Open3D pull request #2207
Opened 2020-08-20 00:10 UTC by junha-l

Initial pull requests for implementing NearestNeighbor Class.

### Functionality

For every search type, the search is performed on CPU using NanoFlann.
Every search type supports batch mode.

- KnnSearch

- DynamicRadiusSearch

- FixedRadiusSearch

- HybridSearch

- UnitTests

### To Do

- [ ] Parallelize search using tbb

- [ ] Template class

- [ ] Python bindings

- [ ] Python test script

2020-08-20 00:13 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlann.cpp  23
- cpp/open3d/core/nn/NanoFlann.h  1
- cpp/tests/core/NearestNeighbor.cpp  40
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-20 03:05 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/core/nn/NanoFlann.h  1
- cpp/tests/core/NanoFlann.cpp  23
- cpp/tests/core/NearestNeighbor.cpp  40
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-20 07:39 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NearestNeighbor.cpp  40
- cpp/tests/core/NanoFlann.cpp  23
- cpp/open3d/core/nn/NanoFlann.h  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-20 09:27 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NearestNeighbor.cpp  40
- cpp/open3d/core/nn/NanoFlann.h  1
- cpp/tests/core/NanoFlann.cpp  23
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-20 09:55 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlann.cpp  23
- cpp/tests/core/NearestNeighbor.cpp  40
- cpp/open3d/core/nn/NanoFlann.h  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-20 12:19 UTC, benjaminum requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2207)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @benjaminum, @junha-l, and @yxlao)

___
*[cpp/open3d/core/nn/NanoFlann.h, line 65 at r3](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFAllqg2GpOVwOXJHCe:-MFAllqg2GpOVwOXJHCf:b4mzdgt) ([raw file](https://github.com/intel-isl/open3d/blob/a1bb09c197ff73602ace3643daa3b2484978c168/cpp/open3d/core/nn/NanoFlann.h#L65)):*
> ```objc
> 
> template <int METRIC, class T>
> struct SelectNanoflannAdaptor {};
> ```

This is very specific for this class and can probably be moved to an anonymous namespace in the cpp file.
___
*[cpp/open3d/core/nn/NanoFlann.h, line 108 at r3](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFAkgHW90bmlL5tUYlH:-MFAkgHW90bmlL5tUYlI:bf5uhdv) ([raw file](https://github.com/intel-isl/open3d/blob/a1bb09c197ff73602ace3643daa3b2484978c168/cpp/open3d/core/nn/NanoFlann.h#L108)):*
> ```objc
> 
> protected:
>     std::vector<double> data_;
> ```

Can we change this to Tensor? This way we can avoid a copy in the future.
___
*[cpp/open3d/core/nn/NanoFlann.cpp, line 43 at r3](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFAmUz03VJ9Z_Uw5rM5:-MFAmUz03VJ9Z_Uw5rM6:b-6f3pm) ([raw file](https://github.com/intel-isl/open3d/blob/a1bb09c197ff73602ace3643daa3b2484978c168/cpp/open3d/core/nn/NanoFlann.cpp#L43)):*
> ```cpp
>     core::Dtype dtype = data.GetDtype();
>     if (shape.size() != 2) {
>         utility::LogWarning(
> ```

I think LogError is also OK here. We also have errors in the search functions.
___
*[cpp/tests/CMakeLists.txt, line 43 at r3](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFAnEZX3S7fCLo59avQ:-MFAnEZX3S7fCLo59avR:b-1e4qo6) ([raw file](https://github.com/intel-isl/open3d/blob/a1bb09c197ff73602ace3643daa3b2484978c168/cpp/tests/CMakeLists.txt#L43)):*
> ```CMake
> 
> find_package(Threads)
> find_package(nanoflann REQUIRED)
> ```

Just a comment. The way we find nanoflann will change but we can address this in another PR.


<!-- Sent from Reviewable.io -->

2020-08-21 05:12 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/core/nn/NanoFlann.h  1
- cpp/tests/core/NearestNeighbor.cpp  40
- cpp/tests/core/NanoFlann.cpp  23
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-25 06:19 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NearestNeighbor.cpp  40
- cpp/open3d/core/NanoFlann.h  1
- cpp/tests/core/NanoFlann.cpp  23
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-25 06:45 UTC, yxlao commented
merged master and pushed a commit that enabled nanoflann as the global open3d dependency, like other 3rd party libraries

2020-08-25 06:46 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NearestNeighbor.cpp  40
- cpp/tests/core/NanoFlann.cpp  23
- cpp/open3d/core/NanoFlann.h  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-25 14:30 UTC, junha-l reviewed
> Reviewed 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2207)* status: 1 of 9 files reviewed, 18 unresolved discussions (waiting on @benjaminum, @junha-l, and @yxlao)

___
*[cpp/open3d/core/CMakeLists.txt, line 63 at r10](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFZNarm3SEW29prL0vA:-MFa-mPO2SLpJ75oM25H:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/97f51e128ba947832d671248f37a7dbd58053e9f/cpp/open3d/core/CMakeLists.txt#L63)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

rename to `CORE_NNS_SRC`.

I would prefer the name `nns` (nearest neighbor search), because `nn` can be confused with "neural network" for some PyTorch or TF users (`torch.nn` and `tf.nn`)
</blockquote></details>

Done.
___
*[cpp/open3d/core/CMakeLists.txt, line 64 at r10](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFZNe-cEv38PGcaCDup:-MFa-nE_Br7PpfLyBeS7:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/97f51e128ba947832d671248f37a7dbd58053e9f/cpp/open3d/core/CMakeLists.txt#L64)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

move this files to a `nns` subdirectory, such that the namespace is consistent, i.e.
`open3d::core::nns::Myclass` should be located in `src/open3d/core/nns/MyClass.h`.
</blockquote></details>

Done.
___
*[cpp/tests/CMakeLists.txt, line 43 at r3](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFAnEZX3S7fCLo59avQ:-MFa0V1EDT1ySWLw2gR_:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a1bb09c197ff73602ace3643daa3b2484978c168/cpp/tests/CMakeLists.txt#L43)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

this can be address in:
1) Commit: https://github.com/intel-isl/Open3D/pull/2207/commits/97f51e128ba947832d671248f37a7dbd58053e9f (already in this branch)
2) do not use `nanoflann.hpp` in open3d headers, this allows the user of Open3D to avoid including nanoflann headers
3) remove the nanoflann related cmake statements here

</blockquote></details>

Done.
___
*[cpp/open3d/core/NanoFlann.h, line 1 at r10](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFZPq6d8FsGmvBwRdTG:-MFa-pPm9UKnxNBdtWdL:bka12ec) ([raw file](https://github.com/intel-isl/open3d/blob/97f51e128ba947832d671248f37a7dbd58053e9f/cpp/open3d/core/NanoFlann.h#L1)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

the name of this file can be confusing, as we already have `nanoflann.hpp`. 
perhaps, we could consider renaming it to `NanoFlannAdapter.h`?
</blockquote></details>

Done.
I renamed it as NanoFlannIndex.h since it is more accurate.
___
*[cpp/open3d/core/NanoFlann.h, line 30 at r10](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFZPSny9pYIPdN4q8a6:-MFa0CaECwukmOhV2Js3:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/97f51e128ba947832d671248f37a7dbd58053e9f/cpp/open3d/core/NanoFlann.h#L30)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We should try to avoid using 3rdparty library headers in open3d headers. In this way, a library that links Open3D, such as the unit test, does not need to have the nanoflann headers as well. This can generally be achieved by forward declarations and shared/unique pointers. 

If avoiding `nanoflann.hpp` is not possible or difficult, the fallback solution is to avoid this header being used in `Open3D.h` and avoid including this header in the unit test.
</blockquote></details>

Done.
___
*[cpp/open3d/core/NanoFlann.h, line 60 at r10](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFZSCvE8-z8bOnt6dtK:-MFa0HEKBKfkmJQmAgiz:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/97f51e128ba947832d671248f37a7dbd58053e9f/cpp/open3d/core/NanoFlann.h#L60)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

use `_` for members, such as `num_points_`
</blockquote></details>

Done.
___
*[cpp/open3d/core/NanoFlann.h, line 81 at r10](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFZQYt74Oy19KMVu2uK:-MFa0JPvAFjIlfTTLlzP:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/97f51e128ba947832d671248f37a7dbd58053e9f/cpp/open3d/core/NanoFlann.h#L81)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

This class name can also be confusing:`NanoFlann::` and `nanoflann::` looks similar but they are quite different. Could we consider renaming this class?
</blockquote></details>

Done.
___
*[cpp/open3d/core/NearestNeighbor.h, line 29 at r10](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFZRwDn0j5aQIm-xgf-:-MFa0O8sBUmHP6A52kvy:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/97f51e128ba947832d671248f37a7dbd58053e9f/cpp/open3d/core/NearestNeighbor.h#L29)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove `iostream` and use our own logging methods
</blockquote></details>

Done.
___
*[cpp/open3d/core/NearestNeighbor.h, line 47 at r10](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFZS2gr2AI2z_v2AOzy:-MFa0Oiu2udrM8rL2gXQ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/97f51e128ba947832d671248f37a7dbd58053e9f/cpp/open3d/core/NearestNeighbor.h#L47)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`const core::Tensor &tensor` -> `const core::Tensor &data`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-25 14:30 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NearestNeighbor.cpp  40
- cpp/tests/core/NanoFlannIndex.cpp  23
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-25 14:43 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NearestNeighbor.cpp  40
- cpp/tests/core/NanoFlannIndex.cpp  23
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-26 12:50 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NearestNeighbor.cpp  16
- cpp/tests/core/NanoFlannIndex.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-26 13:44 UTC, junha-l reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2207)* status: 1 of 9 files reviewed, 18 unresolved discussions (waiting on @benjaminum, @junha-l, and @yxlao)

___
*[cpp/tests/core/NanoFlann.cpp, line 61 at r10](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFZW7T59Y8uYP-nh-70:-MFf-neN-KI-bjXc_jQU:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/97f51e128ba947832d671248f37a7dbd58053e9f/cpp/tests/core/NanoFlann.cpp#L61)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Sorry for the confusion, the `Rand` approach for unit test is actually deprecated. You can refer to `cpp/tests/core/Tensor.cpp` to see our current way for unit test.

In summary,
- Step 1: identify what we want to test: test basic functionality? test corner case? etc.
- Step 2: hand-design small inputs (e.g. for a simple example, instead of `knn=30` use `k = 2` and/or `k = 3`, also reduce the input points to say 5-10 points)
- Step 3: derive the expected results manually, the small input size in step 1 makes it possible to derive the results by hand
- Step 4: test the expected result is the same as actual result

In this way, the unit tests:
- can be more simple
- have results that are more interpretable
- can be designed to test corner case explicitly, here are some ideas:
    - wrong inputs like k == 0 or k == -1
    - what happens if the number of points is smaller than k? will the algorithm still work or will it throw an exception? 
    - what happens if some distances the same? what are the rules to break a tie?
    - can we handle overlapping points correctly?
    - did we correctly throw an exception if dtype is not matching?
    - ...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-27 11:32 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NearestNeighbor.cpp  16
- cpp/tests/core/NanoFlannIndex.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-27 11:38 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  6
- cpp/tests/core/NearestNeighbor.cpp  16
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-27 11:44 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  6
- cpp/tests/core/NearestNeighbor.cpp  16
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-27 11:45 UTC, junha-l reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2207)* status: 3 of 9 files reviewed, 43 unresolved discussions (waiting on @benjaminum, @junha-l, and @yxlao)

___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 117 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFihLqtDSR4ee7QfrlG:-MFjhcAE5CN1pOnmbqjt:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L117)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

mention the expected shape, e.g. must be 2D, with shape `{n, d}`.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 118 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFif23h3P8B16ZtJ1wq:-MFjheOw4fX048DfmdCa:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L118)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

After re-thinking about the namings, i think we can have more informative function names and variable names. In fact, the name `Tensor` and `Data` are not very informative, for example, in`SetTensorData`, it is not clear:

1. is this tensor a query tensor, or dataset tensor?
2. should the tensor be one tensor or multiple tensors?

We can have the following naming conventions:

- Instead of "tensor", use "point" for one point (shape `{d}`) and "points" for multiple points (shape `{n, d}`).
- Be explicit about "dataset" points and "query" points

For example, 
```cpp
bool SetTensorData(const core::Tensor &data);
```
will become:
```cpp
bool SetDatasetPoints(const core::Tensor &dataset_points);
```

We can apply this naming convention to the rest of the code, to make everything consistent.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 121 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFihILp-c15ypWsnRk2:-MFjhf6cENX7QIKJ4Kf8:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L121)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

mention the expected shape, e.g. must be 2D, with shape `{n, d}`.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 122 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFij9jw4UpOX8W5vIK9:-MFjhgNoAM_bkXy1qbcV:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L122)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add `\return` comment to describe the return tensors and their shapes.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 123 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFihEEP3DdmzqMUnIVa:-MFjhkdx0aLYmpORM_Ko:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L123)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

rename to `const core::Tensor &query_points` since the input should be shape `{n, d}`
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 127 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFihxge6hdQmkx74b6K:-MFjhlyB-PXnIn8nV5U3:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L127)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

mention the shape.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 128 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFijIpo4sYDStVFug0Q:-MFjhnV3-mJidoRGL9uf:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L128)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add `\return` comment to describe the return tensors and their shapes.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 130 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFihavl9TerNKfwMpDU:-MFjiTGv9WLwHqfdn4zN:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L130)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

- same: `query_points`
- why `double *radii`? can we do `const std::vector<double>& radii)`?
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 133 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFihvdJDurR6a67wQkh:-MFjiV1m4iHqpJPk_Pid:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L133)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

mention the shape.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 134 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFijJSJ9R1ud4hUVtdi:-MFjiW2B8A4PmIqi0Eqg:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L134)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add `\return` comment to describe the return tensors and their shapes.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 136 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFihuWJ5VPMO-lHjS6h:-MFjiXFa6LY8ELDRZEeS:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L136)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`query_points`
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 139 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFii5XT1MQKQAg2_q3m:-MFjiZ5U257sd6NlzGpB:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L139)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we can call it `dataset_points_`
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 142 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFiiHQ_3yizY_idXEa8:-MFjiaHl8BshxoIQ9GTB:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L142)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Redundant, typically we don't store information that can be directly derived from each other. For example, `Tensor` does not store `device_` since `Tensor::blob_::device_` has the information already.

Create a function called `GetDimension() const` that returns `dataset_points_.shape[1]`
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.h, line 143 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFiiRfF53dcDG1o4ow_:-MFjicS63G1vv5JBB7Tp:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.h#L143)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

redundant, create a function called `GetDatasetSize() const` that returns `dataset_points_.shape[0]`
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 48 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFi [...]

2020-08-27 12:15 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones added
============
- cpp/tests/core/NearestNeighbor.cpp  16
- cpp/tests/core/NanoFlannIndex.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-27 12:16 UTC, junha-l reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2207)* status: 3 of 9 files reviewed, 43 unresolved discussions (waiting on @benjaminum and @yxlao)

___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 102 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFisjgy747D68Sr41At:-MFjjCCT8Qy1NT5L6zS6:b-7secf7) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.cpp#L102)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

what will be the possible values for `num_results`? what happens if it is smaller than `k`? in this case, how do we know in the `result_indices` and `result_distances` corresponds to which input?
</blockquote></details>

There are two possible cases.
1. if the size_of_dataset > = k, num_results = k
2. if the size_of_dataset < k, num_results = size_of_dataset

For either cases, the single_indices and single_distances should have the same size, num_results, for every query point.
So I used global num_results variable, rather than accumulate all num_results.

Now I changed it to accumulate all num_results, as in SearchRadius, and check if all entries in the accumulated num_results are the same. If there are different value, LogError.
 
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 113 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFiqqpNC8xHLsM4vBLr:-MFjlKZR3x9XN22n6n34:b3zyg4q) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.cpp#L113)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

looks like `num_results` corresponds to each query point, i.e. we're not accumulating the total num_results, why do we do global num_results < 1?
</blockquote></details>

As mentioned above, num_results must be exactly the same for every query. 
So I used global variable rather than accumulating all num_results.
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 120 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFisrJ20GKpB9fN0Fxg:-MFjlcqB28Biaau1uvsK:b-1t2kem) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.cpp#L120)):*
> There are two possible cases.
> 1. if the size_of_dataset > = k, num_results = k
> 2. if the size_of_dataset < k, num_results = size_of_dataset
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 144 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFitOCu9TaJ69k_OjFL:-MFjq7NtDLVm8aRr15Nm:b-g04je0) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NanoFlannIndex.cpp#L144)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

> ```
> std::vector<size_t> result_nums;
> ```
do we also want this for KNN search? in KNN, we only have a single number of result.
</blockquote></details>

Yes. I added it.
___
*[cpp/open3d/core/nns/NearestNeighbor.h, line 63 at r12](https://reviewable.io/reviews/intel-isl/open3d/2207#-MFithmbA6gqxm0ilCid:-MFjj9_r2ddSTqAweLRi:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0cbefe2cfafdef24dcda6422b528eb10a9e41cc1/cpp/open3d/core/nns/NearestNeighbor.h#L63)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Please update:
1) variable names
2) function names
3) docstrings
according to the comments in nanoflannindex.h.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-27 12:22 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NanoFlannIndex.cpp  6
- cpp/tests/core/NearestNeighbor.cpp  16
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-28 09:03 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NearestNeighbor.cpp  16
- cpp/tests/core/NanoFlannIndex.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-30 10:26 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NearestNeighbor.cpp  16
- cpp/tests/core/NanoFlannIndex.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-30 11:18 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/core/NearestNeighborSearch.cpp  18
- cpp/tests/core/NanoFlannIndex.cpp  4
- cpp/tests/test_utility/Compare.cpp  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6042269&bid=19797932)

2020-08-30 11:52 UTC, merged