Support CPU/GPU hashmap
intel-isl/Open3D pull request #2226
Opened 2020-08-24 22:00 UTC by theNded

Initial PR with pybind. 
- [x] Highly efficient GPU hash table
- [x] Placeholder CPU hash table, to be improved with SIMD in the next iteration.
- [x] Pybind with default hash functions and equations
- [ ] More error check and comments
- [ ] Tensor interface for iterators after #2208 #2195 are merged.

2020-08-24 22:04 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  4
         

Clones added
============
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  3
- cpp/tests/core/Hashmap.cpp  12
- cpp/open3d/core/hashmap/Hashmap.h  1
- cpp/pybind/core/hashmap.cpp  12
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  2
- cpp/open3d/core/hashmap/CPU/HashmapCPU.hpp  4
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  2
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  3
- python/test/core/test_hashmap.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-01 01:44 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  8
         

Clones added
============
- cpp/pybind/core/hashmap.cpp  13
- cpp/open3d/core/hashmap/Hashmap.h  1
- cpp/open3d/core/hashmap/CPU/HashmapCPU.hpp  4
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  2
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  3
- python/test/core/test_hashmap.py  5
- cpp/tests/core/Hashmap.cpp  15
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  2
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-01 03:01 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  8
         

Clones added
============
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  3
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  2
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  2
- cpp/open3d/core/hashmap/Hashmap.h  1
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  3
- python/test/core/test_hashmap.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-01 09:24 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  8
         

Clones added
============
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  3
- python/test/core/test_hashmap.py  5
- cpp/open3d/core/hashmap/CPU/HashmapCPU.hpp  4
- cpp/open3d/core/hashmap/Hashmap.h  1
- cpp/tests/core/Hashmap.cpp  15
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  2
- cpp/pybind/core/hashmap.cpp  13
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  3
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-03 02:10 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  8
         

Clones added
============
- cpp/tests/core/Hashmap.cpp  15
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  3
- cpp/open3d/core/hashmap/CPU/HashmapCPU.hpp  4
- python/test/core/test_hashmap.py  5
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  2
- cpp/open3d/core/hashmap/Hashmap.h  1
- cpp/pybind/core/hashmap.cpp  13
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  2
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-04 11:49 UTC, yxlao requested changes
Part I review, only reviewed framework and CPU;
CUDA part will be next

> Reviewed 6 of 23 files at r1, 6 of 12 files at r2, 2 of 6 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2226#-:-MGNwaYr8kbcVjpyQ1Tn:b-nu3192)* status: 17 of 25 files reviewed, 40 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/Tensor.h, line 445 at r3](https://reviewable.io/reviews/intel-isl/open3d/2226#-MG7xmZM-rtPYV4YD9vJ:-MG7xmZM-rtPYV4YD9vK:bb7phvt) ([raw file](https://github.com/intel-isl/open3d/blob/41e768d98fdb4b4388cd1d35ca96de58454c0367/cpp/open3d/core/Tensor.h#L445)):*
> ```objc
>     }
> 
>     /// Adds a tensor andp returns the resulting tensor.
> ```

typo
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 35 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNhlha1qxXMbp4YDoT:-MGNhlha1qxXMbp4YDoU:bo3a6ki) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/DeviceHashmap.h#L35)):*
> ```objc
> namespace open3d {
> namespace core {
> constexpr size_t kDefaultElemsPerBucket = 4;
> ```

put this in the macro header? (e.g. traits.h)
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 41 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNl_no0_wlnv_On7dz:-MGNl_no0_wlnv_On7e-:b9jwhcw) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/DeviceHashmap.h#L41)):*
> ```objc
>     // key_size_ before calling operator().
>     DefaultHash() {}
>     DefaultHash(size_t key_size) : key_size_in_int_(key_size / sizeof(int)) {}
> ```

what happens, if key_size is smaller than `sizeof(int)`? e.g. uint8. If were are not supporting it, at least we should throw an exception.
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 83 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGIGuKO7ZaSPT5sRT30:-MGIGuKO7ZaSPT5sRT31:b-1r01ml) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/DeviceHashmap.h#L83)):*
> ```objc
> /// Base class: shared interface
> template <typename Hash = DefaultHash, typename KeyEq = DefaultKeyEq>
> class DeviceHashmap {
> ```

shall `DeviceHashmap` inherit `Hashmap`?
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 184 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNnhqF-VDeoIF5RwW1:-MGNnhqF-VDeoIF5RwW2:bnpx81m) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/DeviceHashmap.h#L184)):*
> ```objc
> /// bucket_count.
> template <typename Hash, typename KeyEq>
> std::shared_ptr<DeviceHashmap<Hash, KeyEq>> CreateDeviceHashmap(
> ```

i couldn't find the definition of this function, same for the other `CreateDeviceHashmap`
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 188 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNmqDB6D0F-efve-JX:-MGNmqDB6D0F-efve-JY:b-up2aer) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/DeviceHashmap.h#L188)):*
> ```objc
>         size_t dsize_key,
>         size_t dsize_value,
>         Device device);
> ```

in pybind, you're using const Device&, let's be consistent in general
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 206 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNnrfO-WPSdU-xp1Pm:-MGNnrfO-WPSdU-xp1Pn:b-j0p6z4) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/DeviceHashmap.h#L206)):*
> ```objc
> /// User-friendly interface: just roughly estimate capacity, we handle
> /// bucket_count.
> std::shared_ptr<DefaultDeviceHashmap> CreateDefaultDeviceHashmap(
> ```

this is declared in `DeviceHAshmap.h` but defined in `Hashmap.cpp`, it would be the best if the file names match. same for the other factory functions.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 43 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNciuH8F7oFewTXWMP:-MGNciuI1LnjowoO-KYw:b-4doum3) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L43)):*
> ```objc
>             Device device);
> 
>     Hashmap(size_t init_capacity,
> ```

let's put this one first, as it is for the user.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 48 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNcn2Y1_m94LNJfQhs:-MGNcn2Y1_m94LNJfQht:by9h0je) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L48)):*
> ```objc
>             Device device);
> 
>     ~Hashmap(){};
> ```

`virtual ~Hashmap(){}`(add `virtual` and without `;`)
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 51 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNd536B3O7UVBMXKZ9:-MGNd536B3O7UVBMXKZA:b-51fqjh) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L51)):*
> ```objc
> 
>     /// Rehash expects extra memory space at runtime, since it consists of
>     /// 1) dumping all key value pairs to a buffer
> ```

are we doing `1) -> 4) -> 2) -> 3)`? this may decrease memory usage.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 57 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNdo2QDZfIOa1jqMZT:-MGNdo2QDZfIOa1jqMZU:b-ne6b0o) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L57)):*
> ```objc
>     void Rehash(size_t buckets);
> 
>     /// Parallel insert contiguous arrays of keys and values.
> ```

Since the user is already passing `void *` keys, we don't need to emphasize the "contiguous" array of keys, as that is already implied when passing a buffer. IMHO, stating contiguous here can be initially confusing to the user.

When the user passes Tensor, then we should emphasize "contiguous tensor".
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 60 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGHDh7T9UEgGrwg5Tu-:-MGHDh7T9UEgGrwg5Tu0:b9c9oa7) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L60)):*
> ```objc
>     /// Output iterators and masks can be nullptrs if return iterators are not
>     /// to be processed.
>     void Insert(const void* input_keys,
> ```

shall we have an interface for tensors? can be done in a separate PR.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 62 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGHHbjv6LXPFbllOLvP:-MGHHbjwCsB_HY-T59TN:bdbgsd7) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L62)):*
> ```objc
>     void Insert(const void* input_keys,
>                 const void* input_values,
>                 iterator_t* output_iterators,
> ```

at insert, why shall we care about `output_iterators` and `output_masks`? it is possible that the insertion fails? shall it be hidden away from the user?
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 69 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGHFmeI6H-T5CArbQHv:-MGHFmeI6H-T5CArbQHw:b-wfkyk0) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L69)):*
> ```objc
>     /// Specifically useful for large value elements (e.g., a tensor), where we
>     /// can do in-place management after activation.
>     void Activate(const void* input_keys,
> ```

is this something that can happen automatically? can we add a unit test for this?
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 106 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNg60F1IqgqNvM6fHR:-MGNg60F1IqgqNvM6fHS:b-fcxmb8) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19 [...]

2020-09-09 19:27 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  8
         

Clones added
============
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  3
- cpp/pybind/core/hashmap.cpp  13
- python/test/core/test_hashmap.py  5
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  6
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  13
- cpp/open3d/core/hashmap/Hashmap.h  1
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  3
- cpp/tests/core/Hashmap.cpp  17
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-09 20:34 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  8
         

Clones added
============
- python/test/core/test_hashmap.py  2
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  3
- cpp/open3d/core/hashmap/Hashmap.h  1
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  13
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  3
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  6
- cpp/tests/core/Hashmap.cpp  17
- cpp/pybind/core/hashmap.cpp  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-09 21:20 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  8
         

Clones added
============
- cpp/tests/core/Hashmap.cpp  14
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  3
- cpp/pybind/core/hashmap.cpp  13
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  5
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  12
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  3
- python/test/core/test_hashmap.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-09 21:32 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  8
         

Clones added
============
- python/test/core/test_hashmap.py  2
- cpp/tests/core/Hashmap.cpp  14
- cpp/pybind/core/hashmap.cpp  13
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  5
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  12
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  3
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-09 21:55 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  17
         

Clones added
============
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  3
- python/test/core/test_hashmap.py  2
- cpp/tests/core/Hashmap.cpp  14
- cpp/pybind/core/hashmap.cpp  13
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  5
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  12
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-16 18:02 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  17
         

Clones added
============
- cpp/tests/core/Hashmap.cpp  14
- python/test/core/test_hashmap.py  2
- cpp/pybind/core/hashmap.cpp  13
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  2
- cpp/open3d/core/hashmap/TensorHash.cpp  4
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  2
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  5
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  12
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-17 00:04 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  17
         

Clones added
============
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  5
- cpp/open3d/core/hashmap/TensorHash.cpp  4
- cpp/pybind/core/hashmap.cpp  13
- python/test/core/test_hashmap.py  2
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  2
- cpp/tests/core/Hashmap.cpp  14
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  2
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-17 01:50 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  17
         

Clones added
============
- cpp/open3d/core/hashmap/Hashmap.cpp  11
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  10
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  2
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  2
- python/test/core/test_hashmap.py  2
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  5
- cpp/tests/core/Hashmap.cpp  14
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-17 02:20 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  17
         

Clones added
============
- cpp/open3d/core/hashmap/Hashmap.cpp  11
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  2
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  2
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  10
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  5
- cpp/tests/core/Hashmap.cpp  12
- python/test/core/test_hashmap.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-17 02:22 UTC, theNded reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2226)* status: 4 of 26 files reviewed, 40 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/Tensor.h, line 445 at r3](https://reviewable.io/reviews/intel-isl/open3d/2226#-MG7xmZM-rtPYV4YD9vJ:-MGnqhc7Bg4ttTAlMgMI:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/41e768d98fdb4b4388cd1d35ca96de58454c0367/cpp/open3d/core/Tensor.h#L445)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 35 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNhlha1qxXMbp4YDoT:-MGnqioz4c3sVI8ve4c1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/DeviceHashmap.h#L35)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

put this in the macro header? (e.g. traits.h)
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 41 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNl_no0_wlnv_On7dz:-MGnqk_F93Jo_N5i8m3h:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/DeviceHashmap.h#L41)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

what happens, if key_size is smaller than `sizeof(int)`? e.g. uint8. If were are not supporting it, at least we should throw an exception.
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 83 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGIGuKO7ZaSPT5sRT30:-MGnqlVt4aP_5PC2BdFp:b-2cd5t) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/DeviceHashmap.h#L83)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

shall `DeviceHashmap` inherit `Hashmap`?
</blockquote></details>

No, the role is the same as the DeviceMemoryManager.
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 184 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNnhqF-VDeoIF5RwW1:-MGnriI0453VfRoMMkAX:b-bu6l58) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/DeviceHashmap.h#L184)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

i couldn't find the definition of this function, same for the other `CreateDeviceHashmap`
</blockquote></details>

It is in TemplateHashmap with the wrong name `CreateHashmap`
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 188 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNmqDB6D0F-efve-JX:-MGnsqzw87QN7r4LEgEC:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/DeviceHashmap.h#L188)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

in pybind, you're using const Device&, let's be consistent in general
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/DeviceHashmap.h, line 206 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNnrfO-WPSdU-xp1Pm:-MGo530X171-zFvWqP4F:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/DeviceHashmap.h#L206)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

this is declared in `DeviceHAshmap.h` but defined in `Hashmap.cpp`, it would be the best if the file names match. same for the other factory functions.
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 43 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNciuH8F7oFewTXWMP:-MGo5ABy7bGDm0jYSQS2:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L43)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

let's put this one first, as it is for the user.
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 48 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNcn2Y1_m94LNJfQhs:-MGo5JTxDRv_s250GOQ-:b-8lqcd3) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L48)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`virtual ~Hashmap(){}`(add `virtual` and without `;`)
</blockquote></details>

This is not virtual class, we have virtual in DeviceHashmap
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 51 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNd536B3O7UVBMXKZ9:-MHOnriVAwMUOb6yzNtz:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L51)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

are we doing `1) -> 4) -> 2) -> 3)`? this may decrease memory usage.
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 57 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNdo2QDZfIOa1jqMZT:-MGo65TaAMZdDd8_dRj1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L57)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Since the user is already passing `void *` keys, we don't need to emphasize the "contiguous" array of keys, as that is already implied when passing a buffer. IMHO, stating contiguous here can be initially confusing to the user.

When the user passes Tensor, then we should emphasize "contiguous tensor".
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 60 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGHDh7T9UEgGrwg5Tu-:-MHOkDvp-OiMjDDZYMG3:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L60)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

shall we have an interface for tensors? can be done in a separate PR.
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 62 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGHHbjv6LXPFbllOLvP:-MGoMofY5sK656ptKXrG:bvmye9n) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L62)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

at insert, why shall we care about `output_iterators` and `output_masks`? it is possible that the insertion fails? shall it be hidden away from the user?
</blockquote></details>

An example is `voxel_downsample`, duplicates will fail. Returned iterators/masks might be processed later.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 69 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGHFmeI6H-T5CArbQHv:-MGoN2BC9Vjqk_JPUzxQ:b-fcvqxy) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L69)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

is this something that can happen automatically? can we add a unit test for this?
</blockquote></details>

This is useful for TSDF voxels, and later can be generalized with random initializers.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 106 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNg60F1IqgqNvM6fHR:-MGo6M_IDViwkk2jrm_6:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L106)):*
<details><summary><i>Previously, yxlao (Yixing L [...]

2020-09-17 14:16 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  17
         

Clones added
============
- python/test/core/test_hashmap.py  2
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  2
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  2
- cpp/open3d/core/hashmap/Hashmap.cpp  11
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  10
- cpp/tests/core/Hashmap.cpp  12
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-17 15:33 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  17
         

Clones added
============
- cpp/tests/core/Hashmap.cpp  12
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  5
- python/test/core/test_hashmap.py  4
- cpp/open3d/core/hashmap/Hashmap.cpp  11
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  10
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  2
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-25 12:11 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  17
         

Clones added
============
- cpp/open3d/core/hashmap/CUDA/InternalKvPairManager.h  1
- cpp/open3d/core/hashmap/CUDA/InternalMemoryManager.h  1
- cpp/tests/core/Hashmap.cpp  12
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  5
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  10
- cpp/open3d/core/hashmap/Hashmap.cpp  11
- python/test/core/test_hashmap.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-25 12:17 UTC, yxlao requested changes
> Reviewed 15 of 25 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2226)* status: 15 of 26 files reviewed, 87 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/hashmap/DeviceHashmap.cpp, line 3 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI4B4wh71i3Xdlah8pJ:-MI49M4S5f8TjhSI2b74:bcedazt) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/DeviceHashmap.cpp#L3)):*
> ```
> // REVIEW: shall we remove all .cpp files from hashmap, making this a
> // header-only library?
> ```
Can be done in a separate PR to keep the changes small
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 62 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGHHbjv6LXPFbllOLvP:-MHVo8MvDPQ22xuZboxr:b-hhj17a) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L62)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

An example is `voxel_downsample`, duplicates will fail. Returned iterators/masks might be processed later.
</blockquote></details>

I see. That makes sense. 

What do you think about directly returning a Pair of iterators and masks? Directly return can also avoid the issue of the inconsistent sizes of the iterators. Do we have use cases of the in-place version that will boost the performance?
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 122 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNoU5DEJNB56FJ8_sF:-MHW2nEp1U5vEInvgh4a:bcnaqct) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L122)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

TBD
</blockquote></details>

A separate question, can we use `DeviceHashmap` as the container here? 
___
*[cpp/open3d/core/hashmap/Hashmap.cpp, line 98 at r6](https://reviewable.io/reviews/intel-isl/open3d/2226#-MHW1LvkAlvYIQnPiucA:-MHW1Lvl8UTA4hmpqZBw:bf67paz) ([raw file](https://github.com/intel-isl/open3d/blob/747049bc624fd658c9383d3e440b6206a108f74a/cpp/open3d/core/hashmap/Hashmap.cpp#L98)):*
> ```cpp
>     Dtype dtype_it(Dtype::DtypeCode::Object, sizeof(iterator_t), "iterator_t");
> 
>     output_iterators = Tensor({count}, dtype_it, GetDevice());
> ```

similar comments, since we are allocating new tensors here, we might consider directly return `pair(output_iterators, ouput_masks)`, instead of passing them in as Tensor&. 
___
*[cpp/open3d/core/hashmap/TemplateHashmap.h, line 31 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNs7Zb6XWZVX49fEZN:-MHW0Tsx572go0Yxj23t:bbico1x) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/TemplateHashmap.h#L31)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Sounds great! Can be done in another PR though.
</blockquote></details>

Yes sure. 
___
*[cpp/open3d/core/hashmap/Traits.h, line 53 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI4AXGO3ZbZTssT-yc0:-MI4AXGO3ZbZTssT-yc1:bxpun7w) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/Traits.h#L53)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> // REVIEW: I keep thinking ptr_t is a pointer. It is could also be confusing to
> // see `ptr_t*`.
> // We also use ptr_t to refer to index, e.g. `prt_t iterator_ptr`, which in this
> // case it is actually the integer index but not `iterator_t*`. storage. Would
> // it make sense to rename this to `addr_t` or `index_t`?
> ```
</details>

___
*[cpp/open3d/core/hashmap/CPU/HashmapCPU.h, line 154 at r6](https://reviewable.io/reviews/intel-isl/open3d/2226#-MHW3VE55v94l7koTuU5:-MHW3VE55v94l7koTuU6:b-t65oof) ([raw file](https://github.com/intel-isl/open3d/blob/747049bc624fd658c9383d3e440b6206a108f74a/cpp/open3d/core/hashmap/CPU/HashmapCPU.h#L154)):*
> ```objc
>         if (res.second) {
>             output_iterators[i] = iterator_t(dst_key, dst_value);
>             output_masks[i] = 1;
> ```

shall we consider using `true`, `false` for consistency? same for other booleans.
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 109 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49UbD1O4tr0P3ePS7:-MI49UbD1O4tr0P3ePS8:b-b3j330) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L109)):*
> ```
> // REVIEW: i would call this kv_mgr_ to be consistent.
> ```
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 116 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49VPlDH0OwFxT3SRb:-MI49VPlDH0OwFxT3SRc:bhnq7ja) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L116)):*
> ```
> // REVIEW: can we merge the `InsertImpl` to `Insert` directly. Same for the
>     // others.
> ```
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 149 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49Wm-48VlCioop32U:-MI49Wm-48VlCioop32V:b-t7jdyi) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L149)):*
> ```
> // REVIEW: nit: order these functions to be the same as the order declared in
> // the class.
> ```
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 152 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49Xgf24IjbYQV4p4g:-MI49Xgf24IjbYQV4p4h:bghwr69) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L152)):*
> ```
> // REVIEW: we could consider removing `this->` for simplicity.
> ```
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 156 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49Y_l1beRXw_JPf4X:-MI49Y_l1beRXw_JPf4Y:b9p6h9g) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L156)):*
> ```
> // REVIEW: mention that we're allocating for the actual storage taht stores
>     // the key-value pair.
> ```
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 165 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49ZSHEtIPe3lWAWLA:-MI49ZSHEtIPe3lWAWLB:b-tadl1p) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L165)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> // REVIEW: InternalNodeManager seems to determine the maximum number of
>     // entries that we can have. Do we have a mechanism to protect against
>     // indexing out-of-range? E.g. what is the maximum number of keys can
>     // hashmap support (e.g. can it be bigger than 4GB)? What is the maximum
>     // total memory used by the hashmap?
> ```
</details>

___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 171 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49_H29dvLbGQBWWFK:-MI49_H29dvLbGQBWWFL:b5wc93f) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L171)):*
> ```
> // REVIEW: move this after all teh allocations. e.g. after allocating
>     // gpu_context_.bucket_list_head_. In this way keep the 3 allocations
>     // together.
> ```
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 205 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49aANC-RxMc9WIzcX:-MI49aANC-RxMc9WIzcY:b6btgx1) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L205)):*
<details><summary><i alt="summary">Quoted  [...]

2020-09-28 03:52 UTC, theNded reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2226)* status: 12 of 25 files reviewed, 87 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/hashmap/DeviceHashmap.cpp, line 3 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI4B4wh71i3Xdlah8pJ:-MIFhF3E8vZSxo4dT_CU:b-h6zr3d) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/DeviceHashmap.cpp#L3)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

> ```
> // REVIEW: shall we remove all .cpp files from hashmap, making this a
> // header-only library?
> ```
Can be done in a separate PR to keep the changes small
</blockquote></details>

TODO later.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 62 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGHHbjv6LXPFbllOLvP:-MIFgf2z4r8xfhrTwQ2N:b-gp30gk) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L62)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

I see. That makes sense. 

What do you think about directly returning a Pair of iterators and masks? Directly return can also avoid the issue of the inconsistent sizes of the iterators. Do we have use cases of the in-place version that will boost the performance?
</blockquote></details>

Directly returning pointers means that user will take the responsibility to free the pointers that are not allocated by themselves, which is counter-intuitive. This interface assume user will have full control of the data. Directly returning pairs might be supported in Tensor level wrappers (e.g. SparseTensor I've initially written.)
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 122 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNoU5DEJNB56FJ8_sF:-MIFhLWmBViFMsqX_Fo-:bxhun95) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/Hashmap.h#L122)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

A separate question, can we use `DeviceHashmap` as the container here? 
</blockquote></details>

DeviceHashmap is templated. If we want a templated hashmap, we will have to put it in a separate header-only PR.
___
*[cpp/open3d/core/hashmap/Hashmap.cpp, line 98 at r6](https://reviewable.io/reviews/intel-isl/open3d/2226#-MHW1LvkAlvYIQnPiucA:-MIFhq-U3xWa52oi6mP5:b3prfkc) ([raw file](https://github.com/intel-isl/open3d/blob/747049bc624fd658c9383d3e440b6206a108f74a/cpp/open3d/core/hashmap/Hashmap.cpp#L98)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

similar comments, since we are allocating new tensors here, we might consider directly return `pair(output_iterators, ouput_masks)`, instead of passing them in as Tensor&. 
</blockquote></details>

This is for consistency to the pointer interface. At python interfaces / SparseTensors we will choose to return.
___
*[cpp/open3d/core/hashmap/TemplateHashmap.h, line 31 at r4](https://reviewable.io/reviews/intel-isl/open3d/2226#-MGNs7Zb6XWZVX49fEZN:-MIFi2Hn-0aQyKwOa_PI:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fce197994dac1fe06f336de0d2c19f51d3204338/cpp/open3d/core/hashmap/TemplateHashmap.h#L31)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Yes sure. 
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Traits.h, line 53 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI4AXGO3ZbZTssT-yc0:-MIFsE7R1ixaJDuabgdJ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/Traits.h#L53)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

> ```
> // REVIEW: I keep thinking ptr_t is a pointer. It is could also be confusing to
> // see `ptr_t*`.
> // We also use ptr_t to refer to index, e.g. `prt_t iterator_ptr`, which in this
> // case it is actually the integer index but not `iterator_t*`. storage. Would
> // it make sense to rename this to `addr_t` or `index_t`?
> ```

</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/CPU/HashmapCPU.h, line 154 at r6](https://reviewable.io/reviews/intel-isl/open3d/2226#-MHW3VE55v94l7koTuU5:-MIFlFGj2fb2DbwuhtMN:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/747049bc624fd658c9383d3e440b6206a108f74a/cpp/open3d/core/hashmap/CPU/HashmapCPU.h#L154)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

shall we consider using `true`, `false` for consistency? same for other booleans.
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 109 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49UbD1O4tr0P3ePS7:-MIHpfEiBUvPMg-ia_7R:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L109)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

> ```
> // REVIEW: i would call this kv_mgr_ to be consistent.
> ```

</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 116 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49VPlDH0OwFxT3SRb:-MIFmWDuD3ak3GYKKfcn:bw5f5bx) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L116)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

> ```
> // REVIEW: can we merge the `InsertImpl` to `Insert` directly. Same for the
>     // others.
> ```

</blockquote></details>

InsertImpl does exactly the insertion, while Insert has to manage memory and potentially evoke Rehash. Rehash also calls InsertImpl; if we do not separate Insert and InsertImpl, we will face a recursive loop. To avoid this the separation was implemented, and for consistency others were also separated.
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 149 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49Wm-48VlCioop32U:-MIFtrJS3OSVL_Ri8R6g:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L149)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

> ```
> // REVIEW: nit: order these functions to be the same as the order declared in
> // the class.
> ```

</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 152 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49Xgf24IjbYQV4p4g:-MIFtrwm7AayBzpafYdi:bfqyx21) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L152)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

> ```
> // REVIEW: we could consider removing `this->` for simplicity.
> ```

</blockquote></details>

There will be compilation error, as it is accessing a memeber inherited from a templated class.
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 156 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49Y_l1beRXw_JPf4X:-MIFvL_r2C_yMrZWIcRP:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L156)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

> ```
> // REVIEW: mention that we're allocating for the actual storage taht stores
>     // the key-value pair.
> ```

</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h, line 165 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI49ZSHEtIPe3lWAWLA:-MIFwj1QCNKKp_fB3giT:bo62xme) ([raw file](https://github.com/intel-isl/open3d/blob [...]

2020-09-28 03:55 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  17
         

Clones added
============
- python/test/core/test_hashmap.py  4
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  5
- cpp/tests/core/Hashmap.cpp  23
- cpp/open3d/core/hashmap/Hashmap.cpp  11
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-28 05:17 UTC, yxlao approved these changes
> Reviewed 2 of 25 files at r5, 11 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2226)* status: 13 of 25 files reviewed, 4 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDAImpl.cuh, line 140 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI4A9zG02NoTr4QzTrT:-MII4JnF99r_HIM432tv:b-59uqu8) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDAImpl.cuh#L140)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

unit, from legacy SlabHash code.
</blockquote></details>

ok, changed to `unit`
___
*[cpp/open3d/core/hashmap/CUDA/HashmapCUDAImpl.cuh, line 221 at r7](https://reviewable.io/reviews/intel-isl/open3d/2226#-MI4ABuw77H7m6yJipiB:-MII4OyUAA8AFbuW3XHF:b-duxs01) ([raw file](https://github.com/intel-isl/open3d/blob/c61039cb32dc0a0f056fb94d40da71107a2d279d/cpp/open3d/core/hashmap/CUDA/HashmapCUDAImpl.cuh#L221)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

As above.
</blockquote></details>

updated to unit


<!-- Sent from Reviewable.io -->

2020-09-28 05:21 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- python/test/core/test_hashmap.py  17
         

Clones added
============
- cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h  3
- python/test/core/test_hashmap.py  4
- cpp/open3d/core/hashmap/Hashmap.cpp  11
- cpp/tests/core/Hashmap.cpp  23
- cpp/open3d/core/hashmap/CPU/HashmapCPU.h  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6064551&bid=19862009)

2020-09-28 08:24 UTC, merged