Build wheel squash commit
intel-isl/Open3D pull request #2288
Opened 2020-09-04 17:38 UTC by ssheorey

o use the uploaded wheels from a specific commit, create a workflow with this GitHub action. The wheels will be stored for 30 days. They can also be downloaded from the Actions tab on the website.

Build configurations:

Ubuntu, MacOS, Windows wheels are built for:
 Python version: 3.6, 3.7, 3.8
 SHARED: OFF
 BUILD_RPC_INTERFACE: ON
 BUILD_CUDA_MODULE: ON (Ubuntu 18.04)
     BUILD_TENSORFLOW_OPS: ON
     BUILD_PYTORCH_OPS: ON
 BUILD_CUDA_MODULE: OFF (Ubuntu 18.04, MacOS, Windows)
     BUILD_TENSORFLOW_OPS: ON
     BUILD_PYTORCH_OPS: ON
 Release mode

- Multi-arch wheel for Linux (CPU+CUDA) with automatic fallback from CUDA to CPU
if no GPU is available. pybind, open3d_tf_ops and open3d_torch_ops created in
    separate architecture folders {cpu,cuda}
- Wheels are downloaded and Python unit tests are run in a clean environment
(Python 3.6, 3.7, 3.8)
- TF and PyTorch (major.minor) versions checked against Open3D build versions.
- run_ci.sh configurations: 2 without CUDA and 3 with CUDA

2020-09-04 17:42 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 2
           

Clones added
============
- python/open3d/ml/torch/__init__.py  1
- python/open3d/ml/tf/python/ops/lib.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6128222&bid=20045132)

2020-09-04 18:16 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 2
           

Clones added
============
- python/open3d/ml/torch/__init__.py  1
- python/open3d/ml/tf/python/ops/lib.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6128222&bid=20045132)

2020-09-04 19:14 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 2
           

Clones added
============
- python/open3d/ml/torch/__init__.py  1
- python/open3d/ml/tf/python/ops/lib.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6128222&bid=20045132)

2020-09-04 20:15 UTC, benjaminum approved these changes
> Reviewed 16 of 28 files at r1, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2288)* status: 17 of 28 files reviewed, all discussions resolved (waiting on @benjaminum and @yxlao)



<!-- Sent from Reviewable.io -->

2020-09-04 21:12 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 2
           

Clones added
============
- python/open3d/ml/tf/python/ops/lib.py  1
- python/open3d/ml/torch/__init__.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6128222&bid=20045132)

2020-09-04 22:14 UTC, germanros1987 commented on .github/workflows/ubuntu.yml
> +          reportRun python -m pip install open3d  -f ..
could we make it more explicit? (easier to catch problems)

2020-09-04 22:16 UTC, germanros1987 commented on .github/workflows/windows.yml
> +    types: [opened, reopened, synchronize]    # Rebuild on new pushes to PR
remove space

2020-09-04 22:17 UTC, germanros1987 commented on .github/workflows/windows.yml
> +          pip install --upgrade pip
potential source of problems.

2020-09-04 22:19 UTC, germanros1987 commented on .github/workflows/windows.yml
> +          python -c "import open3d; open3d.pybind.core.kernel.test_mkl_integration()"
Shouldn't be open3d.core.kernel?

2020-09-04 22:19 UTC, germanros1987 commented on .github/workflows/windows.yml
> +          python -m pip install --upgrade pip
careful?

2020-09-04 22:22 UTC, germanros1987 commented on .github/workflows/windows.yml
> +          python -c "import open3d; open3d.pybind.core.kernel.test_mkl_integration()"
open3d.core... ?

2020-09-04 23:00 UTC, germanros1987 approved these changes

2020-09-05 00:07 UTC, ssheorey reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2288)* status: 15 of 31 files reviewed, 5 unresolved discussions (waiting on @benjaminum, @germanros1987, and @yxlao)

___
*[.github/workflows/ubuntu.yml, line 150 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGPBj3lIYEScguUu1x7-r4-150:-MGQ_K07Cou9IimsON5e:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/ubuntu.yml#L150)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

could we make it more explicit? (easier to catch problems)
</blockquote></details>

Done.
___
*[.github/workflows/windows.yml, line 49 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGPBj3lIYEScguUu1x8-r4-49:-MGQ_MXJ1lvgmWxZEOQP:b-6trfs3) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/windows.yml#L49)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

potential source of problems.
</blockquote></details>

Fixed version now
___
*[.github/workflows/windows.yml, line 58 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGPBj3lIYEScguUu1x8-r4-58:-MGQ_Q_d3leWLuAtoyPz:bv86170) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/windows.yml#L58)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

Shouldn't be open3d.core.kernel? 
</blockquote></details>

From Yixing: Only for unit test, removed since duplicated in Python unit test
___
*[.github/workflows/windows.yml, line 85 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGPBj3lIYEScguUu1x8-r4-85:-MGQ_ay17f8pewig_yg8:bd9kt9o) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/windows.yml#L85)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

careful?
</blockquote></details>

Fixed versions
___
*[.github/workflows/windows.yml, line 128 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGPBj3lIYEScguUu1x8-r4-128:-MGQ_e6HEOHrrRfYu7Um:ba3dfob) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/windows.yml#L128)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

open3d.core... ?
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2020-09-05 00:08 UTC, yxlao requested changes
> Reviewed 5 of 28 files at r1, 2 of 5 files at r2, 4 of 5 files at r4, 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2288)* status: 23 of 31 files reviewed, 29 unresolved discussions (waiting on @benjaminum, @germanros1987, @ssheorey, and @yxlao)

___
*[.github/workflows/macos.yml, line 53 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQYYRp-esZRxj4mj4k:-MGQYYRp-esZRxj4mj4l:bhonz2i) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L53)):*
> ```YAML
>           brew install ccache
>           ccache -M 2G  # GitHub's total cache limit is 5GB for all OSes.
>           rm -rf $(brew --cache)  # Remove homebrew cached packages
> ```

would it be possible to remove this for now? since we're using `DCMAKE_BUILD_TYPE=Release`, this already brings down the total binary size from 11-12G to ~5-6G, which should be fairly sufficient; also macos doesn't have any of the cuda stuff

same for other brew cache remove code
___
*[.github/workflows/macos.yml, line 60 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQYWB8-82etBwVNjkm:-MGQYWB8-82etBwVNjkn:b-jhgyqy) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L60)):*
> ```YAML
>           ./util/run_ci.sh
>           ccache -s
>           echo
> ```

remove the extra blank line
___
*[.github/workflows/macos.yml, line 61 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQYTE47oWfGxkjOR7C:-MGQYTE47oWfGxkjOR7D:bpubhcp) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L61)):*
> ```YAML
>           ccache -s
>           echo
>           echo "Disk space used: $(df -h $PWD)"
> ```

if we're going to print, shall we put this at the very end?
___
*[.github/workflows/macos.yml, line 63 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQY8RT8T597c68IX_Z:-MGQY8RT8T597c68IX__:bxm2ldz) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L63)):*
> ```YAML
>           echo "Disk space used: $(df -h $PWD)"
> ```

remove extra blank line
___
*[.github/workflows/macos.yml, line 64 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQXoXwE3g69dDV5aSb:-MGQXoXwE3g69dDV5aSc:b7a875c) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L64)):*
> ```YAML
> 
> 
>   build-macos-wheel:
> ```

- rename to build-wheel
- give this step name
___
*[.github/workflows/macos.yml, line 117 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQXulM1AWCmipV3RiN:-MGQXulM1AWCmipV3RiO:b-cxbr2z) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L117)):*
> ```YAML
>           if-no-files-found: error
> 
>   test-macos-wheel:
> ```

test-wheel
___
*[.github/workflows/macos.yml, line 118 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQXwFBAVGx6QsXz_Iq:-MGQXwFBAVGx6QsXz_Ir:bdvy14i) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L118)):*
> ```YAML
> 
>   test-macos-wheel:
>     name: Test macos wheel
> ```

Test wheel
___
*[.github/workflows/macos.yml, line 149 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQRZ9y7rZ1xxBl42Du:-MGQRZ9y7rZ1xxBl42Dv:b-pcn5kw) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L149)):*
> ```YAML
>           install_python_dependencies with-unit-test
>           reportRun python -m pip install open3d -f ..
>           printf "\n\nInstalled wheel folder structure:\n"
> ```

we've been using echo in front, shall we keep using `echo` to be consistent?
also, would it be possible to remove the `\n`, it would look better on the code
___
*[.github/workflows/macos.yml, line 154 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQSGBi0XyuX0geOOcV:-MGQSGBj-0_xcsGAgiOt:bauq45i) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L154)):*
> ```YAML
>           python -m pip freeze
>           printf "\n\nDynamic libraries used:\n"
>           DLL_PATH=$(dirname $(python -c "import open3d; print(open3d.cpu.pybind.__file__)"))/..
> ```

if they are common for macos and ubuntu, could we merge them into the util scripts?
___
*[.github/workflows/macos.yml, line 158 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQMopY1JW-rLQyRphH:-MGQMopY1JW-rLQyRphI:b-1w7buw) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L158)):*
> ```YAML
>           echo
>           test_wheel
>           reportJobFinishSession
> ```

i'd remove all of the `reportJobFinishSession` and `reportJobStart`, they are previously used in Travis to print time stamps, but now github actions have but in time stamps
___
*[.github/workflows/ubuntu.yml, line 4 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQZ5i6CcEe1vd_beoe:-MGQZ5i6CcEe1vd_beof:bbn67uf) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/ubuntu.yml#L4)):*
> ```
> workflow_dispatch
> ```
this is great!
___
*[.github/workflows/ubuntu.yml, line 21 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQ_Eo93UAlAc9kk62E:-MGQ_Eo93UAlAc9kk62F:b-ay0gwg) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/ubuntu.yml#L21)):*
> ```YAML
>       SHARED: ${{ matrix.SHARED }}
>       BUILD_CUDA_MODULE: OFF
>       BUILD_TENSORFLOW_OPS: ${{ matrix.SHARED }}
> ```

why is this determined by matrix.SHARED?
___
*[.github/workflows/ubuntu.yml, line 64 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQXXSz2sxcNSUhdz_p:-MGQXXT-5OKqJ4mR1_Pd:b88cb80) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/ubuntu.yml#L64)):*
> ```YAML
>           echo "Disk space used: $(df -h $PWD)"
> 
>   build-ubuntu-wheel:
> ```

let's call this `build-wheel` since it is already under `Ubuntu CI`
___
*[.github/workflows/ubuntu.yml, line 65 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQXd9Z9A6erCCMH-6Y:-MGQXd9Z9A6erCCMH-6Z:blft9a4) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/ubuntu.yml#L65)):*
> ```YAML
> 
>   build-ubuntu-wheel:
>     name: Make Python package
> ```

make the name consistent with the tag, e.g. `name: Make wheel`
___
*[.github/workflows/ubuntu.yml, line 102 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQ_MiK3Ncch9kwXWkJ:-MGQ_MiK3Ncch9kwXWkK:btt89zc) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/ubuntu.yml#L102)):*
> ```YAML
>           sudo apt-get --yes install ccache
>           ccache -M 2G  # GitHub's total cache limit is 5GB for all OSes.
>           sudo apt-get clean    # Remove apt-get cache
> ```

after switching to the `Release` buld type, we can remove this, to keep the script clean
___
*[.github/workflows/ubuntu.yml, line 120 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQXjsoBIlnOK2cyuti:-MGQXjsoBIlnOK2cyutj:b-u8v9ey) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/ubuntu.yml#L120)):*
> ```YAML
>           if-no-files-found: error
> 
>   test-ubuntu-wheel:
> ```

same, remove `ubuntu`
___
*[.github/workflows/ubuntu.yml, line 121 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQXlT3098CobjBa1RX:-MGQXlT3098CobjBa1RY:bdvy14i) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f [...]

2020-09-05 00:08 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 2
           

Clones added
============
- python/open3d/ml/torch/__init__.py  1
- python/open3d/ml/tf/python/ops/lib.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6128222&bid=20045132)

2020-09-05 02:02 UTC, ssheorey reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2288)* status: 23 of 31 files reviewed, 29 unresolved discussions (waiting on @benjaminum, @germanros1987, and @yxlao)

___
*[.github/workflows/macos.yml, line 53 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQYYRp-esZRxj4mj4k:-MGQiSlZ3uV3oKbQP57w:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L53)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

would it be possible to remove this for now? since we're using `DCMAKE_BUILD_TYPE=Release`, this already brings down the total binary size from 11-12G to ~5-6G, which should be fairly sufficient; also macos doesn't have any of the cuda stuff

same for other brew cache remove code
</blockquote></details>

Done.
___
*[.github/workflows/macos.yml, line 60 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQYWB8-82etBwVNjkm:-MGQjwds2pNupBKpddx1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L60)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove the extra blank line
</blockquote></details>

Done.
___
*[.github/workflows/macos.yml, line 61 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQYTE47oWfGxkjOR7C:-MGQjx7p7qjOqtOzjz8I:b-3k2z0g) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L61)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

if we're going to print, shall we put this at the very end?
</blockquote></details>

Each job runs on a different machine, so the disk limit would be specific to the job. I only put it on the job where we expect more disk space needed.
The output doesn't look useful in Linux / Mac (~219GB). I'll remove this. Windows output actually shows the 10.34GB used / 14GB limit so I'll keep it there.
___
*[.github/workflows/macos.yml, line 63 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQY8RT8T597c68IX_Z:-MGQm0cM0Jw-ZCZc7NQs:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L63)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove extra blank line
</blockquote></details>

Done.
___
*[.github/workflows/macos.yml, line 64 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQXoXwE3g69dDV5aSb:-MGQmWPR5mpQGYk6ZHhW:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L64)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

- rename to build-wheel
- give this step name
</blockquote></details>

Done.
___
*[.github/workflows/macos.yml, line 117 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQXulM1AWCmipV3RiN:-MGQmXBHBvHnzJLWjI6A:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L117)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

test-wheel
</blockquote></details>

Done.
___
*[.github/workflows/macos.yml, line 118 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQXwFBAVGx6QsXz_Iq:-MGQmX_P6xpquqRAMbr-:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L118)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Test wheel
</blockquote></details>

Done.
___
*[.github/workflows/macos.yml, line 149 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQRZ9y7rZ1xxBl42Du:-MGQndnLAiPNUoNbOST5:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L149)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we've been using echo in front, shall we keep using `echo` to be consistent?
also, would it be possible to remove the `\n`, it would look better on the code
</blockquote></details>

Done.
___
*[.github/workflows/macos.yml, line 154 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQSGBi0XyuX0geOOcV:-MGQnl-PDXyWzNEkeIha:buzde6s) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L154)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

if they are common for macos and ubuntu, could we merge them into the util scripts?
</blockquote></details>

Its `ldd` vs `otool -L`.  I intended this to be temporary  that we can remove after the release, but I can script it if you think it's useful in the CI all the time.
___
*[.github/workflows/macos.yml, line 158 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQMopY1JW-rLQyRphH:-MGQoQvXEsuFqT63RBx5:bli1f1u) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/macos.yml#L158)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

i'd remove all of the `reportJobFinishSession` and `reportJobStart`, they are previously used in Travis to print time stamps, but now github actions have but in time stamps
</blockquote></details>

Done. Also removed `date`
___
*[.github/workflows/ubuntu.yml, line 4 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQZ5i6CcEe1vd_beoe:-MGQrDUt3FXlFiXFUXxR:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/ubuntu.yml#L4)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

> ```
> workflow_dispatch
> ```
this is great!
</blockquote></details>

Done.
___
*[.github/workflows/ubuntu.yml, line 21 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQ_Eo93UAlAc9kk62E:-MGQrF427MvZMZt0wP3Y:bfxkjux) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/ubuntu.yml#L21)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

why is this determined by matrix.SHARED?
</blockquote></details>

It's based on Benjamin's recommendations. I'll rename the matrix variable to CONFIG to clarify that there is no intentional relation.
___
*[.github/workflows/ubuntu.yml, line 64 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQXXSz2sxcNSUhdz_p:-MGQqx6SBwbxBXZ-_bEt:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/ubuntu.yml#L64)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

let's call this `build-wheel` since it is already under `Ubuntu CI`
</blockquote></details>

Done.
___
*[.github/workflows/ubuntu.yml, line 65 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQXd9Z9A6erCCMH-6Y:-MGQr9V2CpR868X7mNQ1:bl27qp0) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/ubuntu.yml#L65)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

make the name consistent with the tag, e.g. `name: Make wheel`
</blockquote></details>

Build wheel
___
*[.github/workflows/ubuntu.yml, line 102 at r4](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGQ_MiK3Ncch9kwXWkJ:-MGQsH4PAX85oc12jIKC:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/fb53bd7236b50074d75af83f432a2f72a93f6e3d/.github/workflows/ubuntu.yml#L102)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

after switching to the `Release` buld type, we can remove this, to keep the script clean
</blockquote></det [...]

2020-09-05 02:15 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 2
           

Clones added
============
- python/open3d/ml/tf/python/ops/lib.py  1
- python/open3d/ml/torch/__init__.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6128222&bid=20045132)

2020-09-05 03:59 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 2
           

Clones added
============
- python/open3d/ml/torch/__init__.py  1
- python/open3d/ml/tf/python/ops/lib.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6128222&bid=20045132)

2020-09-05 08:32 UTC, yxlao requested changes
> Reviewed 9 of 28 files at r1, 4 of 7 files at r6, 10 of 10 files at r7.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2288)* status: all files reviewed, 11 unresolved discussions (waiting on @germanros1987, @ssheorey, and @yxlao)

___
*[python/open3d/ml/contrib/__init__.py, line 28 at r7](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGSO-Ct8Ld45HinO86U:-MGSO-Ct8Ld45HinO86V:bz3cost) ([raw file](https://github.com/intel-isl/open3d/blob/c764fc207b737f351a3e711a18a3e87cbf521e42/python/open3d/ml/contrib/__init__.py#L28)):*
> ```Python
> 
> import open3d
> if open3d.__DEVICE_API__ == 'cuda':
> ```

we have created quite a few new `__init__.py` to promote namespaces, is it possible to do it in one place e.g. in top level? or is it recommended to do it in separate `__init__.py`? 

my personal preference is to put them in one location when possible, which is more organized than splitting them up.


<!-- Sent from Reviewable.io -->

2020-09-05 08:40 UTC, yxlao approved these changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2288)* status: all files reviewed, 11 unresolved discussions (waiting on @germanros1987, @ssheorey, and @yxlao)

___
*[python/open3d/ml/contrib/__init__.py, line 28 at r7](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGSO-Ct8Ld45HinO86U:-MGSPvOF4GXyTpK_AQWR:b-ubjszf) ([raw file](https://github.com/intel-isl/open3d/blob/c764fc207b737f351a3e711a18a3e87cbf521e42/python/open3d/ml/contrib/__init__.py#L28)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we have created quite a few new `__init__.py` to promote namespaces, is it possible to do it in one place e.g. in top level? or is it recommended to do it in separate `__init__.py`? 

my personal preference is to put them in one location when possible, which is more organized than splitting them up.
</blockquote></details>

btw, we can do this in future PR, so as long as the tests are passing, it lgtm


<!-- Sent from Reviewable.io -->

2020-09-05 20:21 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 2
           

Clones added
============
- python/open3d/ml/torch/__init__.py  1
- python/open3d/ml/tf/python/ops/lib.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6128222&bid=20045132)

2020-09-05 20:28 UTC, ssheorey reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2288)* status: 29 of 30 files reviewed, 11 unresolved discussions (waiting on @germanros1987 and @yxlao)

___
*[python/open3d/ml/contrib/__init__.py, line 28 at r7](https://reviewable.io/reviews/intel-isl/open3d/2288#-MGSO-Ct8Ld45HinO86U:-MGUvTvp8a7HPj3llP_P:bf42t80) ([raw file](https://github.com/intel-isl/open3d/blob/c764fc207b737f351a3e711a18a3e87cbf521e42/python/open3d/ml/contrib/__init__.py#L28)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

btw, we can do this in future PR, so as long as the tests are passing, it lgtm
</blockquote></details>

How would we do this and still ensure that imports like this work:
`from open3d.ml.contrib import subsample`
I think this runs the `__init__.py` in `open3d/ml/contrib`
Thanks. I'll merge this in after the tests pass and we can talk about this next week.


<!-- Sent from Reviewable.io -->

2020-09-05 20:32 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 2
           

Clones added
============
- python/open3d/ml/torch/__init__.py  1
- python/open3d/ml/tf/python/ops/lib.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6128222&bid=20045132)

2020-09-05 21:45 UTC, merged

2025-08-15 14:06 UTC, malkia commented
Why was -DSTATIC_WINDOWS_RUNTIME=ON enforced here? This makes the .pyd link to the static CRT, and not to the dynamic one thus causing issues where you have duplicate CRT state and then further issues down the line - possibly this crash here - https://github.com/microsoft/mimalloc/issues/1128#issuecomment-3191489443

Since VS2015 the Dynamic CRT's in MSVC are compatible (almost) - https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170

2025-08-15 19:48 UTC, ssheorey commented
Hi @malkia please open a bug report (and preferably a PR) to explain your issue and suggest resolutions.