Ray/line to axis-aligned bounding box intersections
intel-isl/Open3D pull request #2358
Opened 2020-09-19 21:33 UTC by mattj23

Tests to check between `Eigen::ParametrizedLine<double, 3>` and `AxisAlignedBoundingBox` added to the `IntersectionTests` static class.  Documentation, unit tests, and example program containing stress/performance test included.

* Two underlying implementations were included, the highly optimized ray-tracing standard 'slab' algorithm, and a naive exact algorithm which runs much slower but correctly handles the corner cases where the slab algorithm fails
* Methods to handle both the line case (all intersections along the line direction, both forward and backwards of the line origin) and the ray case are included
* The slab functions contain overloads for the precomputed direction component inverses, which speeds up the slab method another 15% to 20% for cases where the same ray/line will be tested against multiple AABBs
* All methods have both a `double` returning parameter version (can be used to recover the intersection point from the `ParametrizedLine` or to sort intersecting boxes in order for algorithms that can take advantage of priority) and a `bool` returning test function.
* Parameter versions use `std::nan` and `std::isnan` to handle non-intersection cases.

2020-09-19 21:37 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- examples/cpp/LineToAABB.cpp  6
- cpp/tests/geometry/IntersectionTest.cpp  20
- cpp/open3d/geometry/IntersectionTest.cpp  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-09-21 07:25 UTC, griegler requested changes
Thanks for this PR, it looks great. I would only like to move the code from the example to `cpp/benchmarks` which would be the preferred place. The code there will also be executed in the CI.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358#-:-MHjXeqO-EPl-S4XhcXg:b-yjpyyp)* status: all files reviewed, 1 unresolved discussion (waiting on @mattj23)

___
*[examples/cpp/LineToAABB.cpp, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d/2358#-MHjX_r0ASV8-Sjit0OW:-MHjX_r1ERe5stplbPEn:b-1urgtf) ([raw file](https://github.com/intel-isl/open3d/blob/79b7bf0385254fa6bde2bc155e36bbb14fe59b15/examples/cpp/LineToAABB.cpp#L1)):*
> ```cpp
> // ----------------------------------------------------------------------------
> ```

`benchmarks` might be a better place for this code.


<!-- Sent from Reviewable.io -->

2020-09-22 22:50 UTC, mattj23 commented
@griegler, I'm still reworking the intersections into different line/ray/segment classes like we talked about.  It ended up producing something that feels relatively elegant and, at least in my toy cases, has no measurable performance impact.  I ended up running with the concept and adding other methods to the classes for different types of intersections and measurements that make sense for what the classes are, so it's taking a little longer to reshape and write tests.

Looking at the contents of the benchmark folder, it's a little cryptic to me how the code inside works.  Is this a framework I can find documentation for? Or is there a guide on how benchmarks are to be written?

2020-09-23 06:16 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/geometry/Line3D.h  2
- cpp/open3d/geometry/Line3D.cpp  2
- cpp/tests/geometry/Line3D.cpp  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-09-23 06:25 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/geometry/Line3D.h  2
- cpp/open3d/geometry/Line3D.cpp  2
- cpp/tests/geometry/Line3D.cpp  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-09-23 06:55 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/geometry/Line3D.cpp  15
- cpp/open3d/geometry/Line3D.cpp  2
- cpp/open3d/geometry/Line3D.h  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-09-24 09:12 UTC, griegler requested changes
Thanks. That looks much cleaner. Below I propose a slight reorganization of the classes.
Regardings benchmarks we use `google/benchmark`, you can have a look here: https://github.com/google/benchmark

> Reviewed 8 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358#-:-MHzNW9r-32b7mnEroQ4:bn1ez6y)* status: all files reviewed, 4 unresolved discussions (waiting on @mattj23)

___
*[cpp/open3d/geometry/Line3D.h, line 67 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MHzLsOb0rmgGTze9MdR:-MHzLsOb0rmgGTze9MdS:b-xpa989) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L67)):*
> ```objc
> /// lookup, or consider a hand implementation of your problem in which you
> /// carefully account for the semantics yourself.
> class Line3D : protected Eigen::ParametrizedLine<double, 3> {
> ```

Instead of `Eigen::ParametrizedLine` can we derive from `Geometry3D` as the other types in Open3D. You can use `ParametrizedLine` within the class if really needed.
___
*[cpp/open3d/geometry/Line3D.h, line 214 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MHzMlUSD2MhJ_5P9bJ4:-MHzMlUSD2MhJ_5P9bJ5:b-3cbz3q) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L214)):*
> ```objc
> /// has an origin and a direction and extends infinitely only in that specific
> /// direction.
> class Ray3D : public Line3D {
> ```

Here the semantics are not really clear. Is `Ray` really base class of `Line3D` in the sense that it should inherit all the semantics from `Line3D`?
Especially, a ray has a different set of attrs (origin and direction).
I would suggest a base class `LineBase3D` that inherits from `Geometry3D` and `Line3D`, `Ray3D` and `Segment3D` inherit from `LineBase3D`.
Then `LineBase3D` contains only the attributes and method signatures that are really shared by all three specializations.
___
*[cpp/open3d/geometry/Line3D.h, line 279 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MHzMVV38JsmN5ot8S3R:-MHzMVV38JsmN5ot8S3S:bjhcamp) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L279)):*
> ```objc
> /// of what happens in the underlying Eigen implementation without changing
> /// the api surface for client code.
> class Segment3D : public Line3D {
> ```

Here the semantics are not really clear. Is `Segment3D` really base class of `Line3D` in the sense that it should inherit all the semantics from `Line3D`?
___
*[cpp/open3d/geometry/Line3D.cpp, line 290 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MHzNOhj8seiVSJq67q1:-MHzNOhj8seiVSJq67q2:b-v6n1oq) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.cpp#L290)):*
> ```cpp
> 
> }  // namespace geometry
> }  // namespace open3d
> ```

some weird characters at the and of this line


<!-- Sent from Reviewable.io -->

2020-09-24 12:58 UTC, mattj23 commented
> Instead of `Eigen::ParametrizedLine` can we derive from `Geometry3D` as the other types in Open3D. You can use `ParametrizedLine` within the class if really needed.

Regardless of how it gets restructured, I don't think we can derive from `Geometry3D`, since `Geometry3D` requires methods to compute bounding volumes around the shape and both lines and rays are infinite by definition.

I think my intent here was to make some very simple and lightweight/fast primitives for testing intersections and distances.  `Geometry3D` is derived from `Geometry` which seems to be the base class for things which can be drawn by the visualizer, is that correct? 

> I would suggest a base class `LineBase3D` that inherits from `Geometry3D` and `Line3D`, `Ray3D` and `Segment3D` inherit from `LineBase3D`

I actually started by implementing a `LineBase` and deriving all three from it, complete with unit tests and all, before I stepped back and realized I had over-complicated it.

In its implementation `Eigen::ParametrizedLine` is effectively two vectors, `m_origin` and `m_direction`, and all space occupied by the line is represented by a scalar parameter `t`, which is conceptually allowed to vary from -infinity to +infinity.  This is a base parametric representation of a line, and `Line3D` doesn't really add anything to it; it basically does exactly the same thing as `ParametrizedLine` except that I resolve some ambiguity regarding intersections with parallel planes.

`Ray3D` is actually a special case of `Line3D`, in that it also has an origin and direction, but `t` is subjected to the additional constraint that `t >= 0` in places where the ray exists.

`Segment3D` is in turn a special case of `Ray3D` in that it has an origin and direction and a length, and the additional constraint that `t <= length` in places where the segment exists.  

`Segment3D` was the original motivation for all of the subclassing, in the sense that a line segment can actually be represented by `ParametrizedLine` by storing its starting point in `m_origin` and setting `m_direction` to be the vector from the start point to the end point and interpret the segment as existing where `0 <= t <= 1`.  This works, all unit tests pass, and originally I was satisfied with this, until I noticed that Eigen's documentation warns that it expects the direction to be normalized, which this approach prevents you from doing.

I derived `Segment3D` and `Ray3D` from `Line3D` but in retrospect probably could have shortened the code further by deriving `Segment3D` from `Ray3D` instead.  I'm convinced that the semantics make sense with `Ray3D` being a special case of `Line3D`, and `Segment3D` being a special case of `Ray3D`, but I will defer to your opinion.  

Would you still like me to restructure them from a common base class?  And what would you like me to do about inheriting from `Geometry3D`?  We'd have to resolve what to do about generating a bounding box around the infinite cases, and learning and implementing graphics features for these is probably beyond what I can reasonably find time for.  Also, adding a lot of overhead to these classes would reduce their usefulness in cases where they'd be used to do ray-tracing and collision type checks.

2020-09-29 00:36 UTC, mattj23 commented
@griegler, @benjaminum, is there still interest in this? I don't mind looking into google benchmarks but work is taking more of my time these next few weeks.  Is there any guidance for me regarding the questions I had above?

2020-10-01 09:18 UTC, griegler requested changes
We are still interested, sorry for the delay.
Just a tip for the future, replying in Reviewable (see violet box in the very first post) would make the conversation a bit easier.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358#-:-MIYQe3bEjGK9dgw7DKt:b-o66f7a)* status: all files reviewed, 4 unresolved discussions (waiting on @benjaminum and @mattj23)

___
*[cpp/open3d/geometry/Line3D.h, line 67 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MHzLsOb0rmgGTze9MdR:-MIYQf4i6KXC8OoGpv-v:brq0xz8) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L67)):*
<details><summary><i>Previously, griegler (Gernot) wrote…</i></summary><blockquote>

Instead of `Eigen::ParametrizedLine` can we derive from `Geometry3D` as the other types in Open3D. You can use `ParametrizedLine` within the class if really needed.
</blockquote></details>

You are right. Geometry3D` are not sensible base classes here due to the interface. And `Geometry` is the base class for `drawable` classes, which might be tricky for rays and lines to (although interesting for future extensions). 
___
*[cpp/open3d/geometry/Line3D.h, line 214 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MHzMlUSD2MhJ_5P9bJ4:-MIYRtQsAjxa4BD449VT:b7wfl89) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L214)):*
<details><summary><i>Previously, griegler (Gernot) wrote…</i></summary><blockquote>

Here the semantics are not really clear. Is `Ray` really base class of `Line3D` in the sense that it should inherit all the semantics from `Line3D`?
Especially, a ray has a different set of attrs (origin and direction).
I would suggest a base class `LineBase3D` that inherits from `Geometry3D` and `Line3D`, `Ray3D` and `Segment3D` inherit from `LineBase3D`.
Then `LineBase3D` contains only the attributes and method signatures that are really shared by all three specializations.
</blockquote></details>

Your arguments are sound on this topic. I will ping @benjaminum that he also has another look to get a second opinion.


<!-- Sent from Reviewable.io -->

2020-10-01 11:04 UTC, benjaminum requested changes
@mattj23 The doc strings look good. Thanks! I just added some minor questions to the code.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358#-:-MIYo63K5zEXIJ9OtGby:b-qbztpj)* status: all files reviewed, 6 unresolved discussions (waiting on @mattj23)

___
*[cpp/open3d/geometry/Line3D.h, line 45 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MIYgPgj0__wmGoqwKD0:-MIYgPgj0__wmGoqwKD1:bfplsxg) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L45)):*
> ```objc
> ///
> /// \brief Line3D is a class which derives from
> /// Eigen::ParametrizedLine<double, 3> in order to capture the semantic
> ```

Can there be memory alignment issues when we use Line3D in a vector or pass an object by value?
___
*[cpp/open3d/geometry/Line3D.h, line 109 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MIYhxmw5rmLrQ6V-MZD:-MIYhxmw5rmLrQ6V-MZE:b5jcueq) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L109)):*
> ```objc
>     /// Line3D. Will return an empty result if the line is parallel to the
>     /// plane.
>     utility::optional<double> LineIntersectionParameter(
> ```

LinePointAt and LineIntersectonParameter seem a bit special. LineIntersectionParameter is just a shortcut for accessing the base class IntersectionParameter. It is a good idea if we expect to use this a lot. If not we could also remove it.

Would a PointAt method which takes the line type into account make sense? Or would it rather make sense to hide this function in Ray3D and Segment3D?


<!-- Sent from Reviewable.io -->

2020-10-01 16:35 UTC, mattj23 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358)* status: all files reviewed, 6 unresolved discussions (waiting on @benjaminum, @griegler, and @mattj23)

___
*[cpp/open3d/geometry/Line3D.h, line 45 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MIYgPgj0__wmGoqwKD0:-MIZqXuT-1ako4QiTxEM:bsacokz) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L45)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Can there be memory alignment issues when we use Line3D in a vector or pass an object by value?
</blockquote></details>

I'm not quite sure, this is not something I know much about.  Is there any way I can test this, and if so, what should I be looking for?
___
*[cpp/open3d/geometry/Line3D.h, line 109 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MIYhxmw5rmLrQ6V-MZD:-MIZrBm-AH5RMeIfugL6:b-ari4wk) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L109)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

LinePointAt and LineIntersectonParameter seem a bit special. LineIntersectionParameter is just a shortcut for accessing the base class IntersectionParameter. It is a good idea if we expect to use this a lot. If not we could also remove it.

Would a PointAt method which takes the line type into account make sense? Or would it rather make sense to hide this function in Ray3D and Segment3D?
</blockquote></details>

I went back and forth on this concept myself and came up with no obvious best answer.  I welcome whatever direction you and @griegler feel is best.  Here are the things that went through my head as I tried to decide:

1. Originally, I intended to simply expose the underlying `ParametrizedLine` by inheriting publicly, but quickly realized that this would create a confusing mess where things like `intersectionParameter` would exist alongside the semantically enforced versions, so I ruled that out
2. However, because these are intended to be performance oriented classes, I thought it would be infuriating for an end user to create a `Ray3D` or a `Segment3D` and then be blocked from the underlying `Eigen` object if they needed to use part of it, forcing them to create a *second* instance of `ParametrizedLine` if they needed access to those features, like  using `LineIntersectionParameter` when they have a `Segment3D`
3. Additionally, when I started to create  `PointAt` methods which enforced ray or segment semantics, I realized that it wasn't obviously clear to me how they should behave.  Should a point behind the origin of a ray or beyond the endpoint of a segment return the closest valid point on the entity?  Or should they return something like an empty `optional` to indicate that there is no such point at that location?  The underlying problem is not one of what the function should output, but that the function inputs only make sense in a specific domain of `double` and that I couldn't figure out what was the right thing to do with an "invalid" input.  I also couldn't figure out if one of those options made more practical sense for most use cases.
4. In the end I attempted to sidestep the issue by forcing the use of `LinePointAt` which I thought would be unambiguous about how it behaves and has a valid output for all values of `double`.  

I'm not satisfied with the solution I came up with; it was a cheap way out because I couldn't figure out how to reconcile the underlying issue.  Any guidance here would be greatly appreciated.


<!-- Sent from Reviewable.io -->

2020-10-01 16:47 UTC, mattj23 commented
> Just a tip for the future, replying in Reviewable (see violet box in the very first post) would make the conversation a bit easier.

I apologize, I'm still figuring this out.  Thanks for your patience!

2020-10-01 21:18 UTC, benjaminum requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358)* status: all files reviewed, 6 unresolved discussions (waiting on @griegler and @mattj23)

___
*[cpp/open3d/geometry/Line3D.h, line 45 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MIYgPgj0__wmGoqwKD0:-MI_sUNe7I5zkTaFkfaT:b3a0ycv) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L45)):*
<details><summary><i>Previously, mattj23 (Matthew Jarvis) wrote…</i></summary><blockquote>

I'm not quite sure, this is not something I know much about.  Is there any way I can test this, and if so, what should I be looking for?
</blockquote></details>

I had a look at https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Geometry/ParametrizedLine.h#L33 
It seems we are fine as long as we stay in 3D.
___
*[cpp/open3d/geometry/Line3D.h, line 109 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MIYhxmw5rmLrQ6V-MZD:-MI_su9p8k9jbAdIBtoK:bg9kiw0) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L109)):*
<details><summary><i>Previously, mattj23 (Matthew Jarvis) wrote…</i></summary><blockquote>

I went back and forth on this concept myself and came up with no obvious best answer.  I welcome whatever direction you and @griegler feel is best.  Here are the things that went through my head as I tried to decide:

1. Originally, I intended to simply expose the underlying `ParametrizedLine` by inheriting publicly, but quickly realized that this would create a confusing mess where things like `intersectionParameter` would exist alongside the semantically enforced versions, so I ruled that out
2. However, because these are intended to be performance oriented classes, I thought it would be infuriating for an end user to create a `Ray3D` or a `Segment3D` and then be blocked from the underlying `Eigen` object if they needed to use part of it, forcing them to create a *second* instance of `ParametrizedLine` if they needed access to those features, like  using `LineIntersectionParameter` when they have a `Segment3D`
3. Additionally, when I started to create  `PointAt` methods which enforced ray or segment semantics, I realized that it wasn't obviously clear to me how they should behave.  Should a point behind the origin of a ray or beyond the endpoint of a segment return the closest valid point on the entity?  Or should they return something like an empty `optional` to indicate that there is no such point at that location?  The underlying problem is not one of what the function should output, but that the function inputs only make sense in a specific domain of `double` and that I couldn't figure out what was the right thing to do with an "invalid" input.  I also couldn't figure out if one of those options made more practical sense for most use cases.
4. In the end I attempted to sidestep the issue by forcing the use of `LinePointAt` which I thought would be unambiguous about how it behaves and has a valid output for all values of `double`.  

I'm not satisfied with the solution I came up with; it was a cheap way out because I couldn't figure out how to reconcile the underlying issue.  Any guidance here would be greatly appreciated.


</blockquote></details>

1. I agree, not exposing ParametrizedLine reduces possible confusion.
2. Since Line3D is the base class you can do `segment3d.Line3D::IntersectionParameter()`, right? However, LineIntersectionParameter is a lot shorter.
Another way would be to implement something like `segment3d.line().IntersectionParameter()` similar to what Eigen is doing with `.matrix()` and `.array()`.
3.,4. It feels like not having PointAt for Ray and Segment would be the best.

I remember you have planned to add more features that will make use of these classes. Would it make sense to go forward with the current solution and fine-tune the classes on the go?


<!-- Sent from Reviewable.io -->

2020-10-02 04:26 UTC, mattj23 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358)* status: all files reviewed, 6 unresolved discussions (waiting on @griegler and @mattj23)

___
*[cpp/open3d/geometry/Line3D.h, line 109 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MIYhxmw5rmLrQ6V-MZD:-MIbX5op0aX16pAnaNtD:bs4j1nz) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L109)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

1. I agree, not exposing ParametrizedLine reduces possible confusion.
2. Since Line3D is the base class you can do `segment3d.Line3D::IntersectionParameter()`, right? However, LineIntersectionParameter is a lot shorter.
Another way would be to implement something like `segment3d.line().IntersectionParameter()` similar to what Eigen is doing with `.matrix()` and `.array()`.
3.,4. It feels like not having PointAt for Ray and Segment would be the best.

I remember you have planned to add more features that will make use of these classes. Would it make sense to go forward with the current solution and fine-tune the classes on the go?
</blockquote></details>

I didn't know C++ well enough to know that `segment3d.Line3D::IntersectionParameter()` was even possible, so I learned something new today.  

I think that overall I like the `segment3d.line()` the best; it's unambiguous, easy, and uses a familiar interface.  Should it be `segment3d.line()` returning the base `ParametrizedLine<double, 3>`, or a `segment3d.Line3D()` returning the base `Line3D`?  I think it should be the former, since then you get all of the functionality of the underlying Eigen class, does that seem reasonable?

I have some triangle intersection code ready which uses these classes, and I've actually been using it myself in code I'm running for the past few weeks.  I'd like to clean up Line3D as we've been discussing, fix some typos I found in the docs, and potentially add a few line/line distance and intersections tests.  If you're OK with me doing that first I'd be happy to continue to fine-tune the classes as we go.


<!-- Sent from Reviewable.io -->

2020-10-02 05:39 UTC, benjaminum requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358)* status: all files reviewed, 6 unresolved discussions (waiting on @griegler and @mattj23)

___
*[cpp/open3d/geometry/Line3D.h, line 109 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MIYhxmw5rmLrQ6V-MZD:-MIbhUBY8udoBbZ30LCZ:bedw5qk) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L109)):*
<details><summary><i>Previously, mattj23 (Matthew Jarvis) wrote…</i></summary><blockquote>

I didn't know C++ well enough to know that `segment3d.Line3D::IntersectionParameter()` was even possible, so I learned something new today.  

I think that overall I like the `segment3d.line()` the best; it's unambiguous, easy, and uses a familiar interface.  Should it be `segment3d.line()` returning the base `ParametrizedLine<double, 3>`, or a `segment3d.Line3D()` returning the base `Line3D`?  I think it should be the former, since then you get all of the functionality of the underlying Eigen class, does that seem reasonable?

I have some triangle intersection code ready which uses these classes, and I've actually been using it myself in code I'm running for the past few weeks.  I'd like to clean up Line3D as we've been discussing, fix some typos I found in the docs, and potentially add a few line/line distance and intersections tests.  If you're OK with me doing that first I'd be happy to continue to fine-tune the classes as we go.
</blockquote></details>

I was thinking of `segment3d.line()` returning a ref to Line3D but `segment3d.Line3D()` makes a lot more sense as function name for that.

Going forward and fine-tune on the go was just a suggestion. Please add changes as you see fit and until you are comfortable with the PR.


<!-- Sent from Reviewable.io -->

2020-10-02 17:34 UTC, mattj23 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358)* status: all files reviewed, 6 unresolved discussions (waiting on @griegler and @mattj23)

___
*[cpp/open3d/geometry/Line3D.h, line 109 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MIYhxmw5rmLrQ6V-MZD:-MIeLpHKBpwjSN5kY3rM:b-f42mqj) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L109)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

I was thinking of `segment3d.line()` returning a ref to Line3D but `segment3d.Line3D()` makes a lot more sense as function name for that.

Going forward and fine-tune on the go was just a suggestion. Please add changes as you see fit and until you are comfortable with the PR.

</blockquote></details>

I just started in this direction and hit an obstacle.  If I expose a `segment3d.Line3D`, and put a `.PointAt(double)` on `Line3D`, and `Segment3D` and `Ray3D` publicly inherit from `Line3D`, I end up with a `.PointAt(double)` that I don't want directly on `Ray3D` and `Segment3D`.  Is there a way around this? Do I need to make all inheritance private or protected to prevent this?  Do you think that's worth doing for a clean interface, or should I fall back to exposing the `Eigen::ParametrizedLine` which is not publicly inherited to avoid the issue?


<!-- Sent from Reviewable.io -->

2020-10-03 13:45 UTC, benjaminum requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358)* status: all files reviewed, 6 unresolved discussions (waiting on @griegler and @mattj23)

___
*[cpp/open3d/geometry/Line3D.h, line 109 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MIYhxmw5rmLrQ6V-MZD:-MIidgBh8bY8Q206nf9b:b442qtl) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L109)):*
<details><summary><i>Previously, mattj23 (Matthew Jarvis) wrote…</i></summary><blockquote>

I just started in this direction and hit an obstacle.  If I expose a `segment3d.Line3D`, and put a `.PointAt(double)` on `Line3D`, and `Segment3D` and `Ray3D` publicly inherit from `Line3D`, I end up with a `.PointAt(double)` that I don't want directly on `Ray3D` and `Segment3D`.  Is there a way around this? Do I need to make all inheritance private or protected to prevent this?  Do you think that's worth doing for a clean interface, or should I fall back to exposing the `Eigen::ParametrizedLine` which is not publicly inherited to avoid the issue?
</blockquote></details>

Do we want this to work?
```
Line3D* line = new Segment3D();
```


<!-- Sent from Reviewable.io -->

2020-10-03 22:14 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/geometry/Line3D.cpp  19
- cpp/open3d/geometry/Line3D.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-10-03 22:28 UTC, mattj23 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @griegler and @mattj23)

___
*[cpp/open3d/geometry/Line3D.h, line 109 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MIYhxmw5rmLrQ6V-MZD:-MIkXv0v0Fsb-KtgkWXF:b-ob0fx6) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L109)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Do we want this to work?
```
Line3D* line = new Segment3D();
```
</blockquote></details>

I think we do want that to work, if I'm understanding correctly you're simply referring to the ability to refer to a `Ray3D` or a `Segment3D` by its base class, which in my understanding wouldn't be possible if we inherit privately from `Line3D`?  Apologies if that's a dumb question, I'm still getting up to speed on C++ inheritance.  If so, I think we do need that feature, since it's what allowed me to make the interface relatively clean.  

Over the last two days  I tried reworking it so that `Line()` returns the `ParametrizedLine` and the rest came together fairly cleanly.  Take a look when you get a chance and tell me if you think it's alright.


<!-- Sent from Reviewable.io -->

2020-10-04 05:48 UTC, benjaminum approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> , @griegler do you agree with the changes?

> Reviewed 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358#-:-MIm8XK_42rh4CLjdDai:bj8irr9)* status: all files reviewed, 6 unresolved discussions (waiting on @griegler and @mattj23)

___
*[cpp/open3d/geometry/Line3D.h, line 109 at r2](https://reviewable.io/reviews/intel-isl/open3d/2358#-MIYhxmw5rmLrQ6V-MZD:-MIm8NZc9BZl0l0U7t6S:b3bc9m7) ([raw file](https://github.com/intel-isl/open3d/blob/4e0eb10027b32d6cd80f7efa58268af43e4c0bde/cpp/open3d/geometry/Line3D.h#L109)):*
<details><summary><i>Previously, mattj23 (Matthew Jarvis) wrote…</i></summary><blockquote>

I think we do want that to work, if I'm understanding correctly you're simply referring to the ability to refer to a `Ray3D` or a `Segment3D` by its base class, which in my understanding wouldn't be possible if we inherit privately from `Line3D`?  Apologies if that's a dumb question, I'm still getting up to speed on C++ inheritance.  If so, I think we do need that feature, since it's what allowed me to make the interface relatively clean.  

Over the last two days  I tried reworking it so that `Line()` returns the `ParametrizedLine` and the rest came together fairly cleanly.  Take a look when you get a chance and tell me if you think it's alright.
</blockquote></details>

I think this is a good solution.


<!-- Sent from Reviewable.io -->

2020-10-06 12:52 UTC, mattj23 reviewed
@benjaminum , @griegler , is there anything else I need to do at this point?  Reviewable is telling me that there's an action waiting on me, but I can't quite figure out what it is.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358#-:-MIxxn1c3sLEPv95vLOK:bkqw75f)* status: all files reviewed, 6 unresolved discussions (waiting on @griegler and @mattj23)



<!-- Sent from Reviewable.io -->

2020-10-06 13:00 UTC, benjaminum reviewed
I think the discussions are fine but there is a problem with some of the tests. Can you push another commit to trigger the CI actions? I think there is a way to create commits with no code changes but adding some minor change to the docs or code is fine, too. Just want to make sure that we have the latest changes from master for the CI actions.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358#-:-MIxyhieE8apHt7I4grg:bict06d)* status: all files reviewed, 6 unresolved discussions (waiting on @griegler and @mattj23)



<!-- Sent from Reviewable.io -->

2020-10-06 13:19 UTC, mattj23 reviewed
@benjaminum I think I made a mistake when I merged in from upstream a few days ago without checking to see if upstream was passing.  I brought in 77a12c89 which wasn't passing Ubuntu CI and then neither did mine.  It looks like master is at 6ab81875, which seems to be passing.  Is the correct thing for me to do to merge in 6ab818 and retrigger the CI actions?

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358#-:-MIy1rK78AGotIfuERdP:buvwfbv)* status: all files reviewed, 6 unresolved discussions (waiting on @griegler and @mattj23)



<!-- Sent from Reviewable.io -->

2020-10-06 13:36 UTC, benjaminum reviewed
You can also merge with current master to retrigger the CI, that will work, too. As far as I know the code will always be merged with master before running the checks. This means it was rather bad timing for the checks to run than a mistake.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358#-:-MIy6AQI26HUGFeFbW3n:bqiwto8)* status: all files reviewed, 6 unresolved discussions (waiting on @griegler and @mattj23)



<!-- Sent from Reviewable.io -->

2020-10-06 13:50 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/geometry/Line3D.cpp  19
- cpp/open3d/geometry/Line3D.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-10-07 16:48 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/geometry/Line3D.cpp  19
- cpp/open3d/geometry/Line3D.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-10-07 18:50 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/geometry/Line3D.cpp  2
- cpp/tests/geometry/Line3D.cpp  19
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-10-07 20:30 UTC, mattj23 reviewed
@benjaminum Ok, I had some issue with Xcode throwing a warning about a missing virtual destructor, but once I added that the MacOS CI builds worked too.  Aside from the VM tasks that never seem to start, everything should be working now.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358#-:-MJ3jyVfEBs9hk7A2stS:b-fc6c8l)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @benjaminum, @griegler, and @mattj23)



<!-- Sent from Reviewable.io -->

2020-10-09 08:31 UTC, griegler requested changes
Looks good to me. There is a small issue with some characters at the end of a file (see below). Otherwise, I think we are good to merge.

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358#-:-MJBTxhj4QqtZZEytCEY:b-7j7xal)* status: all files reviewed, 3 unresolved discussions (waiting on @mattj23)

___
*[cpp/open3d/geometry/Line3D.cpp, line 375 at r6](https://reviewable.io/reviews/intel-isl/open3d/2358#-MJBTpWa6spHNe28vcEu:-MJBTpWa6spHNe28vcEv:bds3snr) ([raw file](https://github.com/intel-isl/open3d/blob/4d22c648123f7a31f6b570163379afc60806b272/cpp/open3d/geometry/Line3D.cpp#L375)):*
> ```cpp
> 
> }  // namespace geometry
> }  // namespace open3d
> ```

There are some invalid characters after `open3d`


<!-- Sent from Reviewable.io -->

2020-10-09 18:33 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/geometry/Line3D.cpp  19
- cpp/open3d/geometry/Line3D.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-10-09 19:26 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/geometry/Line3D.cpp  19
- cpp/open3d/geometry/Line3D.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-10-10 00:21 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/geometry/Line3D.cpp  2
- cpp/tests/geometry/Line3D.cpp  19
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-10-10 20:44 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/tests/geometry/Line3D.cpp  19
- cpp/open3d/geometry/Line3D.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-10-12 18:50 UTC, griegler approved these changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358)* status: all files reviewed, 2 unresolved discussions (waiting on @mattj23)



<!-- Sent from Reviewable.io -->

2020-10-12 18:57 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/geometry/Line3D.cpp  2
- cpp/tests/geometry/Line3D.cpp  19
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-10-12 19:11 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/geometry/Line3D.cpp  2
- cpp/tests/geometry/Line3D.cpp  19
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-10-12 21:27 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/geometry/Line3D.cpp  2
- cpp/tests/geometry/Line3D.cpp  19
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-10-12 23:25 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/geometry/Line3D.cpp  2
- cpp/tests/geometry/Line3D.cpp  19
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6206567&bid=20243895)

2020-10-13 03:49 UTC, mattj23 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2358#-:-MJV3oTm6TAFLSrJYl3C:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @mattj23)



<!-- Sent from Reviewable.io -->

2020-10-13 14:45 UTC, merged