Shubhamagarwal12/tensor ply read
intel-isl/Open3D pull request #2377
Opened 2020-09-25 11:52 UTC by ShubhamAgarwal12

Added functionality to read ply file to tensor. Added samples for the unit testing.

2020-09-25 11:57 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/io/file_format/FilePLY.cpp  19
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-09-28 09:22 UTC, yxlao requested changes
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2377)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @ShubhamAgarwal12 and @yxlao)

___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 151 at r1](https://reviewable.io/reviews/intel-isl/open3d/2377#-MIIzVZS08I1_VTc8BTd:-MIIzVZS08I1_VTc8BTe:br85xnx) ([raw file](https://github.com/intel-isl/open3d/blob/0fae5be19ce361b26c20d9d747f2577d04ac5f9a/cpp/open3d/io/file_format/FilePLY.cpp#L151)):*
> ```cpp
>     if (index == 2) {  // reading 'z'
>         state_ptr->points.PushBack(
>                 core::Tensor(state_ptr->cur_points, {3}, core::Dtype::Float64));
> ```

we can directly assign x, y, z to the tensorlist individually, without the need for temporary vectors.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 575 at r1](https://reviewable.io/reviews/intel-isl/open3d/2377#-MIJ-2bN9kCBoTs0q7S5:-MIJ-2bN9kCBoTs0q7S6:bn4ej0i) ([raw file](https://github.com/intel-isl/open3d/blob/0fae5be19ce361b26c20d9d747f2577d04ac5f9a/cpp/open3d/io/file_format/FilePLY.cpp#L575)):*
> ```cpp
>     PLYReaderState state;
> 
>     state.vertex_num = ply_set_read_cb(ply_file, "vertex", "x",
> ```

Since the main goal of this PR is to support PLY with different custom attributes (not just vertex, color and normal), is there a way to read the custom attributes from the PLY? We can search for the real-world PLY files (from sources listed in asana and others) to see how custom attributes are used and make sure we can parse them correctly.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 596 at r1](https://reviewable.io/reviews/intel-isl/open3d/2377#-MIIrqhK9lwoY6ehTf-T:-MIIrqhK9lwoY6ehTf-U:b9jjmlt) ([raw file](https://github.com/intel-isl/open3d/blob/0fae5be19ce361b26c20d9d747f2577d04ac5f9a/cpp/open3d/io/file_format/FilePLY.cpp#L596)):*
> ```cpp
>     }
> 
>     state.points = core::TensorList({3}, core::Dtype::Float64);
> ```

Since we already know the number of vertices, could we:
- Add `TensorList(size, element_shape, dtype, device)` constructor for `TensorList` so that it will preallocate memory.
- At the callback function, assign tensors directly to tensorlist, instead of using the push back function.


<!-- Sent from Reviewable.io -->

2020-10-02 09:08 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/io/file_format/FilePLY.cpp  19
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-09 06:24 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/io/file_format/FilePLY.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-09 06:54 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/io/file_format/FilePLY.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-09 07:08 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/io/file_format/FilePLY.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-13 06:21 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/io/file_format/FilePLY.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-13 06:27 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/io/file_format/FilePLY.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-14 08:04 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/io/file_format/FilePLY.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-14 08:26 UTC, yxlao requested changes
> Reviewed 2 of 9 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2377)* status: 4 of 8 files reviewed, 10 unresolved discussions (waiting on @ShubhamAgarwal12 and @yxlao)

___
*[cpp/open3d/core/TensorList.h, line 89 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa74227K5sgWVdi-G1:-MJa74227K5sgWVdi-G2:b-53w44d) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/core/TensorList.h#L89)):*
> ```objc
>     /// Constructs a tensorlist with specified size
>     ///
>     /// \param size of the tensorlist
> ```

`Size of the tensorlist.` 
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 34 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa7HDk79lG7_kssYGh:-MJa7HDl2GWVf0r1xYvD:b19nbh1) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L34)):*
> ```cpp
> #include "open3d/io/TriangleMeshIO.h"
> #include "open3d/io/VoxelGridIO.h"
> #include "open3d/t/io/PointCloudIO.h"
> ```

remove this
actually, can we reset this file to be the same as `master`?
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1009 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa7VQN6_YGjCZSDCxH:-MJa7VQN6_YGjCZSDCxI:b-eo42zp) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1009)):*
> ```cpp
> }  // namespace io
> 
> namespace t {
> ```

Move all the `namespace t` items into the `open3d/t` directory.  We shall keep the change to the `open3d/io` directory minimal.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1016 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa82aS9B_hR8jbur1W:-MJa82aS9B_hR8jbur1X:b-z0kpk0) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1016)):*
> ```cpp
> struct PLYReaderState {
>     utility::CountingProgressReporter *progress_bar;
>     std::unordered_map<std::string, core::TensorList> properties;
> ```

Rename `properties` to `attributes` to be consistent, see `cpp/open3d/t/geometry/PointCloud.h`
Same for the rest.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1017 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa7v3JArNktF0H2EPi:-MJa7v3KBjZwA0-WNafk:b-ypt209) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1017)):*
> ```cpp
>     utility::CountingProgressReporter *progress_bar;
>     std::unordered_map<std::string, core::TensorList> properties;
>     std::vector<const char *> property_name;
> ```

can we use string instead of char?
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1018 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa8J5k300CLgbag5hK:-MJa8J5k300CLgbag5hL:b-fmtbe9) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1018)):*
> ```cpp
>     std::unordered_map<std::string, core::TensorList> properties;
>     std::vector<const char *> property_name;
>     std::vector<long> property_index;
> ```

Use `int64_t` to be consistent with the int types in `TensorList.h`, same for the test.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1065 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa9JFh3N9ZVX-VeIIE:-MJa9JFh3N9ZVX-VeIIF:b-r3h6zt) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1065)):*
> ```cpp
>     long property_id = 0;
> 
>     // get first ply element; assuming it will be vertex
> ```

individual comment line shall start with a capital letter and end with `.`, same for other comments.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1070 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa9lfnBDHudmWZujZE:-MJa9lfnBDHudmWZujZF:bcc3tnb) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1070)):*
> ```cpp
> 
>     while (property) {
>         state.property_name.push_back("");
> ```

i would initialize an empty `std::string property_name` here, after the value is filed, then push it to the vector.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1100 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJaC52K9rJqaRRL_xA0:-MJaC52K9rJqaRRL_xA1:b-9vwbft) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1100)):*
> ```cpp
>     // add base elements
>     if (state.properties.find("x") != state.properties.end()) {
>         core::TensorList points = core::TensorList(
> ```

i would create a lambda function `ConcatColumns` where:
- it takes 3 tensorlists as input, and it checks the tensorlists are 1d, same length, same type and same device
- it returns a new tensorlist of size (N, 3)

this way we can reuse the code to deal with points, normals and colors
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1103 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJaBtIwEAnFKFgMmBJc:-MJaBtIwEAnFKFgMmBJd:bv5brkn) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1103)):*
> ```cpp
>                 state.property_num[property_id - 1], {3}, core::Dtype::Float64);
>         points.AsTensor().Slice(1, 0, 1) =
>                 state.properties["x"].AsTensor().Slice(1, 0, 1);
> ```

the second `Slice()` is not necessary.


<!-- Sent from Reviewable.io -->

2020-10-15 02:46 UTC, yxlao requested changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2377)* status: 5 of 8 files reviewed, 11 unresolved discussions (waiting on @ShubhamAgarwal12)

___
*[examples/test_data/test_sample_ascii.ply, line 4 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJe86IbC7Yeq3WgYyw4:-MJe86IbC7Yeq3WgYyw5:b66ukoq) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/examples/test_data/test_sample_ascii.ply#L4)):*
> ```
> format ascii 1.0
> element vertex 7
> property float32 x
> ```

Let's respect the datatype specified in the `ply` file, i.e. create the same data type tensorlist. If it is not supported in our `Dtype.h` we can throw an exception.


<!-- Sent from Reviewable.io -->

2020-10-15 18:44 UTC, ShubhamAgarwal12 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2377)* status: 5 of 8 files reviewed, 11 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/TensorList.h, line 89 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa74227K5sgWVdi-G1:-MJflTnE-9Ai6aR4zrqi:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/core/TensorList.h#L89)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`Size of the tensorlist.` 
</blockquote></details>

Done.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 151 at r1](https://reviewable.io/reviews/intel-isl/open3d/2377#-MIIzVZS08I1_VTc8BTd:-MJVg1w78U3p8u-r0Cpp:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0fae5be19ce361b26c20d9d747f2577d04ac5f9a/cpp/open3d/io/file_format/FilePLY.cpp#L151)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we can directly assign x, y, z to the tensorlist individually, without the need for temporary vectors.
</blockquote></details>

Done.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 575 at r1](https://reviewable.io/reviews/intel-isl/open3d/2377#-MIJ-2bN9kCBoTs0q7S5:-MJVg0aXBHawldJpnRM4:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0fae5be19ce361b26c20d9d747f2577d04ac5f9a/cpp/open3d/io/file_format/FilePLY.cpp#L575)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Since the main goal of this PR is to support PLY with different custom attributes (not just vertex, color and normal), is there a way to read the custom attributes from the PLY? We can search for the real-world PLY files (from sources listed in asana and others) to see how custom attributes are used and make sure we can parse them correctly.
</blockquote></details>

Done.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 596 at r1](https://reviewable.io/reviews/intel-isl/open3d/2377#-MIIrqhK9lwoY6ehTf-T:-MJVfy-DAQz-0geMnqYK:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/0fae5be19ce361b26c20d9d747f2577d04ac5f9a/cpp/open3d/io/file_format/FilePLY.cpp#L596)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Since we already know the number of vertices, could we:
- Add `TensorList(size, element_shape, dtype, device)` constructor for `TensorList` so that it will preallocate memory.
- At the callback function, assign tensors directly to tensorlist, instead of using the push back function.
</blockquote></details>

Done.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 34 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa7HDk79lG7_kssYGh:-MJflZ7W9-skBwukdnBn:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L34)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove this
actually, can we reset this file to be the same as `master`?
</blockquote></details>

Done.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1009 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa7VQN6_YGjCZSDCxH:-MJflZTUCnE1phzZ89eM:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1009)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Move all the `namespace t` items into the `open3d/t` directory.  We shall keep the change to the `open3d/io` directory minimal.
</blockquote></details>

Done.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1016 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa82aS9B_hR8jbur1W:-MJflemH5VcjF2LC5Jlk:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1016)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Rename `properties` to `attributes` to be consistent, see `cpp/open3d/t/geometry/PointCloud.h`
Same for the rest.

</blockquote></details>

Done.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1017 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa7v3JArNktF0H2EPi:-MJfpEHh2-o9l_q9Sqot:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1017)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

can we use string instead of char?
</blockquote></details>

Done.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1018 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa8J5k300CLgbag5hK:-MJft8uVBwCd-HY0cJ_G:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1018)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Use `int64_t` to be consistent with the int types in `TensorList.h`, same for the test.
</blockquote></details>

Done.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1065 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa9JFh3N9ZVX-VeIIE:-MJfuD-O63Ien9F6myko:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1065)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

individual comment line shall start with a capital letter and end with `.`, same for other comments.
</blockquote></details>

Done.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1070 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa9lfnBDHudmWZujZE:-MJfuFkuAZGOv5XD5xbZ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1070)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

i would initialize an empty `std::string property_name` here, after the value is filed, then push it to the vector.
</blockquote></details>

Done.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1100 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJaC52K9rJqaRRL_xA0:-MJh9im39QANDfs6DCDW:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1100)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

i would create a lambda function `ConcatColumns` where:
- it takes 3 tensorlists as input, and it checks the tensorlists are 1d, same length, same type and same device
- it returns a new tensorlist of size (N, 3)

this way we can reuse the code to deal with points, normals and colors
</blockquote></details>

Done.
___
*[cpp/open3d/io/file_format/FilePLY.cpp, line 1103 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJaBtIwEAnFKFgMmBJc:-MJh9jzC5Hk6erh0TcKt:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/io/file_format/FilePLY.cpp#L1103)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

the second `Slice()` is not necessary.
</blockquote></details>

Done.
___
*[examples/test_data/test_sample_ascii.ply, line 4 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJe86IbC7Yeq3WgYyw4:-MJhZV-M1vSY1X6QG1dZ:bf170t5) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/examples/test_data/test_sample_ascii.ply#L4)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Let's respect the datatype specified in the `ply` file, i.e. create the same data type tensorlist. If it is not supported in our `Dtype.h` we can throw an exception.
</blockquote></details>

Usually for colours, there can be dat [...]

2020-10-16 04:02 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/t/io/file_format/FilePLY.cpp  1
- cpp/open3d/io/file_format/FilePLY.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-16 04:57 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/t/io/file_format/FilePLY.cpp  1
- cpp/open3d/io/file_format/FilePLY.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-16 06:07 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/t/io/file_format/FilePLY.cpp  1
- cpp/open3d/io/file_format/FilePLY.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-16 06:20 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/t/io/file_format/FilePLY.cpp  1
- cpp/open3d/io/file_format/FilePLY.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-16 08:36 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- cpp/open3d/t/io/file_format/FilePLY.cpp  1
- cpp/open3d/io/file_format/FilePLY.cpp  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-16 11:29 UTC, yxlao requested changes
> Reviewed 1 of 6 files at r1, 1 of 9 files at r2, 5 of 6 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2377)* status: all files reviewed, 20 unresolved discussions (waiting on @ShubhamAgarwal12)

___
*[cpp/open3d/core/TensorList.h, line 89 at r3](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJa74227K5sgWVdi-G1:-MJk4qd9-KKVl0R54TfC:b-f2dwrn) ([raw file](https://github.com/intel-isl/open3d/blob/347650df46a7b0f7f17ad0e85d8e43d6d33bd41a/cpp/open3d/core/TensorList.h#L89)):*
<details><summary><i>Previously, ShubhamAgarwal12 (Shubham Agarwal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

add `.` at the end.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 52 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl4v_t5Sv6IdCZZCEu:-MJl4v_t5Sv6IdCZZCEv:b-izphnr) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L52)):*
> ```cpp
> };
> 
> int ReadPropertyCallback(p_ply_argument argument) {
> ```

rename all property to attributes to be consistent with the `PointCloud` class
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 54 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl699119pmYqykcuXC:-MJl699119pmYqykcuXD:b5ff0mb) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L54)):*
> ```cpp
> int ReadPropertyCallback(p_ply_argument argument) {
>     PLYReaderState *state_ptr;
>     long id;
> ```

use `int64_t` since the `attribute_index` and `attribute_num` are all `int64_t`
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 61 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl6Mlv3XbIQMoqPAMo:-MJl6Mlv3XbIQMoqPAMp:b-jsooh) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L61)):*
> ```cpp
>     }
> 
>     double value = ply_get_argument_value(argument);
> ```

Just for the information, the inputs can be different data types, if we use double here, how are we handling different types?
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 64 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl6_nvCktgxekHFZF5:-MJl6_nvCktgxekHFZF6:b8q3a79) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L64)):*
> ```cpp
> 
>     state_ptr->attributes[state_ptr->attribute_name[id]]
>                          [state_ptr->attribute_index[id]][0] = value;
> ```

why do we need the `[0]`, are they 1-d list always?
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 72 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl60mwB_ZVm0Q3RCRK:-MJl60mwB_ZVm0Q3RCRL:bjgwkee) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L72)):*
> ```cpp
> }
> 
> bool ConcatColumns(core::TensorList a,
> ```

use `const core::TensorList&` as inputs
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 76 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl5QmN9KFl1hlB1OjK:-MJl5QmN9KFl1hlB1OjL:b4rexhh) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L76)):*
> ```cpp
>                    core::TensorList c,
>                    core::TensorList &combined) {
>     if (!(a.GetSize() == b.GetSize()) || !(a.GetSize() == c.GetSize()))
> ```

add `{}` to be consistent
`a.GetSize() != b.GetSize()` is simpler
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 78 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl5SKS0v9ooVVVban7:-MJl5SKS0v9ooVVVban8:b-nuad4o) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L78)):*
> ```cpp
>     if (!(a.GetSize() == b.GetSize()) || !(a.GetSize() == c.GetSize()))
>         return false;
>     if (!(a.GetDtype() == b.GetDtype()) || !(a.GetDtype() == c.GetDtype()))
> ```

add `{}` to be consistent
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 87 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl6-ia5-YuSbm0OQUp:-MJl6-ia5-YuSbm0OQUq:b-rzhpbe) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L87)):*
> ```cpp
>     combined.AsTensor().Slice(1, 2, 3) = c.AsTensor();
> 
>     return true;
> ```

return `core::TensorList`, otherwise, throw exception
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 90 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl6ysf6AveQDc3E2cG:-MJl6ysf6AveQDc3E2cH:bdtnqrb) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L90)):*
> ```cpp
> }
> 
> core::Dtype getDtype(e_ply_type type) {
> ```

`core::Dtype GetDtype(e_ply_type type)`
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 125 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl7IOd31dkG70HjI4m:-MJl7IOd31dkG70HjI4n:b-but9vf) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L125)):*
> ```cpp
>     using namespace ply_pointcloud_reader;
> 
>     p_ply ply_file = ply_open(filename.c_str(), NULL, 0, NULL);
> ```

let's use `null_ptr`, same for other `NULL`
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 127 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl8enuE9GkiwBydLfx:-MJl8enuE9GkiwBydLfy:bgiktri) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L127)):*
> ```cpp
>     p_ply ply_file = ply_open(filename.c_str(), NULL, 0, NULL);
>     if (!ply_file) {
>         utility::LogWarning("Read PLY failed: unable to open file: {}",
> ```

add `.`
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 140 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl7QBp0Qn3c2i4Uz34:-MJl7QBp0Qn3c2i4Uz35:bo4z57n) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L140)):*
> ```cpp
>     p_ply_property property = NULL;
>     e_ply_type type, length_type, value_type;
>     long property_id = 0;
> ```

`int_64 t`
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 145 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl56XDCrP2xspajFYo:-MJl56XDCrP2xspajFYp:b-ygnz4d) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L145)):*
> ```cpp
>     // Get first ply element; assuming it will be vertex.
>     p_ply_element element = ply_get_next_element(ply_file, NULL);
>     property = ply_get_next_property(element, NULL);
> ```

same, rename all property to attributes to be consistent with the `PointCloud` class
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 152 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl7Y5QA1uXG4U9sban:-MJl7Y5QA1uXG4U9sbao:bgiktri) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L152)):*
> ```cpp
> 
>         if (getDtype(type) == core::Dtype::Undefined) {
>             utility::LogWarning("Read PLY failed: unsupported datatype");
> ```

add `.`
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 175 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl7ZH1AmRvzqkaq1tH:-MJl7ZH1AmRvzqkaq1tI:bgiktri) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L175)):*
> ```cpp
> 
>     if (!ply_read(ply_file)) {
>         utility::LogWarning("Read PLY failed: unable to read file: {}",
> ```

add `.`
___
*[cpp/open3d/t/io/ [...]

2020-10-16 15:16 UTC, ShubhamAgarwal12 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2377)* status: 7 of 10 files reviewed, 20 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 52 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl4v_t5Sv6IdCZZCEu:-MJlkNnD7r_DZaRpMUPT:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L52)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

rename all property to attributes to be consistent with the `PointCloud` class
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 54 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl699119pmYqykcuXC:-MJlk_FND_glw6ff5qOb:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L54)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

use `int64_t` since the `attribute_index` and `attribute_num` are all `int64_t`
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 61 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl6Mlv3XbIQMoqPAMo:-MJlmI-s1sKIwF-vywLn:bfgjot5) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L61)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Just for the information, the inputs can be different data types, if we use double here, how are we handling different types?
</blockquote></details>

The function ply_get_argument_value returns a double value. I thought, since it is the largest of all the datatypes in ply. It will be able to store all kinds of data. 
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 64 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl6_nvCktgxekHFZF5:-MJlmtlF5nuPGz-iIreC:b-5q57no) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L64)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

why do we need the `[0]`, are they 1-d list always?
</blockquote></details>

Yes, currently it reads only 1-d lists. There is a datatype PLY_VECTOR which has higher dimensional data but that can have different datatypes in a list so we can't pass it to the TensorList.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 72 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl60mwB_ZVm0Q3RCRK:-MJlnnbYANcrsPQg5b-C:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L72)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

use `const core::TensorList&` as inputs
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 76 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl5QmN9KFl1hlB1OjK:-MJls7-HBmuAK27g2bNa:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L76)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add `{}` to be consistent
`a.GetSize() != b.GetSize()` is simpler
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 78 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl5SKS0v9ooVVVban7:-MJlsIeoBbJykMeV9diC:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L78)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add `{}` to be consistent
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 87 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl6-ia5-YuSbm0OQUp:-MJlyqN74eOgfJXOqTSw:b-heql9r) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L87)):*
> This is not an exception. A user may want to specify only red and blue colours instead of all 3 or may rename some other field to "red" with a different datatype.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 90 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl6ysf6AveQDc3E2cG:-MJlsuEY9qQnaC8Ej8X2:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L90)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`core::Dtype GetDtype(e_ply_type type)`
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 125 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl7IOd31dkG70HjI4m:-MJlu2O04f7vKCNmjPg6:b-k0qwp) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L125)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

let's use `null_ptr`, same for other `NULL`
</blockquote></details>

null_ptr seems to be only there in the test files.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 127 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl8enuE9GkiwBydLfx:-MJluXo_EZHevHfL3WoP:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L127)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add `.`
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 140 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl7QBp0Qn3c2i4Uz34:-MJludJB8Z3shphkcTgi:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L140)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`int_64 t`
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 145 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl56XDCrP2xspajFYo:-MJludby9xQRoaLcYCsd:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L145)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same, rename all property to attributes to be consistent with the `PointCloud` class
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 152 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl7Y5QA1uXG4U9sban:-MJluetV2iCRfyP6vzH2:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L152)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add `.`
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 175 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl7ZH1AmRvzqkaq1tH:-MJlugbl7saFkY-9MXEf:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L175)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add `.`
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 186 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl9EHWEo0IBKONC7zZ:-MJluz2W4yHez6BCIOvy:b-5um9gz) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L186)):*
<details><summary><i>Previously, yxlao (Y [...]

2020-10-16 15:25 UTC, ShubhamAgarwal12 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2377)* status: 7 of 10 files reviewed, 20 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 54 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl699119pmYqykcuXC:-MJm-_ZN9Cd6FmKMzjZ6:blwb2j9) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L54)):*
<details><summary><i>Previously, ShubhamAgarwal12 (Shubham Agarwal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, pressed Done by mistake. ply_get_argument_user_data function requires the datatype to be long.


<!-- Sent from Reviewable.io -->

2020-10-19 06:59 UTC, ShubhamAgarwal12 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2377)* status: 5 of 9 files reviewed, 20 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 87 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl6-ia5-YuSbm0OQUp:-MJzcrCv9JElZY_nTC92:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L87)):*
<details><summary><i>Previously, ShubhamAgarwal12 (Shubham Agarwal) wrote…</i></summary><blockquote>

> This is not an exception. A user may want to specify only red and blue colours instead of all 3 or may rename some other field to "red" with a different datatype.
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 125 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl7IOd31dkG70HjI4m:-MJzcsxiAGC697mSAPKj:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L125)):*
<details><summary><i>Previously, ShubhamAgarwal12 (Shubham Agarwal) wrote…</i></summary><blockquote>

null_ptr seems to be only there in the test files.
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 186 at r6](https://reviewable.io/reviews/intel-isl/open3d/2377#-MJl9EHWEo0IBKONC7zZ:-MJzdaeZ122vQY-e1j7r:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f7823d1ee7521c22092d28d683c719bd0630fe91/cpp/open3d/t/io/file_format/FilePLY.cpp#L186)):*
<details><summary><i>Previously, ShubhamAgarwal12 (Shubham Agarwal) wrote…</i></summary><blockquote>

The issue is: This is not an exception. A user may want to specify only red and blue colours instead of all 3 or may rename some other field to "red" with a different datatype.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-22 04:44 UTC, yxlao reviewed
1. Remove individual attributes after combination
2. Performance speedup
3. After ignoring unsupported attr, continue with the supported ones
   Print msg about the dtype name and attribute that are skipped
4. (Future PR) option to convert to the nearest type

> Reviewed 4 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2377#-:-MKDblZ04jKSL3iGwKkk:bcblnhe)* status: all files reviewed, 1 unresolved discussion (waiting on @yxlao)



<!-- Sent from Reviewable.io -->

2020-10-22 11:06 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-22 12:10 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-22 13:41 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-22 20:38 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-23 02:16 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-25 09:35 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-25 13:12 UTC, yxlao requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2377)* status: 6 of 9 files reviewed, 15 unresolved discussions (waiting on @ShubhamAgarwal12 and @yxlao)

___
*[cpp/open3d/core/TensorList.h, line 94 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUscHmErFKXG0-p4v4:-MKUscHmErFKXG0-p4v5:b-17neby) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/core/TensorList.h#L94)):*
> ```objc
>     /// \param dtype Data type of the contained tensors. e.g. Dtype::Float32.
>     /// \param device Device of the contained tensors. e.g. Device("CPU:0").
>     TensorList(long size,
> ```

Use `int64_t` to avoid windows compilation errors on CI.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 77 at r7](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUquVz4i4cdmxv2_NL:-MKUquVz4i4cdmxv2_NM:b9x82cb) ([raw file](https://github.com/intel-isl/open3d/blob/cd0cd4ff9b73517d296d2086c075425663c89dde/cpp/open3d/t/io/file_format/FilePLY.cpp#L77)):*
> ```cpp
>     core::TensorList combined;
> 
>     if ((a.GetSize() != b.GetSize()) || (a.GetSize() != c.GetSize())) {
> ```

Check`a.NumDims() == 1`, same for b, c.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 42 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUqC6i4-4Lck9w9qdl:-MKUqC6i4-4Lck9w9qdm:bsk2mnr) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L42)):*
> ```cpp
> namespace io {
> 
> namespace ply_pointcloud_reader {
> ```

Remove this namespace. Now, these helper functions can be used for pointcloud/mesh/..., we don't need to make a namespace explicitly for pointcloud.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 44 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUpBaX-X12kGOUYQ_9:-MKUpBaX-X12kGOUYQ_A:b69yrjo) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L44)):*
> ```cpp
> namespace ply_pointcloud_reader {
> 
> struct PLYReaderState {
> ```

### Suggestion 1
This structure is not optimal, e.g. we have several vectors that are fragmented, e.g.
```cpp
attribute_name[id]
attribute_index[id]
attribute_num[id]
```

It's better to group them into one new struct. so that they can share the same index, E.g.
```cpp
attribute_struct[id].name
attribute_struct[id].index
attribute_struct[id].num
```

### Suggestion 2
Use `name_`, which is the conversion of other open3d classes, and it's more clear about member functions.


Reference implementation:
```cpp
struct PLYReaderState {
    struct AttrState {
        std::string name_;
        core::Tensor data_;
        int64_t total_size_;
        int64_t current_size_;
    };
    // Allow fast access of attr_state by name.
    std::unordered_map<std::string, std::shared_ptr<AttrState>>
            name_to_attr_state_;
    // Allow fast access of attr_state by index.
    std::vector<std::shared_ptr<AttrState>> id_to_attr_state_;
    utility::CountingProgressReporter *progress_bar_;
};
```

You'll need to update other locations to adopt this new design.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 53 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUq5wK00v5tUE1VSqS:-MKUq5wK00v5tUE1VSqT:bpc9e7d) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L53)):*
> ```cpp
> 
> template <typename T>
> int ReadAttributeCallback(p_ply_argument argument) {
> ```

use `static` function for all local functions. Same for all other functions.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 68 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUqSHEAUtNCprgJ5I7:-MKUqSHF8vCkTeV4hyFw:bskk97o) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L68)):*
> ```cpp
>                                 [state_ptr->attribute_index[id]]
>                     .GetDataPtr());
>     a_ptr[0] = value;
> ```

Avoid slice. Do:
```cpp
    T *a_ptr = static_cast<T *>(
            state_ptr
                    ->attributes[state_ptr->attribute_name[id]].GetDataPtr());
```

and then:
```cpp
a_ptr[state_ptr->attribute_index[id]] = static_cast<T>(value);
```

According to my test, this approach is several times faster. 
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 80 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUqqHlCULkmcu0H5q_:-MKUqqHlCULkmcu0H5qa:b-4g88yu) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L80)):*
> ```cpp
>                                const core::Tensor &b,
>                                const core::Tensor &c) {
>     core::TensorList combined;
> ```

Move this declaration to right before it is used.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 136 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUr4rb6Bw5w2OLiN-L:-MKUr4rb6Bw5w2OLiN-M:bih1qf9) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L136)):*
> ```cpp
>     } else if (type == PLY_LIST) {
>         return "list";
>     }
> ```

`else {return "unknown";}`
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 188 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUrDTUAgDAqZfeCGYt:-MKUrDTUAgDAqZfeCGYu:bvbiyhp) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L188)):*
> ```cpp
>     }
> 
>     PLYReaderState state;
> ```

Of all these declarations, move them to right before their first usage.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 195 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUrMDf1T3nV2828Bsi:-MKUrMDf1T3nV2828Bsj:b-1l7tiw) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L195)):*
> ```cpp
>     int64_t temp_num = 0;
> 
>     // Get first ply element; assuming it will be vertex.
> ```

We cannot make this assumption.  Loop through all elements, and find the one called "vertex". 
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 200 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUsF1qDXTIdkoZk9JH:-MKUsF1qDXTIdkoZk9JI:bfrpso2) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L200)):*
> ```cpp
> 
>     while (attribute) {
>         ply_get_property_info(attribute, &attribute_nm, &type, &length_type,
> ```

`length_type` and `value_type` is never used, simply replace it with `nullptr`
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 208 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUsPCB2G7ZfLvT3nsk:-MKUsPCB2G7ZfLvT3nsl:b-lbag69) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L208)):*
> ```cpp
>                     "datatype \"{}\".",
>                     attribute_nm, GetDtypeString(type));
>             attribute = ply_get_next_property(element, attribute);
> ```

i think there's a logic error here. You'll also need to do `attribute_id++;`
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 231 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUrVmc57hQzduFXElZ:-MKUrVmc57hQzduFXEl_:boux3fs) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L231)):*
> ```cpp
> 
>     utility::CountingProgressReporter reporter(params.update_progress);
>     reporter.SetTotal(state.attribute_num[0]);
> ```

Same, we can't just pick a random `[0]-th` element to get the size. Use `ply_get_element_info` to get the common size for `vertex`, not just for one [...]

2020-10-25 13:20 UTC, yxlao commented
@ShubhamAgarwal12 Please check out https://github.com/intel-isl/Open3D/blob/yixing/t-ply-read/cpp/open3d/t/io/file_format/FilePLY.cpp for an example implementation of the review comments above. 

You may also use this benchmark script to measure the performance of different implementations:
```python
import open3d as o3d
import time
import numpy as np


if __name__ == "__main__":
    file_name = "/path/to/Open3D/examples/test_data/fragment.ply"
    iterations = 20

    # Benchmark T IO
    s = time.time()
    for _ in range(iterations):
        pct = o3d.t.io.read_point_cloud(file_name)
    print("Time for t.io: ", (time.time() - s) / iterations)

    # Benchmark old IO
    s = time.time()
    for _ in range(iterations):
        pcd = o3d.io.read_point_cloud(file_name)
    print("Time for io: ", (time.time() - s) / iterations)

    # Sanity check
    print(pct.point["points"])
    np.testing.assert_allclose(pct.point["points"].as_tensor().numpy(),
                               np.asarray(pcd.points))

```

2020-10-27 13:27 UTC, ShubhamAgarwal12 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2377)* status: 5 of 9 files reviewed, 15 unresolved discussions (waiting on @ShubhamAgarwal12 and @yxlao)

___
*[cpp/open3d/core/TensorList.h, line 94 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUscHmErFKXG0-p4v4:-MKdMPJAAIZBLLEjiQaC:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/core/TensorList.h#L94)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Use `int64_t` to avoid windows compilation errors on CI.
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 77 at r7](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUquVz4i4cdmxv2_NL:-MKdO1-C0FYONiaYMeD0:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/cd0cd4ff9b73517d296d2086c075425663c89dde/cpp/open3d/t/io/file_format/FilePLY.cpp#L77)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Check`a.NumDims() == 1`, same for b, c.
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 44 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUpBaX-X12kGOUYQ_9:-MKdxtxT7NxRYw1LEng_:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L44)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

### Suggestion 1
This structure is not optimal, e.g. we have several vectors that are fragmented, e.g.
```cpp
attribute_name[id]
attribute_index[id]
attribute_num[id]
```

It's better to group them into one new struct. so that they can share the same index, E.g.
```cpp
attribute_struct[id].name
attribute_struct[id].index
attribute_struct[id].num
```

### Suggestion 2
Use `name_`, which is the conversion of other open3d classes, and it's more clear about member functions.


Reference implementation:
```cpp
struct PLYReaderState {
    struct AttrState {
        std::string name_;
        core::Tensor data_;
        int64_t total_size_;
        int64_t current_size_;
    };
    // Allow fast access of attr_state by name.
    std::unordered_map<std::string, std::shared_ptr<AttrState>>
            name_to_attr_state_;
    // Allow fast access of attr_state by index.
    std::vector<std::shared_ptr<AttrState>> id_to_attr_state_;
    utility::CountingProgressReporter *progress_bar_;
};
```

You'll need to update other locations to adopt this new design.

</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 53 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUq5wK00v5tUE1VSqS:-MKdMzKQBPdVxCB-Ne8n:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L53)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

use `static` function for all local functions. Same for all other functions.
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 68 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUqSHEAUtNCprgJ5I7:-MKdxsBkATBqMlUyYJL9:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L68)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Avoid slice. Do:
```cpp
    T *a_ptr = static_cast<T *>(
            state_ptr
                    ->attributes[state_ptr->attribute_name[id]].GetDataPtr());
```

and then:
```cpp
a_ptr[state_ptr->attribute_index[id]] = static_cast<T>(value);
```

According to my test, this approach is several times faster. 
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 80 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUqqHlCULkmcu0H5q_:-MKdNz_P7CZu3a1d12x1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L80)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Move this declaration to right before it is used.
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 136 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUr4rb6Bw5w2OLiN-L:-MKdO6edDnBTTg79IAc6:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L136)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`else {return "unknown";}`
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 188 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUrDTUAgDAqZfeCGYt:-MKdXO1qEKgGAhxaW08l:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L188)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Of all these declarations, move them to right before their first usage.
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 195 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUrMDf1T3nV2828Bsi:-MKdXPBe6Au2bxigfx3a:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L195)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We cannot make this assumption.  Loop through all elements, and find the one called "vertex". 
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 200 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUsF1qDXTIdkoZk9JH:-MKdXQGl8qN_AMwmpFe-:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L200)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`length_type` and `value_type` is never used, simply replace it with `nullptr`
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 208 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUsPCB2G7ZfLvT3nsk:-MKdXquh6K3tKWaULuvK:blfoxcw) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L208)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

i think there's a logic error here. You'll also need to do `attribute_id++;`
</blockquote></details>

No, I think this should be fine as the index is only used to access the elements from the vector and for Undefined case, the element is not added to the vector itself. 
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 231 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUrVmc57hQzduFXElZ:-MKdYbsACBjUctYYNyFS:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L231)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Same, we can't just pick a random `[0]-th` element to get the size. Use `ply_get_element_info` to get the common size for `vertex`, not just for one attribute of `vertex`.
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 244 at r10](https://reviewable.io/reviews/intel-isl/open3d/2377#-MKUslPG2t-eRfjBjTez:-MKdZoZd0hdWJEguBVCr:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1b1ca46dafc7f792673a0d482c69cd25acf77242/cpp/open3d/t/io/file_format/FilePLY.cpp#L244)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

use `count` instead of `find`, it is more concise. [...]

2020-10-27 13:31 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-27 13:41 UTC, germanros1987 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6237063&bid=20321160)

2020-10-28 09:19 UTC, yxlao approved these changes
> Reviewed 2 of 3 files at r8, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2377)* status: all files reviewed, 4 unresolved discussions (waiting on @ShubhamAgarwal12 and @yxlao)



<!-- Sent from Reviewable.io -->

2020-10-28 09:20 UTC, merged