Added max error threshold
intel-isl/Open3D pull request #2411
Opened 2020-10-01 22:00 UTC by FreakTheMighty

This pull request adds a maximum error threshold to `SimplifyQuadricDecimation`. This allows a user to target a particular quality rather than only targeting a specific triangle count. For example, a user could generate two levels of detail like so:

```python
lq = mesh.simplify_quadric_decimation(2, maximum_error=1e-6)
hq = mesh.simplify_quadric_decimation(2, maximum_error=1e-10)
```

The algorithm will attempt to reduce the mesh to 2 faces, but will exit when it exceeds the specified maximum error.

2020-10-01 22:11 UTC, FreakTheMighty commented
Perhaps someone could help me identify the style issues here. There aren't any details on the CI (that I can find) and I'm struggling to get clear direction from `clang-format`

2020-10-02 06:29 UTC, griegler requested changes
Thanks for your contribution.

Regarding style issues, you can have a look [here](http://www.open3d.org/docs/release/contribute/styleguide.html#open3d-style-guide). If you have installed the correct versions of clang-format and yapf it should reduce to `make apply-style` in your build directory.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2411#-:-MIbyYC81F8t4hL-Gj3a:b-7x4x5v)* status: all files reviewed, 3 unresolved discussions (waiting on @FreakTheMighty)

___
*[cpp/open3d/geometry/TriangleMesh.h, line 415 at r1](https://reviewable.io/reviews/intel-isl/open3d/2411#-MIbz0CnDVw9cTf7pAgh:-MIbz0CnDVw9cTf7pAgi:b-6fu22z) ([raw file](https://github.com/intel-isl/open3d/blob/9a27b50183a687676cb10a7ec6ad7849fa2a1aa3/cpp/open3d/geometry/TriangleMesh.h#L415)):*
> ```objc
>     /// Function to simplify mesh using Quadric Error Metric Decimation by
>     /// Garland and Heckbert.
>     /// \param target_number_of_triangles defines the number of triangles that
> ```

Can you please add a short description of the new parameter here.
___
*[cpp/open3d/geometry/TriangleMesh.h, line 419 at r1](https://reviewable.io/reviews/intel-isl/open3d/2411#-MIbytUW-2OBu1c0PJKO:-MIbytUW-2OBu1c0PJKP:b-bk6cqk) ([raw file](https://github.com/intel-isl/open3d/blob/9a27b50183a687676cb10a7ec6ad7849fa2a1aa3/cpp/open3d/geometry/TriangleMesh.h#L419)):*
> ```objc
>     /// will be reached.
>     std::shared_ptr<TriangleMesh> SimplifyQuadricDecimation(
>             int target_number_of_triangles, float maximum_error) const;
> ```

can we change it to `double maximum_error`, just to be consistent with most other parameters in Open3D. 
___
*[cpp/pybind/geometry/trianglemesh.cpp, line 600 at r1](https://reviewable.io/reviews/intel-isl/open3d/2411#-MIbzkqe-1OEsFWfhL-G:-MIbzkqf50d18ybqb2tl:b8li9hf) ([raw file](https://github.com/intel-isl/open3d/blob/9a27b50183a687676cb10a7ec6ad7849fa2a1aa3/cpp/pybind/geometry/trianglemesh.cpp#L600)):*
> ```cpp
>             {{"target_number_of_triangles",
>               "The number of triangles that the simplified mesh should have. "
>               "It is not guaranteed that this number will be reached."}});
> ```

Could you please add a short description of the new param here too. This is the doc that Python will show.


<!-- Sent from Reviewable.io -->

2020-10-02 14:32 UTC, FreakTheMighty commented
@griegler I believe I've address all of your notes. I'm still working on applying the formatting. I think those docs are a bit out of date. The `_find_clang_format` method seems to be looking for a newer version of `clang-format` then is recommended in the docs.

2020-10-02 14:37 UTC, FreakTheMighty commented
Alright, style fixed!

2020-10-02 15:04 UTC, griegler approved these changes
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2411)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-03 11:02 UTC, merged