Allow arbitrary pinhole camera
intel-isl/Open3D pull request #2564
Opened 2020-11-02 00:05 UTC by pablospe

Function to get view controller from arbitrary pinhole camera parameters. In this function, it is responsibility of the users to
verify the validity of the parameters, in contrast to `ConvertFromPinholeCameraParameters()` function. This can be useful to render images or depthmaps without any restriction in FOV, zoom, etc.

Example of use (python): https://github.com/pablospe/open3D_depthmap_example
(code is already compiled, and can be installed with pip).

This PR is related to the following git issues: #1417, #497, #727, #834, #1389, #2443, #1164, #2036.

2020-11-02 00:57 UTC, pablospe commented
`Style check` seems to fail. I am not sure about the error. Any idea?

2020-11-02 01:26 UTC, theNded commented
> `Style check` seems to fail. I am not sure about the error. Any idea?

Can you please try `make apply-style` and push again?

2020-11-02 12:38 UTC, pablospe commented
Thanks, Wei Dong! I know you from your time at CVG :)

2020-11-02 16:08 UTC, theNded requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2564)* status: all files reviewed, 2 unresolved discussions (waiting on @pablospe)

___
*[cpp/open3d/visualization/visualizer/ViewControl.cpp, line 191 at r2](https://reviewable.io/reviews/intel-isl/open3d/2564#-ML8_AerD-AYZqAZebWk:-ML8_AerD-AYZqAZebWl:b-2eq0w) ([raw file](https://github.com/intel-isl/open3d/blob/0be9574d7229e4b6da15d84202bb5fc23dcc4611/cpp/open3d/visualization/visualizer/ViewControl.cpp#L191)):*
> ```cpp
> }
> 
> bool ViewControl::ConvertFromArbitraryPinholeCameraParameters(
> ```

Many lines of code are duplicates here. I guess a better practice could be adding a flag to `ConvertFromPinholeCameraParameters`, and change the condition checks accordingly: `ViewControl::ConvertFromPinholeCameraParameters(const camera::PinholeCameraParameters & parameters, bool allow_arbitrary=false)`
___
*[cpp/pybind/visualization/viewcontrol.cpp, line 74 at r2](https://reviewable.io/reviews/intel-isl/open3d/2564#-ML8hm7BCQq0x3l1Wovm:-ML8hm7BCQq0x3l1Wovn:bfdey2s) ([raw file](https://github.com/intel-isl/open3d/blob/0be9574d7229e4b6da15d84202bb5fc23dcc4611/cpp/pybind/visualization/viewcontrol.cpp#L74)):*
> ```cpp
>             .def("convert_from_pinhole_camera_parameters",
>                  &ViewControl::ConvertFromPinholeCameraParameters,
>                  "parameter"_a)
> ```

As mentioned above, might be good to add "allow_arbitrary"_a directly to `convert_from_pinhole_camera_parameters`


<!-- Sent from Reviewable.io -->

2020-11-02 16:09 UTC, theNded commented
> Thanks, Wei Dong! I know you from your time at CVG :)

Haha, nice to meet you here again! :-)

2020-11-02 21:47 UTC, pablospe commented
> ViewControl::ConvertFromPinholeCameraParameters(const camera::PinholeCameraParameters & parameters, bool allow_arbitrary=false)

Sounds good. I will implement the changes, it will be a few `if`s which might make the function even more difficult to understand than the current version, but I can give a try. Another possibility is to split the function is smaller functions like this:
https://github.com/intel-isl/Open3D/blob/6a111774345e551d520fa367e4d2c7ff78da3196/cpp/open3d/visualization/visualizer/ViewControl.cpp#L249-L253
and so on. Some code will be repeated but it will be more modular.

What I tried was to implement `ConvertFromPinholeCameraParameters` using the new function `ConvertFromArbitraryPinholeCameraParameters` but the `ProjectionType::Orthogonal` part makes the logic a bit tricky.

To be sincere I don't really understand why all these restrictions are needed in the first place, I believe the reason is to control, for instance, the amount of zoom the user can make to avoid going to infinity. Sometimes I actually would wish to be able to do "more zoom" and I find these constraints a limitation (especially for headless rendering where no user interaction is envolved). I also noticed (but only in Windows) that I can't render images of bigger size than my screen resolution, so the limit for the window size might be related to GLFW. Also, for the FOV, I didn't find a good reason to have a `FIELD_OF_VIEW_MIN`.

2020-11-03 17:37 UTC, pablospe commented
@theNded I made the changes you requested, but I now get the following error when importing open3d in python (compilation and installation seems with `make install; make install-pip-package`)
```
>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/linux_home/pablo/miniconda3/envs/open3d/lib/python3.8/site-packages/open3d/__init__.py", line 83, in <module>
    from open3d.cpu.pybind import (camera, geometry, io, pipelines, utility, t)
ImportError: SystemError: <built-in method join of str object at 0x7f84fac28fb0> returned a result with an error set
>>> 
```

Here the proposed code:
https://github.com/pablospe/Open3D/commit/ed9b60a4115e98a1152a35bba1592572b7b26468
(since it is not working I didn't push it in this branch)

2020-11-05 16:29 UTC, theNded commented
> @theNded I made the changes you requested, but I now get the following error when importing open3d in python (compilation and installation seems with `make install; make install-pip-package`)
> 
> ```
> >>> import open3d
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/mnt/linux_home/pablo/miniconda3/envs/open3d/lib/python3.8/site-packages/open3d/__init__.py", line 83, in <module>
>     from open3d.cpu.pybind import (camera, geometry, io, pipelines, utility, t)
> ImportError: SystemError: <built-in method join of str object at 0x7f84fac28fb0> returned a result with an error set
> >>> 
> ```
> 
> Here the proposed code:
> [pablospe@ed9b60a](https://github.com/pablospe/Open3D/commit/ed9b60a4115e98a1152a35bba1592572b7b26468)
> (since it is not working I didn't push it in this branch)

Sorry for coming back late, I will give you an update today!

2020-11-06 02:46 UTC, theNded commented
It was from this line. Pybind has changed its API but docstring is still there. Removing this line will fix the problem.
https://github.com/pablospe/Open3D/blob/ed9b60a4115e98a1152a35bba1592572b7b26468/cpp/pybind/visualization/viewcontrol.cpp#L111

2020-11-06 17:11 UTC, pablospe commented
> It was from this line. Pybind has changed its API but docstring is still there. Removing this line will fix the problem.
> https://github.com/pablospe/Open3D/blob/ed9b60a4115e98a1152a35bba1592572b7b26468/cpp/pybind/visualization/viewcontrol.cpp#L111

Totally forgot about that. Thanks a lot for taking the time to look at it, specially now it is CVPR deadline! :)

2020-11-06 18:21 UTC, pablospe commented
A test is falling but I believe this is not related to this PR.


`Windows CI / Test wheel (3.8) (pull_request) Failing after 40s
`
```
###### End Diagnostic HTTP information ######
Error: Unable to get ContainersItems from https://pipelines.actions.githubusercontent.com/dILGkAUFyGAIS8pmYBOmQLxTECjnsuN2fuMFAzAEbYPHkkQU5q/_apis/resources/Containers/6380400?itemPath=open3d_win_amd64_wheels
```

```
{"$id":"1","innerException":null,"message":"The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```

2020-11-07 03:00 UTC, theNded commented
@errissa This PR lgtm and won't interrupt current functionalities. May I merge if you think it looks fine?

2020-11-10 21:34 UTC, errissa commented
@theNded This looks good to merge to me.

2020-11-11 01:05 UTC, theNded reviewed
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2564)* status: all files reviewed, 2 unresolved discussions (waiting on @pablospe)



<!-- Sent from Reviewable.io -->

2020-11-11 01:05 UTC, merged

2020-12-01 19:06 UTC, Zumbalamambo commented
@pablospe could you please share the corresponding python wheel that fixes this issue?

2020-12-01 19:39 UTC, pablospe commented
In this example of use (python): https://github.com/pablospe/open3D_depthmap_example
(code is already compiled, and can be installed with pip)

I believe in the open3d version 0.11.3 these commits will be included. I just don't know what is the open3d roadmap and how often a new version is released. Hopefully it is released soon:
https://pypi.org/project/open3d/#history