[Draft] Add draw() as replacement for draw_geometries()
intel-isl/Open3D pull request #2585
Opened 2020-11-06 02:25 UTC by prewettg

Still remaining:
- general animations
- keyframe animations
- asynchronous adding geometry
- ExternalVisualizer RPC support
- on_init callback
- export SetUIState to be callback externally
- add visualization of VoxelGrid to renderer
- add visualization of background image when geometry::Image is passed in

2020-11-19 16:50 UTC, benjaminum requested changes
Most comments are about the scene tree. For the functions called by the user we should rename arguments "geometry" to "obj" to make it shorter and more general.

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2585#-:-MMW-y_JCdHXgnMtxhYW:b-nb6tf3)* status: all files reviewed, 12 unresolved discussions (waiting on @prewettg)

___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 62 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVmxfv7oJ71G2x3Cor:-MMVmxfv7oJ71G2x3Cos:b6mx38f) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L62)):*
> ```objc
>     enum class Shader { STANDARD, NORMALS, DEPTH };
> 
>     struct DrawObject {
> ```

No change request, just a comment:
This is good! Would it help you if we have an interface class for objects that can be passed to the visualizer? All objects that we want to draw have to subclass a Drawable class.
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 108 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVk2Oq58bPWJewzad_:-MMVk2Oq58bPWJewzada:b29zbgs) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L108)):*
> ```objc
>     void SetShader(Shader shader);
> 
>     void AddGeometry(const std::string& name,
> ```

I think there was a misunderstanding with the layers. Can we do groups with the object name? E.g., name="group/subgroup/myobject".
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 113 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVliSm9YAvEb3bq0ed:-MMVliSm9YAvEb3bq0ee:b4bmun7) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L113)):*
> ```objc
>                      const std::string& group = "",
>                      double time = 0.0,
>                      bool is_visible = true);
> ```

No change request, just a comment:
Passing properties like "is_visible" is good. In the future we may want something more generic because the number of properties will grow.
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 122 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVmInQ15ZAtOT_TBkf:-MMVmInQ15ZAtOT_TBkg:bluki3l) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L122)):*
> ```objc
>                      bool is_visible = true);
> 
>     void RemoveGeometry(const std::string& name);
> ```

We can call this function `RemoveObject()`  and use it also for objects that are not geometries like cameras or lights.
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 124 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVmbsp-Yah4FTtew-m:-MMVmbsqC_5bCreKnkdd:b-2nnlv3) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L124)):*
> ```objc
>     void RemoveGeometry(const std::string& name);
> 
>     void ShowGeometry(const std::string& name, bool show);
> ```

Same here `ShowObject()` or `SetObjectVisibility()`
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 126 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVmq3T4fytZ1ayj07O:-MMVmq3T4fytZ1ayj07P:bgah7al) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L126)):*
> ```objc
>     void ShowGeometry(const std::string& name, bool show);
> 
>     DrawObject GetGeometry(const std::string& name) const;
> ```

`GetObject`. How can I get the object that I have set at time=t?
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 133 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVnmxw53fWmC4FXC4Y:-MMVnmxw53fWmC4FXC4Z:b8naqak) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L133)):*
> ```objc
>     void ShowSkybox(bool show);
>     void ShowAxes(bool show);
>     void EnableGroup(const std::string& group, bool enable);
> ```

Probably not necessary, because it will be the same as `ShowObject()`.
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.cpp, line 595 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVqKLg-EF1nt_GPFfF:-MMVqKLg-EF1nt_GPFfG:brimz07) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.cpp#L595)):*
> ```cpp
>         // Geometry list
>         settings.geometries_panel =
>                 new CollapsableVert("Geometries", v_spacing, margins);
> ```

Geometries -> Scene (or Scene tree because we have already used scene).
___
*[cpp/pybind/visualization/drawvisualizer.cpp, line 93 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVy8uz82warFgNmw64:-MMVy8uz82warFgNmw65:b-2w4aok) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/pybind/visualization/drawvisualizer.cpp#L93)):*
> ```cpp
>                  "one parameter, the DrawVisualizer instance, and does not "
>                  "return any value.")
>             .def("add_geometry",
> ```

Can we name this just "add"? or "set" if we can use it to overwrite existing objects. As a python user we do not care much about the type and want to do `add([mesh, camera, light])`.
___
*[examples/python/gui/draw.py, line 92 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVzcR_4oQ77dDXXAJs:-MMVzcR_4oQ77dDXXAJt:b1udsoz) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/examples/python/gui/draw.py#L92)):*
> ```Python
> 
> 
> def actions():
> ```

This feature is just awesome!
___
*[examples/python/gui/draw.py, line 146 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVzyQy5-tgjJq7vnW-:-MMVzyQy5-tgjJq7vnW0:b-hal5br) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/examples/python/gui/draw.py#L146)):*
> ```Python
> 
> 
> def groups():
> ```

The check state does not propagate to the children. Is this intentional?
___
*[python/open3d/visualization/draw.py, line 5 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMW-ZLY1kGbL_awPaE9:-MMW-ZLY1kGbL_awPaEA:b-g31wzf) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/python/open3d/visualization/draw.py#L5)):*
> ```Python
> 
> 
> def draw(geometry=None,
> ```

We need to sync here to make the interface of the ExternalVisualizer compatible.


<!-- Sent from Reviewable.io -->

2020-12-03 23:47 UTC, errissa requested changes
> Reviewed 16 of 39 files at r2, 1 of 13 files at r3, 1 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2585)* status: 19 of 44 files reviewed, 16 unresolved discussions (waiting on @benjaminum, @errissa, and @prewettg)

___
*[cpp/open3d/visualization/gui/Materials/unlitPolygonOffset.mat, line 14 at r4](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNexX5C2BuRlVr1XB3O:-MNexX5C2BuRlVr1XB3P:b-6o3wew) ([raw file](https://github.com/intel-isl/open3d/blob/2b2f9c3a5bd4d2b22c3d818b1328d39fa3e1a29e/cpp/open3d/visualization/gui/Materials/unlitPolygonOffset.mat#L14)):*
> ```
> vertex {
>     void materialVertex(inout MaterialVertexInputs material) {
>         float4 toCamera = 0.001f * (float4(getWorldCameraPosition(), 1.0f) - material.worldPosition);
> ```

This will move the vertex toward/away from camera an amount proportional to the distance between camera and vertex. the bigger the distance the bigger the offset. this is similar to the using the `factor` parameter of glPolygonOffset. The `units` parameter of glPolygonOffset is a constant offset.
___
*[cpp/open3d/visualization/gui/Materials/unlitPolygonOffset.mat, line 16 at r4](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNex3YsDeBSXMwswKYb:-MNex3YuEJTdmEgIVAbk:bx9nc89) ([raw file](https://github.com/intel-isl/open3d/blob/2b2f9c3a5bd4d2b22c3d818b1328d39fa3e1a29e/cpp/open3d/visualization/gui/Materials/unlitPolygonOffset.mat#L16)):*
> ```
>         float4 toCamera = 0.001f * (float4(getWorldCameraPosition(), 1.0f) - material.worldPosition);
>         material.worldPosition += toCamera;
>         
> ```

are these red spaces? If so, the unnecessary spaces should be removed. check-style would catch that if the .mat files were C++ files.
___
*[cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp, line 81 at r4](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNezH_Z7a1diN5ryzIH:-MNezH_Z7a1diN5ryzII:b-wmrmnb) ([raw file](https://github.com/intel-isl/open3d/blob/2b2f9c3a5bd4d2b22c3d818b1328d39fa3e1a29e/cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp#L81)):*
> ```cpp
>     auto e_matrix = t.matrix();
>     return filament::math::mat4(filament::math::mat4::row_major_init{
>             e_matrix(0, 0), e_matrix(0, 1), e_matrix(0, 2), e_matrix(0, 3),
> ```

why this commented out code?
___
*[cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp, line 159 at r4](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNeze9J79mSNUGQCwJb:-MNeze9K-aLwLOGY9XAd:bj2xqu9) ([raw file](https://github.com/intel-isl/open3d/blob/2b2f9c3a5bd4d2b22c3d818b1328d39fa3e1a29e/cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp#L159)):*
> ```cpp
> 
> double FilamentCamera::GetFieldOfView() const {
>     if (projection_.is_defined_by_planes) {
> ```

This comment confuses me a little. is the purpose of the `is_defined_by_planes` flag to set orthographic projections? You can also set perspective projections using planes which would have meaningful FOVs.


<!-- Sent from Reviewable.io -->

2020-12-04 02:40 UTC, prewettg reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2585)* status: 19 of 44 files reviewed, 16 unresolved discussions (waiting on @benjaminum, @errissa, and @prewettg)

___
*[cpp/open3d/visualization/gui/Materials/unlitPolygonOffset.mat, line 14 at r4](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNexX5C2BuRlVr1XB3O:-MNfUXbT8wer2x7g2Bov:b-qdp9ka) ([raw file](https://github.com/intel-isl/open3d/blob/2b2f9c3a5bd4d2b22c3d818b1328d39fa3e1a29e/cpp/open3d/visualization/gui/Materials/unlitPolygonOffset.mat#L14)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

This will move the vertex toward/away from camera an amount proportional to the distance between camera and vertex. the bigger the distance the bigger the offset. this is similar to the using the `factor` parameter of glPolygonOffset. The `units` parameter of glPolygonOffset is a constant offset.
</blockquote></details>

That was my intent. Not sure I understand the question/problem?
___
*[cpp/open3d/visualization/gui/Materials/unlitPolygonOffset.mat, line 16 at r4](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNex3YsDeBSXMwswKYb:-MNfULgJ-lb28d6JiJMh:b194zjo) ([raw file](https://github.com/intel-isl/open3d/blob/2b2f9c3a5bd4d2b22c3d818b1328d39fa3e1a29e/cpp/open3d/visualization/gui/Materials/unlitPolygonOffset.mat#L16)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

are these red spaces? If so, the unnecessary spaces should be removed. check-style would catch that if the .mat files were C++ files.
</blockquote></details>

Yep, seem to be spaces. I use Emacs to edit, and the autoindent puts in spaces, and I don't always remember to remove them, apparently. Removed
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 108 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVk2Oq58bPWJewzad_:-MNfXS6J2Mke6SKkH-jY:b3odha5) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L108)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

I think there was a misunderstanding with the layers. Can we do groups with the object name? E.g., name="group/subgroup/myobject".
</blockquote></details>

Depends on time. It may have to wait until we do a full scene graph
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 113 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVliSm9YAvEb3bq0ed:-MNfXbncC2YKekXK0l-5:b-47oghg) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L113)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

No change request, just a comment:
Passing properties like "is_visible" is good. In the future we may want something more generic because the number of properties will grow.
</blockquote></details>

I'd prefer not to prematurely optimize for genericity. If we can't articulate what kinds of generic things are needed now, I think it's better to wait until we know what we need and refactor. This may be a part of the scene graph, anyway.
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 122 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVmInQ15ZAtOT_TBkf:-MNfXzMHCCZDjVBNZA1x:b91tqtm) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L122)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

We can call this function `RemoveObject()`  and use it also for objects that are not geometries like cameras or lights.
</blockquote></details>

This makes more sense for the scene graph. This current version is meant as more of a draw_geometries() replacement
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 124 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVmbsp-Yah4FTtew-m:-MNfY5wE4LyiIgDdJFni:b-3ju4d8) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L124)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Same here `ShowObject()` or `SetObjectVisibility()`
</blockquote></details>

This makes more sense for the scene graph. This current version is meant as more of a draw_geometries() replacement.
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 126 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVmq3T4fytZ1ayj07O:-MNfY7ZH9yq8Xfpto4xb:b-dnzcxl) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L126)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

`GetObject`. How can I get the object that I have set at time=t?
</blockquote></details>

I think callers should keep track of that themselves. But maybe a scene graph query would be useful.
___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.cpp, line 595 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVqKLg-EF1nt_GPFfF:-MNfYixZ--HnMW1thOhT:b-hkp859) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.cpp#L595)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Geometries -> Scene (or Scene tree because we have already used scene).
</blockquote></details>

Deferring until we actually get a proper scene graph.


<!-- Sent from Reviewable.io -->

2020-12-04 02:42 UTC, prewettg reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2585)* status: 16 of 44 files reviewed, 16 unresolved discussions (waiting on @benjaminum, @errissa, and @prewettg)

___
*[cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp, line 81 at r4](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNezH_Z7a1diN5ryzIH:-MNfbxQ8EHu8gXemdx-H:bbwg5s) ([raw file](https://github.com/intel-isl/open3d/blob/2b2f9c3a5bd4d2b22c3d818b1328d39fa3e1a29e/cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp#L81)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

why this commented out code?
</blockquote></details>

Historical reasons. Removed
___
*[cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp, line 159 at r4](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNeze9J79mSNUGQCwJb:-MNfc1NiB6lYvVDlwphX:bp09w1z) ([raw file](https://github.com/intel-isl/open3d/blob/2b2f9c3a5bd4d2b22c3d818b1328d39fa3e1a29e/cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp#L159)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

This comment confuses me a little. is the purpose of the `is_defined_by_planes` flag to set orthographic projections? You can also set perspective projections using planes which would have meaningful FOVs.
</blockquote></details>

True, hadn't thought about that, although given the interface to Camera, the only way you can specify planes is perpendicular ones... I changed the names in the structures to be more precise.


<!-- Sent from Reviewable.io -->

2020-12-04 07:34 UTC, benjaminum requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2585)* status: 16 of 44 files reviewed, 17 unresolved discussions (waiting on @benjaminum, @errissa, and @prewettg)

___
*[cpp/open3d/visualization/visualizer/DrawVisualizer.h, line 126 at r1](https://reviewable.io/reviews/intel-isl/open3d/2585#-MMVmq3T4fytZ1ayj07O:-MNg7eE-AFv2lW-ohlnO:b142uqg) ([raw file](https://github.com/intel-isl/open3d/blob/a8085fe4b3ac5a1d2a23cbd67432fb13ac5363cf/cpp/open3d/visualization/visualizer/DrawVisualizer.h#L126)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

I think callers should keep track of that themselves. But maybe a scene graph query would be useful.
</blockquote></details>

Yes, but they need to be able to pass the time parameter.
___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.h, line 120 at r5](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNgdkpQ-MXhyClqOZ4W:-MNgdkpQ-MXhyClqOZ4X:b-2gnypu) ([raw file](https://github.com/intel-isl/open3d/blob/108815a3f3ab71cf2bd29a74b4b2107d8884e708/cpp/open3d/visualization/visualizer/O3DVisualizer.h#L120)):*
> ```objc
>                      rendering::Material* material = nullptr,
>                      const std::string& group = "",
>                      double order = 0.0,
> ```

time, please.


<!-- Sent from Reviewable.io -->

2020-12-04 17:13 UTC, prewettg reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2585)* status: 16 of 44 files reviewed, 17 unresolved discussions (waiting on @benjaminum, @errissa, and @prewettg)

___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.h, line 120 at r5](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNgdkpQ-MXhyClqOZ4W:-MNij-Nj4X2eyw9kFGVO:b-eer4cu) ([raw file](https://github.com/intel-isl/open3d/blob/108815a3f3ab71cf2bd29a74b4b2107d8884e708/cpp/open3d/visualization/visualizer/O3DVisualizer.h#L120)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

time, please.
</blockquote></details>

German nixed the idea of time. Instead he wants an ordering, so that if you give objects with t=[0, 1, 2, 7] you don't get five seconds of nothing. So it's no longer clock time, but if your timestep is constant (presumably most cases), "order" and "time" are essentially the same thing.


<!-- Sent from Reviewable.io -->

2020-12-04 17:32 UTC, benjaminum reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2585)* status: 16 of 44 files reviewed, 17 unresolved discussions (waiting on @benjaminum, @errissa, @germanros1987, and @prewettg)

___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.h, line 120 at r5](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNgdkpQ-MXhyClqOZ4W:-MNilXka7LrnAwCxK48-:b-8ifzh8) ([raw file](https://github.com/intel-isl/open3d/blob/108815a3f3ab71cf2bd29a74b4b2107d8884e708/cpp/open3d/visualization/visualizer/O3DVisualizer.h#L120)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

German nixed the idea of time. Instead he wants an ordering, so that if you give objects with t=[0, 1, 2, 7] you don't get five seconds of nothing. So it's no longer clock time, but if your timestep is constant (presumably most cases), "order" and "time" are essentially the same thing.
</blockquote></details>

Yes, it is the same and even if we call it time there wouldn't be five seconds of nothing. Calling it time makes the parameter easy to understand because in most of the cases we will use time to order the objects. @germanros1987 can we call it time? If I could wish for one of the comments to be addressed, it would be this one.


<!-- Sent from Reviewable.io -->

2020-12-04 18:52 UTC, prewettg reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2585)* status: 16 of 46 files reviewed, 17 unresolved discussions (waiting on @benjaminum, @errissa, @germanros1987, and @prewettg)

___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.h, line 120 at r5](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNgdkpQ-MXhyClqOZ4W:-MNj2RIZ8cdNkfvaAMJM:bx7nik0) ([raw file](https://github.com/intel-isl/open3d/blob/108815a3f3ab71cf2bd29a74b4b2107d8884e708/cpp/open3d/visualization/visualizer/O3DVisualizer.h#L120)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Yes, it is the same and even if we call it time there wouldn't be five seconds of nothing. Calling it time makes the parameter easy to understand because in most of the cases we will use time to order the objects. @germanros1987 can we call it time? If I could wish for one of the comments to be addressed, it would be this one.
</blockquote></details>

But "time" is specifically what this is not. If I specify objects at t=[0, 1, 2, 3], I would expect to see object 1 show up at 1.0 seconds, object 2 at 2.0 seconds, etc. But what will happen is that object 1 shows up at 100 ms (that being the default frame time), object 2 at 200 ms, etc. Likewise, if I am specifying time, then I would expect with t=[0, 1, 5] that object 0 is displayed for 1 second, object 1 for 4 seconds (1.0 - 4.99), and object 2 for one frame. But in actuality what will happen is that object 0 will be displayed for 100 ms, then object 1 for 100 ms, and object 2 for 100 ms. So instead of a 5+ second animation as suggested by "time", we actually get a 300 ms animation (assuming the default frame time of 100 ms). Actually, the length of the animation is entirely dependent on len(unique_times) * frame_time, which is completely opposite of the expectation of a parameter named "time", at least to my way of thinking. To my mind, if a parameter is called "time", then implied units is "seconds" (possibly also "milliseconds");  in this case the unit is "frame number as given by the index into the list of sorted unique values, not the actual value specified by the parameter", which I submit are two completely different things. At least with a parameter named "order" you are under no illusions that it corresponds to anything related to the passing of events as commonly measured in seconds.


<!-- Sent from Reviewable.io -->

2020-12-04 18:59 UTC, benjaminum reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2585)* status: 16 of 46 files reviewed, 10 unresolved discussions (waiting on @benjaminum, @errissa, @germanros1987, and @prewettg)

___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.h, line 120 at r5](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNgdkpQ-MXhyClqOZ4W:-MNj63zG4EjG9mCcYCUJ:b-9mqylm) ([raw file](https://github.com/intel-isl/open3d/blob/108815a3f3ab71cf2bd29a74b4b2107d8884e708/cpp/open3d/visualization/visualizer/O3DVisualizer.h#L120)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

But "time" is specifically what this is not. If I specify objects at t=[0, 1, 2, 3], I would expect to see object 1 show up at 1.0 seconds, object 2 at 2.0 seconds, etc. But what will happen is that object 1 shows up at 100 ms (that being the default frame time), object 2 at 200 ms, etc. Likewise, if I am specifying time, then I would expect with t=[0, 1, 5] that object 0 is displayed for 1 second, object 1 for 4 seconds (1.0 - 4.99), and object 2 for one frame. But in actuality what will happen is that object 0 will be displayed for 100 ms, then object 1 for 100 ms, and object 2 for 100 ms. So instead of a 5+ second animation as suggested by "time", we actually get a 300 ms animation (assuming the default frame time of 100 ms). Actually, the length of the animation is entirely dependent on len(unique_times) * frame_time, which is completely opposite of the expectation of a parameter named "time", at least to my way of thinking. To my mind, if a parameter is called "time", then implied units is "seconds" (possibly also "milliseconds");  in this case the unit is "frame number as given by the index into the list of sorted unique values, not the actual value specified by the parameter", which I submit are two completely different things. At least with a parameter named "order" you are under no illusions that it corresponds to anything related to the passing of events as commonly measured in seconds.
</blockquote></details>

Please have a look at the visualization examples+viewer that I compiled.


<!-- Sent from Reviewable.io -->

2020-12-08 03:22 UTC, errissa requested changes
> Reviewed 4 of 39 files at r2, 3 of 13 files at r3, 5 of 13 files at r4, 3 of 4 files at r5, 16 of 17 files at r6, 3 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2585)* status: 39 of 47 files reviewed, 8 unresolved discussions (waiting on @errissa, @germanros1987, and @prewettg)

___
*[cpp/open3d/visualization/gui/Materials/unlitPolygonOffset.mat, line 14 at r4](https://reviewable.io/reviews/intel-isl/open3d/2585#-MNexX5C2BuRlVr1XB3O:-MO-Kc0L-Fh2TuM8ZbjG:bngmth6) ([raw file](https://github.com/intel-isl/open3d/blob/2b2f9c3a5bd4d2b22c3d818b1328d39fa3e1a29e/cpp/open3d/visualization/gui/Materials/unlitPolygonOffset.mat#L14)):*
<details><summary><i>Previously, prewettg wrote…</i></summary><blockquote>

That was my intent. Not sure I understand the question/problem?
</blockquote></details>

There's no problem, just wanted to make sure you understood that this isn't an exact replacement for glPolygonOffset and that the solution you implemented is what you wanted. It seems to work when I tested.
___
*[cpp/open3d/visualization/visualizer/O3DVisualizerSelections.h, line 107 at r7](https://reviewable.io/reviews/intel-isl/open3d/2585#-MO-LzL8CdSn4dX3-dos:-MO-LzL8CdSn4dX3-dot:b-pstgp) ([raw file](https://github.com/intel-isl/open3d/blob/4a7b8b159698123782a3576a0e70420341adfceb/cpp/open3d/visualization/visualizer/O3DVisualizerSelections.h#L107)):*
> ```objc
>     };
> 
>     int point_size_ = 3;
> ```

why point size of 3 as the default?


<!-- Sent from Reviewable.io -->

2020-12-08 16:44 UTC, benjaminum approved these changes
LGTM. Some changes will be addressed in another PR. @prewettg please check @errissa comments before merging.

> Reviewed 1 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2585#-:-MO2Dgsr2pnwTTJ3XimI:b3dzif3)* status: 28 of 45 files reviewed, 8 unresolved discussions (waiting on @errissa, @germanros1987, and @prewettg)



<!-- Sent from Reviewable.io -->

2020-12-09 23:53 UTC, errissa reviewed
> Reviewed 8 of 11 files at r7, 7 of 10 files at r8, 7 of 8 files at r10.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2585)* status: 45 of 46 files reviewed, 8 unresolved discussions (waiting on @errissa, @germanros1987, and @prewettg)



<!-- Sent from Reviewable.io -->

2020-12-10 15:31 UTC, errissa approved these changes

2020-12-10 21:32 UTC, merged