RealSense SDK v2
intel-isl/Open3D pull request #2646
Opened 2020-11-20 05:53 UTC by ssheorey

- RealSense SDK v2 build is complicated and result in multiple libraries, firmware files and dependency on libusb. New method of installing such 3rd party libraries using [this method](https://crascit.com/2015/07/25/cmake-gtest/) but with `find_package()` instead of `add_subdirectory()` to keep `librealsense` build config separate from our build config. This downloads, builds and installs librealsense during configure step, so that `find_package()` can find it.
- The build adds ~5 minutes - switching to USE_SYSTEM_LIBREALSENSE=ON by default is recommended.
- Support for RealSense bag file format: RGB8/BGR8/ARGB8/ABGR8 + Z16 format with same frame rate for color and depth.
- New example for reading RS bag file and visualizing color and depth: `RealSenseBagReader`. 
- New example for connecting to RealSense cameras and and visualizing color and depth: `RealSenseViewer`: User can select resolution and frame rates and can also align depth image to color image.
- Tensor based RGBDImage class
- Conversion of tensor based Image and RGBDImage classes to legacy classes

2020-11-21 15:23 UTC, theNded commented
Just curious: are we dropping rs's official python binding and use our data structures (in C++) as a bridge? I tried and it seems official pybind for rs is especially hard to configure on macOS.

2020-11-23 21:23 UTC, ssheorey commented
> Just curious: are we dropping rs's official python binding and use our data structures (in C++) as a bridge? I tried and it seems official pybind for rs is especially hard to configure on macOS.

Yes, that is the plan. Official RS doesn't support macOS. They have a some feature requests for it, but not sure if they are planning to officially support it.

We have sufficient functionality in this PR for basic RGBD acquisition for Open3D. Do let me know if something is missing.

2020-12-10 00:49 UTC, ssheorey commented
Some Windows CI workflows are failing due to disk space errors.

2020-12-11 21:58 UTC, theNded requested changes
> Reviewed 53 of 71 files at r1, 2 of 11 files at r2, 5 of 15 files at r3, 8 of 17 files at r6, 14 of 18 files at r8, 1 of 2 files at r9, 10 of 11 files at r10.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2646)* status: all files reviewed, 6 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[cpp/open3d/t/geometry/Image.cpp, line 80 at r9](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOIWm8gBdeNrle8uMwI:-MOIWm8gBdeNrle8uMwJ:bsbnfi0) ([raw file](https://github.com/intel-isl/open3d/blob/37758c96708398b5b8e50470f3ad89f63f892e81/cpp/open3d/t/geometry/Image.cpp#L80)):*
> ```cpp
>         memcpy(image_legacy.data_.data(), data_.GetDataPtr(),
>                image_legacy.data_.size());
>     } else {
> ```

Is this critical for RealSense's internal data? Otherwise I think directly using `.Contiguous` + memcpy would be enough.
___
*[cpp/open3d/t/io/sensor/realsense/RSBagReader.h, line 115 at r10](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOIaElR1gf2OOqq7aqb:-MOIaElR1gf2OOqq7aqc:bs24fgx) ([raw file](https://github.com/intel-isl/open3d/blob/052f8c249c766105a520e7dbb20bc6b41c624ada/cpp/open3d/t/io/sensor/realsense/RSBagReader.h#L115)):*
> ```objc
>     bool is_eof_ = false,  ///< Write by frame_reader_thread. Non-atomic OK
>                            ///< since 1 byte.
>             is_opened_ = false;  ///< Read by frame_reader_thread. Non-atomic OK
> ```

Separate properties by `;`
___
*[cpp/open3d/t/io/sensor/realsense/RSBagReader.h, line 131 at r10](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOIaQDx1c74eDl0rrRJ:-MOIaQDx1c74eDl0rrRK:bs24fgx) ([raw file](https://github.com/intel-isl/open3d/blob/052f8c249c766105a520e7dbb20bc6b41c624ada/cpp/open3d/t/io/sensor/realsense/RSBagReader.h#L131)):*
> ```objc
>             frame_position_us_;  ///< buffer for frame position in us
>     std::atomic<uint64_t> head_fid{
>             0},           ///< Next write position by frame_reader_thread.
> ```

Separate properties by `;`
___
*[cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp, line 230 at r10](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOImGf52fHhL-87fL0W:-MOImGf69wJaLaLSFDau:b7t4bs4) ([raw file](https://github.com/intel-isl/open3d/blob/052f8c249c766105a520e7dbb20bc6b41c624ada/cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp#L230)):*
> ```cpp
>         need_frames.wait(lock, [this] {
>             return !is_opened_ ||
>                    head_fid < tail_fid + frame_buffer_.size() / 4;
> ```

What is 4 here? Can you comment / replace it with a const number here?
___
*[cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp, line 246 at r10](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOImtAw44KrT671NRmt:-MOImtAw44KrT671NRmu:b2nreh6) ([raw file](https://github.com/intel-isl/open3d/blob/052f8c249c766105a520e7dbb20bc6b41c624ada/cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp#L246)):*
> ```cpp
>         utility::LogError("Null file handler. Please call Open().");
>     }
>     if (!is_eof_ && head_fid < tail_fid + frame_buffer_.size() / 4)
> ```

Same as above.
___
*[examples/python/reconstruction_system/config/realsense.json, line 3 at r10](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOIntVL4x01KTMz36sH:-MOIntVL4x01KTMz36sI:b-rih0u8) ([raw file](https://github.com/intel-isl/open3d/blob/052f8c249c766105a520e7dbb20bc6b41c624ada/examples/python/reconstruction_system/config/realsense.json#L3)):*
> ```JSON
> {
>     "name": "Realsense bag file",
>     "path_dataset": "dataset/realsense.bag",
> ```

Will you please update the script to download an example file as well (once they are ready)? Or maybe I can upload it once it is ready.


<!-- Sent from Reviewable.io -->

2020-12-14 03:56 UTC, yxlao requested changes
> Reviewed 50 of 71 files at r1, 1 of 11 files at r2, 5 of 15 files at r3, 8 of 17 files at r6, 13 of 18 files at r8, 1 of 2 files at r9, 10 of 11 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2646)* status: all files reviewed, 28 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/geometry/Geometry2D.h, line 1 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTmouq9yXOQOX1SQCt:-MOTmouq9yXOQOX1SQCu:b9opipc) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/Geometry2D.h#L1)):*
> ```objc
> // ----------------------------------------------------------------------------
> ```

We removed the `Geometry3D.h` in the tensor-based implementation since we decided that the inheritance doesn't bring us much. PointCloud's `GetMinBound` and  TriangleMesh's `GetMinBound` are not inherited. We can consider removing Geometry2D to simplify the implementation. 
___
*[cpp/open3d/t/geometry/Image.h, line 133 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTn3H88vITps0H_M4q:-MOTn3H88vITps0H_M4r:b2nhwrx) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/Image.h#L133)):*
> ```objc
>     core::Tensor AsTensor() const { return data_; }
> 
>     /// Compute min 2D coordinates for the data (always {0, 0})
> ```

`.`
___
*[cpp/open3d/t/geometry/Image.h, line 138 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTn55cA36rfalePWqc:-MOTn55cA36rfalePWqd:b2nhwrx) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/Image.h#L138)):*
> ```objc
>     };
> 
>     /// Compute max 2D coordinates for the data ({cols, rows})
> ```

`.`
___
*[cpp/open3d/t/geometry/Image.h, line 140 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTnJKZ5wtfYyvY4Ne4:-MOTnJKZ5wtfYyvY4Ne5:b6628zz) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/Image.h#L140)):*
> ```objc
>     /// Compute max 2D coordinates for the data ({cols, rows})
>     core::Tensor GetMaxBound() const override {
>         return core::Tensor(std::vector<int64_t>{GetCols(), GetRows()}, {2},
> ```

For the image class, could we switch to `row, col` order here? We might need to change other locations to accommodate this `row, col` order. We'd like to be consistent such that this matches the tensor shape. 

In general, we have the following comments in `Image.h`, which recommends the `(row, col, channel)` order:
```
    /// Row-major storage is used, similar to OpenCV. Use (row, col, channel)
    /// indexing order for image creation and accessing. In general, (r, c, ch)
    /// are the preferred variable names for consistency, and avoid using width,
    /// height, u, v, x, y for coordinates.
```
___
*[cpp/open3d/t/geometry/Image.h, line 147 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTn4872bwQlHoMZCLi:-MOTn4872bwQlHoMZCLj:b2nhwrx) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/Image.h#L147)):*
> ```objc
>     open3d::geometry::Image ToLegacyImage() const;
> 
>     /// Text description
> ```

`.`
___
*[cpp/open3d/t/geometry/Image.cpp, line 80 at r9](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOIWm8gBdeNrle8uMwI:-MOTo3HD-zEA4wTv_p1x:b-i5nvqt) ([raw file](https://github.com/intel-isl/open3d/blob/37758c96708398b5b8e50470f3ad89f63f892e81/cpp/open3d/t/geometry/Image.cpp#L80)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Is this critical for RealSense's internal data? Otherwise I think directly using `.Contiguous` + memcpy would be enough.
</blockquote></details>

Agreed. `.Contiguous` should be sufficient (and likely faster, as we observe from pcd and mesh)
___
*[cpp/open3d/t/geometry/Image.cpp, line 78 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOToBwr3oxW-qYVkZsL:-MOToBwr3oxW-qYVkZsM:brhhs4w) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/Image.cpp#L78)):*
> ```cpp
>                          (int)elem_sz);
>     if (data_.IsContiguous()) {
>         memcpy(image_legacy.data_.data(), data_.GetDataPtr(),
> ```

1. We don't have restrictions on the`data_`'s dtype to the user. We shall check it is one of `{unit8, uint16, float32}`, otherwise, throw an exception. The legacy image can only accept these 3 dtypes. Also, there are different types that have the same byte size (e.g. float32 and int32)  so it is necessary to check. 
2. `Image` can be stored in GPU. So use `MemoryManager::MemcpyToHost` to take care of both cases.
3. Also, add unit tests for `ToLegacyImage` on both CPU and GPU, of different #channels.
___
*[cpp/open3d/t/geometry/RGBDImage.h, line 40 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTpKlE8oyBFHf2edjI:-MOTpKlE8oyBFHf2edjJ:b-rivt1x) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/RGBDImage.h#L40)):*
> ```objc
> ///
> /// \brief RGBDImage is for a pair of registered color and depth images,
> ///
> ```

extra empty line here?
___
*[cpp/open3d/t/geometry/RGBDImage.h, line 56 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTpb8S6WNxIVNiOblk:-MOTpb8S6WNxIVNiObll:bqulkkq) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/RGBDImage.h#L56)):*
> ```objc
>           depth_(depth) {}
> 
>     ~RGBDImage() override {
> ```

we don't need to call `Clear` explicitly,
`virtual ~RGBDImage() override {}` should be sufficient
___
*[cpp/open3d/t/geometry/RGBDImage.h, line 61 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTowZF80C81WU22d40:-MOTowZF80C81WU22d41:b-t9jy4j) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/RGBDImage.h#L61)):*
> ```objc
>     };
> 
>     /// Clear stored data
> ```

let's standardize the formatting in this header:
- add `.` to the end of each dostring comments
- add an empty line between member functions
___
*[cpp/open3d/t/geometry/RGBDImage.cpp, line 46 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTpzvx9SvPuJQsfxTg:-MOTpzvy95GlcWOPZFr2:b8aaxme) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/RGBDImage.cpp#L46)):*
> ```cpp
>             "Color [channels={}, format={}, device={}]\n"
>             "Depth [channels={}, format={}, device={}]",
>             color_.GetCols(), color_.GetRows(), color_.GetChannels(),
> ```

Same, let's make the order the same as the tensor shape order: `row, col, channel`.

Although technically the shape of color and depth shall match, since we don't enforce this programmatically, it is useful to print it out for debugging.

e.g. 

```
Color [shape(rols, cols)={}, channels={}, format={}, device={}]
Depth [shape(rols, cols)={}, channels={}, format={}, device={}]
```
___
*[cpp/open3d/t/io/CMakeLists.txt, line 8 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTsJTqB1-yQz03uw-n:-MOTsJTqB1-yQz03uw-o:b-6lo0a0) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/io/CMakeLists.txt#L8)):*
> ```CMake
> )
> 
> file(GLOB SENSOR_IO_SRC "sensor/*.cpp")
> ```

We are switching to the convention of listing the file names explicitly.  Also see discussions https://stackoverflow.com/q/1027247.
___
*[cpp/open3d/t/io/sensor/RGBDVideoMetadata.h, line 50 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTy4b-0LhO6qPKP4ak:-MOTy4b035bOkWfC79Ez:b-1uit50) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/io/sensor/RGBDVideoMetadata.h#L50)):*
> `` [...]

2020-12-15 04:38 UTC, ssheorey reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2646)* status: 73 of 90 files reviewed, 28 unresolved discussions (waiting on @ssheorey, @theNded, and @yxlao)

___
*[cpp/open3d/t/geometry/Geometry2D.h, line 1 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTmouq9yXOQOX1SQCt:-MOZeGrb4Cfju1aUOeJx:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/Geometry2D.h#L1)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We removed the `Geometry3D.h` in the tensor-based implementation since we decided that the inheritance doesn't bring us much. PointCloud's `GetMinBound` and  TriangleMesh's `GetMinBound` are not inherited. We can consider removing Geometry2D to simplify the implementation. 
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.h, line 133 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTn3H88vITps0H_M4q:-MOZeKPF4yzFTE-pbIzT:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/Image.h#L133)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`.`
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.h, line 138 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTn55cA36rfalePWqc:-MOZeKtNDwT_ItAcUSyT:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/Image.h#L138)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`.`
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.h, line 140 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTnJKZ5wtfYyvY4Ne4:-MOZeOJh6Lk7Qti9hQVF:b-v70ha1) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/Image.h#L140)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

For the image class, could we switch to `row, col` order here? We might need to change other locations to accommodate this `row, col` order. We'd like to be consistent such that this matches the tensor shape. 

In general, we have the following comments in `Image.h`, which recommends the `(row, col, channel)` order:
```
    /// Row-major storage is used, similar to OpenCV. Use (row, col, channel)
    /// indexing order for image creation and accessing. In general, (r, c, ch)
    /// are the preferred variable names for consistency, and avoid using width,
    /// height, u, v, x, y for coordinates.
```
</blockquote></details>

Done. Also in ToString() and pybind.
___
*[cpp/open3d/t/geometry/Image.h, line 147 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTn4872bwQlHoMZCLi:-MOZeUUe0sia9Luv5Ax6:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/Image.h#L147)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`.`
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.cpp, line 80 at r9](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOIWm8gBdeNrle8uMwI:-MOZeXAC2GNBLs5hdmbR:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/37758c96708398b5b8e50470f3ad89f63f892e81/cpp/open3d/t/geometry/Image.cpp#L80)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Agreed. `.Contiguous` should be sufficient (and likely faster, as we observe from pcd and mesh)
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.cpp, line 78 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOToBwr3oxW-qYVkZsL:-MOZfm2cB6RQy469hMU4:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/Image.cpp#L78)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

1. We don't have restrictions on the`data_`'s dtype to the user. We shall check it is one of `{unit8, uint16, float32}`, otherwise, throw an exception. The legacy image can only accept these 3 dtypes. Also, there are different types that have the same byte size (e.g. float32 and int32)  so it is necessary to check. 
2. `Image` can be stored in GPU. So use `MemoryManager::MemcpyToHost` to take care of both cases.
3. Also, add unit tests for `ToLegacyImage` on both CPU and GPU, of different #channels.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/RGBDImage.h, line 40 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTpKlE8oyBFHf2edjI:-MOZfoDH-uRg576yKezX:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/RGBDImage.h#L40)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

extra empty line here?
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/RGBDImage.h, line 56 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTpb8S6WNxIVNiOblk:-MOZfpQ_8eEm3YhVGk5D:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/RGBDImage.h#L56)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we don't need to call `Clear` explicitly,
`virtual ~RGBDImage() override {}` should be sufficient
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/RGBDImage.h, line 61 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTowZF80C81WU22d40:-MOZeYtiEwaVYgPLG0Gz:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/RGBDImage.h#L61)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

let's standardize the formatting in this header:
- add `.` to the end of each dostring comments
- add an empty line between member functions
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/RGBDImage.cpp, line 46 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTpzvx9SvPuJQsfxTg:-MOZeb0PD6it_8eaCvPt:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/geometry/RGBDImage.cpp#L46)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Same, let's make the order the same as the tensor shape order: `row, col, channel`.

Although technically the shape of color and depth shall match, since we don't enforce this programmatically, it is useful to print it out for debugging.

e.g. 

```
Color [shape(rols, cols)={}, channels={}, format={}, device={}]
Depth [shape(rols, cols)={}, channels={}, format={}, device={}]
```

</blockquote></details>

Done.
___
*[cpp/open3d/t/io/CMakeLists.txt, line 8 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTsJTqB1-yQz03uw-n:-MOZecKqBcsL5i_uxxKK:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/io/CMakeLists.txt#L8)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We are switching to the convention of listing the file names explicitly.  Also see discussions https://stackoverflow.com/q/1027247.
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/sensor/RGBDVideoMetadata.h, line 50 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTy4b-0LhO6qPKP4ak:-MOZedQS2lsnExCzwq-q:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d2594108f797a446d05181dc96d701eb708eabe8/cpp/open3d/t/io/sensor/RGBDVideoMetadata.h#L50)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same, add `.` to the comments
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/sensor/RGBDVideoReader.h, line 78 at r11](https://reviewable.io/reviews/intel-isl/open3d/2646#-MOTyBsuCTd [...]

2020-12-15 16:05 UTC, merged