#5 [HEAD: Final PR for ICP] ICP Point to Plane and Point to Point Registration and Example
intel-isl/Open3D pull request #2743
Opened 2020-12-11 12:32 UTC by reyanshsolis

2020-12-13 03:40 UTC, yxlao requested changes
> Reviewed 1 of 10 files at r1, 4 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2743)* status: 5 of 13 files reviewed, 12 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/t/pipelines/CMakeLists.txt, line 12 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOOvqXO8rJo3ZqUqB5w:-MOOt_KS3mr8BwTvY4-U:b-nx2sb8) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/CMakeLists.txt#L12)):*
> ```CMake
> add_library(tpipelines OBJECT
>             ${SRC}
>             ${RPLY_SOURCE_FILES}
> ```

can `rply` and `libzf` be removed?
___
*[cpp/open3d/t/pipelines/registration/CorrespondenceChecker.h, line 70 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPAKcQ3fJ-USEe193s:-MOPAKcR3IQyekVQUQ7g:b3kfeys) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/CorrespondenceChecker.h#L70)):*
> ```objc
>     /// \param source Source point cloud.
>     /// \param target Target point cloud.
>     /// \param corres Correspondence set between source and target point cloud.
> ```

mention the shape and dtype of the tensor. what happens if the shape and dtype do no match?
___
*[cpp/open3d/t/pipelines/registration/CorrespondenceChecker.h, line 71 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPANfw6_w6nITqQvax:-MOPANfw6_w6nITqQvay:bh4pl7n) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/CorrespondenceChecker.h#L71)):*
> ```objc
>     /// \param target Target point cloud.
>     /// \param corres Correspondence set between source and target point cloud.
>     /// \param transformation The estimated transformation (inplace).
> ```

same, mention the shape and dtype of the tensor
___
*[examples/cpp/CMakeLists.txt, line 54 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOOu-A61AmXpHYUF8sh:-MOOu-A61AmXpHYUF8si:b-jw4hq8) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/examples/cpp/CMakeLists.txt#L54)):*
> ```CMake
> EXAMPLE_CPP(RGBDOdometry              ${CMAKE_PROJECT_NAME})
> EXAMPLE_CPP(TriangleMesh              ${CMAKE_PROJECT_NAME})
> EXAMPLE_CPP(TensorICPRegistrationCUDA ${CMAKE_PROJECT_NAME})
> ```

We can only keep one file and allow options to switch between CPU and CUDA in the code.
___
*[examples/cpp/TensorICPRegistration.cpp, line 31 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOOwKV87wncgdV_zUI4:-MOOwKV95bVUNV9ODO0G:b-rfgi6p) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/examples/cpp/TensorICPRegistration.cpp#L31)):*
> ```cpp
> 
> #include "open3d/Open3D.h"
> #include "open3d/core/nns/NearestNeighborSearch.h"
> ```

Let's remove all the other headers such that the user only needs to import `Open3D.h`.
If `Open3D.h` isn't sufficient, we shall edit `Open3d.h.in` to include that.
___
*[examples/cpp/TensorICPRegistration.cpp, line 40 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOOxeBf5bwdcMGuijhF:-MOOxeBgDYd0bynHkvOA:bgggpxq) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/examples/cpp/TensorICPRegistration.cpp#L40)):*
> ```cpp
> void VisualizeRegistration(const open3d::t::geometry::PointCloud &source,
>                            const open3d::t::geometry::PointCloud &target,
>                            const core::Tensor &Transformation) {
> ```

variables are lower case `transformation`
___
*[examples/cpp/TensorICPRegistration.cpp, line 41 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOP8m9l47NS008aPWIh:-MOOxgqu5slv4_UpT1PJ:b-spkozt) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/examples/cpp/TensorICPRegistration.cpp#L41)):*
> ```cpp
>                            const open3d::t::geometry::PointCloud &target,
>                            const core::Tensor &Transformation) {
>     auto pcd = source;
> ```

- please also check if `auto pcd = source;` produces a "deep copy" or "shallow copy" of the point cloud. When the `pcd` is transformed, check if the values of the `source` are also affected.
- we can call it `source_transformed` instead of `pcd`
___
*[examples/cpp/TensorICPRegistration.cpp, line 43 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOOyL5F2G6WbFEBJIgP:-MOOyL5F2G6WbFEBJIgQ:b-57wyp2) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/examples/cpp/TensorICPRegistration.cpp#L43)):*
> ```cpp
>     auto pcd = source;
>     pcd.Transform(Transformation);
>     std::shared_ptr<geometry::PointCloud> source_transformed_ptr(
> ```

`make_shared<geometry::PointCloud>`
___
*[examples/cpp/TensorICPRegistration.cpp, line 76 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOP9Gr-12QTQKJs9duZ:-MOP9Gr03eu23Z9BbMgL:b-ro1xw5) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/examples/cpp/TensorICPRegistration.cpp#L76)):*
> ```cpp
>     // Manual Transformation
>     std::vector<double> trans_init_vec{
>             0.862, 0.011, -0.507, 0.5,  -0.139, 0.967, -0.215, 0.7,
> ```

If a user use this example to run ICP on other inputs, it may fail. Since this requires known initial transformation, let's refactor this to a unit test instead. In this way we can use the inputs from `examples/test_data/ICP`.
___
*[examples/cpp/TensorICPRegistration.cpp, line 88 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOOw3RH-WBzc6mnKDw9:-MOOw3RH-WBzc6mnKDwA:b82c3ei) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/examples/cpp/TensorICPRegistration.cpp#L88)):*
> ```cpp
>     auto corres = evaluation.correspondence_set_;
> 
>     std::cout << " Iteration - 0 [Manual Init Transformation] " << std::endl
> ```

change the `cout` to `LogInfo`
___
*[examples/cpp/TensorICPRegistration.cpp, line 128 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOOw5sVAP5Z9G-ARHz7:-MOOw5sVAP5Z9G-ARHz8:bbxgeqp) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/examples/cpp/TensorICPRegistration.cpp#L128)):*
> ```cpp
> 
>     return 0;
> }
> ```

add an additional line at the end
___
*[examples/cpp/TensorICPRegistrationCUDA.cpp, line 1 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOP9rs22cnYcWBQOrvh:-MOP9rs22cnYcWBQOrvi:b-2nx249) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/examples/cpp/TensorICPRegistrationCUDA.cpp#L1)):*
> ```cpp
> // ----------------------------------------------------------------------------
> ```

remove this file and enable device switching in code.


<!-- Sent from Reviewable.io -->

2020-12-13 04:59 UTC, theNded requested changes
> Reviewed 2 of 10 files at r1, 6 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2743)* status: all files reviewed, 19 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 90 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPRRq7E7CdKAQ1GJvI:-MOPRRq7E7CdKAQ1GJvJ:b-txi7p) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/Registration.h#L90)):*
> ```objc
>     ///
>     /// \param transformation The estimated transformation matrix.
>     RegistrationResult(const core::Tensor &transformation /*= core::Tensor::Eye(
> ```

These default values shouldn't be commented out in headers. Use them as default values and comment out them in .cpp
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 85 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPRd8d2NdVv5oTv-xU:-MOPRd8d2NdVv5oTv-xV:b-znopt) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/Registration.cpp#L85)):*
> ```cpp
>     // Reduction Sum of "distances"
>     // in KNN Distances is returned not DistancesSqaure, unlike HybridSearch
>     auto error2 = ((dist_select).Sum({0})).Item<float_t>();
> ```

Use squared_error for clarity.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 141 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPRmf6-GCC8vnImvI3:-MOPRmf6-GCC8vnImvI4:b-znopt) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/Registration.cpp#L141)):*
> ```cpp
> 
>     // Reduction Sum of "distances"
>     auto error2 = (dist_select.Sum({0})).Item<float_t>();
> ```

Use squared_error for clarity.
___
*[cpp/open3d/t/pipelines/registration/SolveTransform.h, line 37 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPSAdG2qFeiNpIOQ0S:-MOPSAdG2qFeiNpIOQ0T:bfjyib5) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/SolveTransform.h#L37)):*
> ```objc
> #include "open3d/t/pipelines/registration/CorrespondenceChecker.h"
> #include "open3d/t/pipelines/registration/TransformationEstimation.h"
> ```

Consider put this file at a higher level. `ComputeTransformationFromPose|Rt` will be reused in odometry and pose graph optimization; Solve PointToPlane will be reused in odometry.
___
*[cpp/open3d/t/pipelines/registration/SolveTransform.h, line 57 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPSS7N0IOzHDaKlbYQ:-MOPSS7N0IOzHDaKlbYR:ba3o3qj) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/SolveTransform.h#L57)):*
> ```objc
>                                            const core::Device &device);
> 
> core::Tensor Compute_A(const core::Tensor &source_select,
> ```

Rename.
___
*[cpp/open3d/t/pipelines/registration/SolveTransform.cpp, line 59 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPSk8J9cw_7ZAhoaR5:-MOPSk8J9cw_7ZAhoaR6:b-8n3pye) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/SolveTransform.cpp#L59)):*
> ```cpp
>             R);
>     // Translation and Scale [Assumed to be 1]
>     transformation[0][3] = t[0];
> ```

Use some mixed index get tricks here?
___
*[cpp/open3d/t/pipelines/registration/SolveTransform.cpp, line 101 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPSfwF9TwYENZzNz_w:-MOPSfwF9TwYENZzNz_x:b-8n3pye) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/SolveTransform.cpp#L101)):*
> ```cpp
>     transformation[2][2] = X[1].Cos() * X[0].Cos();
> 
>     // Translation from Pose X
> ```

Use some mixed index get tricks here?


<!-- Sent from Reviewable.io -->

2020-12-13 21:16 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2743)* status: 0 of 15 files reviewed, 19 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/t/pipelines/CMakeLists.txt, line 12 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOOvqXO8rJo3ZqUqB5w:-MORkpuWDgn5cVtoKPLf:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/CMakeLists.txt#L12)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

can `rply` and `libzf` be removed?
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/CorrespondenceChecker.h, line 70 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPAKcQ3fJ-USEe193s:-MOQFHtn1-C_6olCb3e5:b-jlxkl1) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/CorrespondenceChecker.h#L70)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

mention the shape and dtype of the tensor. what happens if the shape and dtype do no match?
</blockquote></details>

CorrespondenceChecker is not implemented yet, as it is not being used right now, it may be removed from this PR. Just initiated the file for future reference. 
___
*[cpp/open3d/t/pipelines/registration/CorrespondenceChecker.h, line 71 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPANfw6_w6nITqQvax:-MORkshn4B059hzQE1OO:b-na44an) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/CorrespondenceChecker.h#L71)):*
> CorrespondenceChecker is not implemented yet, as it is not being used right now, it may be removed from this PR. Just initiated the file for future reference. 
___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 90 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPRRq7E7CdKAQ1GJvI:-MORlAHq1OqsZ0D_FhPl:b5a9jgh) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/Registration.h#L90)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

These default values shouldn't be commented out in headers. Use them as default values and comment out them in .cpp
</blockquote></details>

yes, I had a doubt about this. A default constructor is required, but if a initialize with a transformation matrix on CPU, then the object will throw a device error if being used with other data on GPU. Therefore I wanted to make it compulsory for the user to initialize with a transformation tensor with a device same as point cloud data. Maybe, I can add a constructor RegistrationResult(device)? @thended 
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 85 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPRd8d2NdVv5oTv-xU:-MOSOl_IDt2yclr9f3iO:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/Registration.cpp#L85)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Use squared_error for clarity.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 141 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPRmf6-GCC8vnImvI3:-MOSOmC2A1uS_M3JM6F-:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/Registration.cpp#L141)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Use squared_error for clarity.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/SolveTransform.h, line 37 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPSAdG2qFeiNpIOQ0S:-MOSOo69E4vd8JepW59x:b-9xtq7l) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/SolveTransform.h#L37)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Consider put this file at a higher level. `ComputeTransformationFromPose|Rt` will be reused in odometry and pose graph optimization; Solve PointToPlane will be reused in odometry.
</blockquote></details>

Should I move the functions `ComputeTransformationFromPose|Rt` back to TransformationEstimation.cpp as Static ? 
Initially, I had the entire SolveTransform file inside in TransformationEstimation. I moved them to make the TransformationEstimation code look clean, with the idea, as better ops come in, eventually just improve or remove this SolveTransform.

The problem with creating a dedicated class with all these functions as static is that it throws an error that functions are declared by not used. Can I just add them to LinAlg?

Currently these functions are accessible as `open3d::t::pipelines::registration::ComputeTransformationFromRt()`
___
*[cpp/open3d/t/pipelines/registration/SolveTransform.h, line 57 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPSS7N0IOzHDaKlbYQ:-MORmOwLBjqOuY7K1lzU:benf3lf) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/SolveTransform.h#L57)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Rename.
</blockquote></details>

any suggestions? like it's is not entirely cross-product, It's a very specific function for the purpose I guess.  [ComputePointToPlaneCrossProductSourceNormal] 
___
*[cpp/open3d/t/pipelines/registration/SolveTransform.cpp, line 59 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPSk8J9cw_7ZAhoaR5:-MOSZz0TCbPzKyfhVCXU:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/SolveTransform.cpp#L59)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Use some mixed index get tricks here?
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/SolveTransform.cpp, line 101 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPSfwF9TwYENZzNz_w:-MOSZyj3-5FKU-Rs3iZJ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/SolveTransform.cpp#L101)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Use some mixed index get tricks here?
</blockquote></details>

Done.
___
*[examples/cpp/CMakeLists.txt, line 54 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOOu-A61AmXpHYUF8sh:-MORoZYK6aiEvgeQJAuF:bb6un1j) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/examples/cpp/CMakeLists.txt#L54)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We can only keep one file and allow options to switch between CPU and CUDA in the code.
</blockquote></details>

Done
___
*[examples/cpp/TensorICPRegistration.cpp, line 31 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOOwKV87wncgdV_zUI4:-MORoaHwBrmykGJc0c_q:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/examples/cpp/TensorICPRegistration.cpp#L31)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Let's remove all the other headers such that the user only needs to import `Open3D.h`.
If `Open3D.h` isn't sufficient, we shall edit `Open3d.h.in` to include that.
</blockquote></details>

Done.
___
*[examples/cpp/TensorICPRegistration.cpp, line 40 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOOxeBf5bwdcMGuijhF:-MORoraX9R-lJNczLMta:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/examples/cpp/TensorICP [...]

2020-12-16 20:36 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2743)* status: 0 of 22 files reviewed, 19 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/t/pipelines/registration/SolveTransform.h, line 37 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPSAdG2qFeiNpIOQ0S:-MOhFjGhDhVP_SrKHKrT:bg1j56d) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/SolveTransform.h#L37)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Should I move the functions `ComputeTransformationFromPose|Rt` back to TransformationEstimation.cpp as Static ? 
Initially, I had the entire SolveTransform file inside in TransformationEstimation. I moved them to make the TransformationEstimation code look clean, with the idea, as better ops come in, eventually just improve or remove this SolveTransform.

The problem with creating a dedicated class with all these functions as static is that it throws an error that functions are declared by not used. Can I just add them to LinAlg?

Currently these functions are accessible as `open3d::t::pipelines::registration::ComputeTransformationFromRt()`
</blockquote></details>

moved to a higher level. Done.
___
*[cpp/open3d/t/pipelines/registration/SolveTransform.h, line 57 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPSS7N0IOzHDaKlbYQ:-MOhFpCi9933hCVTQQGb:b70kqlt) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/SolveTransform.h#L57)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

any suggestions? like it's is not entirely cross-product, It's a very specific function for the purpose I guess.  [ComputePointToPlaneCrossProductSourceNormal] 
</blockquote></details>

Removed this function.


<!-- Sent from Reviewable.io -->

2020-12-17 04:24 UTC, theNded requested changes
> Reviewed 1 of 19 files at r3, 24 of 26 files at r5.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2743)* status: 21 of 22 files reviewed, 25 unresolved discussions (waiting on @reyanshsolis, @theNded, and @yxlao)

___
*[cpp/open3d/core/Tensor.cpp, line 770 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOis_EX1n3kqaDeSU1m:-MOis_EY4o06-UJocnzb:b-mj2idc) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/core/Tensor.cpp#L770)):*
> ```cpp
> }
> 
> double Tensor::Det_() const {
> ```

In the future we shall use QR decomposition to compute Determinant. QR decomposition has been used in LeastSquares but not exposed. I may probably modify the linear algebra module and expose some of the useful functionalities.
Ref: https://en.wikipedia.org/wiki/QR_decomposition#Computing_the_QR_decomposition
___
*[cpp/open3d/t/io/sensor/RGBDVideoReader.cpp, line 57 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOiszUdElI0D2FQQC2t:-MOiszUdElI0D2FQQC2u:bpxa6kz) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/io/sensor/RGBDVideoReader.cpp#L57)):*
> ```cpp
>     using namespace open3d::io;
>     if (!IsOpened()) {
>         open3d::utility::LogError("Null file handler. Please call Open().");
> ```

Is this change from merging another PR? It feels wierd that we simultaneously use namespace `open3d::utility::filesystem` and introduce `open3d::utility` 
___
*[cpp/open3d/t/pipelines/SolveTransformation.cu, line 38 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOiudMMD48Q-HdusMhn:-MOiudMNE0Xs7QwQUxaS:bnnxx41) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/SolveTransformation.cu#L38)):*
> ```Cuda
> namespace t {
> namespace pipelines {
> ```

Is there any specific reason to split cuda implementation? We can use `.Item` to access entries from a host launch, or copy the Tensor to CPU, perform the operation, and copy it back to cuda (where the code can be written device agnostic). 
___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 90 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPRRq7E7CdKAQ1GJvI:-MOivQ6BAuJaaD0TE535:b20sp5q) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/Registration.h#L90)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

yes, I had a doubt about this. A default constructor is required, but if a initialize with a transformation matrix on CPU, then the object will throw a device error if being used with other data on GPU. Therefore I wanted to make it compulsory for the user to initialize with a transformation tensor with a device same as point cloud data. Maybe, I can add a constructor RegistrationResult(device)? @thended 
</blockquote></details>

For RegistrationResult let's remove the comment as well, it is not required. For Evaluate Registration we can keep the default initialization on CPU and do a conversion according to input point cloud device type. 
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 51 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOivond1DZxa4aU5OqG:-MOivond1DZxa4aU5OqH:b-41bqb3) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/registration/Registration.cpp#L51)):*
> ```cpp
>     target.GetPoints().AssertDtype(dtype);
>     if (target.GetDevice() != device) {
>         open3d::utility::LogError(
> ```

again it is better to keep the convention `utility::LogError`. Is it somehow not working now? It is anyway nested in the open3d namespace.
___
*[cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp, line 105 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOiw78O07us75p5rIpM:-MOiw78O07us75p5rIpN:bhithy0) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp#L105)):*
> ```cpp
>     target.GetPoints().AssertDtype(dtype);
>     if (target.GetDevice() != device) {
>         open3d::utility::LogError(
> ```

Same, remove open3d
___
*[cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp, line 120 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOiw9K-9sZgHIpvdzQY:-MOiw9K02ezkuDHGVqDp:b-bk75k4) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp#L120)):*
> ```cpp
>             (source_select - target_select).Mul_(target_n_select);
>     error_t.Mul_(error_t);
>     double error = (double)error_t.Sum({0, 1}).Item<float_t>();
> ```

static_cast<double>


<!-- Sent from Reviewable.io -->

2020-12-17 04:27 UTC, theNded commented
This PR is in a good shape, but we have to investigate and profile step-by-step and figure out why both CPU/GPU versions are (2x or more) slower than the legacy CPU version. I think we may merge this after benchmarking the new nns module and have a sense of what's going on there.

2020-12-17 08:29 UTC, yxlao requested changes
> Reviewed 2 of 19 files at r3, 11 of 26 files at r5, 2 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2743)* status: 17 of 23 files reviewed, 27 unresolved discussions (waiting on @reyanshsolis, @theNded, and @yxlao)

___
*[cpp/open3d/core/Tensor.h, line 441 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjC6K35bnRMS7ptTBU:-MOjC6K35bnRMS7ptTBV:b-fgp85h) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/core/Tensor.h#L441)):*
> ```objc
>     /// \brief Expects input to be 3x3 Matrix
>     /// returns Determinant of the matrix (double)
>     double Det_() const;
> ```

Let's call it `Det()`
___
*[cpp/open3d/core/Tensor.cpp, line 774 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjCOV7CIPfLcDEfRgK:-MOjCOV7CIPfLcDEfRgL:b-ludzra) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/core/Tensor.cpp#L774)):*
> ```cpp
>     this->AssertShape({3, 3});
>     this->AssertDtype(core::Dtype::Float32);
>     core::Tensor D_ = this->Copy();
> ```

We'll need to copy to CPU first (if the tensor is from CUDA). And then use 3 temporary variables so that we don't need to write back to the tensor. Add unit test for this function. 

Added assana task: https://app.asana.com/0/1111336323009173/1199629019899533/f for the full implementation in a separate PR.
___
*[cpp/open3d/t/io/sensor/RGBDVideoMetadata.h, line 44 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjD53L50i3M8UVlavY:-MOjD53MEXZmY8Qe91B9:b-dqrl1o) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/io/sensor/RGBDVideoMetadata.h#L44)):*
> ```objc
> 
> /// RGBD video metadata.
> class RGBDVideoMetadata : public open3d::utility::IJsonConvertible {
> ```

`open3d::` may be removed
___
*[cpp/open3d/t/io/sensor/RGBDVideoMetadata.h, line 51 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjD9r7D-0p7jvzL_W4:-MOjD9r7D-0p7jvzL_W5:b-dqrl1o) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/io/sensor/RGBDVideoMetadata.h#L51)):*
> ```objc
> 
>     /// Text description
>     using open3d::utility::IJsonConvertible::ToString;
> ```

`open3d::` may be removed
___
*[cpp/open3d/t/pipelines/CMakeLists.txt, line 16 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjDNJjEItK66KKxGbH:-MOjDNJjEItK66KKxGbI:b-l900iu) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/CMakeLists.txt#L16)):*
> ```CMake
> )
> 
> if(BUILD_CUDA_MODULE)
> ```

```
set(ALL_PIPELINE_SRC
    ${REGISTRATION_SRC}
    ${UTILITY_SRC})
```

and then

```
if(BUILD_CUDA_MODULE)
    set(ALL_PIPELINE_SRC
        ${ALL_PIPELINE_SRC}
        ${UTILITY_CUDA_SRC})
endif()
```

such that we don't need to list the common sources repeatedly.
___
*[cpp/open3d/t/pipelines/CMakeLists.txt, line 35 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjDj9yEQBLhtRfn0bf:-MOjDj9yEQBLhtRfn0bg:b-oos0fs) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/CMakeLists.txt#L35)):*
> ```CMake
> open3d_set_global_properties(tpipelines)
> open3d_set_open3d_lib_properties(tpipelines)
> open3d_link_3rdparty_libraries(tpipelines)
> ```

add extra line at the end 
if you're on vscode the option is `"files.insertFinalNewline": true,`
___
*[cpp/open3d/t/pipelines/SolveTransformation.h, line 39 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjEerCEH6nhv-xS2cO:-MOjEerCEH6nhv-xS2cP:bnjcfxr) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/SolveTransformation.h#L39)):*
> ```objc
> namespace pipelines {
> 
> // Utility functions
> ```

remove these 4 lines.
___
*[cpp/open3d/t/pipelines/SolveTransformation.h, line 45 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjEiyD5rBhq8Hhy6Pz:-MOjEiyD5rBhq8Hhy6Q-:byarbwt) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/SolveTransformation.h#L45)):*
> ```objc
> 
> /// \brief Functions for Computing Transformation Matrix {4,4}
> /// from Rotation {3,3} and Translation {3}
> ```

In general, add a `.` for all comments and docstrings. Could we do it for all files in this PR?
___
*[cpp/open3d/t/pipelines/SolveTransformation.cu, line 38 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOiudMMD48Q-HdusMhn:-MOjF3db1O76FLaTmaRT:b9reueh) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/SolveTransformation.cu#L38)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Is there any specific reason to split cuda implementation? We can use `.Item` to access entries from a host launch, or copy the Tensor to CPU, perform the operation, and copy it back to cuda (where the code can be written device agnostic). 
</blockquote></details>

The second approach would work. Or we can also share the code by adding a common function.

For the first approach, getting `tensor[x][y].Item<float>()` multiple times could be inefficient since each time Item is called there will be a device->host transfer.  There will be a few dozen device->host transfer in this function if we do it in this way.
___
*[cpp/open3d/t/pipelines/SolveTransformationImpl.h, line 41 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjn3li6UllA-FBzeSu:-MOjn3li6UllA-FBzeSv:bk7kaew) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformationImpl.h#L41)):*
> ```objc
> /// Shared implementation for ComputeTransformationFromPose.
> OPEN3D_HOST_DEVICE inline void ComputeTransformationFromPoseImpl(
>         float *transformation_ptr, float *X_ptr) {
> ```

change to `const float* X_ptr` for all related functions
___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 90 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPRRq7E7CdKAQ1GJvI:-MOjG-6JCbQOvsSBspcc:b-p1qbl2) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/Registration.h#L90)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

For RegistrationResult let's remove the comment as well, it is not required. For Evaluate Registration we can keep the default initialization on CPU and do a conversion according to input point cloud device type. 
</blockquote></details>

Ok, this approach also works.
___
*[examples/cpp/CMakeLists.txt, line 63 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjnCiT-WfdB3JXg5Jr:-MOjnCiT-WfdB3JXg5Js:b-5e2tly) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/examples/cpp/CMakeLists.txt#L63)):*
> ```CMake
> EXAMPLE_CPP(Voxelization              ${CMAKE_PROJECT_NAME})
> EXAMPLE_CPP(OpenMP                    ${CMAKE_PROJECT_NAME} ${OPENMP_TARGET})
> EXAMPLE_CPP(BenchmarkNNS 	          ${CMAKE_PROJECT_NAME})
> ```

are there some tabs here? use spaces
___
*[examples/cpp/TensorICPCompareLegacy.cpp, line 1 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjnPab7-1Aj_t9RHiG:-MOjnPab7-1Aj_t9RHiH:b-j713tu) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/examples/cpp/TensorICPCompareLegacy.cpp#L1)):*
> ```cpp
> // ----------------------------------------------------------------------------
> ```

We can merge this to the unit tests and remove this file.
- to reduce duplicated source code
- it is not providing much information for the user as an example

When it is a unit test, we can still easily run a single unit test by using the gtest filter argument, e.g.

```bash
make tests -j
./bin/tests --gtest_ [...]

2020-12-17 10:30 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2743)* status: 8 of 23 files reviewed, 27 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/Tensor.h, line 441 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjC6K35bnRMS7ptTBU:-MOjrUp34ay4AS0tHwdj:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/core/Tensor.h#L441)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Let's call it `Det()`
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.cpp, line 770 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOis_EX1n3kqaDeSU1m:-MOjgxfY3yRAsFdfG1NG:b-7cexfm) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/core/Tensor.cpp#L770)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

In the future we shall use QR decomposition to compute Determinant. QR decomposition has been used in LeastSquares but not exposed. I may probably modify the linear algebra module and expose some of the useful functionalities.
Ref: https://en.wikipedia.org/wiki/QR_decomposition#Computing_the_QR_decomposition
</blockquote></details>

thanks for the reference, will do that in the next PR.
___
*[cpp/open3d/core/Tensor.cpp, line 774 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjCOV7CIPfLcDEfRgK:-MOk1t_o5sOayGNtPI11:b-npkww1) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/core/Tensor.cpp#L774)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We'll need to copy to CPU first (if the tensor is from CUDA). And then use 3 temporary variables so that we don't need to write back to the tensor. Add unit test for this function. 

Added assana task: https://app.asana.com/0/1111336323009173/1199629019899533/f for the full implementation in a separate PR.
</blockquote></details>

```
    D_[0][0] = D_[0][0] * (D_[1][1] * D_[2][2] - D_[1][2] * D_[2][1])
                    - D_[0][1] * (D_[1][0] * D_[2][2] - D_[2][0] * D_[1][2])
                    + D_[0][2] * (D_[1][0] * D_[2][1] - D_[2][0] * D_[1][1]);
```
can we just do this directly for now?

Unit Test added.
___
*[cpp/open3d/t/io/sensor/RGBDVideoMetadata.h, line 44 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjD53L50i3M8UVlavY:-MOjrrbv8L9J5vEQITxr:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/io/sensor/RGBDVideoMetadata.h#L44)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`open3d::` may be removed
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/sensor/RGBDVideoMetadata.h, line 51 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjD9r7D-0p7jvzL_W4:-MOjrs6T7jruBcJeX8zH:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/io/sensor/RGBDVideoMetadata.h#L51)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`open3d::` may be removed
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/sensor/RGBDVideoReader.cpp, line 57 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOiszUdElI0D2FQQC2t:-MOjh2JF09gEuknNV7FR:byk5hq7) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/io/sensor/RGBDVideoReader.cpp#L57)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Is this change from merging another PR? It feels wierd that we simultaneously use namespace `open3d::utility::filesystem` and introduce `open3d::utility` 
</blockquote></details>

I removed it now, during development I had created a utility for t namespace, therefore changed the open3d::utility functions.
___
*[cpp/open3d/t/pipelines/CMakeLists.txt, line 16 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjDNJjEItK66KKxGbH:-MOjsOEqCZoo7bWW8gkG:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/CMakeLists.txt#L16)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

```
set(ALL_PIPELINE_SRC
    ${REGISTRATION_SRC}
    ${UTILITY_SRC})
```

and then

```
if(BUILD_CUDA_MODULE)
    set(ALL_PIPELINE_SRC
        ${ALL_PIPELINE_SRC}
        ${UTILITY_CUDA_SRC})
endif()
```

such that we don't need to list the common sources repeatedly.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/CMakeLists.txt, line 35 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjDj9yEQBLhtRfn0bf:-MOk2Dc84fCL1erivklA:b-v9pu2c) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/CMakeLists.txt#L35)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

add extra line at the end 
if you're on vscode the option is `"files.insertFinalNewline": true,`
</blockquote></details>

thanks. Done.
___
*[cpp/open3d/t/pipelines/SolveTransformation.h, line 39 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjEerCEH6nhv-xS2cO:-MOk2K--AXZjnRdOganv:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/SolveTransformation.h#L39)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove these 4 lines.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/SolveTransformation.h, line 45 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjEiyD5rBhq8Hhy6Pz:-MOk30pA21-yqL-8BwmG:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/SolveTransformation.h#L45)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

In general, add a `.` for all comments and docstrings. Could we do it for all files in this PR?
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/SolveTransformation.cu, line 38 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOiudMMD48Q-HdusMhn:-MOk3BNA7VJzeJ6roFys:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/SolveTransformation.cu#L38)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

The second approach would work. Or we can also share the code by adding a common function.

For the first approach, getting `tensor[x][y].Item<float>()` multiple times could be inefficient since each time Item is called there will be a device->host transfer.  There will be a few dozen device->host transfer in this function if we do it in this way.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/SolveTransformationImpl.h, line 41 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjn3li6UllA-FBzeSu:-MOjx2zAEzefG6EMLE4n:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformationImpl.h#L41)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

change to `const float* X_ptr` for all related functions
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 90 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPRRq7E7CdKAQ1GJvI:-MOkBYGK5OSKWLAB0xEm:b-kwwdrh) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/Registration.h#L90)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Ok, this approach also works.
</blockquote></details>

To accomplish this, a copy needs to be created in the source. In the updated implement [...]

2020-12-17 10:55 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2743)* status: 8 of 23 files reviewed, 27 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/t/io/sensor/RGBDVideoReader.cpp, line 57 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOiszUdElI0D2FQQC2t:-MOkJVTNDpQVEbATsP-y:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/io/sensor/RGBDVideoReader.cpp#L57)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

I removed it now, during development I had created a utility for t namespace, therefore changed the open3d::utility functions.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/CMakeLists.txt, line 35 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjDj9yEQBLhtRfn0bf:-MOkK57DDlA-aWr7cAKh:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/t/pipelines/CMakeLists.txt#L35)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

thanks. Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-17 13:12 UTC, yxlao requested changes
> Reviewed 2 of 19 files at r3, 1 of 26 files at r5, 6 of 8 files at r6, 15 of 19 files at r7.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2743)* status: 15 of 18 files reviewed, 41 unresolved discussions (waiting on @reyanshsolis, @theNded, and @yxlao)

___
*[cpp/open3d/core/Tensor.cpp, line 774 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjCOV7CIPfLcDEfRgK:-MOkiX5s2bqxF-8-5LxM:b-wk61ij) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/core/Tensor.cpp#L774)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

```
    D_[0][0] = D_[0][0] * (D_[1][1] * D_[2][2] - D_[1][2] * D_[2][1])
                    - D_[0][1] * (D_[1][0] * D_[2][2] - D_[2][0] * D_[1][2])
                    + D_[0][2] * (D_[1][0] * D_[2][1] - D_[2][0] * D_[1][1]);
```
can we just do this directly for now?

Unit Test added.
</blockquote></details>

yeah, this is fine for now.
___
*[cpp/open3d/t/pipelines/CMakeLists.txt, line 21 at r7](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOkii3l9roZ4ORfoxWv:-MOkii3l9roZ4ORfoxWw:b-p7w9t9) ([raw file](https://github.com/intel-isl/open3d/blob/06c259e444c58d96384e9abfc7972bfcf2b24148/cpp/open3d/t/pipelines/CMakeLists.txt#L21)):*
> ```CMake
> 
> if(BUILD_CUDA_MODULE)
>     set(ALL_PIPELINE_SRC
> ```

```
if(BUILD_CUDA_MODULE)
    set(ALL_PIPELINE_SRC
        ${ALL_PIPELINE_SRC}
        ${UTILITY_CUDA_SRC})
endif()
```
the point is to avoid listing `ALL_PIPELINE_SRC` again
___
*[cpp/open3d/t/pipelines/SolveTransformation.h, line 1 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk-6yf9D8HnrVFS3T_:-MOk-6yf9D8HnrVFS3Ta:b-wznm6c) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformation.h#L1)):*
> ```objc
> // ----------------------------------------------------------------------------
> ```

Forllowing the convention from `cpp/open3d/core/EigenConverter.h`
`TransformationConverter.h` may be a better name for this file.
___
*[cpp/open3d/t/pipelines/SolveTransformation.h, line 44 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk0cY-8x1T_jBQiVfv:-MOk0cY-8x1T_jBQiVfw:bd4nd9s) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformation.h#L44)):*
> ```objc
> // t::pipelines::ComputeTransformationFromPose
> 
> /// \brief Functions for Computing Transformation Matrix {4,4}
> ```

`Functions for computing transformation matrix` (fix letter case)

Do the following docstring (add return and put the description in parameters but not in brief.)

```cpp
/// \brief Convert rotation and translation to the transformation matrix.
///
/// \param R Rotation, a tensor of shape {3, 3} and dtype Float32.
/// \param t Translation, a tensor of shape {3, 3} and dtype Float32.
/// \return Transformation, a tensor of shape {4, 4}, dtype Float32.
```

Do the same for `ComputeTransformationFromPose`.
___
*[cpp/open3d/t/pipelines/SolveTransformation.h, line 48 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk-BWA6uDNY2ZRjU9s:-MOjvD2C923H5Nsm-38d:bpjjuh4) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformation.h#L48)):*
> ```objc
> /// \param R Rotation Tensor {3,3} Float32
> /// \param t Translation Tensor {3} Float32
> core::Tensor ComputeTransformationFromRt(const core::Tensor &R,
> ```

Forllowing the convention from `cpp/open3d/core/EigenConverter.h`, use `to` instead of `from`. 
We can rename to `RtToTransformation`,
___
*[cpp/open3d/t/pipelines/SolveTransformation.h, line 51 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk0hwpBes_1y59qSxb:-MOk0hwpBes_1y59qSxc:b-cioojn) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformation.h#L51)):*
> ```objc
>                                          const core::Tensor &t);
> 
> /// \brief Functions for Computing Transformation Matrix {4,4}
> ```

`Functions for computing transformation matrix` (fix letter case)
___
*[cpp/open3d/t/pipelines/SolveTransformation.h, line 52 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk1j8a60iZUUQS1x_v:-MOk1j8a60iZUUQS1x_w:b-d2yxwp) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformation.h#L52)):*
> ```objc
> 
> /// \brief Functions for Computing Transformation Matrix {4,4}
> /// from Pose {6} [alpha, beta, gamma, tx, ty, tz]
> ```

similarly, put the description `[alpha, beta, gamma, tx, ty, tz]` in `\param X`
___
*[cpp/open3d/t/pipelines/SolveTransformation.h, line 54 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk-P6H2PZOxvYOG4zh:-MOk-P6H2PZOxvYOG4zi:b-g2cqkf) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformation.h#L54)):*
> ```objc
> /// from Pose {6} [alpha, beta, gamma, tx, ty, tz]
> /// \param X Pose {6} Float32
> core::Tensor ComputeTransformationFromPose(const core::Tensor &X);
> ```

`PostToTransformation`
___
*[cpp/open3d/t/pipelines/SolveTransformation.cpp, line 38 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjzUDrDk1JiQf5ksSv:-MOjzUDrDk1JiQf5ksSw:b-ogfgqk) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformation.cpp#L38)):*
> ```cpp
> namespace pipelines {
> 
> core::Tensor ComputeTransformationFromRt(const core::Tensor &R,
> ```

unit test for this is missing
___
*[cpp/open3d/t/pipelines/SolveTransformation.cpp, line 53 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk1Zp27Jt4rzP_vUDe:-MOk1Zp27Jt4rzP_vUDf:b-6k32gg) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformation.cpp#L53)):*
> ```cpp
>             {core::TensorKey::Slice(0, 3, 1), core::TensorKey::Slice(0, 3, 1)},
>             R);
>     // Translation and Scale [Assumed to be 1]
> ```

move the scale comment
___
*[cpp/open3d/t/pipelines/SolveTransformation.cpp, line 57 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk1WUWDJcJrrc09czG:-MOk1WUWDJcJrrc09czH:b-egmclj) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformation.cpp#L57)):*
> ```cpp
>             {core::TensorKey::Slice(0, 3, 1), core::TensorKey::Slice(3, 4, 1)},
>             t.Reshape({3, 1}));
>     transformation[3][3] = 1;
> ```

// Scale (assumed to be 1).
transformation[3][3] = 1;
___
*[cpp/open3d/t/pipelines/SolveTransformation.cpp, line 61 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjza72BDK1wWSsD6TR:-MOjza72BDK1wWSsD6TS:b-ogfgqk) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformation.cpp#L61)):*
> ```cpp
> }
> 
> core::Tensor ComputeTransformationFromPose(const core::Tensor &X) {
> ```

unit test for this is missing
___
*[cpp/open3d/t/pipelines/SolveTransformation.cpp, line 68 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk1yYcD9G4BMAkpTFm:-MOk1yYcD9G4BMAkpTFn:bdlts9z) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/SolveTransformation.cpp#L68)):*
> ```cpp
>     core::Tensor transformation = core::Tensor::Zeros({4, 4}, dtype, device);
>     transformation = transformation.Contiguous();
>     auto X_copy = X.Contiguous();
> ```

```cpp
Tensor X_contiguous = X.Contiguous();
```
`Contiguous()` does not necessarily produce a copy. Also prefer to use `Tensor` instead of `auto`.

`auto` can be used when the type name is long and can be easily inferred from the same line without extra information, e.g.
```c [...]

2020-12-18 07:32 UTC, yxlao requested changes
> Reviewed 8 of 13 files at r8, 10 of 10 files at r9.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2743)* status: all files reviewed, 25 unresolved discussions (waiting on @reyanshsolis, @theNded, and @yxlao)

___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 77 at r9](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOnUv2iDjljRVCEZ9q-:-MOnUv2iDjljRVCEZ9q0:b4abqix) ([raw file](https://github.com/intel-isl/open3d/blob/6ecbdb2c1b5d564802e524d4b20440f1e7f0cff1/cpp/open3d/t/geometry/PointCloud.cpp#L77)):*
> ```cpp
> 
> PointCloud PointCloud::Copy(const core::Device device) const {
>     PointCloud pcd(device);
> ```

Need to iterate the map can copy each tensor, not just the 3 default ones.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 96 at r9](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOogZWa16MpUyzW8I6I:-MOogZWa16MpUyzW8I6J:b-qdxsju) ([raw file](https://github.com/intel-isl/open3d/blob/6ecbdb2c1b5d564802e524d4b20440f1e7f0cff1/cpp/open3d/t/pipelines/registration/Registration.cpp#L96)):*
> ```cpp
> 
>     // Reduction sum of "distances" for error.
>     auto squared_error = (dist_select.Sum({0})).Item<float_t>();
> ```

`float squared_error = (dist_select.Sum({0})).Item<float>();`
use `float` instead of `float_t` for all the source code in this pr.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 185 at r9](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOoh6eb7wbB3VPymgDO:-MOoh6eb7wbB3VPymgDP:b-qdruuu) ([raw file](https://github.com/intel-isl/open3d/blob/6ecbdb2c1b5d564802e524d4b20440f1e7f0cff1/cpp/open3d/t/pipelines/registration/Registration.cpp#L185)):*
> ```cpp
>         transformation_device = update.Matmul(transformation_device);
>         source_transformed.Transform(update);
>         RegistrationResult backup = result;
> ```

Whenever using `=` for objects, be very careful. This invokes the copy constructor. In this case, the tensors in `RegistrationResult` are not copied for the reason we discussed in previous comments. For any class that stores `Tensor` as is member variable, consider disabling the copy constructor and copy assignment operator (TODO).

In this PR, let's do the simpler approach. We just need to store the `double prev_fitness_` and `double prev_inliner_rmse_`.
___
*[cpp/open3d/t/pipelines/registration/TransformationEstimation.h, line 49 at r9](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOoiJThD5-fR56zMuLK:-MOoiJThD5-fR56zMuLL:b-zd88aw) ([raw file](https://github.com/intel-isl/open3d/blob/6ecbdb2c1b5d564802e524d4b20440f1e7f0cff1/cpp/open3d/t/pipelines/registration/TransformationEstimation.h#L49)):*
> ```objc
> namespace registration {
> 
> typedef std::pair<core::Tensor, core::Tensor> CorrespondenceSet;
> ```

Previously, Eigen gives us the shape and dtype info. But now, it is hidden. Please add a comment on the shape and dtype of the two tensors stored in `CorrespondenceSet` and what they represent.

Also, can it be one tensor (of a larger shape) instead of two tensors? Why did we choose the current design?
___
*[cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp, line 56 at r9](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOojVOJ0T518X4abYV1:-MOojVOJ0T518X4abYV2:buv7tx3) ([raw file](https://github.com/intel-isl/open3d/blob/6ecbdb2c1b5d564802e524d4b20440f1e7f0cff1/cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp#L56)):*
> ```cpp
>     error_t.Mul_(error_t);
>     error = static_cast<double>(error_t.Sum({0, 1}).Item<float_t>());
>     return std::sqrt(error / (double)corres.second.GetShape()[0]);
> ```

Don't mix the usage of `(double)` and `static_cast<double>`

For this PR, let's convert them to `static_cast<double>` as it is more ugly (to remind the developer that we are doing the conversion).
___
*[cpp/tests/t/geometry/PointCloud.cpp, line 124 at r9](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOnb7Rq6FvV-Q_FAUj9:-MOnb7Rr7SuFv4Z2Q4Yu:bt52z7u) ([raw file](https://github.com/intel-isl/open3d/blob/6ecbdb2c1b5d564802e524d4b20440f1e7f0cff1/cpp/tests/t/geometry/PointCloud.cpp#L124)):*
> ```cpp
>     core::Dtype dtype = core::Dtype::Float32;
> 
>     t::geometry::PointCloud pcd(device);
> ```

1. Copy the point cloud `Setters` unit test example to give the point cloud: points, colors and labels. This way we test both default attributes and custom attributes.
2. Use `IsSame()` to check if the tensor is NOT the same tensor. Use `AllClose()` to check their value are the same. e.g. 
    ```
    EXPECT_FALSE(a_copy.IsSame(a));
    EXPECT_TRUE(a_copy.AllClose(a));
    ```
___
*[cpp/tests/t/pipelines/registration/Registration.cpp, line 74 at r9](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOncWkW57Ol0Ju8fgPl:-MOncWkW57Ol0Ju8fgPm:b3ma0ni) ([raw file](https://github.com/intel-isl/open3d/blob/6ecbdb2c1b5d564802e524d4b20440f1e7f0cff1/cpp/tests/t/pipelines/registration/Registration.cpp#L74)):*
> ```cpp
>     EXPECT_DOUBLE_EQ(reg_result.inlier_rmse_, 0.0);
>     EXPECT_DOUBLE_EQ(reg_result.fitness_, 0.0);
>     EXPECT_EQ(reg_result.transformation_.ToFlatVector<float_t>(),
> ```

use `float` instead of `float_t`, change this for all the unit tests


<!-- Sent from Reviewable.io -->

2020-12-18 12:38 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2743)* status: 11 of 22 files reviewed, 25 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/Tensor.cpp, line 770 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOis_EX1n3kqaDeSU1m:-MOlE4dg6t7f70vyqWUy:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/core/Tensor.cpp#L770)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

thanks for the reference, will do that in the next PR.
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.cpp, line 774 at r5](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjCOV7CIPfLcDEfRgK:-MOl7XcZ67OCksF9cGN7:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ee0c37b335b6a5bedc5f19ad8dfffe8bebdf086/cpp/open3d/core/Tensor.cpp#L774)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

yeah, this is fine for now.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 77 at r9](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOnUv2iDjljRVCEZ9q-:-MOpGaIe3hI8dax8cjI_:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ecbdb2c1b5d564802e524d4b20440f1e7f0cff1/cpp/open3d/t/geometry/PointCloud.cpp#L77)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Need to iterate the map can copy each tensor, not just the 3 default ones.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/CMakeLists.txt, line 21 at r7](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOkii3l9roZ4ORfoxWv:-MOn-6--1SOAWcLwEzju:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/06c259e444c58d96384e9abfc7972bfcf2b24148/cpp/open3d/t/pipelines/CMakeLists.txt#L21)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

```
if(BUILD_CUDA_MODULE)
    set(ALL_PIPELINE_SRC
        ${ALL_PIPELINE_SRC}
        ${UTILITY_CUDA_SRC})
endif()
```
the point is to avoid listing `ALL_PIPELINE_SRC` again
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 90 at r2](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOPRRq7E7CdKAQ1GJvI:-MOpGgGzEJGKnIRUDKDq:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f4cb39f2d0271f2a7135cdee919ee2cc0f7a0d54/cpp/open3d/t/pipelines/registration/Registration.h#L90)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

To accomplish this, a copy needs to be created in the source. In the updated implementation I am using this to create a shallow copy if on the same device, and a deep copy with device transfer otherwise. This also forgives the user for device mismatch.

```cpp    
core::Tensor transformation_device;
    if(transformation.GetDevice() == device) {
        transformation_device = transformation;
    }
    else {
        transformation_device = transformation.Copy(device);
    }
```
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 50 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk6Sqh5uFdXqKt-DBL:-MOmY2Vu7Ex0wyPyZ-qx:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/registration/Registration.h#L50)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

move this to the function docstring
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 103 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk6gsN5u-GnbmaDKKo:-MOmYoJJAbPhcaGeKpd8:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/registration/Registration.h#L103)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

lower case `C`
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 120 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk6lMXCMbMI7u5SaRy:-MOmVvnc4M9YTkbzyCv1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/registration/Registration.h#L120)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

format `\param` to a new line
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 133 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOk6pHjDcEFp8EA5FFL:-MOmVv1B1rtiQrr3-vDx:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/registration/Registration.h#L133)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

format `\param` to a new line
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 147 at r6](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOjuXM26qDtOzJJHB1A:-MOmVtKOEhSOZwIHc9DT:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/db9f83685aba8db34884979167aecd0fd80f60b6/cpp/open3d/t/pipelines/registration/Registration.h#L147)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

let's remove this and turn it into an asana task
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 96 at r9](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOogZWa16MpUyzW8I6I:-MOp-uw47pWDHrWbwYHD:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ecbdb2c1b5d564802e524d4b20440f1e7f0cff1/cpp/open3d/t/pipelines/registration/Registration.cpp#L96)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`float squared_error = (dist_select.Sum({0})).Item<float>();`
use `float` instead of `float_t` for all the source code in this pr.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 185 at r9](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOoh6eb7wbB3VPymgDO:-MOp-vn078k0Iat5qI39:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/6ecbdb2c1b5d564802e524d4b20440f1e7f0cff1/cpp/open3d/t/pipelines/registration/Registration.cpp#L185)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Whenever using `=` for objects, be very careful. This invokes the copy constructor. In this case, the tensors in `RegistrationResult` are not copied for the reason we discussed in previous comments. For any class that stores `Tensor` as is member variable, consider disabling the copy constructor and copy assignment operator (TODO).

In this PR, let's do the simpler approach. We just need to store the `double prev_fitness_` and `double prev_inliner_rmse_`.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/TransformationEstimation.h, line 49 at r9](https://reviewable.io/reviews/intel-isl/open3d/2743#-MOoiJThD5-fR56zMuLK:-MOotn2S-YJuJCIvet1k:bhci0ao) ([raw file](https://github.com/intel-isl/open3d/blob/6ecbdb2c1b5d564802e524d4b20440f1e7f0cff1/cpp/open3d/t/pipelines/registration/TransformationEstimation.h#L49)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Previously, Eigen gives us the shape and dtype info. But now, it is hidden. Please add a comment on the shape and dtype of the two tensors stored in `CorrespondenceSet` and what they represent.

Also, can it be one tensor (of a larger shape) instead of two tensors? Why did we choose the current design?
</blockquote></details>

yes, I thought this was more convenient like we get 2 tensors of Nx1 from Search (indices, distances), and then I use it to create a pair of two tensors (not the same shape, the shape of corres.first is Nx1 where N is the number of source points [...]

2020-12-18 16:22 UTC, yxlao approved these changes
> Reviewed 10 of 11 files at r11.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2743)* status: 21 of 22 files reviewed, 15 unresolved discussions (waiting on @theNded and @yxlao)



<!-- Sent from Reviewable.io -->

2020-12-18 16:22 UTC, merged