octree updates
intel-isl/Open3D pull request #2833
Opened 2020-12-29 01:32 UTC by plusk01

Changes to `Octree` include:
- new `OctreePointColorLeafNode` (subclass of `OctreeColorLeafNode`) to allow storing of point cloud point indices in each leaf node
- Previously only `OctreeLeafNode` objects had `f_init` and `f_update` functions, which provide flexibility to the user for custom leaf objects. This has been extended to `OctreeInternalNode` objects with `fi_init` and `fi_update` functions (for leaf nodes, renamed to `fl_init`, `fl_update`). For API backward compatibility, if these functions are omitted, the default behavior (i.e., nothing) is used.
-  new `OctreeInternalPointNode` (subclass of `OctreeInternalNode`) to allow internal nodes to store the point cloud point indices of all of its children (useful for searching / processing regions of the point cloud)
- Allow early stopping in `Octree::Traverse` method---For a point cloud with ~50k points and a `max_depth` of 9, this makes `LocateLeafNode` run at ~7 usec. Without early stopping, this search visits every node and takes ~5000 usec.
- C++ and Python examples (via a .ipynb tutorial), added to tutorial docs next to `voxelization`

Fixes #1178, #2681

2020-12-29 01:34 UTC, plusk01 commented
I also tried out @griegler's suggestion (https://github.com/intel-isl/Open3D/issues/1178#issuecomment-540416136) to help users understand the flexibility of the `Octree` class, however, I kept facing inheritance / downcasting walls with pybind (e.g., see attached). It seems related to #572. If anyone has any hints, I'd be happy to try it out.

![octree_advanced_error](https://user-images.githubusercontent.com/3934603/103252744-10046e00-494c-11eb-8873-6426d20539cd.png)

2020-12-30 09:27 UTC, yxlao requested changes

2020-12-30 09:27 UTC, yxlao commented on examples/python/geometry/octree.ipynb
> +{
Please clear all outputs for cells before checking-in the notebook. The CI will run the notebook automatically.

2020-12-30 10:47 UTC, yxlao commented
> I also tried out @griegler's suggestion ([#1178 (comment)](https://github.com/intel-isl/Open3D/issues/1178#issuecomment-540416136)) to help users understand the flexibility of the `Octree` class, however, I kept facing inheritance / downcasting walls with pybind (e.g., see attached). It seems related to #572. If anyone has any hints, I'd be happy to try it out.

Regarding this, I don't have a readily available solution. We used python inheritance before, e.g. https://github.com/intel-isl/Open3D/blob/45fc6d3e4e4bb43e945f7297bb8e7788f310b2d2/python/open3d/core.py#L209, but it was for a simpler case without the trampoline class. The inheritance structure and trampoline class make `OctreeColorLeafNode`'s python inheritance more tricky.

2021-01-04 16:08 UTC, plusk01 commented on cpp/open3d/geometry/Octree.cpp
> +    // if missing, create basic internal node init and update functions
capitalization?

2021-01-04 16:26 UTC, plusk01 commented on cpp/open3d/geometry/Octree.cpp
> +        return this->indices_.size() == (that_point_color_node.indices_.size());
Good catch. I've added `color_` comparison and `indices == indices`.

An `unordered_set` would be useful for the indices comparison step, but I chose `vector` for simplicity and to better interface with `PointCloud::SelectByIndex(const std::vector<size_t> &indices, bool invert = false)`. Further, I'm not sure where `LeafNode::operator==` is being used, so the cost of `vector` comparison may be small (maybe I'm wrong?)

2021-01-04 16:26 UTC, plusk01 commented on cpp/open3d/geometry/Octree.cpp
> +                    "Internal error: leaf node must be OctreeLeafNode");
Oops, I meant `OctreePointColorLeafNode`

2021-01-06 14:13 UTC, plusk01 commented
rebased and force pushed to see if that fixes Ubuntu OpenBLAS CI arm64 build (`pillow` issue)

2021-01-07 02:45 UTC, yxlao commented
Thanks @plusk01. 

Right, recent updates from `pillow` broke our arm64 CI. It has been resolved in `master`.

2021-01-07 02:46 UTC, merged