LU factorisation and Determinant Op
intel-isl/Open3D pull request #2879
Opened 2021-01-08 09:31 UTC by reyanshsolis

### Status: Not ready for review

TODO:
- [ ] cuBLAS wrapper
- [ ] LAPACK wrapper
- [ ] open3d linAlg LUfactorisation CPU and GPU
- [ ] unit test for LUfactorisation
- [ ] determinant op
- [ ] unit test for determinant op
- [ ] pybind and python unit-test for LUfactorisation
- [ ] pybind and python unit-test for determinant op
________

Advanced TODO:
LAPACK _compact routine for optimization and support batch

2021-01-19 11:23 UTC, yxlao requested changes
> Reviewed 15 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2879)* status: all files reviewed, 14 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[cpp/open3d/core/Tensor.h, line 561 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MROwZ6y5e2etO7lX2b6:-MROwZ6y5e2etO7lX2b7:b9ba0hk) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/Tensor.h#L561)):*
> ```objc
>     Tensor T() const;
> 
>     /// \brief Expects input to be 2D square tensor.
> ```

\brief Compute the determinant of a 2D square tensor.
___
*[cpp/open3d/core/Tensor.h, line 1068 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MROwlDb2NT1Bj-5MQB3:-MROwlDb2NT1Bj-5MQB4:bz6zjq9) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/Tensor.h#L1068)):*
> ```objc
>     Tensor LeastSquares(const Tensor& rhs) const;
> 
>     /// Computes LU factorisation of the sqaure tensor *this, using P * A = L *
> ```

remove `*this`
___
*[cpp/open3d/core/Tensor.h, line 1073 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRP6CqW6giwcTqOUoyw:-MRP6CqW6giwcTqOUoyx:b-saf0wa) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/Tensor.h#L1073)):*
> ```objc
>     /// 1D int tensor (The pivot indices, indicating row i of the matrix was
>     /// interchanged with row IPIV(i)).
>     std::tuple<Tensor, Tensor> LU() const;
> ```

Similar to Wei, I also recommend following numpy/scipy's convention (`p, l, u = lu(A)`):  https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html. This would be cleaner and the extra memory use is acceptable.
___
*[cpp/open3d/core/linalg/BlasWrapper.h, line 134 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPHs6PByYu1hVGlWPO:-MRPHs6PByYu1hVGlWPP:bwiqs4l) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/BlasWrapper.h#L134)):*
> ```objc
>                                         scalar_t *A_data[],
>                                         int lda,
>                                         int *PivotArray,
> ```

nit: let's standardize the naming: `pivot_array`, `info_array`, `batch_size`
___
*[cpp/open3d/core/linalg/BlasWrapper.h, line 138 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPIJj_DGkMPzpIH4WV:-MRPIJj_DGkMPzpIH4WW:b-93yqsy) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/BlasWrapper.h#L138)):*
> ```objc
>                                         int batchSize) {
>     utility::LogError("Unsupported data type.");
>     return CUBLAS_STATUS_NOT_SUPPORTED;
> ```

This applies to other wrapper functions as well: if we only have `double` and `float`, could we simply have two versions of overloaded functions instead of having templates? 

To minimize the change, we can try if this idea works for this PR. If it works, we can update other wrappers in a separate PR.
___
*[cpp/tests/core/Linalg.cpp, line 98 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPMnHJBJ5rArUqjIgT:-MRPMnHKCOvVJ6qJAQOF:bm2yri4) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/tests/core/Linalg.cpp#L98)):*
> ```cpp
> 
>     // LU test for 3x3 square 2D tensor of dtype Float32
>     core::Tensor A_3x3f(std::vector<float>{2, 3, 1, 3, 3, 1, 2, 4, 1}, {3, 3},
> ```

we can use the new `Tensor::Init`
___
*[cpp/tests/core/Linalg.cpp, line 103 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPMq3h6LJmo-K3OPO1:-MRPMq3h6LJmo-K3OPO2:btiu07r) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/tests/core/Linalg.cpp#L103)):*
> ```cpp
>     core::Tensor A3f, ipiv3f;
>     std::tie(A3f, ipiv3f) = A_3x3f.LU();
>     std::vector<float> result_vecf{3.0,      3.0,      1.0, 0.666667, 2.0,
> ```

we can create a tensor for the reference output as well, and use `Tensor::AllClose()` for comparision. This way, we don't need to convert to flat vector.
___
*[cpp/tests/core/Tensor.cpp, line 1197 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPN6eJ4plqYvQXQ5EU:-MRPN6eJ4plqYvQXQ5EV:bu8z589) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/tests/core/Tensor.cpp#L1197)):*
> ```cpp
>     // Float32
>     std::vector<float> vals_f{-5, 0, -1, 1, 2, -1, -3, 4, 1};
>     core::Tensor tf(vals_f, {3, 3}, dtype, device);
> ```

same, use `Tensor::Init` for all
___
*[python/test/core/test_linalg.py, line 105 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPNGc38a2tLVnGHMBy:-MRPNGc38a2tLVnGHMBz:bvwgtle) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/python/test/core/test_linalg.py#L105)):*
> ```Python
>         with pytest.raises(RuntimeError) as excinfo:
>             a.det()
>         assert 'Only tensors with Float32 or Float64 are supported' in str(
> ```

I would add an indentation here such that `exeinfo` is used within the context manager `with`. Same for the rest of this file.
___
*[cpp/open3d/core/linalg/LU.h, line 34 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPFHq67UOUoVeZYzH-:-MRPFHq67UOUoVeZYzH0:b46ktk) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.h#L34)):*
> ```objc
> namespace core {
> 
> // TODO: Batch LU factorisation to be added.
> ```

Is batched LU needed for some of our applications?
___
*[cpp/open3d/core/linalg/LU.h, line 48 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPJLe9-aY0zIz8Mvwf:-MRPJLeAEknAbjN4c124:b-petg4c) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.h#L48)):*
> ```objc
> void LU(const Tensor& A, Tensor& output, Tensor& ipiv);
> 
> void LUCPU(void* A_data,
> ```

There is something wried about this pattern: ideally, we want to hide `LUCPU` and LUCUDA` from the public-facing headers. This can be a future work (the same applies to other linalg functions).
___
*[cpp/open3d/core/linalg/LU.cpp, line 64 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPLHYpBK0g6g7scMsd:-MRPLHYqCAy-kMYap4aa:b-km08hy) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.cpp#L64)):*
> ```cpp
>     if (device.GetType() == Device::DeviceType::CUDA) {
> #ifdef BUILD_CUDA_MODULE
>         ipiv = core::Tensor::Empty({n}, core::Dtype::Int32, device);
> ```

can we move this logic to `LUCUDA`and `LUCPU`

e.g. 

```cpp
if (device.GetType() == Device::DeviceType::CUDA) {
    LUCUDA(A, output, ipiv);
} else {
    LUCPU(A, output, ipiv);
}
```
___
*[cpp/open3d/core/linalg/LU.cpp, line 69 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPLiwA2hO2z415Vc_n:-MRPLiwA2hO2z415Vc_o:b7u1978) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.cpp#L69)):*
> ```cpp
>         // "output" tensor is modified in-place as ouput.
>         // cuSolver: COL_MAJOR
>         Tensor output_ = A.T().To(device, /*copy=*/true);
> ```

`A.T().Clone()` would be more clear. `Clone` also ensures the tensor to be contiguous.
___
*[cpp/open3d/core/linalg/LU.cpp, line 96 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPLcd82MbbHJ7kPejj:-MRPLcd82MbbHJ7kPejk:b-7rrq8p) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.cpp#L96)):*
> ```cpp
>         LUCPU(A_data, ipiv_data, n, dtype, device);
>     }
>     return;
> ```

remove return


<!-- Sent from Reviewable.io -->

2021-01-20 17:32 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2879)* status: all files reviewed, 13 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/Tensor.h, line 561 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MROwZ6y5e2etO7lX2b6:-MRVF3q_CJ32z0eE3at1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/Tensor.h#L561)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

\brief Compute the determinant of a 2D square tensor.
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.h, line 1068 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MROwlDb2NT1Bj-5MQB3:-MRVogQe3HxPEpcwgyR2:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/Tensor.h#L1068)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove `*this`
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.h, line 1073 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRP6CqW6giwcTqOUoyw:-MRQ53_Q4vdfJgQKqYt1:b-2wm368) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/Tensor.h#L1073)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Similar to Wei, I also recommend following numpy/scipy's convention (`p, l, u = lu(A)`):  https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html. This would be cleaner and the extra memory use is acceptable.
</blockquote></details>

would you also like me to add the following optional parameters in scipy ?

permute_lbool, optional
Perform the multiplication P*L (Default: do not permute)
overwrite_abool, optional
Whether to overwrite data in a (may improve performance)
check_finitebool, optional
___
*[cpp/open3d/core/linalg/BlasWrapper.h, line 138 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPIJj_DGkMPzpIH4WV:-MRVpvRj7pn9RsFDMKGm:b-x8l8li) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/BlasWrapper.h#L138)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

This applies to other wrapper functions as well: if we only have `double` and `float`, could we simply have two versions of overloaded functions instead of having templates? 

To minimize the change, we can try if this idea works for this PR. If it works, we can update other wrappers in a separate PR.
</blockquote></details>

The batched function is not required as such in this PR. Should I still change it to double and float overload functions, or remove the function itself, to implement when required in the future?
___
*[cpp/tests/core/Linalg.cpp, line 98 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPMnHJBJ5rArUqjIgT:-MRVeNwi2I0qguzVAkx0:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/tests/core/Linalg.cpp#L98)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we can use the new `Tensor::Init`
</blockquote></details>

Done.
___
*[cpp/tests/core/Linalg.cpp, line 103 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPMq3h6LJmo-K3OPO1:-MRVeNMq7psVCRrq6Gcl:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/tests/core/Linalg.cpp#L103)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we can create a tensor for the reference output as well, and use `Tensor::AllClose()` for comparision. This way, we don't need to convert to flat vector.
</blockquote></details>

Done.
___
*[cpp/tests/core/Tensor.cpp, line 1197 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPN6eJ4plqYvQXQ5EU:-MRVnu34AJtcWnHYDoWZ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/tests/core/Tensor.cpp#L1197)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same, use `Tensor::Init` for all
</blockquote></details>

Done.
___
*[python/test/core/test_linalg.py, line 105 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPNGc38a2tLVnGHMBy:-MRVpYwcBBb6O6ZQeycD:b6iwu77) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/python/test/core/test_linalg.py#L105)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

I would add an indentation here such that `exeinfo` is used within the context manager `with`. Same for the rest of this file.
</blockquote></details>

Done. Should I also do the same with other linalg test functions?
___
*[cpp/open3d/core/linalg/LU.h, line 34 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPFHq67UOUoVeZYzH-:-MRQ5U7L56rmujBv17YM:bgkc31s) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.h#L34)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Is batched LU needed for some of our applications?
</blockquote></details>

not right now, I thought we may slowly start adding batch routines for all the linAlg functions like numpy and scipy supports batch. I removed the comment, however. 
___
*[cpp/open3d/core/linalg/LU.h, line 48 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPJLe9-aY0zIz8Mvwf:-MRVGTtR5uMnCpUigqdN:b821oye) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.h#L48)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

There is something wried about this pattern: ideally, we want to hide `LUCPU` and LUCUDA` from the public-facing headers. This can be a future work (the same applies to other linalg functions).
</blockquote></details>

yes, I agree with your point, however, the core/linalg can itself be removed from public-facing headers since a wrapper for each of these functions is already there in Tensor.h for users to use. 
To hide it further, I can make an additional header file for each of the linalg functions which will include the main function header. 
___
*[cpp/open3d/core/linalg/LU.cpp, line 64 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPLHYpBK0g6g7scMsd:-MRVIDjy0snPyKT5ecLy:bkr8oyp) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.cpp#L64)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

can we move this logic to `LUCUDA`and `LUCPU`

e.g. 

```cpp
if (device.GetType() == Device::DeviceType::CUDA) {
    LUCUDA(A, output, ipiv);
} else {
    LUCPU(A, output, ipiv);
}
```
</blockquote></details>

yes, it can be done, but a similar convention has been followed in other linalg functions such as Inverse, Solve. 
Should I let it be like this, or change them all or change only this function? 
___
*[cpp/open3d/core/linalg/LU.cpp, line 69 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPLiwA2hO2z415Vc_n:-MRVR3xl6EJGI_pZeSnZ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.cpp#L69)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`A.T().Clone()` would be more clear. `Clone` also ensures the tensor to be contiguous.
</blockquote></details>

Done.
___
*[cpp/open3d/core/linalg/LU.cpp, line 96 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPLcd82MbbHJ7kPejj:-MRVRAwu-wG-MSO7pHke:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.cpp#L96)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary>< [...]

2021-01-20 17:52 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2879)* status: 8 of 15 files reviewed, 13 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/linalg/BlasWrapper.h, line 138 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPIJj_DGkMPzpIH4WV:-MRVv7xLEVS1T0d-XpF3:bss4a2b) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/BlasWrapper.h#L138)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

The batched function is not required as such in this PR. Should I still change it to double and float overload functions, or remove the function itself, to implement when required in the future?
</blockquote></details>

Removed.
___
*[cpp/open3d/core/linalg/LU.h, line 34 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPFHq67UOUoVeZYzH-:-MRVulY45HVHEGoNAzby:bvpeo2n) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.h#L34)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

not right now, I thought we may slowly start adding batch routines for all the linAlg functions like numpy and scipy supports batch. I removed the comment, however. 
</blockquote></details>

Removed. Done.
___
*[cpp/open3d/core/linalg/LU.cpp, line 64 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPLHYpBK0g6g7scMsd:-MRVutrXEfjAkhmXYId7:b-3kzfvw) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.cpp#L64)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

yes, it can be done, but a similar convention has been followed in other linalg functions such as Inverse, Solve. 
Should I let it be like this, or change them all or change only this function? 
</blockquote></details>

Refactoring to Rfollow in a separate PR. 


<!-- Sent from Reviewable.io -->

2021-01-20 18:58 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2879)* status: 6 of 16 files reviewed, 13 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/linalg/LU.h, line 48 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPJLe9-aY0zIz8Mvwf:-MRW9G7o-XTsRFVY70Dt:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/linalg/LU.h#L48)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

yes, I agree with your point, however, the core/linalg can itself be removed from public-facing headers since a wrapper for each of these functions is already there in Tensor.h for users to use. 
To hide it further, I can make an additional header file for each of the linalg functions which will include the main function header. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 09:27 UTC, yxlao requested changes
> Reviewed 3 of 10 files at r3, 13 of 21 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2879)* status: 17 of 23 files reviewed, 25 unresolved discussions (waiting on @reyanshsolis, @theNded, and @yxlao)

___
*[cpp/open3d/core/Tensor.h, line 1073 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRP6CqW6giwcTqOUoyw:-MRgfQlvArlP4pk5JOti:bumqhvz) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/Tensor.h#L1073)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

would you also like me to add the following optional parameters in scipy ?

permute_lbool, optional
Perform the multiplication P*L (Default: do not permute)
overwrite_abool, optional
Whether to overwrite data in a (may improve performance)
check_finitebool, optional
</blockquote></details>

those can be ignored for now, would be too complex for this PR
___
*[cpp/open3d/core/Tensor.h, line 1080 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe1ibD6sarm7QWtrUO:-MTe1ibE9CKYvpyFxy8b:blllk1b) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/Tensor.h#L1080)):*
> ```objc
>     Tensor LeastSquares(const Tensor& rhs) const;
> 
>     /// \brief Computes LU factorisation of the sqaure tensor,
> ```

`sqaure` -> `square`, replace all
___
*[cpp/open3d/core/Tensor.h, line 1081 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe1rZ-8EW0a0tUdG3N:-MTe1rZ-8EW0a0tUdG3O:b-rdmt6y) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/Tensor.h#L1081)):*
> ```objc
> 
>     /// \brief Computes LU factorisation of the sqaure tensor,
>     /// using A = P * L * U and returns tuple (P, L, U).
> ```

Scipy and pytorch LU decomposition of a non-square matrix, any reason why we limit to square matrix here? 
___
*[cpp/open3d/core/Tensor.h, line 1091 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe2ApWBwYZtY70kNzh:-MTe2ApWBwYZtY70kNzi:b-5fwzqw) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/Tensor.h#L1091)):*
> ```objc
>     /// ipiv of shape {n}. [ipiv, output = open3d.core.lu_with_ipiv(a)]
>     ///
>     /// \returns \p [IPIV] 1D int tensor. It contains the pivot indices,
> ```

the `\p` doesn't work here, also it is `\return` not `\returns` (replace all)

We can say something like:

```cpp
/// \return Tuple {ipiv, output}. Where ipiv ...; and output ... 
```
___
*[cpp/open3d/core/Tensor.h, line 1094 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe1nMYEetkxi-roTQ4:-MTe1nMYEetkxi-roTQ5:b3eb3ow) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/Tensor.h#L1094)):*
> ```objc
>     /// indicating row i of the matrix was interchanged with row IPIV(i)).
>     /// \p [Output] it has L as lower triangular values and U as upper
>     /// triangle values including the main diagonal (diagonal elemetes of L to
> ```

`elemetes` -> `elements`, replace all
___
*[cpp/open3d/core/Tensor.h, line 1096 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe2cW686fSYTRyjaTS:-MTe2cW686fSYTRyjaTT:bnq09rs) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/Tensor.h#L1096)):*
> ```objc
>     /// triangle values including the main diagonal (diagonal elemetes of L to
>     /// be taken as unity).
>     std::tuple<Tensor, Tensor> LU_with_ipiv() const;
> ```

Rename to `LUIpiv` to match our naming conversion. 

Actually, what does the `i` in `ipiv` mean? Does it stand for "integer" "pivot"?
___
*[cpp/open3d/core/Tensor.h, line 1111 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe3TtKDK_wNs9O1x8H:-MTe3TtKDK_wNs9O1x8I:bz74inv) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/Tensor.h#L1111)):*
> ```objc
>     /// \brief Returns the lower triangular matrix of the 2D tensor,
>     /// above the given diagonal index. [The value of diagonal = col - row,
>     /// therefore 0 is the main diagonal (i = j), and it shifts towards right
> ```

Here we are mixing the use of i, j, col, row, m, n. Let's make them consistent. Same for `Triu`, `Tril`, Triul`. 
___
*[cpp/open3d/core/linalg/Det.h, line 37 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe553I5TGMjUxK6nsH:-MTe553I5TGMjUxK6nsI:b-hcmdmw) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/linalg/Det.h#L37)):*
> ```objc
> /// \param A input 2D sqaure matrix.
> /// \return determinant [double].
> double Det(const Tensor& A);
> ```

I am fine with removing the documentation here for things under `core/linalg`, to avoid duplication. Similar to 


We can simply point the user to the `Tensor::Det`. E.g.

```cpp
// See documentation for `core::Tensor::Det`.
```

Could you do this for the rest of the functions?
___
*[cpp/open3d/core/linalg/Det.cpp, line 46 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe6YMp-Oe-FIwpmVaV:-MTe6YMp-Oe-FIwpmVaW:btnleh6) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/linalg/Det.cpp#L46)):*
> ```cpp
> 
>     DISPATCH_FLOAT32_FLOAT64_DTYPE(A.GetDtype(), [&]() {
>         scalar_t* output_ptr = static_cast<scalar_t*>(output_cpu.GetDataPtr());
> ```

you can now do `GetDataPtr<scalar_t>()`, apply this to the rest of this PR
___
*[cpp/open3d/core/linalg/TriangularMat.h, line 1 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe7cQj9zx-OI9MH19y:-MTe7cQj9zx-OI9MH19z:b-jwlpgo) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/linalg/TriangularMat.h#L1)):*
> ```objc
> // ----------------------------------------------------------------------------
> ```

Could we call this `Tri.h` to be simpler (and more consistent with the function name).
___
*[cpp/open3d/core/linalg/TriangularMat.cpp, line 41 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe8M6U8HNVcCMEudKu:-MTe8M6U8HNVcCMEudKv:b-lapfoz) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/linalg/TriangularMat.cpp#L41)):*
> ```cpp
>     SizeVector A_shape = A.GetShape();
>     if (A_shape.size() != 2) {
>         utility::LogError("Tensor A must be 2D, but got {}D.", A_shape.size());
> ```

`Tensor A` -> `Tensor`, since the user may not know about `A` if they use `Tensor::Triu`. 

Same for the rest.
___
*[cpp/open3d/core/linalg/TriangularMat.cpp, line 70 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe8cwf4Z1HJMok68Qv:-MTe8cwf4Z1HJMok68Qw:b-fr97wo) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/linalg/TriangularMat.cpp#L70)):*
> ```cpp
> 
>     // Check dimensions.
>     SizeVector A_shape = A.GetShape();
> ```

group the sanity checks in one function for `tril`, `triu`, `triul`, to avoid code duplication
___
*[cpp/open3d/core/linalg/TriangularMatCUDA.cu, line 48 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe9Bq20rTKy8xLuD_p:-MTe9Bq20rTKy8xLuD_q:b-7qytya) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/linalg/TriangularMatCUDA.cu#L48)):*
> ```Cuda
>                     const int64_t idx = workload_idx / cols;
>                     const int64_t idy = workload_idx % cols;
>                     if (idy - idx >= diagonal)
> ```

add `{}`, same for the rest
___
*[cpp/pybind/core/tensor.cpp, line 404 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe9NQj9gr5pR16QXGR:-MTe9NQj9gr5pR16QXGS:bj7v1kz) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/pybind/c [...]

2021-02-18 12:42 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2879)* status: 5 of 25 files reviewed, 25 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/Tensor.h, line 1073 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRP6CqW6giwcTqOUoyw:-MTfWflM3FbKsMYlrSmY:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/cpp/open3d/core/Tensor.h#L1073)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

those can be ignored for now, would be too complex for this PR
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.h, line 1080 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe1ibD6sarm7QWtrUO:-MTnWYul4i8r0AgJAuQp:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/Tensor.h#L1080)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`sqaure` -> `square`, replace all
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.h, line 1081 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe1rZ-8EW0a0tUdG3N:-MTnyb759dtPcmEcueHN:b-tbb5a) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/Tensor.h#L1081)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Scipy and pytorch LU decomposition of a non-square matrix, any reason why we limit to square matrix here? 
</blockquote></details>

Only square matrix support was required for our current purpose. I will test non-square cases and update if we can support that too. 
___
*[cpp/open3d/core/Tensor.h, line 1091 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe2ApWBwYZtY70kNzh:-MTnXEN824b9ytymJYU_:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/Tensor.h#L1091)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

the `\p` doesn't work here, also it is `\return` not `\returns` (replace all)

We can say something like:

```cpp
/// \return Tuple {ipiv, output}. Where ipiv ...; and output ... 
```
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.h, line 1094 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe1nMYEetkxi-roTQ4:-MTnXK9q-S7ZKnW_nXwU:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/Tensor.h#L1094)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`elemetes` -> `elements`, replace all
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.h, line 1096 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe2cW686fSYTRyjaTS:-MTnypLn2BphCHG7xkPJ:b-vz18x0) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/Tensor.h#L1096)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Rename to `LUIpiv` to match our naming conversion. 

Actually, what does the `i` in `ipiv` mean? Does it stand for "integer" "pivot"?
</blockquote></details>

ipiv is the "integer array of pivot indices". So, I guess you are right. However, I didn't find any official documentation confirmation. 
___
*[cpp/open3d/core/Tensor.h, line 1111 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe3TtKDK_wNs9O1x8H:-MTnYc1I-o6KZPgbUfXv:b-oj3pbq) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/Tensor.h#L1111)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Here we are mixing the use of i, j, col, row, m, n. Let's make them consistent. Same for `Triu`, `Tril`, Triul`. 
</blockquote></details>

changed i = j to row = col. m, n represents the shape of the matrix. [the value of the diagonal parameter must be between [-m, n] where {m, n} is the shape of input tensor].
___
*[cpp/open3d/core/linalg/Det.h, line 37 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe553I5TGMjUxK6nsH:-MToqU5h-rBvRE-vfxj8:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/linalg/Det.h#L37)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

I am fine with removing the documentation here for things under `core/linalg`, to avoid duplication. Similar to 


We can simply point the user to the `Tensor::Det`. E.g.

```cpp
// See documentation for `core::Tensor::Det`.
```

Could you do this for the rest of the functions?
</blockquote></details>

Done.
___
*[cpp/open3d/core/linalg/Det.cpp, line 46 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe6YMp-Oe-FIwpmVaV:-MTnZs8p5qxJoZtUIueF:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/linalg/Det.cpp#L46)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

you can now do `GetDataPtr<scalar_t>()`, apply this to the rest of this PR
</blockquote></details>

Done.
___
*[cpp/pybind/core/tensor.cpp, line 404 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe9NQj9gr5pR16QXGR:-MTnkX6TBjmvuYAGw5IM:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/pybind/core/tensor.cpp#L404)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we can rename this to `lu_ipiv`, if we rename the corresponding function in c++
</blockquote></details>

Done.
___
*[python/test/core/test_linalg.py, line 105 at r2](https://reviewable.io/reviews/intel-isl/open3d/2879#-MRPNGc38a2tLVnGHMBy:-MTp5oW7A-mQKz9FP-Mc:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/676a694639fafa99f002216b76b089cbe496d854/python/test/core/test_linalg.py#L105)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

yes, you may change them all
</blockquote></details>

Done.
___
*[cpp/open3d/core/linalg/LU.cpp, line 37 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe6t1v--yf2g-xn0WD:-MTn_6XC5qioPvJ3eiaT:b7m6wdn) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/linalg/LU.cpp#L37)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`static core::Tensor ...`.

Can we just put the implementation here? (e.g. without forward declaration)
</blockquote></details>

I have made GetColPermutation and OutputToPLU functions`inline` Are you also suggesting to make them `static` ? 
___
*[cpp/open3d/core/linalg/LU.cpp, line 42 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe71O3DggKp4mXcVdy:-MToqa3n6vhFSBVNd9VY:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/linalg/LU.cpp#L42)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`static void OutputToPLU ...`.

Can we just put the implementation here? (e.g. without forward declaration)
</blockquote></details>

Done.
___
*[cpp/open3d/core/linalg/LU.cpp, line 131 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe84I_3Wm9SrfbXsQZ:-MTn_fdL5kMW5IMmQdH3:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/linalg/LU.cpp#L131)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`col_permutation` to match the naming convention
</blockquote></details>

Done.
___
*[cpp/open3d/core/linalg/LU.cpp, line 149 at r5](https://reviewable.io/reviews/intel-isl/open3d/2879#-MTe7Oc90NnjMOghzvV8:-MTn_v6X8kDHbVnYuAQl:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d773120ce0d9c78ae49f8755a2e709ca8a495806/cpp/open3d/core/linalg/L [...]

2021-03-01 09:45 UTC, yxlao approved these changes
> Reviewed 13 of 23 files at r6.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2879)* status: 15 of 25 files reviewed, 11 unresolved discussions (waiting on @theNded and @yxlao)



<!-- Sent from Reviewable.io -->

2021-03-01 09:51 UTC, merged