Image processing Ops sample with IPP and NPP
intel-isl/Open3D pull request #2898
Opened 2021-01-14 23:33 UTC by ssheorey

- Image::Dilate() with NPP and IPP. No ARM support, limited datatype support on CPU/GPU.
- Image::ConvertTo() and Image::LinearTransform() (in terms of tensor operations)
- CUDA_CALL and IPP_CALL macros to call CUDA/IPP functions only if CUDA/IPP support is built
- Install IPP-IW from OpenCV Github release
- Use NPP from CUDA installation
- Separate checking for (dtype, channels) support for each image op for NPP and IPP
- C++ Unit tests

Note:
- IPP IW from OpenCV is used for quick integration
- No support for USE_SYSTEM_IPP

TODO: Python bindings

2021-01-19 09:11 UTC, yxlao requested changes
Seems like there are some file permission change `normal -> executable`:

![image.png](https://files.reviewableusercontent.io/images/reviewable/1501945/YBrAZaIi6lAHszO-Di3OOJ0X/image.png)

> Reviewed 13 of 19 files at r1, 7 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2898#-:-MRNVjLr98CDZyia6uE7:b-85t7hn)* status: 20 of 21 files reviewed, 32 unresolved discussions (waiting on @reyanshsolis, @ssheorey, @theNded, and @yxlao)

___
*[3rdparty/find_dependencies.cmake, line 1140 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNBbzq4a_UVv9P_hpo:-MRNBbzq4a_UVv9P_hpp:ba70th5) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/3rdparty/find_dependencies.cmake#L1140)):*
> ```CMake
> if (WITH_IPPICV)
>     include(${Open3D_3RDPARTY_DIR}/ippicv/ippicv.cmake)
>     if (WITH_IPPICV)    # If platform is unsupported, this will fail
> ```

shall we add arm64 detection to switch off `WITH_IPPICV` automatically?
___
*[3rdparty/find_dependencies.cmake, line 1143 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNFbej0xIn53owTZSb:-MRNFbej0xIn53owTZSc:bjit6rz) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/3rdparty/find_dependencies.cmake#L1143)):*
> ```CMake
>         message(STATUS "IPP-ICV ${IPPICV_VERSION_STRING} available. Building interface wrappers IPP-IW.")
>         import_3rdparty_library(3rdparty_ippicv
>             INCLUDE_DIRS "${IPPIW_INCLUDE_DIR}" "${IPPICV_INCLUDE_DIR}"
> ```

We can concatenate `IPPICV_INCLUDE_DIR` and `IPPIW_INCLUDE_DIR` in `ippicv.cmake`, such that we only need to use `IPPICV_INCLUDE_DIR` here. This would be more consistent with the usage of other libraries.

Same for the `LIBRARIES` property.
___
*[3rdparty/ippicv/ippicv.cmake, line 26 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNGNZi5A-tO4grIT28:-MRNGNZi5A-tO4grIT29:b-ov5olo) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/3rdparty/ippicv/ippicv.cmake#L26)):*
> ```CMake
> else()
>     set(WITH_IPPICV OFF)
>     message(WARNING "IPP-ICV disabled: Unsupported Platform.")
> ```

shall we use `FATAL_ERROR` here as well?
___
*[3rdparty/ippicv/ippicv.cmake, line 40 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNH2-R7dtMe7e7Wy9Z:-MRNH2-R7dtMe7e7Wy9_:br991z1) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/3rdparty/ippicv/ippicv.cmake#L40)):*
Perhaps `PATCH_COMMAND` would be more clear here, since it is our own patch.

From https://cmake.org/cmake/help/v3.19/module/ExternalProject.html, it seems like `UPDATE_COMMAND` refers to source code version updates.

> by default the external project’s sources will be updated if the download method supports updates **(e.g. a git repository would be checked if the GIT_TAG does not refer to a specific commit).**
___
*[cpp/open3d/core/Tensor.h, line 761 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNIa_v7Fu-sYT2uhPh:-MRNIa_v7Fu-sYT2uhPi:b-l9lpxa) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/core/Tensor.h#L761)):*
> ```objc
>     Tensor Abs_();
> 
>     /// Element wise clipping of tensor values so that resulting values lie in
> ```

- Nit: `Element-wise`
- Nit: `returning a new tensor.` (with `.`)
- Add `\param min_val` and `\param max_val`, such that `\p` works
___
*[cpp/open3d/core/Tensor.cpp, line 908 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNLb1D2oXPZO6PD8sY:-MRNLb1D2oXPZO6PD8sZ:bxpf1o4) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/core/Tensor.cpp#L908)):*
> ```cpp
> Tensor Tensor::Clip(double min_val, double max_val) const {
>     Tensor dst_tensor(shape_, dtype_, GetDevice());
>     /* kernel::UnaryEW(*this, dst_tensor, kernel::UnaryEWOpCode::Abs) ; */
> ```

remove comments?
___
*[cpp/open3d/core/Tensor.cpp, line 914 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNLc8P23IKynpVK9UQ:-MRNLc8P23IKynpVK9UR:bxpf1o4) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/core/Tensor.cpp#L914)):*
> ```cpp
> 
> Tensor Tensor::Clip_(double min_val, double max_val) {
>     /* kernel::UnaryEW(*this, *this, kernel::UnaryEWOpCode::Abs); */
> ```

remove comments?
___
*[cpp/open3d/t/geometry/CMakeLists.txt, line 12 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNLkds6jPTGh4_HvFn:-MRNLkds6jPTGh4_HvFo:b4xk36r) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/CMakeLists.txt#L12)):*
> ```CMake
>     kernel/PointCloudCUDA.cu
>     kernel/TSDFVoxelGridCUDA.cu
>     kernel/nppImage.cpp
> ```

By our naming convention, we can call it `NPPImage` or `NppImage`. Same for `ipp`.
___
*[cpp/open3d/t/geometry/CMakeLists.txt, line 37 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNM7Rs27bWIJIVVG8c:-MRNM7Rs27bWIJIVVG8d:b-m1imf1) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/CMakeLists.txt#L37)):*
> ```CMake
> if (WITH_IPPICV)
>     list(APPEND ALL_T_GEOMETRY_SRC ${T_GEOMETRY_KERNEL_IPP_SRC})
> endif()
> ```

This part looks quite convoluted. We actually only need one variable `T_GEOMETRY_SRC` and we can just append to it with `set` instead of `list(APPEND`. We also don't need to distinguish the `KERNEL` or `IPP` sources.

Something like:
```
set(T_GEOMETRY_SRC 
    cpu_source_0.cpp
    cpu_source_1.cpp
)

if(BUILD_CUDA_MODULE)
    set(T_GEOMETRY_SRC
        ${T_GEOMETRY_SRC}
        cuda_source_0.cpp
        cuda_source_1.cpp
    )
endif()

if(WITH_IPPICV)
    set(T_GEOMETRY_SRC
        ${T_GEOMETRY_SRC}
        ipp_source_0.cpp
        ipp_source_1.cpp
    )
endif()
```
___
*[cpp/open3d/t/geometry/CMakeLists.txt, line 50 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNP0vFCOyYNhQNG7br:-MRNP0vFCOyYNhQNG7bs:b-c62vfg) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/CMakeLists.txt#L50)):*
> ```CMake
> 
> if (WITH_IPPICV)
>     target_compile_definitions(tgeometry PRIVATE WITH_IPPICV HAVE_IPPICV=true)
> ```

is there a way we can reduce this to one, e.g. only using `WITH_IPPICV`?

Future work: we may need to unify all macros in code to have `OPEN3D_` prefix to avoid collision with other libraries.
___
*[cpp/open3d/t/geometry/Image.h, line 170 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNTRoqEL4kuGyUsTMt:-MRNTRoqEL4kuGyUsTMu:bm566er) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/Image.h#L170)):*
> ```objc
>             -std::numeric_limits<double>::max();
> 
>     /// Returns an Image with the specified \p Dtype.
> ```

`\p dtype`
___
*[cpp/open3d/t/geometry/Image.h, line 177 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNTTfq0pkab33iptEr:-MRNTTfq0pkab33iptEs:b-h0f0pj) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/Image.h#L177)):*
> ```objc
>     /// \param copy If true, a new tensor is always created; if false, the copy
>     /// is avoided when the original tensor already has the targeted dtype.
>     Image ConvertTo(core::Dtype dtype,
> ```

Let's rename it to `Image::To` following https://github.com/intel-isl/Open3D/pull/2877 . 

It may be tricky to define `SCALE_DEFAULT`, would `optional` help here? E.g .
```
Image To(
    core::Dtype dtype,
    bool copy = false,
    utility::optional<double> scale = utility::nullopt,
    utility::optional<double> offset = utility::nullopt
) const;
```
(Moving `copy` to the front to be consistent with #2877. `offset` doesn't need to be `optional` but it might be good to keep the symmetry.)

Then the default scale can b [...]

2021-01-25 18:47 UTC, ssheorey reviewed
Good catch. I think that happened when I tested on Windows and copied the changed files back to my Mac. Fixed.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2898#-:-MRRWd4U3D_LbOSzPsb7:b-krxdt4)* status: 7 of 22 files reviewed, 28 unresolved discussions (waiting on @reyanshsolis, @theNded, and @yxlao)

___
*[3rdparty/find_dependencies.cmake, line 1140 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNBbzq4a_UVv9P_hpo:-MRR_n70DOBpRbOXAhYo:b7fwuen) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/3rdparty/find_dependencies.cmake#L1140)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

shall we add arm64 detection to switch off `WITH_IPPICV` automatically?
</blockquote></details>

That currently happens inside `ippicv.cmake`. Added it here for clarity.
___
*[3rdparty/find_dependencies.cmake, line 1143 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNFbej0xIn53owTZSb:-MRRhcNY-ZlHEs-4b_Hx:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/3rdparty/find_dependencies.cmake#L1143)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We can concatenate `IPPICV_INCLUDE_DIR` and `IPPIW_INCLUDE_DIR` in `ippicv.cmake`, such that we only need to use `IPPICV_INCLUDE_DIR` here. This would be more consistent with the usage of other libraries.

Same for the `LIBRARIES` property.
</blockquote></details>

Done.
___
*[3rdparty/ippicv/ippicv.cmake, line 26 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNGNZi5A-tO4grIT28:-MRRYF0078KXYFop0kJl:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/3rdparty/ippicv/ippicv.cmake#L26)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

shall we use `FATAL_ERROR` here as well?
</blockquote></details>

Done.
___
*[3rdparty/ippicv/ippicv.cmake, line 40 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNH2-R7dtMe7e7Wy9Z:-MRRYLEv0qtI_AaEk5JG:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/3rdparty/ippicv/ippicv.cmake#L40)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Perhaps `PATCH_COMMAND` would be more clear here, since it is our own patch.

From https://cmake.org/cmake/help/v3.19/module/ExternalProject.html, it seems like `UPDATE_COMMAND` refers to source code version updates.

> by default the external project’s sources will be updated if the download method supports updates **(e.g. a git repository would be checked if the GIT_TAG does not refer to a specific commit).**
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.h, line 761 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNIa_v7Fu-sYT2uhPh:-MRRiJuU5S52A9QI0ERp:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/core/Tensor.h#L761)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

- Nit: `Element-wise`
- Nit: `returning a new tensor.` (with `.`)
- Add `\param min_val` and `\param max_val`, such that `\p` works
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.cpp, line 908 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNLb1D2oXPZO6PD8sY:-MRRivD_98CkpY7H34cw:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/core/Tensor.cpp#L908)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove comments?
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.cpp, line 914 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNLc8P23IKynpVK9UQ:-MRRivmj5hg4y-49RIpJ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/core/Tensor.cpp#L914)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove comments?
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/CMakeLists.txt, line 12 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNLkds6jPTGh4_HvFn:-MRRYmNl11HRRDwf_1T0:b-x3d1h4) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/CMakeLists.txt#L12)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

By our naming convention, we can call it `NPPImage` or `NppImage`. Same for `ipp`.
</blockquote></details>

Renamed to NPPImage and IPPImage
___
*[cpp/open3d/t/geometry/CMakeLists.txt, line 37 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNM7Rs27bWIJIVVG8c:-MRRmDjU9yhNwYt417p0:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/CMakeLists.txt#L37)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

This part looks quite convoluted. We actually only need one variable `T_GEOMETRY_SRC` and we can just append to it with `set` instead of `list(APPEND`. We also don't need to distinguish the `KERNEL` or `IPP` sources.

Something like:
```
set(T_GEOMETRY_SRC 
    cpu_source_0.cpp
    cpu_source_1.cpp
)

if(BUILD_CUDA_MODULE)
    set(T_GEOMETRY_SRC
        ${T_GEOMETRY_SRC}
        cuda_source_0.cpp
        cuda_source_1.cpp
    )
endif()

if(WITH_IPPICV)
    set(T_GEOMETRY_SRC
        ${T_GEOMETRY_SRC}
        ipp_source_0.cpp
        ipp_source_1.cpp
    )
endif()
```
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/CMakeLists.txt, line 50 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNP0vFCOyYNhQNG7br:-MRRta2Y3MFyO1pH-sQ2:b-tx2mh0) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/CMakeLists.txt#L50)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

is there a way we can reduce this to one, e.g. only using `WITH_IPPICV`?

Future work: we may need to unify all macros in code to have `OPEN3D_` prefix to avoid collision with other libraries.
</blockquote></details>

Done. Moved HAVE_IPPICV to a `static const bool` member of `t::Geoemetry::Image`
___
*[cpp/open3d/t/geometry/Image.h, line 170 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNTRoqEL4kuGyUsTMt:-MRRuiax9o4Oj0L3l_oC:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/Image.h#L170)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`\p dtype`
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.h, line 177 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNTTfq0pkab33iptEr:-MRRxpBlCRA43B7MW6CR:bicm4nc) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/Image.h#L177)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Let's rename it to `Image::To` following https://github.com/intel-isl/Open3D/pull/2877 . 

It may be tricky to define `SCALE_DEFAULT`, would `optional` help here? E.g .
```
Image To(
    core::Dtype dtype,
    bool copy = false,
    utility::optional<double> scale = utility::nullopt,
    utility::optional<double> offset = utility::nullopt
) const;
```
(Moving `copy` to the front to be consistent with #2877. `offset` doesn't need to be `optional` but it might be good to keep the symmetry.)

Then the default scale can be handled in the function definition.
</blockquote></details>

Done (for scale. Kept offset default at 0).
___
*[cpp/open3d/t/geometry/Image.cpp, line 102 at r3](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRO82hZ2KAIiSsQLtFE:-MRS0G_797lJ6cvtQ4pH:b-xeoz13) ([raw file](https://github.com/intel-isl/open3d/blo [...]

2021-01-27 14:22 UTC, reyanshsolis requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2898)* status: 5 of 25 files reviewed, 29 unresolved discussions (waiting on @ssheorey, @theNded, and @yxlao)

___
*[cpp/open3d/t/geometry/Image.h, line 177 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNTTfq0pkab33iptEr:-MS3BtvCDrXAQS1N1PhM:b-ayu27) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/Image.h#L177)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Done (for scale. Kept offset default at 0).
</blockquote></details>

Can we support overloading "To" functions for device transfers? 
To(device), To(device, dtype, copy), To(dtype, copy, scale, offset). 
___
*[cpp/open3d/t/geometry/Image.h, line 164 at r5](https://reviewable.io/reviews/intel-isl/open3d/2898#-MS3CW3A1UIbDr3p9izm:-MS3CW3A1UIbDr3p9izn:b-9zmyu1) ([raw file](https://github.com/intel-isl/open3d/blob/6fe2f0294054e15dc3c50e5b2add14af1099107a/cpp/open3d/t/geometry/Image.h#L164)):*
> ```objc
>     /// \param half_kernel_size A dilation mask of size 2*half_kernel_size+1 is
>     /// used.
>     Image Dilate(int half_kernel_size = 1) const;
> ```

Can we also add in-place functions for such operations, such as Dilate_ that will modify *this itself ?


<!-- Sent from Reviewable.io -->

2021-01-28 00:40 UTC, ssheorey reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2898)* status: 5 of 27 files reviewed, 29 unresolved discussions (waiting on @reyanshsolis, @theNded, and @yxlao)

___
*[cpp/open3d/t/geometry/Image.h, line 177 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNTTfq0pkab33iptEr:-MS4P8PP6LGO4-mwU4cn:bv04u8e) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/Image.h#L177)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Can we support overloading "To" functions for device transfers? 
To(device), To(device, dtype, copy), To(dtype, copy, scale, offset). 
</blockquote></details>

Added `To(device)`, `CPU()`, `CUDA()`, `Clone()` (+ tests) so we now have equivalent functionality in `PointCloud` and `Image`.  Can add `To(device, dtype)` in another PR if there is need.
___
*[cpp/open3d/t/geometry/Image.h, line 164 at r5](https://reviewable.io/reviews/intel-isl/open3d/2898#-MS3CW3A1UIbDr3p9izm:-MS4Q49C6DOfUl6oE-oM:bgg24n4) ([raw file](https://github.com/intel-isl/open3d/blob/6fe2f0294054e15dc3c50e5b2add14af1099107a/cpp/open3d/t/geometry/Image.h#L164)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Can we also add in-place functions for such operations, such as Dilate_ that will modify *this itself ?
</blockquote></details>

Dilate (like Filter) is a neighbourhood operation and can't be done in place.


<!-- Sent from Reviewable.io -->

2021-01-28 03:49 UTC, reyanshsolis requested changes
> Reviewed 13 of 20 files at r5, 9 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2898)* status: all files reviewed, 29 unresolved discussions (waiting on @ssheorey, @theNded, and @yxlao)

___
*[cpp/open3d/t/geometry/Image.h, line 177 at r2](https://reviewable.io/reviews/intel-isl/open3d/2898#-MRNTTfq0pkab33iptEr:-MS6135v8JyDaZEmUl87:b-ewk8my) ([raw file](https://github.com/intel-isl/open3d/blob/151079dafdb35b50f87b0cb2b1e9a7283f99e9a3/cpp/open3d/t/geometry/Image.h#L177)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Added `To(device)`, `CPU()`, `CUDA()`, `Clone()` (+ tests) so we now have equivalent functionality in `PointCloud` and `Image`.  Can add `To(device, dtype)` in another PR if there is need.
</blockquote></details>

Thanks. This is helpful.
___
*[cpp/open3d/t/geometry/Image.h, line 164 at r5](https://reviewable.io/reviews/intel-isl/open3d/2898#-MS3CW3A1UIbDr3p9izm:-MS61Ovk31TgTDOjkgzh:b43ejbi) ([raw file](https://github.com/intel-isl/open3d/blob/6fe2f0294054e15dc3c50e5b2add14af1099107a/cpp/open3d/t/geometry/Image.h#L164)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Dilate (like Filter) is a neighbourhood operation and can't be done in place.
</blockquote></details>

right! understood, thanks for the clarification. 
___
*[cpp/open3d/t/geometry/kernel/IPPImage.h, line 47 at r6](https://reviewable.io/reviews/intel-isl/open3d/2898#-MS62jzO1usuLWCe6xAc:-MS62jzP9lKo5EZsZyOf:b-jwjxry) ([raw file](https://github.com/intel-isl/open3d/blob/b3e2c2a39461178645ed1def8f7c3b3c66c0a75e/cpp/open3d/t/geometry/kernel/IPPImage.h#L47)):*
> ```objc
>     if (dtype == core::Dtype::UInt8 || dtype == core::Dtype::Bool) {
>         return ipp8u;
>     } else if (dtype == core::Dtype::UInt16) {
> ```

`else if (dtype == core::Dtype::UInt16) { return ipp16u; }` repeated twice. 


<!-- Sent from Reviewable.io -->

2021-01-28 04:04 UTC, ssheorey reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2898)* status: all files reviewed, 29 unresolved discussions (waiting on @reyanshsolis, @theNded, and @yxlao)

___
*[cpp/open3d/t/geometry/kernel/IPPImage.h, line 47 at r6](https://reviewable.io/reviews/intel-isl/open3d/2898#-MS62jzO1usuLWCe6xAc:-MS68tX1C4sTcfqGBFMc:b4x3gpo) ([raw file](https://github.com/intel-isl/open3d/blob/b3e2c2a39461178645ed1def8f7c3b3c66c0a75e/cpp/open3d/t/geometry/kernel/IPPImage.h#L47)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

`else if (dtype == core::Dtype::UInt16) { return ipp16u; }` repeated twice. 
</blockquote></details>

Thanks. Will remove.


<!-- Sent from Reviewable.io -->

2021-01-31 23:30 UTC, yxlao approved these changes
> Reviewed 12 of 20 files at r5, 8 of 9 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2898)* status: all files reviewed, 29 unresolved discussions (waiting on @reyanshsolis, @theNded, and @yxlao)



<!-- Sent from Reviewable.io -->

2021-01-31 23:30 UTC, merged