Fix linking issue of Torch/TF Ops
intel-isl/Open3D pull request #2957
Opened 2021-01-28 14:41 UTC by sanskar107

Fix linking of Torch/TF Ops with Open3D.

2021-01-28 15:13 UTC, benjaminum requested changes
Looks good but we must address the following before we can merge
- We need to add the unit test from the ml-link branch (https://github.com/intel-isl/Open3D/blob/b0c0ed9fbb311a3858f84d3cd86a347cd5ca6d42/python/test/ml_ops/test_tf_training_graph_mode.py)
- Document the configuration that produces the linking problem (I can do that)

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2957#-:-MS8XX9K88Ftp8Np3cVU:b-pko5om)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yxlao)



<!-- Sent from Reviewable.io -->

2021-01-29 01:14 UTC, yxlao approved these changes

2021-02-17 22:57 UTC, germanros1987 commented
@sanskar107 have we addressed @benjaminum requests?

2021-02-17 23:30 UTC, benjaminum commented
> @sanskar107 have we addressed @benjaminum requests?

yes

2021-02-19 00:55 UTC, merged