IPP/NPP image operators
intel-isl/Open3D pull request #2972
Opened 2021-01-30 20:42 UTC by theNded

Do not merge until #2898 is merged.

This PR brings
- [x] Gaussian filter
- [x] Bilateral filter
- [x] Sobel filter
- [x] RGB to gray conversion
supported by IPP/NPP.

Pending features:
- [ ] Box filter for downsampling
- [ ] Pybind
- [ ] Tests

2021-02-12 13:40 UTC, yxlao requested changes
> Reviewed 6 of 13 files at r6, 7 of 14 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2972)* status: 15 of 19 files reviewed, 18 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[3rdparty/ippicv/CMakeLists.txt, line 14 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLLB4nE_kYUeuukoDg:-MTLLB4oAmoeIe1jTMlW:b-i2yvov) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/3rdparty/ippicv/CMakeLists.txt#L14)):*
> ```CMake
> 
> add_library(ippiw STATIC ${lib_srcs} ${lib_hdrs})
> add_compile_definitions(IW_ENABLE_iwiResize_Nearest=1)
> ```

Theoretically, it's better to use `target_*` to prevent properties from leaking.

`target_compile_definitions(ippiw PRIVATE IW_ENABLE_iwiResize_Nearest=1)`, or, is `PRIVATE` suffucient?

`include_directories` shall be `target_include_directories(ippiw PRIVATE ...)`
___
*[cpp/open3d/core/Dispatch.h, line 58 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLRSEt-eDGnoHQ2Uy3:-MTLRSEu0l7CEJ2LXeBL:b-5qiiwd) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/core/Dispatch.h#L58)):*
> ```objc
>             return __VA_ARGS__();                           \
>         } else if (DTYPE == open3d::core::Dtype::Int16) {   \
>             using scalar_t = int16_t;                       \
> ```

We shall add some tests for int16 computation. I think we're missing some more `int16` changes. These are a subset of them:

```diff
diff --git a/cpp/open3d/core/Tensor.cpp b/cpp/open3d/core/Tensor.cpp
index dd9771561..f388e429e 100644
--- a/cpp/open3d/core/Tensor.cpp
+++ b/cpp/open3d/core/Tensor.cpp
@@ -83,6 +83,8 @@ private:
             dl_data_type.code = DLDataTypeCode::kDLFloat;
         } else if (dtype == Dtype::Float64) {
             dl_data_type.code = DLDataTypeCode::kDLFloat;
+        } else if (dtype == Dtype::Int16) {
+            dl_data_type.code = DLDataTypeCode::kDLInt;
         } else if (dtype == Dtype::Int32) {
             dl_data_type.code = DLDataTypeCode::kDLInt;
         } else if (dtype == Dtype::Int64) {
@@ -1152,6 +1154,9 @@ Tensor Tensor::FromDLPack(const DLManagedTensor* src) {
             break;
         case DLDataTypeCode::kDLInt:
             switch (src->dl_tensor.dtype.bits) {
+                case 16:
+                    dtype = Dtype::Int32;
+                    break;
                 case 32:
                     dtype = Dtype::Int32;
                     break;
diff --git a/cpp/pybind/core/tensor.cpp b/cpp/pybind/core/tensor.cpp
index 7a0dae766..a2b3aa51e 100644
--- a/cpp/pybind/core/tensor.cpp
+++ b/cpp/pybind/core/tensor.cpp
@@ -51,6 +51,7 @@
     });                                                                     \
     tensor.def(#py_name, &Tensor::cpp_name<float>);                         \
     tensor.def(#py_name, &Tensor::cpp_name<double>);                        \
+    tensor.def(#py_name, &Tensor::cpp_name<int16_t>);                       \
     tensor.def(#py_name, &Tensor::cpp_name<int32_t>);                       \
     tensor.def(#py_name, &Tensor::cpp_name<int64_t>);                       \
     tensor.def(#py_name, &Tensor::cpp_name<uint8_t>);                       \
@@ -65,6 +66,10 @@
         return Tensor::Full({}, value, self.GetDtype(), self.GetDevice()) \
                 .cpp_name(self);                                          \
     });                                                                   \
+    tensor.def(#py_name, [](const Tensor& self, int16_t value) {          \
+        return Tensor::Full({}, value, self.GetDtype(), self.GetDevice()) \
+                .cpp_name(self);                                          \
+    });                                                                   \
     tensor.def(#py_name, [](const Tensor& self, int32_t value) {          \
         return Tensor::Full({}, value, self.GetDtype(), self.GetDevice()) \
                 .cpp_name(self);                                          \
@@ -264,6 +269,7 @@ void pybind_core_tensor(py::module& m) {
     BindTensorCreation(tensor, "ones", Tensor::Ones);
     BindTensorFullCreation<float>(tensor);
     BindTensorFullCreation<double>(tensor);
+    BindTensorFullCreation<int16_t>(tensor);
     BindTensorFullCreation<int32_t>(tensor);
     BindTensorFullCreation<int64_t>(tensor);
     BindTensorFullCreation<uint8_t>(tensor);
@@ -584,6 +590,8 @@ void pybind_core_tensor(py::module& m) {
             return py::float_(tensor.Item<float>());
         } else if (dtype == Dtype::Float64) {
             return py::float_(tensor.Item<double>());
+        } else if (dtype == Dtype::Int16) {
+            return py::int_(tensor.Item<int16_t>());
         } else if (dtype == Dtype::Int32) {
             return py::int_(tensor.Item<int32_t>());
         } else if (dtype == Dtype::Int64) {
                                  \
```

In fact, I'll create a separate `int16` PR, such that we have a clean example for what needs to be changed. In case we need to add a new dtype in the future.
___
*[cpp/open3d/core/Tensor.h, line 343 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLMAQw2QPrI9UexNNS:-MTLMAQw2QPrI9UexNNT:b-6gfpz3) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/core/Tensor.h#L343)):*
> ```objc
>                          const Device& device = core::Device("CPU:0"));
> 
>     /// Reverse a Tensor
> ```

In the comment, could you specify the behavior when the Tensor is n-dimensional? e.g. will it reverse everything or some dimension?
___
*[cpp/open3d/core/Tensor.cpp, line 244 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLM4V35cQwUXyWag_F:-MTLM4V48XtbVn3EbIWy:bje7xn4) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/core/Tensor.cpp#L244)):*
> ```cpp
> 
> Tensor Tensor::Reverse() const {
>     // Unoptimized with ai. Can be improved when negative step in Slice is
> ```

Could you add `TODO: ` to the comment, this way it will be easier to search for it. 
___
*[cpp/open3d/t/geometry/Image.h, line 192 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLNvIy1oeLASfYk6J5:-MTLNvIy1oeLASfYk6J6:b724gow) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L192)):*
> ```objc
> 
>     /// Converts a 3-channel RGB image to a new 1-channel Grayscale image.
>     Image RGBToGray() const;
> ```

previously we have this:

```
enum class ColorToIntensityConversionType {
        /// R, G, B channels have equal weights.
        Equal,
        /// Weighted R, G, B channels: I = 0.299 * R + 0.587 * G + 0.114 * B.
        Weighted,
    };
```

Do we need to:
- implement both?
- or, mention in the docstring of the current behavior and add a `// TODO`?
___
*[cpp/open3d/t/geometry/Image.h, line 197 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLMTXd85VesHiYs2bS:-MTLMTXeE86AzVQcZz_W:b-t4mhci) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L197)):*
> ```objc
>     /// Downsample if sampling rate is < 1. Upsample if sampling rate > 1.
>     /// Aspect ratio is always kept.
>     enum InterpType {
> ```

Why not `enum class`?
___
*[cpp/open3d/t/geometry/Image.h, line 204 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLNBhL2t_3JomVc_JJ:-MTLNBhL2t_3JomVc_JK:bhiveeo) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L204)):*
> ```objc
>         Super = 4
>     };
>     Image Resize(float sampling_rate = 0.5f, int interp_type = Nearest) const;
> ```

`Image Resize(float, InterpType) const;` might be more type-safe
___
*[cpp/open3d/t/geometry/Image.h, line 209 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLN7NxBWd0I-WD-2IU:-MTL [...]

2021-02-13 04:00 UTC, theNded reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2972)* status: 8 of 20 files reviewed, 18 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[3rdparty/ippicv/CMakeLists.txt, line 14 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLLB4nE_kYUeuukoDg:-MTOVmLc3Lf7CGgjjI2I:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/3rdparty/ippicv/CMakeLists.txt#L14)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Theoretically, it's better to use `target_*` to prevent properties from leaking.

`target_compile_definitions(ippiw PRIVATE IW_ENABLE_iwiResize_Nearest=1)`, or, is `PRIVATE` suffucient?

`include_directories` shall be `target_include_directories(ippiw PRIVATE ...)`


</blockquote></details>

Done.
___
*[cpp/open3d/core/Dispatch.h, line 58 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLRSEt-eDGnoHQ2Uy3:-MTOWCIu62_VxhBKtabf:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/core/Dispatch.h#L58)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We shall add some tests for int16 computation. I think we're missing some more `int16` changes. These are a subset of them:

```diff
diff --git a/cpp/open3d/core/Tensor.cpp b/cpp/open3d/core/Tensor.cpp
index dd9771561..f388e429e 100644
--- a/cpp/open3d/core/Tensor.cpp
+++ b/cpp/open3d/core/Tensor.cpp
@@ -83,6 +83,8 @@ private:
             dl_data_type.code = DLDataTypeCode::kDLFloat;
         } else if (dtype == Dtype::Float64) {
             dl_data_type.code = DLDataTypeCode::kDLFloat;
+        } else if (dtype == Dtype::Int16) {
+            dl_data_type.code = DLDataTypeCode::kDLInt;
         } else if (dtype == Dtype::Int32) {
             dl_data_type.code = DLDataTypeCode::kDLInt;
         } else if (dtype == Dtype::Int64) {
@@ -1152,6 +1154,9 @@ Tensor Tensor::FromDLPack(const DLManagedTensor* src) {
             break;
         case DLDataTypeCode::kDLInt:
             switch (src->dl_tensor.dtype.bits) {
+                case 16:
+                    dtype = Dtype::Int32;
+                    break;
                 case 32:
                     dtype = Dtype::Int32;
                     break;
diff --git a/cpp/pybind/core/tensor.cpp b/cpp/pybind/core/tensor.cpp
index 7a0dae766..a2b3aa51e 100644
--- a/cpp/pybind/core/tensor.cpp
+++ b/cpp/pybind/core/tensor.cpp
@@ -51,6 +51,7 @@
     });                                                                     \
     tensor.def(#py_name, &Tensor::cpp_name<float>);                         \
     tensor.def(#py_name, &Tensor::cpp_name<double>);                        \
+    tensor.def(#py_name, &Tensor::cpp_name<int16_t>);                       \
     tensor.def(#py_name, &Tensor::cpp_name<int32_t>);                       \
     tensor.def(#py_name, &Tensor::cpp_name<int64_t>);                       \
     tensor.def(#py_name, &Tensor::cpp_name<uint8_t>);                       \
@@ -65,6 +66,10 @@
         return Tensor::Full({}, value, self.GetDtype(), self.GetDevice()) \
                 .cpp_name(self);                                          \
     });                                                                   \
+    tensor.def(#py_name, [](const Tensor& self, int16_t value) {          \
+        return Tensor::Full({}, value, self.GetDtype(), self.GetDevice()) \
+                .cpp_name(self);                                          \
+    });                                                                   \
     tensor.def(#py_name, [](const Tensor& self, int32_t value) {          \
         return Tensor::Full({}, value, self.GetDtype(), self.GetDevice()) \
                 .cpp_name(self);                                          \
@@ -264,6 +269,7 @@ void pybind_core_tensor(py::module& m) {
     BindTensorCreation(tensor, "ones", Tensor::Ones);
     BindTensorFullCreation<float>(tensor);
     BindTensorFullCreation<double>(tensor);
+    BindTensorFullCreation<int16_t>(tensor);
     BindTensorFullCreation<int32_t>(tensor);
     BindTensorFullCreation<int64_t>(tensor);
     BindTensorFullCreation<uint8_t>(tensor);
@@ -584,6 +590,8 @@ void pybind_core_tensor(py::module& m) {
             return py::float_(tensor.Item<float>());
         } else if (dtype == Dtype::Float64) {
             return py::float_(tensor.Item<double>());
+        } else if (dtype == Dtype::Int16) {
+            return py::int_(tensor.Item<int16_t>());
         } else if (dtype == Dtype::Int32) {
             return py::int_(tensor.Item<int32_t>());
         } else if (dtype == Dtype::Int64) {
                                  \
```

In fact, I'll create a separate `int16` PR, such that we have a clean example for what needs to be changed. In case we need to add a new dtype in the future.
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.h, line 343 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLMAQw2QPrI9UexNNS:-MTOWD413Y3UuDybFEJ_:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/core/Tensor.h#L343)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

In the comment, could you specify the behavior when the Tensor is n-dimensional? e.g. will it reverse everything or some dimension?
</blockquote></details>

Done.
___
*[cpp/open3d/core/Tensor.cpp, line 244 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLM4V35cQwUXyWag_F:-MTOWDTe5YtfTis2fghQ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/core/Tensor.cpp#L244)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Could you add `TODO: ` to the comment, this way it will be easier to search for it. 
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.h, line 192 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLNvIy1oeLASfYk6J5:-MTOWJ6_9HWF7JAv_lC0:b-qtd1na) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L192)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

previously we have this:

```
enum class ColorToIntensityConversionType {
        /// R, G, B channels have equal weights.
        Equal,
        /// Weighted R, G, B channels: I = 0.299 * R + 0.587 * G + 0.114 * B.
        Weighted,
    };
```

Do we need to:
- implement both?
- or, mention in the docstring of the current behavior and add a `// TODO`?
</blockquote></details>

Equal weights are unconventional and generally do not make a difference in RGBD odometry. I think it is time to drop it.
___
*[cpp/open3d/t/geometry/Image.h, line 197 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLMTXd85VesHiYs2bS:-MTOWW2V0zqq-D0gjjsP:b-zi9c0a) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L197)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Why not `enum class`?
</blockquote></details>

If we use enum class, then this type has to be referred to in kernel's header, so there will be a loop: Image -> kernel/Image -> Image. Same reason for using int below. If there is a better solution we can adopt it.
___
*[cpp/open3d/t/geometry/Image.h, line 204 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLNBhL2t_3JomVc_JJ:-MTOX7rjDyruPWI9Njje:b-ya81ng) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L204)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`Image Resize(float, InterpType) const;` might be more type-safe
</blockquote></details>

Same as above
___
*[cpp/open3d/t/geometry/Image.h, line 209 at r8] [...]

2021-02-13 19:36 UTC, ssheorey requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2972)* status: 7 of 21 files reviewed, 35 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/Dtype.cpp, line 37 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTICMmo3SDcOoglRQx_:-MTICMmo3SDcOoglRQxa:bhdcxjq) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/core/Dtype.cpp#L37)):*
> ```cpp
> static_assert(sizeof(double  ) == 8, "Unsupported platform: double must be 8 bytes."  );
> static_assert(sizeof(int     ) == 4, "Unsupported platform: int must be 4 bytes."     );
> static_assert(sizeof(int16_t ) == 2, "Unsupported platform: int16_t must be 2 bytes.");
> ```

These `static_assert`s should be unnecessary for `[u]int[8|16|32|64]_t` datatypes, since this is their definition:
https://en.cppreference.com/w/cpp/types/integer
___
*[cpp/open3d/t/geometry/Image.h, line 226 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTIF6B72TUJN5GLkX9j:-MTIF6B72TUJN5GLkX9k:begzxq6) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L226)):*
> ```objc
>                           float value_sigma = 20.0f,
>                           float dist_sigma = 10.0f) const;
> ```

dist_sigma -> distance_sigma is clearer (also update documentation)
___
*[cpp/open3d/t/geometry/Image.h, line 229 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTIFUnQBSNGqczIlWiW:-MTIFUnQBSNGqczIlWiX:bcndekn) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L229)):*
> ```objc
>     /// Return a new image after Gaussian filtering.
>     /// A fixed sigma is computed by sigma = 0.4F + (mask width / 2) * 0.6F.
>     /// Possible kernel_size: odd numbers >= 3 are supported.
> ```

Is F = kernel_size?
\param kernel_size Odd numbers >= 3 are supported
___
*[cpp/open3d/t/geometry/Image.h, line 237 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTIGlIm08tuiLfHwk7f:-MTIGlIm08tuiLfHwk7g:bisvv9s) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L237)):*
> ```objc
> 
>     /// Return a new downsampled image with pyramid downsampling formed by a
>     /// chained 5x5 Gaussian filter and a downsampling operation.
> ```

Document Gaussian filter sigma and downsampling factor used.
___
*[cpp/pybind/t/geometry/image.cpp, line 71 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRn9hPBxvZ7yvvCXpH:-MTRn9hPBxvZ7yvvCXpI:b6ek04a) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/pybind/t/geometry/image.cpp#L71)):*
> ```cpp
>                 {"kernel_size", "Kernel size for filters and dilations."},
>                 {"value_sigma", "Standard deviation for the image content."},
>                 {"dist_sigma",
> ```

`distance_sigma` is clearer
___
*[cpp/pybind/t/geometry/image.cpp, line 140 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRnTqW36ch0S9OChqE:-MTRnTqW36ch0S9OChqF:b-8vvvn6) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/pybind/t/geometry/image.cpp#L140)):*
> ```cpp
>                  "kernel_size"_a = 3)
>             .def("filter", &Image::Filter,
>                  "Return a new image given the filtering kernel.", "kernel"_a)
> ```

Return a new image after filtering with the given kernel.
___
*[cpp/pybind/t/geometry/image.cpp, line 163 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRnq8T9Pd4DtAdPQ02:-MTRnq8T9Pd4DtAdPQ03:btg52m2) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/pybind/t/geometry/image.cpp#L163)):*
> ```cpp
>                  "{1, 3, 4} channels. An 8-connected neighborhood is used to "
>                  "create the dilation mask.",
>                  "sampling_rate"_a = 0.5, "interp_type"_a = Image::Nearest)
> ```

Update documentation for `resize()`
___
*[cpp/pybind/t/geometry/image.cpp, line 167 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRnyCH0ObHcqesTpm6:-MTRnyCH0ObHcqesTpm7:bqftwgx) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/pybind/t/geometry/image.cpp#L167)):*
> ```cpp
>                  "Return a new downsampled image with pyramid downsampling "
>                  "formed by a"
>                  "chained 5x5 Gaussian filter and a downsampling operation.")
> ```

Specify downsampling factor. Check that C++ and Python documentation are equivalent.
___
*[cpp/pybind/t/geometry/image.cpp, line 170 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRo1gc4DV6i9_BasFk:-MTRo1gc4DV6i9_BasFl:b-uk4yyh) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/pybind/t/geometry/image.cpp#L170)):*
> ```cpp
>             .def("rgb_to_gray", &Image::RGBToGray,
>                  "Converts a 3-channel RGB image to a new 1-channel Grayscale "
>                  "image.")
> ```

Specify algorithm used (e.g. weights for RGB channels or the equation). Check that C++ and Python documentation are equivalent.
___
*[cpp/tests/t/geometry/Image.cpp, line 195 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRqbhe-Q8s_GLBmaiO:-MTRqbhe-Q8s_GLBmaiP:badfpqz) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L195)):*
> ```cpp
> }
> 
> TEST_P(ImagePermuteDevices, FilterBilateral) {
> ```

Can we add tests for `uint8_t`?  That's a common use case.  It may work to create the input and output ref data with `Image::To()`, so that 1.0f -> 255. Ideally, the output should also be just scaled up + quantized, but we need to check that.
___
*[cpp/tests/t/geometry/Image.cpp, line 240 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRrIHN14S8NRrXExoE:-MTRrIHN14S8NRrXExoF:b850duw) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L240)):*
> ```cpp
> // Note: in 5 x 5 NPP adds a weird offset.
> TEST_P(ImagePermuteDevices, FilterGaussian) {
>     core::Device device = GetParam();
> ```

Add `uint8_t` tests as  for `FilterBilateral()`
___
*[cpp/tests/t/geometry/Image.cpp, line 271 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRrTdS9qZ6Mgaxi5CV:-MTRrTdS9qZ6Mgaxi5CW:b850duw) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L271)):*
> ```cpp
> 
> TEST_P(ImagePermuteDevices, Filter) {
>     core::Device device = GetParam();
> ```

Add `uint8_t` tests as  for `FilterBilateral()`
___
*[cpp/tests/t/geometry/Image.cpp, line 400 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRrgHVDi_8lJbqmpyZ:-MTRrgHVDi_8lJbqmpy_:bowhhh0) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L400)):*
> ```cpp
>         EXPECT_TRUE(im.AsTensor().AllClose(core::Tensor(
>                 output_ref, {3, 3, 1}, core::Dtype::Float32, device)));
>     }
> ```

Can we add one test for the combination: Bilinear interpolation and `uint8_t`?
___
*[cpp/tests/t/geometry/Image.cpp, line 404 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRs0i94ZrnzpbvmNYJ:-MTRs0i94ZrnzpbvmNYK:b850duw) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L404)):*
> ```cpp
> 
> TEST_P(ImagePermuteDevices, PyrDown) {
>     core::Device device = GetParam();
> ```

Add `uint8_t` tests as  for `FilterBilateral()`
___
*[cpp/open3d/t/geometry/kernel/IPPImage.cpp, line 274 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTILCYN8t8gX0oWftF2:-MTILCYN8t8gX0oWftF3:b87jtcl) ([raw file](https://github.com/intel-isl/open3d/blob [...]

2021-02-16 05:34 UTC, theNded reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2972)* status: 7 of 21 files reviewed, 35 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[3rdparty/ippicv/CMakeLists.txt, line 14 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLLB4nE_kYUeuukoDg:-MTdHBxgEJgQgQKA9erN:bh4bv66) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/3rdparty/ippicv/CMakeLists.txt#L14)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

target_compile_definitions seems not working, roll back
___
*[cpp/open3d/core/Dtype.cpp, line 37 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTICMmo3SDcOoglRQx_:-MTdHHwSDjj-G4kas9nJ:b-igqwx9) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/core/Dtype.cpp#L37)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

These `static_assert`s should be unnecessary for `[u]int[8|16|32|64]_t` datatypes, since this is their definition:
https://en.cppreference.com/w/cpp/types/integer
</blockquote></details>

It would still be a reminder for what types are supported I guess.
___
*[cpp/open3d/t/geometry/Image.h, line 226 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTIF6B72TUJN5GLkX9j:-MTdHPia6VkZCTZura0K:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L226)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

dist_sigma -> distance_sigma is clearer (also update documentation)
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.h, line 229 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTIFUnQBSNGqczIlWiW:-MTdHQRm1JfOzBJAofvD:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L229)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Is F = kernel_size?
\param kernel_size Odd numbers >= 3 are supported
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/Image.h, line 237 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTIGlIm08tuiLfHwk7f:-MTdHR2vEVUKpMs_IBRI:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L237)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Document Gaussian filter sigma and downsampling factor used.
</blockquote></details>

Done.
___
*[cpp/pybind/t/geometry/image.cpp, line 71 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRn9hPBxvZ7yvvCXpH:-MTdH_YT6IsVnoYdwWg8:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/pybind/t/geometry/image.cpp#L71)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`distance_sigma` is clearer
</blockquote></details>

Done.
___
*[cpp/pybind/t/geometry/image.cpp, line 140 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRnTqW36ch0S9OChqE:-MTdHaAy4JEZBjXkN76f:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/pybind/t/geometry/image.cpp#L140)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Return a new image after filtering with the given kernel.
</blockquote></details>

Done.
___
*[cpp/pybind/t/geometry/image.cpp, line 163 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRnq8T9Pd4DtAdPQ02:-MTdHbBn4tA0zek7YYu2:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/pybind/t/geometry/image.cpp#L163)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Update documentation for `resize()`
</blockquote></details>

Done.
___
*[cpp/pybind/t/geometry/image.cpp, line 167 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRnyCH0ObHcqesTpm6:-MTdHbms25-U-ZeImf0u:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/pybind/t/geometry/image.cpp#L167)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Specify downsampling factor. Check that C++ and Python documentation are equivalent.
</blockquote></details>

Done.
___
*[cpp/pybind/t/geometry/image.cpp, line 170 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRo1gc4DV6i9_BasFk:-MTdHcTH43G1XqpkVfsr:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/pybind/t/geometry/image.cpp#L170)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Specify algorithm used (e.g. weights for RGB channels or the equation). Check that C++ and Python documentation are equivalent.
</blockquote></details>

Done.
___
*[cpp/tests/t/geometry/Image.cpp, line 195 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRqbhe-Q8s_GLBmaiO:-MTdJllx8KFz1w6S8Ten:b4qvk1j) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L195)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can we add tests for `uint8_t`?  That's a common use case.  It may work to create the input and output ref data with `Image::To()`, so that 1.0f -> 255. Ideally, the output should also be just scaled up + quantized, but we need to check that.
</blockquote></details>

We will need two versions for uint8 per function according to devices, since their outputs are not only unequal to Image::To(UInt8), but also unequal to each other. Will do if this exhaustive enumeration is necessary.
___
*[cpp/tests/t/geometry/Image.cpp, line 240 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRrIHN14S8NRrXExoE:-MTdKCag0fmKthmVGrzW:b-ya81ng) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L240)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add `uint8_t` tests as  for `FilterBilateral()`
</blockquote></details>

Same as above
___
*[cpp/tests/t/geometry/Image.cpp, line 271 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRrTdS9qZ6Mgaxi5CV:-MTdKDZL7zxMb6a5tLiK:b2nreg6) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L271)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add `uint8_t` tests as  for `FilterBilateral()`
</blockquote></details>

Same as above
___
*[cpp/tests/t/geometry/Image.cpp, line 400 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRrgHVDi_8lJbqmpyZ:-MTdJVo08F98-vujuOn4:b-ya81ng) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L400)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can we add one test for the combination: Bilinear interpolation and `uint8_t`?
</blockquote></details>

Same as above
___
*[cpp/tests/t/geometry/Image.cpp, line 404 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRs0i94ZrnzpbvmNYJ:-MTdKGoLEvQYGR-xS4yd:b-ya81ng) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L404)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add `uint8_t` tests as  for `FilterBilateral()`
</blockquote></details>

Same as above
___
*[cpp/open3d/t/geometry/kernel/IPPImage.cpp, line 274 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTILCYN8t8gX0oWftF2:-MTdHSgp2H72uNZodTaB:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/kernel/IPPImage.cpp#L274)):*
<details> [...]

2021-02-16 09:40 UTC, yxlao commented
@theNded could you add a unit test where

```cmake
add_compile_definitions(IW_ENABLE_iwiResize_Nearest=1)
```
works, but 

```cmake
target_compile_definitions(ippiw PRIVATE IW_ENABLE_iwiResize_Nearest=1)
``` 
does not work?

In my test, both of them can pass the unit tests.

2021-02-16 16:34 UTC, theNded commented
> @theNded could you add a unit test where
> 
> ```cmake
> add_compile_definitions(IW_ENABLE_iwiResize_Nearest=1)
> ```
> 
> works, but
> 
> ```cmake
> target_compile_definitions(ippiw PRIVATE IW_ENABLE_iwiResize_Nearest=1)
> ```
> 
> does not work?
> 
> In my test, both of them can pass the unit tests.

It's working now, I have re-reverted. Probably failed due to cache issues.

2021-02-16 16:52 UTC, yxlao commented
Thanks @theNded . Could you review/merge https://github.com/intel-isl/Open3D/pull/3035 before merging this one?

2021-02-16 17:23 UTC, ssheorey reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2972)* status: 7 of 21 files reviewed, 35 unresolved discussions (waiting on @ssheorey, @theNded, and @yxlao)

___
*[cpp/tests/t/geometry/Image.cpp, line 195 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRqbhe-Q8s_GLBmaiO:-MTfmxGwELfEkMo_Ohux:bp7q0q8) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L195)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

We will need two versions for uint8 per function according to devices, since their outputs are not only unequal to Image::To(UInt8), but also unequal to each other. Will do if this exhaustive enumeration is necessary.
</blockquote></details>

I think it's a good idea to have the `uint8_t` tests, since we've found inconsistent / sometimes inaccurate results with the float tests. This will prevent surprises when users try out these functions with int images. Also, this will guard against changes in IPP / NPP future versions, like NPP changing the Sobel kernel in CUDA 10.2.


<!-- Sent from Reviewable.io -->

2021-02-16 17:27 UTC, yxlao approved these changes
LGTM after addressing Sameer's comments and mering #3035

> Reviewed 2 of 14 files at r7, 6 of 8 files at r9, 1 of 1 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2972#-:-MTfsIk84qKnGD-pMKDv:be93vvp)* status: 12 of 21 files reviewed, 26 unresolved discussions (waiting on @ssheorey, @theNded, and @yxlao)

___
*[cpp/open3d/t/geometry/Image.h, line 197 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLMTXd85VesHiYs2bS:-MTQApVk04L07Yq0tb5K:bmr8i2f) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L197)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

If we use enum class, then this type has to be referred to in kernel's header, so there will be a loop: Image -> kernel/Image -> Image. Same reason for using int below. If there is a better solution we can adopt it.
</blockquote></details>

lf `Image.h` does not depend on `kernel/Image` then it shall be good. Currently `Image.h` does not depend on `kernel/Image`, but `Image.cpp` may depend on `kernel/Image`.

Am I missing another use case (which is not in this PR)?


<!-- Sent from Reviewable.io -->

2021-02-17 02:30 UTC, theNded reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2972)* status: 9 of 21 files reviewed, 26 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[cpp/open3d/t/geometry/Image.h, line 197 at r8](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTLMTXd85VesHiYs2bS:-MThoMp9ExlKDEFKXCX5:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a318bf4d0e1a32bc246de9f0babfde66f7e0867f/cpp/open3d/t/geometry/Image.h#L197)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

lf `Image.h` does not depend on `kernel/Image` then it shall be good. Currently `Image.h` does not depend on `kernel/Image`, but `Image.cpp` may depend on `kernel/Image`.

Am I missing another use case (which is not in this PR)?
</blockquote></details>

Done.
___
*[cpp/tests/t/geometry/Image.cpp, line 195 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRqbhe-Q8s_GLBmaiO:-MThoRbc2T81qGV5AtCs:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L195)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

I think it's a good idea to have the `uint8_t` tests, since we've found inconsistent / sometimes inaccurate results with the float tests. This will prevent surprises when users try out these functions with int images. Also, this will guard against changes in IPP / NPP future versions, like NPP changing the Sobel kernel in CUDA 10.2.
</blockquote></details>

Done.
___
*[cpp/tests/t/geometry/Image.cpp, line 240 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRrIHN14S8NRrXExoE:-MThoSerD4iJj3_xx4gF:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L240)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[cpp/tests/t/geometry/Image.cpp, line 271 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRrTdS9qZ6Mgaxi5CV:-MThoUuN87RId7Qz7rZf:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L271)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[cpp/tests/t/geometry/Image.cpp, line 400 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRrgHVDi_8lJbqmpyZ:-MThoW6I1QvQkLSWE3cA:b48wbcz) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L400)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done; however, it seems that NPP's all operations are falling back to Nearest except for Super (CUDA 10.2). Might need double check on other versions.
___
*[cpp/tests/t/geometry/Image.cpp, line 404 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRs0i94ZrnzpbvmNYJ:-MTholRp5pn3Topm6MRT:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L404)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-19 17:49 UTC, ssheorey approved these changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2972)* status: 9 of 21 files reviewed, 24 unresolved discussions (waiting on @ssheorey, @theNded, and @yxlao)

___
*[cpp/tests/t/geometry/Image.cpp, line 400 at r12](https://reviewable.io/reviews/intel-isl/open3d/2972#-MTRrgHVDi_8lJbqmpyZ:-MTvOySFE_zqMSf0wL_t:b1n1j75) ([raw file](https://github.com/intel-isl/open3d/blob/89aa7c04bc084f753b6320752c46fb71359cd774/cpp/tests/t/geometry/Image.cpp#L400)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Done; however, it seems that NPP's all operations are falling back to Nearest except for Super (CUDA 10.2). Might need double check on other versions.
</blockquote></details>

Thanks. Let's disable incorrect NPP implementations for now. We can re-check after upgrading to CUDA 11.0.


<!-- Sent from Reviewable.io -->

2021-02-21 01:45 UTC, merged