Fix compilation on Windows when building with CUDA.
intel-isl/Open3D pull request #3036
Opened 2021-02-13 22:41 UTC by Dudulle

There were a few different issues during build. Mainly the following:

- A few compiler options were added to nvcc instead of the c++ compiler.
- A few warnings treated as errors. Some were fixed and others were silenced.
- Member variables were not initialized in the right order in some parts of CUDA. The reorder check was removed although there might be a better fix for this?
- nvcc does not support the [[deprecated]] attribute which is used in fmt.

This was tested with CUDA 10.1.

2021-02-19 22:05 UTC, ssheorey commented on 3rdparty/find_dependencies.cmake
> +        target_compile_options(3rdparty_mkl INTERFACE "$<$<COMPILE_LANGUAGE:CXX>:/DMKL_ILP64>")
`target_compile_definitions(3rdparty_mkl INTERFACE "$<$<COMPILE_LANGUAGE:CXX>:MKL_ILP64>")`
can be common to both `UNIX` and `MSVC`

2021-02-19 22:11 UTC, ssheorey commented
Thanks for this PR. This has been a long standing user request. We don't have a CI setup to test Windows builds with CUDA currently. Were you able to run all C++ and Python unit tests with this CUDA build? Please let us know if any tests are failing with CUDA.

2021-02-19 23:26 UTC, Dudulle commented
@ssheorey I only ran the c++ tests for now and will try the python tests in the next few days.

In the c++ tests, 5 related to cuda failed with an out of memory error. I did not look into it much yet but it seems like ~2GB of memory (my card has 4GB) is being allocated and not deallocated in a passing test.

2021-02-20 04:05 UTC, ssheorey commented
@Dudulle Can you paste the results of the unit tests here? We can take a hand at fixing things if something looks broken.

2021-02-20 20:06 UTC, Dudulle commented
@ssheorey Here are the results of the c++ unit tests:
> [----------] Global test environment tear-down
[==========] 1131 tests from 74 test suites ran. (86062 ms total)
[  PASSED  ] 1120 tests.
[  SKIPPED ] 1 test, listed below:
[  SKIPPED ] RGBDImage.CreateFromNYUFormat
[  FAILED  ] 10 tests, listed below:
[  FAILED  ] FileSystem.File_Exists_Remove
[  FAILED  ] FileSystem.ListFilesInDirectory
[  FAILED  ] FileSystem.ListFilesInDirectoryWithExtension
[  FAILED  ] FileSystem.GetPathComponents
[  FAILED  ] Tensor/TensorPermuteDevices.ReduceSum64bit1D/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
[  FAILED  ] Tensor/TensorPermuteDevices.ReduceSum64bit2DCase0/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
[  FAILED  ] Tensor/TensorPermuteDevices.ReduceSum64bit2DCase1/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
[  FAILED  ] Tensor/TensorPermuteDevices.ReduceSum64bit2DCase2/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
[  FAILED  ] Tensor/TensorPermuteDevices.ReduceSum64bit2DCase3/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>
[  FAILED  ] Tensor/TensorPermuteDevices.ReduceSumLargeArray/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>

I've looked a bit deeper and no memory seems to be released in the Tensor tests.
The big chunk of memory is allocated here but it seems it is not the only place where there is a leak:
https://github.com/intel-isl/Open3D/blob/31e5d4d16eabbe05d5bb2765deaa7c13c4dcd18a/cpp/tests/core/Tensor.cpp#L1562
I'm also reaching this line: https://github.com/intel-isl/Open3D/blob/31e5d4d16eabbe05d5bb2765deaa7c13c4dcd18a/cpp/open3d/core/MemoryManagerCUDACached.cu#L121

The python package also does not work so I could not run the python tests.
I don't use python much so I'll leave that part for someone with more experience.
First there is the following error:
> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "L:\Source\Open3D\.venv38\lib\site-packages\open3d\__init__.py", line 62, in <module>
    _pybind_cuda = _CDLL(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 363, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable

If I use hardcoded paths it then says it cannot find the module or a dependency.

2021-02-24 06:32 UTC, yxlao requested changes
Looks good to me in general. Regarding the silenced MSVC warnings, we can create a separate PR to actually fix the warnings and re-enable the flags.

Could you make some additional changes:
1. merge master (include changes from #3070)
2. add the following to `.github/workflows/windows.yml` to run unit test on Windows CI. This only runs the CPU unit tests, but it is already a substantial improvement. 
    ```diff
    diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
    index 626989dbf..f03f4b38a 100644
    --- a/.github/workflows/windows.yml
    +++ b/.github/workflows/windows.yml
    @@ -75,6 +75,10 @@ jobs:
                 --target build-examples-iteratively
               cmake --build . --parallel ${{ env.NPROC }} --config ${{ matrix.CONFIG }} `
                 --target INSTALL
    +      - name: Run C++ unit tests
    +        working-directory: ${{ env.BUILD_DIR }}
    +        run: |
    +          .\bin\${{ matrix.CONFIG }}\tests.exe
           - name: Linking to Open3D
             run: |
               $ErrorActionPreference = 'Stop'
    ```
3. For the failed tests, exclude them with  `gtest_filter`. E.g. `--gtest_filter="-*Reduce*Sum*"` will filter out the big `Sum` unit tests that can cause the out-of-memory error. See https://stackoverflow.com/a/14021997/1255535 for details.

2021-02-24 12:27 UTC, Dudulle commented
@yxlao Thanks for the feedback.

I've added the change to enable the unit tests on CI.
I've also pushed a few changes I made yesterday to remove warning C4456 and a couple assertions I ran into.

For the remaining warnings silenced here, besides the type conversion warnings all of them come from either CUDA or Eigen.
I've noticed the warnings in Eigen are all fixed upstream since end of January but one is added [here](https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/CwiseBinaryOp.h#L106), something about using `__host__` and `__device__` before a default constructor. I did not update it in this PR as the current version is quite old so I'm unsure it is safe to do so.

2021-02-24 18:38 UTC, Dudulle commented
It seems a few CI are out of memory during the tests.
On my side I now have one test failing (with CUDA, works on CPU) from the new tests in ba9200b3915bacf22cab002024205adfe92d7492
`[  FAILED  ] Image/ImagePermuteDevices.FilterSobel/1, where GetParam() = 8-byte object <01-00 00-00 00-00 00-00>`
One of the CI seems to fail another of these tests and another one in UniformTSDFVolume.RealData.
And some fail to build with unresolved symbol in ippiw.lib.

2021-02-25 09:42 UTC, yxlao commented
@Dudulle Right, it is fine that some tests are not passing just now. You may add `--gtest_filter` to filter out those tests in `windows.yml` for now. The tests can be fixed in later PRs.

2021-02-25 15:05 UTC, Dudulle commented
@yxlao Thanks,
Besides the failing tests, the builds with BUILD_SHARED_LIBS=ON will all fail because of an assert ([know issue apparently](https://github.com/zeromq/czmq/issues/1788)):
`Assertion failed: Successful WSASTARTUP not yet performed [10093] (C:\Open3D\build\zeromq\src\ext_zeromq\src\signaler.cpp:190)`
And the remaining ones with STATIC_WINDOWS_RUNTIME=ON fail to build the tests.

Should I change it to only build the tests for when they are both off and disable the tests going out of memory?

2021-02-25 23:53 UTC, yxlao commented
> Should I change it to only build the tests for when they are both off and disable the tests going out of memory?

Yes.

To disable a GitHub actions step, we can do something similar to this:
https://github.com/intel-isl/Open3D/blob/f65a6f10c4683cc6885fe6e7c0762365aff7efbc/.github/workflows/windows.yml#L102

And it seems that we can `&&` the two conditions together (see [here](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#operators)).

2021-02-27 23:42 UTC, yxlao approved these changes

2021-03-04 01:32 UTC, ssheorey commented
I'm looking into this error:
> Traceback (most recent call last):
> File "", line 1, in
> File "L:\Source\Open3D.venv38\lib\site-packages\open3d_init_.py", line 62, in
> _pybind_cuda = CDLL(
> File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\ctypes_init.py", line 363, in init
> if '/' in name or '\' in name:
> TypeError: argument of type 'WindowsPath' is not iterable

2021-03-04 10:56 UTC, Dudulle commented
Rebased on master to resolve conflicts in `Tensor.h`

2021-03-04 10:58 UTC, Dudulle reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3036)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @ssheorey)

___
*[3rdparty/find_dependencies.cmake, line 1076 at r1](https://reviewable.io/reviews/intel-isl/open3d/3036#-MTSYa5KHJy_SNdf44p3-r1-1076:-MUwsvTq1GgfKvE-JmqV:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/5ffff22cab8a15af7328e7cf72ac846d0d8c25b1/3rdparty/find_dependencies.cmake#L1076)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`target_compile_definitions(3rdparty_mkl INTERFACE "$<$<COMPILE_LANGUAGE:CXX>:MKL_ILP64>")`
can be common to both `UNIX` and `MSVC`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-05 12:12 UTC, yxlao commented
There are various topics here. Let's summarize them. 

Here's my current understanding: 

1. Windows CUDA compilation and running basic things with C++: supported in this PR
2. Windows C++ unit test CPU: supported for `SHARED: OFF, STATIC_RUNTIME: OFF`, with some tests filtered
3. Windows C++ unit test CUDA: what is the status?
4. Windows CUDA compilation and running basic things with Python wheel: what is the status?
5. Windows Python unit test CPU: what is the status?
6. Windows Python unit test CUDA: what is the status?

@Dudulle could you correct me on the table above? It is just for documenting what is expected to work, we don't need to address all of them in this PR,

@ssheorey does the error `TypeError: argument of type 'WindowsPath' is not iterable` belong to item 4. above?

2021-03-05 23:18 UTC, Dudulle commented
@yxlao

> Windows CUDA compilation and running basic things with C++: supported in this PR
Windows C++ unit test CPU: supported for SHARED: OFF, STATIC_RUNTIME: OFF, with some tests filtered

Correct. Filtered tests fail because of lack of memory.
Tests would pass with `SHARED_LIBS: ON` and `STATIC_RUNTIME: OFF` but fail because of an assert in `zeromq` on exit.
Linking error with `SHARED_LIBS: OFF` and `STATIC_RUNTIME: ON` (unresolved symbols in `ippiw.lib`)

>Windows C++ unit test CUDA: what is the status?

All tests pass except `Image/ImagePermuteDevices.FilterSobel`.
Tests disabled in CI also fail for me on CUDA because of lack of memory.
Tested with `SHARED_LIBS: OFF` and `STATIC_RUNTIME: OFF`.

>Windows CUDA compilation and running basic things with Python wheel: what is the status?
Windows Python unit test CUDA: what is the status?

Python module compiles and can be installed but fails when trying to import.

>Windows Python unit test CPU: what is the status?

Python CPU tests pass.

2021-03-06 00:35 UTC, ssheorey commented
> There are various topics here. Let's summarize them.
> 
> Here's my current understanding:
>     1. Windows CUDA compilation and running basic things with C++: supported in this PR
>     2. Windows C++ unit test CPU: supported for `SHARED: OFF, STATIC_RUNTIME: OFF`, with some tests filtered

It should be OK to turn off the filtering. All tests pass with `SHARED: OFF, STATIC_RUNTIME: OFF` on an 8 vCPU / 30GB / Tesla T4 VM:

```
> PS C:\Users\sameer_sheorey\Open3D\Open3D\build> .\bin\RelWithDebInfo\tests.exe
> [==========] Running 886 tests from 72 test suites.
> [----------] Global test environment set-up.
> [----------] 1 test from PinholeCameraTrajectory
> [ RUN      ] PinholeCameraTrajectory.ConvertToFromJsonValue
> [       OK ] PinholeCameraTrajectory.ConvertToFromJsonValue (1 ms)
> [----------] 1 test from PinholeCameraTrajectory (1 ms total)
> ...
> ...
> [----------] 1 test from Image/ImagePermuteDevicePairs
> [ RUN      ] Image/ImagePermuteDevicePairs.CopyDevice/0
> [       OK ] Image/ImagePermuteDevicePairs.CopyDevice/0 (0 ms)
> [----------] 1 test from Image/ImagePermuteDevicePairs (0 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 886 tests from 72 test suites ran. (88143 ms total)
> [  PASSED  ] 885 tests.
> [  SKIPPED ] 1 test, listed below:
> [  SKIPPED ] RGBDImage.CreateFromNYUFormat
> 
>   YOU HAVE 210 DISABLED TESTS
> 
```

>     3. Windows C++ unit test CUDA: what is the status?

All tests pass:
```
> PS C:\Users\sameer_sheorey\Open3D\Open3D\build> .\bin\RelWithDebInfo\tests.exe
> [==========] Running 1143 tests from 74 test suites.
> [----------] Global test environment set-up.
> [----------] 1 test from PinholeCameraTrajectory
> [ RUN      ] PinholeCameraTrajectory.ConvertToFromJsonValue
> [       OK ] PinholeCameraTrajectory.ConvertToFromJsonValue (1 ms)
> [----------] 1 test from PinholeCameraTrajectory (2 ms total)
> ...
> 
> [----------] 4 tests from Registration/RegistrationPermuteDevices
> [ RUN      ] Registration/RegistrationPermuteDevices.ICPConvergenceCriteriaConstructor/0
> [       OK ] Registration/RegistrationPermuteDevices.ICPConvergenceCriteriaConstructor/0 (0 ms)
> [ RUN      ] Registration/RegistrationPermuteDevices.ICPConvergenceCriteriaConstructor/1
> [       OK ] Registration/RegistrationPermuteDevices.ICPConvergenceCriteriaConstructor/1 (1 ms)
> [ RUN      ] Registration/RegistrationPermuteDevices.RegistrationResultConstructor/0
> [       OK ] Registration/RegistrationPermuteDevices.RegistrationResultConstructor/0 (0 ms)
> [ RUN      ] Registration/RegistrationPermuteDevices.RegistrationResultConstructor/1
> [       OK ] Registration/RegistrationPermuteDevices.RegistrationResultConstructor/1 (0 ms)
> [----------] 4 tests from Registration/RegistrationPermuteDevices (2 ms total)
> 
> ...
> [----------] Global test environment tear-down
> [==========] 1143 tests from 74 test suites ran. (129320 ms total)
> [  PASSED  ] 1142 tests.
> [  SKIPPED ] 1 test, listed below:
> [  SKIPPED ] RGBDImage.CreateFromNYUFormat


  YOU HAVE 210 DISABLED TESTS
```
>     4. Windows CUDA compilation and running basic things with Python wheel: what is the status?
>     5. Windows Python unit test CPU: what is the status?

The attached patch fixes the Python issues. All Python tests pass. I added WITH_FAISS to `open3d._build_config` to skip 2 Python tests if we don't build with FAISS.
[0001-Windows-CUDA-Python-support.patch.zip](https://github.com/intel-isl/Open3D/files/6094301/0001-Windows-CUDA-Python-support.patch.zip)

```
> PS C:\Users\sameer_sheorey\Open3D\Open3D\python\test> python -m pytest --ignore ml --ignore ml_ops
> ================================================= test session starts =================================================
> platform win32 -- Python 3.6.8, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
> rootdir: C:\Users\sameer_sheorey\Open3D\Open3D\python
> collected 331 items
> 
> test_color_map.py .                                                                                              [  0%]
> test_flags.py .                                                                                                  [  0%]
> test_octree.py .........                                                                                         [  3%]
> test_open3d_eigen.py .......................................                                                     [ 15%]
> test_remote_functions.py s                                                                                       [ 15%]
> core\test_core.py .............................................................................................. [ 43%]
> ................................................................................................................ [ 77%]
> .................................                                                                                [ 87%]
> core\test_hashmap.py ......                                                                                      [ 89%]
> core\test_linalg.py ................                                                                             [ 94%]
> core\test_nn.py ss......                                                                                         [ 96%]
> core\test_torch_integration.py ...                                                                               [ 97%]
> t\geometry\test_pointcloud.py ....                                                                               [ 98%]
> t\geometry\test_tensormap.py .                                                                                   [ 99%]
> t\geometry\test_voxelgrid.py .                                                                                   [ 99%]
> t\io\test_realsense.py ss                                                                                        [100%]
> 
> =========================================== 326 passed, 5 skipped in 39.54s ===========================================
```

>     6. Windows Python unit test CUDA: what is the status?

```

> PS C:\Users\sameer_sheorey\Open3D\Open3D\python\test> python -m pytest --ignore ml --ignore ml_ops
> ======================================================== test session starts =========================================================
> platform win32 -- Python 3.6.8, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
> rootdir: C:\Users\sameer_sheorey\Open3D\Open3D\python
> collected 599 items
> 
> test_color_map.py .                                                                                                             [  0%]
> test_flags.py .                                                                                                                 [  0%]
> test_octree.py .........                                                                                                        [  1%]
> test_open3d_eigen.py .......................................                                                                    [  8%]
> test_remote_functions.py s                                                                                                      [  8%]
> core\test_core.py ............................................................................................................. [ 26%]
> ............................................................................................................................... [ 47%]
> ............................................................................................................................... [ 69%]
> ..............................................................................................................                  [ 87%]
> core\test_hashmap.py ............                                                                                               [ 89%]
> core\test_linalg.py ................................                                                                            [ 94%]
> core\test_nn.py ssss........          [...]

2021-03-06 00:38 UTC, ssheorey commented
@Dudulle Can you try the patch? If it work for you, go ahead and commit it.

2021-03-06 13:04 UTC, Dudulle commented
@ssheorey I have tried your patch but I am still having the following error:

>File "<string>", line 1, in <module>
  File "L:\Source\Open3D\.venv38\lib\site-packages\open3d\__init__.py", line 62, in <module>
    _pybind_cuda = _CDLL(
  File "C:\Users\Cyril\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'L:\Source\Open3D\.venv38\lib\site-packages\open3d\cuda\pybind.cp38-win_amd64.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

Maybe this is because of my configuration. Should I enable something else than `BUILD_PYTHON_MODULE`?

2021-03-07 16:23 UTC, Dudulle commented
Added an extra commit to support Visual Studio 16.9+

2021-03-24 10:59 UTC, Dudulle commented
Rebased on master to resolve conflicts in `CMakeLists.txt`.
Enabled all unit tests except for `SHARED=ON,STATIC_RUNTIME=ON` configuration.

2021-03-26 02:23 UTC, merged

2021-03-26 02:23 UTC, yxlao commented
thanks @Dudulle