SceneWidget works with layouts
intel-isl/Open3D pull request #3212
Opened 2021-03-25 00:11 UTC by prewettg

Moves drawing render targets from Open3DScene into SceneWidget, where they get drawn as an ImGUI image. (There is no overhead for this, ImGUI just takes an opaque ID and the ImguiFilamentBridge needs to make sure that the ID identifies the proper texture; in our case the ID is simply Filament's texture ID.) Because the image is incorporated into the UI, the painting order will be correct and SceneWidgets can now be used in a layout.

#!/usr/bin/env python
import open3d as o3d
import open3d.visualization.gui as gui

app = gui.Application.instance
app.initialize()

```
w = app.create_window("SceneWidget and Layout", 1024, 768)
em = w.theme.font_size
left = gui.VGrid(2, 0.5 * em)
widget3d = gui.SceneWidget()
right = gui.Vert(0.5 * em)
horiz = gui.Horiz()
horiz.add_child(left)
horiz.add_child(widget3d)
horiz.add_child(right)
w.add_child(horiz)

left.preferred_width = 10 * em
left.add_child(gui.Label("Double"))
left.add_child(gui.Slider(gui.Slider.Type.DOUBLE))
left.add_child(gui.Label("Options"))
cb = gui.Combobox()
cb.add_item("Item 1")
cb.add_item("Item 2")
cb.add_item("Item 3")
left.add_child(cb)

right.preferred_width = 15 * em
right.add_child(gui.Label("Lorem ipsum dolor"))

widget3d.scene = o3d.visualization.rendering.Open3DScene(w.renderer)
torus = o3d.geometry.TriangleMesh.create_torus()
torus.compute_vertex_normals()
mat = o3d.visualization.rendering.Material()
mat.shader = "defaultLit"
widget3d.scene.add_geometry("Torus", torus, mat)
bbox = widget3d.scene.bounding_box
widget3d.setup_camera(60, bbox, bbox.get_center())

app.run()
```

(If you apply the changes to Layout.h, Layout.cpp, and gui.cpp in a fresh branch, you can see that the script does not show the 3D scene, which is under the horiz layout)

2021-04-01 22:01 UTC, errissa requested changes
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3212)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @prewettg)

___
*[cpp/open3d/visualization/gui/SceneWidget.cpp, line 1069 at r1](https://reviewable.io/reviews/intel-isl/open3d/3212#-MXERZRr5j3eamFgLl-v:-MXERZRs3agZcm6NwlHr:b-qvpysy) ([raw file](https://github.com/intel-isl/open3d/blob/53191d91e7b1b72bb5d88879893cc21a1a073bb6/cpp/open3d/visualization/gui/SceneWidget.cpp#L1069)):*
> ```cpp
>     ImGui::SetNextWindowPos(ImVec2(float(f.x), float(f.y)));
>     ImGui::SetNextWindowSize(ImVec2(float(f.width), float(f.height)));
>     ImGui::Begin(impl_->id_.c_str(), nullptr,
> ```

This sequence here may be causing a double image blit because the the full screen quad is still added to the FilamentScene. If I'm not mistaken, this approach of allowing ImGui to render the render target to screen makes the `window_view` and `window_scene` in Open3DScene unnecessary.


<!-- Sent from Reviewable.io -->

2021-04-01 22:01 UTC, errissa reviewed
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3212)* status: all files reviewed, 1 unresolved discussion (waiting on @prewettg)



<!-- Sent from Reviewable.io -->

2021-04-02 01:02 UTC, prewettg reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3212)* status: all files reviewed, 1 unresolved discussion (waiting on @errissa)

___
*[cpp/open3d/visualization/gui/SceneWidget.cpp, line 1069 at r1](https://reviewable.io/reviews/intel-isl/open3d/3212#-MXERZRr5j3eamFgLl-v:-MXF5IcB0DSGjG2xH-N5:b-rs8o7h) ([raw file](https://github.com/intel-isl/open3d/blob/53191d91e7b1b72bb5d88879893cc21a1a073bb6/cpp/open3d/visualization/gui/SceneWidget.cpp#L1069)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

This sequence here may be causing a double image blit because the the full screen quad is still added to the FilamentScene. If I'm not mistaken, this approach of allowing ImGui to render the render target to screen makes the `window_view` and `window_scene` in Open3DScene unnecessary.
</blockquote></details>

Did Reviewable hide my changes to Open3DScene? This PR removes window_scene and window_view from Open3DScene as you describe (indeed, finding those for a different PR is what inspired this one). Since window_scene is no longer there, it should only be blitted once if my understanding is correct.


<!-- Sent from Reviewable.io -->

2021-04-02 02:01 UTC, errissa approved these changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @prewettg)



<!-- Sent from Reviewable.io -->

2021-04-02 02:01 UTC, merged