Upgrade Tensor-based RGBD odometry
intel-isl/Open3D pull request #3229
Opened 2021-03-30 04:12 UTC by theNded

This PR includes:
- Implement intensity-based RGBD odometry, Real-time visual odometry from dense RGB-D images, ICCV Workshops, 2011
- Implement hybrid RGBD odometry, Colored ICP Revisited, ICCV 2017
- More intuitive source to target loss formulation in kernel implementation
- Enhanced depth preprocessing
- Bug fix: incompatible dtypes in `CreateFromDepthImage` and `CreateFromRGBDImage`
- Initial benchmark:
```
-----------------------------------------------------------------------------------
Benchmark                                         Time             CPU   Iterations
-----------------------------------------------------------------------------------
RGBDOdometryMultiScale/Hybrid_CPU              63.9 ms         61.3 ms           12
RGBDOdometryMultiScale/Intensity_CPU           54.0 ms         51.3 ms           10
RGBDOdometryMultiScale/PointToPlane_CPU        71.5 ms         68.3 ms           10
RGBDOdometryMultiScale/Hybrid_CUDA             20.6 ms         20.5 ms           36
RGBDOdometryMultiScale/Intensity_CUDA          20.1 ms         20.1 ms           36
RGBDOdometryMultiScale/PointToPlane_CUDA       30.1 ms         27.3 ms           38
```

2021-03-30 14:36 UTC, reyanshsolis requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3229)* status: 0 of 17 files reviewed, 6 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp, line 48 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX2RGVfC6vmb8Rzas2B:-MX2RGVfC6vmb8Rzas2C:b-8lkroy) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp#L48)):*
> ```cpp
>     }
>     core::Device device = depth.GetDevice();
>     if (device.GetType() == core::Device::DeviceType::CPU) {
> ```

Do we also need to check shape/shape compatibility anywhere, in the kernel or main function?
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp, line 176 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX2UBtn-gkdL68fD08f:-MX2UBtn-gkdL68fD08g:bs2u0mo) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp#L176)):*
> ```cpp
> 
>     normal_map =
>             core::Tensor::Zeros(vertex_map.GetShape(), vertex_map.GetDtype(),
> ```

For initializing normal_indexer, do we need to initialize normal_map with `Zeros`? 
If we can work with Empty the performance will significantly improve. Same for the rest of the PR.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu, line 41 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX2VVng9fBnpoXLUrMT:-MX2VVng9fBnpoXLUrMU:bx3cvnc) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu#L41)):*
> ```Cuda
> #include "open3d/t/pipelines/kernel/TransformationConverter.h"
> 
> #define WARPSIZE 32
> ```

We can remove these two `#define`. I forgot to remove this after my experiments with the shared memory reduction kernel. 
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h, line 254 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX2WkfM1F1yVrvCCtMW:-MX2WkfM1F1yVrvCCtMX:b8jmpfm) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h#L254)):*
> ```objc
>             (*target_intensity_dy_indexer.GetDataPtrFromCoord<float>(u_t, v_t));
> 
>     // printf("%ld: (%d %d %f) -> (%f %f %f) -> (%d %d) -> depth diff: %f,
> ```

Can we remove this?
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h, line 299 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX2Wu4H0TgTPUAfMmpA:-MX2Wu4H0TgTPUAfMmpB:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h#L299)):*
> ```objc
>     J_D[5] = sqrt_lambda_depth * (d2 - 1.0f);
> 
>     // printf("D: (%d %d) -> (%f %f %f) -> (%d %d), (%f %f %f %f %f %f, %f,
> ```

same.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 111 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX2XtpV9TjvxVNY3qu2:-MX2XtpV9TjvxVNY3qu3:b-e68rw4) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L111)):*
> ```objc
>                                float depth_diff);
> 
> ///
> ```

Extra?

Do you think some of these functions might be better placed at t::Image rather than RGBDOdometry?  


<!-- Sent from Reviewable.io -->

2021-03-31 08:38 UTC, reyanshsolis commented
Kernels are assuming tensors to be contiguous. If we are not certain about that, we may make them contiguous before processing.

2021-04-02 18:15 UTC, ssheorey requested changes
[WIP, will add more comments later]

Can you add function argument descriptions for doxygen to the user facing functions? It's useful for internal functions as well. If the arguments are just Tensors, add the expected dimensions of the inputs and outputs.

`#if defined(BUILD_CUDA_MODULE) && defined(__CUDACC__):`
Just` defined(__CUDACC__)` should be sufficient here.

2021-04-02 18:15 UTC, ssheorey commented on cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h
> +
If this header contains inline implementations, rename to `RGBDOdometryJacobianImpl.h`

2021-04-02 18:15 UTC, ssheorey commented on cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h
> +    //            J_I[3], J_I[4], J_I[5]);
Remove debug code / comments.

2021-04-02 18:15 UTC, ssheorey commented on cpp/open3d/t/pipelines/kernel/TransformationConverter.h
> +/// for Jtr, 1 for residual, 1 for inlier count).
Latex rendering: `\f$ J^tJ \f$`, etc..

2021-04-05 02:36 UTC, theNded reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3229)* status: 0 of 17 files reviewed, 28 unresolved discussions (waiting on @reyanshsolis and @ssheorey)

___
*[cpp/benchmarks/t/pipelines/odometry/RGBDOdometry.cpp, line 65 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX0KHjwV4AH3UYzKg_U-r2-65:-MXUb4lW1O_SWSc5tqGQ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/benchmarks/t/pipelines/odometry/RGBDOdometry.cpp#L65)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Are these 3 `const`?
</blockquote></details>

Done.
___
*[cpp/benchmarks/t/pipelines/odometry/RGBDOdometry.cpp, line 181 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX2eFp53YAbTKXJeA_U:-MXUbBB7-JHgHIbSOJvD:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/benchmarks/t/pipelines/odometry/RGBDOdometry.cpp#L181)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

#ifdef BUILD_CUDA_MODULE section for CUDA benchmark.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/GeometryIndexer.h, line 111 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX0KHjwV4AH3UYzKg_W-r2-111:-MXUbWw20jUgHzEXk65q:bez0l6x) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/geometry/kernel/GeometryIndexer.h#L111)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Remove `_` from name of `public` data members.
</blockquote></details>

Reverted to private and added relevant interface
___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 33 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX0KHjwV4AH3UYzKg_X-r2-33:-MXUd7b11SHry1J9jlEQ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L33)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Just `defined(__CUDACC__)` should be sufficient here.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 35 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX0KHjwV4AH3UYzKg_X-r2-35:-MXUd8yq9TcXVG2CvWIy:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L35)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

[Double underscore identifiers are reserved in C++11](https://stackoverflow.com/a/228797)
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 38 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX0KHjwV4AH3UYzKg_X-r2-38:-MXUdGp18HMgoKxiDSQV:b5d6h25) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L38)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

If we just want to select the namespace, can we use 
`using std::isnan` instead of a `#define`?

</blockquote></details>

That might bring confusion in CUDA kernel code, conditional compilation might be safer.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp, line 48 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX2RGVfC6vmb8Rzas2B:-MXUfRmQCq0fsD8hNIwU:bjkfrd1) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp#L48)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Do we also need to check shape/shape compatibility anywhere, in the kernel or main function?
</blockquote></details>

TODO: We can fix this in a future PR. The missing condition checks are prevalent, many are shared -- need to design specific checkers for reuse.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp, line 80 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX0KHjwV4AH3UYzKg_Z-r2-80:-MXUfmRMAkk_h2bYrSkj:b-lwzgqo) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp#L80)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`CUDA_CALL(PyrDownDepthCUDA, depth, depth_down, depth_diff);`
slightly shorter and includes the `BUILD_CUDA_MODULE` error check.
</blockquote></details>

TODO: Simplify kernel launches in t/pipeline and t/geometry
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp, line 176 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX2UBtn-gkdL68fD08f:-MXUh7hu4C2s0YTXACT8:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp#L176)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

For initializing normal_indexer, do we need to initialize normal_map with `Zeros`? 
If we can work with Empty the performance will significantly improve. Same for the rest of the PR.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu, line 41 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX2VVng9fBnpoXLUrMT:-MXUi9QV3sWnvy9uuc6H:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu#L41)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

We can remove these two `#define`. I forgot to remove this after my experiments with the shared memory reduction kernel. 
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h, line 28 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX0KHjwV4AH3UYzKg_d-r2-28:-MXUiJXK8fM1GR_nSB_G:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h#L28)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

If this header contains inline implementations, rename to `RGBDOdometryJacobianImpl.h`
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h, line 59 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX0KHjwV4AH3UYzKg_d-r2-59:-MXUj9L_4pOyzxUWN9JO:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h#L59)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`source_on_target` = `source_to_target` or `source_from_target`? Could you rename or add a clarifying comment?
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h, line 227 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX0KHjwV4AH3UYzKg_d-r2-227:-MXUjAk5Ayyl_mYoW7VL:bnw9mgr) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h#L227)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

If this is remaining, add person to TODO. eg: `TODO(Wei):`
</blockquote></details>

It's done!
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h, line 254 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX2WkfM1F1yVrvCCtMW:-MXUjLjqAOp2BjlBXfsu:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h#L254)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Can we remove this?
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobian.h, line 264 at r2](https://reviewable. [...]

2021-04-05 07:55 UTC, reyanshsolis commented
@theNded New Benchmark mostly due to changing Zeros to Empty:
```
-----------------------------------------------------------------------------------
Benchmark                                         Time             CPU   Iterations
-----------------------------------------------------------------------------------
RGBDOdometryMultiScale/Hybrid_CPU              43.7 ms         43.4 ms           16
RGBDOdometryMultiScale/Intensity_CPU           36.1 ms         36.1 ms           19
RGBDOdometryMultiScale/PointToPlane_CPU        26.9 ms         26.9 ms           26
RGBDOdometryMultiScale/Hybrid_CUDA             23.1 ms         23.0 ms           30
RGBDOdometryMultiScale/Intensity_CUDA          21.9 ms         21.9 ms           32
RGBDOdometryMultiScale/PointToPlane_CUDA       20.3 ms         20.3 ms           28
```
CPU and CUDA take around the same time for PointToPlane, more motivation to add shared memory reduction XD.

2021-04-05 08:02 UTC, reyanshsolis commented
Do we need to pass the `residual` as `Tensor` or we can just make it `double` everywhere?

2021-04-05 15:10 UTC, theNded commented
> Do we need to pass the `residual` as `Tensor` or we can just make it `double` everywhere?

That could be addressed altogether in a future PR with a refactorization about encapsuled return results and options

2021-04-06 00:07 UTC, ssheorey requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3229)* status: 0 of 17 files reviewed, 26 unresolved discussions (waiting on @reyanshsolis and @theNded)

*[a discussion](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZMSvyEPRCiFA9TiZN:-MXZMSvyEPRCiFA9TiZO:b-6w77la) (no related file):*
For performing RGBDOdometry on a video stream, we'll have a workflow like this:
odometry(frame[0], frame[1])
odometry(frame[1], frame[2])
...
It will help to save intermediate calculations on a frame (eg: pyramid, vertex_map, color_map, normal_map computations) so that they can be reused in the next odometry. This should significantly reduce run time on a video stream. Can we add interfaces for odometry to work like this? So that odometry accepts processed source and outputs processed target in addition to the odometry output.

e.g. The OpenCV `calcOpticalFlowPyrLK()` accepts either an image or a pre-built pyramid for the source frame.

---
*[a discussion](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZSVDj8bInwx4bdZip:-MXZSVDj8bInwx4bdZiq:b-j3xwm9) (no related file):*
Can we do without separate `pipelines/kernel/RGBDOdometry.cpp` and `pipelines/kernel/RGBDOdometry.h`? The current functions in `pipelines/RGBDOdometry.cpp` and `pipelines/RGBDOdometry.h` look mostly like forwarding functions that we can eliminate by moving the functionality from the kernel folder in them. 

---
___
*[cpp/open3d/t/geometry/kernel/PointCloudImpl.h, line 93 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXYTyhU2U4ro8Q-aGwG:-MXYTyhU2U4ro8Q-aGwH:b786tgt) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/geometry/kernel/PointCloudImpl.h#L93)):*
> ```objc
> 
>     int64_t n = rows_strided * cols_strided;
> #if defined(BUILD_CUDA_MODULE) && defined(__CUDACC__)
> ```

Should be OK to replace all instances of 
`#if defined(BUILD_CUDA_MODULE) && defined(__CUDACC__)`
with
`#if defined(__CUDACC__)`
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp, line 80 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX0KHjwV4AH3UYzKg_Z-r2-80:-MXYWf8k4eSWeHYYzTWb:bfu0l3l) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp#L80)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

TODO: Simplify kernel launches in t/pipeline and t/geometry
</blockquote></details>

Optionally, there are many functions with CPU and CUDA implementations. It would be good to have a general macro for a block like this:
`#define RUN_ON_DEVICE(device, function, args, ...) \`
    `if (device.GetType() == core::Device::DeviceType::CPU) { \`
          ` function ## _CPU(args);`
`} else if ... // check and run on CUDA`
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp, line 78 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXYZT8c5yNhS3pp0XzQ:-MXYZT8c5yNhS3pp0XzR:bwvkl02) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp#L78)):*
> ```cpp
> }
> 
> void PyrDownDepthCPU(const core::Tensor& depth,
> ```

Can we use the IPP / NPP versions for `PyrDown` instead of our own? They will likely by faster.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp, line 95 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXYYw3V0Bx_PJZMti8X:-MXYYw3V0Bx_PJZMti8Y:b-3jc9mi) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp#L95)):*
Comment or rename:
> ```
>     const int D = 5;    // Gaussian filter window size
>     const float weights[3] = {0.375f, 0.25f, 0.0625f}; // Gaussian filter weights
> ```
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp, line 115 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXYuOTI4nx7tofs8dtq:-MXYuOTI4nx7tofs8dtr:b7mz87n) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp#L115)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                 int x_mi = std::max(0, 2 * x - D / 2) - 2 * x;
>                 int y_mi = std::max(0, 2 * y - D / 2) - 2 * y;
>                 int x_ma = std::min(cols, 2 * x - D / 2 + D) - 2 * x;
>                 int y_ma = std::min(rows, 2 * y - D / 2 + D) - 2 * y;
> ```
</details>

x_min, x_max, y_min, y_max is clearer
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu, line 80 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZ9aMMCjUlshHfRMme:-MXZ9aMMCjUlshHfRMmf:b-v9bttl) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu#L80)):*
> ```Cuda
> }
> 
> void PyrDownDepthCUDA(const core::Tensor& depth,
> ```

Will NPP PyrDown work for us? That may be faster.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu, line 117 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZ9P_uB8Bs3cwi5W7T:-MXZ9P_uB8Bs3cwi5W7U:b4ki361) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu#L117)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                 int x_mi = max(0, 2 * x - D / 2) - 2 * x;
>                 int y_mi = max(0, 2 * y - D / 2) - 2 * y;
>                 int x_ma = min(cols, 2 * x - D / 2 + D) - 2 * x;
>                 int y_ma = min(rows, 2 * y - D / 2 + D) - 2 * y;
> ```
</details>

x_min, x_max, y_min, y_max is clearer.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu, line 345 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZD7H-9d_Xd4zQeMLj:-MXZD7H-9d_Xd4zQeMLk:b-peuh7g) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu#L345)):*
> ```
> red[<0;100;16M]uced
> ```
typo
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu, line 420 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZC6728in2zqgLbzjB:-MXZC6728in2zqgLbzjC:b-wyftlq) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu#L420)):*
> ```Cuda
>     const int64_t n = rows * cols;
> 
>     // A_29xN is a {29, N} shaped tensor, which is later red[<0;100;16M]uced to
> ```

Typo: `red[<0;100;16M]uced`
___
*[cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp, line 149 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZEpogD3EAtbMEIxDD:-MXZEpogD3EAtbMEIxDE:b-jlmhh) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp#L149)):*
> ```
> Atb.Neg()
> ```
Performing Neg() while copying data (`Atb_local_ptr[j] = -A_1x29_ptr[21 + j];`) may give very slight speedup.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp, line 48 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZLi2a6Ql8_R_02wMq:-MXZLi2a6Ql8_R_02wMr:bxnaumo) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp#L48)):*
> ```cpp
>                                     float depth_diff,
>                                     const std::vector<int>& iterations,
>                                     const Method method) {
> ```

The implementations for the 3 methods look quite distinct. Can we split this large function into separate functions for each of the 3 methods?
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp, line 49 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZGQ1C9XsLpYHjuapf:-MXZGQ1D33BNzGguJHMt:b-asuftz) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b [...]

2021-04-06 02:13 UTC, yxlao reviewed
> Reviewed 3 of 17 files at r1, 3 of 8 files at r2, 6 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3229)* status: 12 of 17 files reviewed, 27 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[cpp/benchmarks/t/pipelines/odometry/RGBDOdometry.cpp, line 144 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZvGg-DPQq4dorzHZ-:-MXZvGg-DPQq4dorzHZ0:bamq8up) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/benchmarks/t/pipelines/odometry/RGBDOdometry.cpp#L144)):*
> ```cpp
>     core::Tensor intrinsic_t = CreateIntrisicTensor();
> 
>     // Warp up
> ```

Warm up


<!-- Sent from Reviewable.io -->

2021-04-07 03:40 UTC, theNded reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3229)* status: 8 of 18 files reviewed, 27 unresolved discussions (waiting on @reyanshsolis, @ssheorey, @theNded, and @yxlao)

___
*[cpp/benchmarks/t/pipelines/odometry/RGBDOdometry.cpp, line 144 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZvGg-DPQq4dorzHZ-:-MXdRr2A86Ij1fsOalTs:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/benchmarks/t/pipelines/odometry/RGBDOdometry.cpp#L144)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Warm up
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/PointCloudImpl.h, line 93 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXYTyhU2U4ro8Q-aGwG:-MXdS7GjBZIFHllTpAuM:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/geometry/kernel/PointCloudImpl.h#L93)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Should be OK to replace all instances of 
`#if defined(BUILD_CUDA_MODULE) && defined(__CUDACC__)`
with
`#if defined(__CUDACC__)`
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp, line 80 at r2](https://reviewable.io/reviews/intel-isl/open3d/3229#-MX0KHjwV4AH3UYzKg_Z-r2-80:-MXdTzRJ-_oQW66VVC5d:bb7462z) ([raw file](https://github.com/intel-isl/open3d/blob/19109ed1fa488549427b26756c4d1b023b0a9711/cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp#L80)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Optionally, there are many functions with CPU and CUDA implementations. It would be good to have a general macro for a block like this:
`#define RUN_ON_DEVICE(device, function, args, ...) \`
    `if (device.GetType() == core::Device::DeviceType::CPU) { \`
          ` function ## _CPU(args);`
`} else if ... // check and run on CUDA`
</blockquote></details>

TODO
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp, line 78 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXYZT8c5yNhS3pp0XzQ:-MXdSNqo8Ztq6zCmg0iB:b-o2iklf) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp#L78)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can we use the IPP / NPP versions for `PyrDown` instead of our own? They will likely by faster.
</blockquote></details>

The performance was similar, while ours added a truncation during gaussian blur, which reduced noise from downsampling edge pixels.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp, line 95 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXYYw3V0Bx_PJZMti8X:-MXdUJx28v_TniaqXWv2:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp#L95)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Comment or rename:
> ```
>     const int D = 5;    // Gaussian filter window size
>     const float weights[3] = {0.375f, 0.25f, 0.0625f}; // Gaussian filter weights
> ```
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp, line 115 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXYuOTI4nx7tofs8dtq:-MXdVBu62G32xZe8icsb:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp#L115)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>                 int x_mi = std::max(0, 2 * x - D / 2) - 2 * x;
>                 int y_mi = std::max(0, 2 * y - D / 2) - 2 * y;
>                 int x_ma = std::min(cols, 2 * x - D / 2 + D) - 2 * x;
>                 int y_ma = std::min(rows, 2 * y - D / 2 + D) - 2 * y;
> ```
x_min, x_max, y_min, y_max is clearer
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu, line 80 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZ9aMMCjUlshHfRMme:-MXdWjtTDmezogwBIinf:b-ya81ng) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu#L80)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Will NPP PyrDown work for us? That may be faster.
</blockquote></details>

Same as above
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu, line 117 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZ9P_uB8Bs3cwi5W7T:-MXdWmK67bGoOcvXeIpW:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu#L117)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>                 int x_mi = max(0, 2 * x - D / 2) - 2 * x;
>                 int y_mi = max(0, 2 * y - D / 2) - 2 * y;
>                 int x_ma = min(cols, 2 * x - D / 2 + D) - 2 * x;
>                 int y_ma = min(rows, 2 * y - D / 2 + D) - 2 * y;
> ```
x_min, x_max, y_min, y_max is clearer.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu, line 345 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZD7H-9d_Xd4zQeMLj:-MXdWunj5iOWmxcSsxgZ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu#L345)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> red[<0;100;16M]uced
> ```
typo
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu, line 420 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZC6728in2zqgLbzjB:-MXdX2xBEcXfsHVRry5K:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu#L420)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Typo: `red[<0;100;16M]uced`
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp, line 149 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZEpogD3EAtbMEIxDD:-MXdX5eU0zjqgFV8MlP3:b-whkrmt) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp#L149)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> Atb.Neg()
> ```
Performing Neg() while copying data (`Atb_local_ptr[j] = -A_1x29_ptr[21 + j];`) may give very slight speedup.
</blockquote></details>

This is only 1x6, so maintaining readability might be better.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp, line 49 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZGQ1C9XsLpYHjuapf:-MXdXR-rAOEyY_vtKFdb:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp#L49)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`// TODO(author): `
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp, line 72 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZKoIb59pemIr1vt7L:-MXdY16NBB4GtfWw73aZ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfda6f34ff99655b4815c4c8f1/cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp#L72)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Is this `n_levels` or `n_scales` (more descriptive)?
</blockquote></details>

Done.
___
*[cpp/tests/t/pipelines/odometry/RGBDOdometry.cpp, line 67 at r3](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXZIsXo-RTS7shZ4v1E:-MXdXiW1BpkzCF_0BFOt:b-e3jnjb) ([raw file](https://github.com/intel-isl/open3d/blob/d8c63003484859dfd [...]

2021-04-08 15:45 UTC, theNded commented
Can we merge?

2021-04-08 16:11 UTC, reyanshsolis approved these changes
> Reviewed 2 of 17 files at r1, 3 of 8 files at r2, 7 of 9 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3229)* status: all files reviewed, 27 unresolved discussions (waiting on @reyanshsolis, @ssheorey, @theNded, and @yxlao)



<!-- Sent from Reviewable.io -->

2021-04-08 16:40 UTC, ssheorey approved these changes
Yes, please go ahead. One last thing is that Doxygen chokes on `\param argument` instead of `\p argument` so the docs just stop before `argument`:
![image.png](https://files.reviewableusercontent.io/images/reviewable/41028320/tdjFCrj363A8-1ctbwxA5gfK/image.png)

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3229#-:-MXmKeaF9hf-FXT4OCo0:b-rjqrp1)* status: all files reviewed, 31 unresolved discussions (waiting on @reyanshsolis, @ssheorey, @theNded, and @yxlao)

___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 53 at r4](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXmKBtj6xDz_rzmCH0S:-MXmKBtj6xDz_rzmCH0T:br02kt9) ([raw file](https://github.com/intel-isl/open3d/blob/919f421f0e858ed6405da955ace76606d18c498d/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L53)):*
> ```
> /// RGBD images, and perform hierarchical odometry using specified \param
> /// method.
> ```
\p method
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 87 at r4](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXmInYk1r9RCr-mgksk:-MXmInYk1r9RCr-mgksl:b-dkirqv) ([raw file](https://github.com/intel-isl/open3d/blob/919f421f0e858ed6405da955ace76606d18c498d/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L87)):*
> ```objc
> /// \f$ V_q \f$ denotes the vertex at pixel q in the target,
> /// \f$ N_p \f$ denotes the normal at pixel p in the source.
> /// q is obtained by transforming p with \param init_source_to_target then
> ```

\p init_source_to_target
\p intrinsics
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 116 at r4](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXmK-yv2C469jziNBBR:-MXmK-yv2C469jziNBBS:baqtqzp) ([raw file](https://github.com/intel-isl/open3d/blob/919f421f0e858ed6405da955ace76606d18c498d/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L116)):*
> ```
> /// q is obtained by transforming p with \param init_source_to_target then
> /// projecting with \param intrinsics.
> ```
\p init_source_to_target
\p intrinsics
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 158 at r4](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXmK2u3BlP8FdYMRjeG:-MXmK2u3BlP8FdYMRjeH:baqtqzp) ([raw file](https://github.com/intel-isl/open3d/blob/919f421f0e858ed6405da955ace76606d18c498d/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L158)):*
> ```
> /// q is obtained by transforming p with \param init_source_to_target then
> /// projecting with \param intrinsics.
> ```
\p init_source_to_target
\p intrinsics


<!-- Sent from Reviewable.io -->

2021-04-08 17:54 UTC, theNded commented
> Yes, please go ahead. One last thing is that Doxygen chokes on `\param argument` instead of `\p argument` so the docs just stop before `argument`:
> ![image.png](https://camo.githubusercontent.com/91a612b404c68003b7934ad4a1948246772bb75cb0d8e4a83e99419042004407/68747470733a2f2f66696c65732e72657669657761626c6575736572636f6e74656e742e696f2f696d616765732f72657669657761626c652f34313032383332302f74646a4643726a33363341382d316374627778413567664b2f696d6167652e706e67)
> 
> > _[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3229#-:-MXmKeaF9hf-FXT4OCo0:b-rjqrp1)_ status: all files reviewed, 31 unresolved discussions (waiting on @reyanshsolis, @ssheorey, @theNded, and @yxlao)
> 
> _[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 53 at r4](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXmKBtj6xDz_rzmCH0S:-MXmKBtj6xDz_rzmCH0T:br02kt9) ([raw file](https://github.com/intel-isl/open3d/blob/919f421f0e858ed6405da955ace76606d18c498d/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L53)):_
> 
> > ```
> > /// RGBD images, and perform hierarchical odometry using specified \param
> > /// method.
> > ```
> 
> \p method
> 
> _[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 87 at r4](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXmInYk1r9RCr-mgksk:-MXmInYk1r9RCr-mgksl:b-dkirqv) ([raw file](https://github.com/intel-isl/open3d/blob/919f421f0e858ed6405da955ace76606d18c498d/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L87)):_
> 
> > ```objc
> > /// \f$ V_q \f$ denotes the vertex at pixel q in the target,
> > /// \f$ N_p \f$ denotes the normal at pixel p in the source.
> > /// q is obtained by transforming p with \param init_source_to_target then
> > ```
> 
> \p init_source_to_target
> \p intrinsics
> 
> _[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 116 at r4](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXmK-yv2C469jziNBBR:-MXmK-yv2C469jziNBBS:baqtqzp) ([raw file](https://github.com/intel-isl/open3d/blob/919f421f0e858ed6405da955ace76606d18c498d/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L116)):_
> 
> > ```
> > /// q is obtained by transforming p with \param init_source_to_target then
> > /// projecting with \param intrinsics.
> > ```
> 
> \p init_source_to_target
> \p intrinsics
> 
> _[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 158 at r4](https://reviewable.io/reviews/intel-isl/open3d/3229#-MXmK2u3BlP8FdYMRjeG:-MXmK2u3BlP8FdYMRjeH:baqtqzp) ([raw file](https://github.com/intel-isl/open3d/blob/919f421f0e858ed6405da955ace76606d18c498d/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L158)):_
> 
> > ```
> > /// q is obtained by transforming p with \param init_source_to_target then
> > /// projecting with \param intrinsics.
> > ```
> 
> \p init_source_to_target
> \p intrinsics

Thanks! Could you please let me know the commands to generate doxygen? I'm haven't taken a look at that before...

2021-04-13 15:39 UTC, theNded commented
Can we please merge this PR?

2021-04-13 17:37 UTC, merged