Optimize RGBD odometry
intel-isl/Open3D pull request #3323
Opened 2021-04-21 22:00 UTC by theNded

This PR is depending on #3314 and #3318.

Introduces sum reduction in `__shared__` memory without the usage of cub global reduction. Roughly we have 5x speedup with this change.

2021-04-26 18:35 UTC, reyanshsolis commented
Are we intentionally not adding ` open3d/t/geometry/Utility.h`, to `Open3D.h.in` ?

[Not important - we may do it in a later refactoring]:
We may add the `utility` namespace in the same file and move the `TransformationConverter` files to this later.
The Eigen equivalent functions `TransformMatrix4dToVector6d`, `TransformVector6dToMatrix4d`, `SolveJacobianSystemAndObtainExtrinsicMatrix`, `SolveLinearSystemPSD` are also under a `utility` namespace.

2021-04-29 05:18 UTC, reyanshsolis requested changes
> Reviewed 4 of 53 files at r1, 6 of 54 files at r4, 48 of 48 files at r5.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3323)* status: all files reviewed, 9 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/geometry/Image.h, line 242 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZQsxl187Vgn2BDxKDW:-MZQsxl2-MuLILbQhguA:balbb60) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/geometry/Image.h#L242)):*
> ```objc
>     Image PyrDown() const;
> 
>     /// Preprocess a image of shape (rows, cols, channels=1), typically used for
> ```

May we want to add the `\brief` and `\return` keywords, in docstring? 
Same for the rest of this PR.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp, line 95 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZQumxL4IMvnqYUuQMm:-MZQumxL4IMvnqYUuQMn:b-kjhy3s) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp#L95)):*
> ```cpp
> 
>                     if (valid) {
>                         float d_huber = HuberDeriv(r, depth_huber_delta);
> ```

So this is like `Robust Kernel: weight`?
Do we want to add a custom option later too, like in Legacy Registration, to pass any outlier rejection method / loss function? 
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryImpl.h, line 46 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZQwCAk18TUjhieTjbQ:-MZQwCAl7HHVaot3tWt0:bwbpl2f) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/kernel/RGBDOdometryImpl.h#L46)):*
> ```objc
>                                 float& inlier_residual,
>                                 int& inlier_count,
>                                 float depth_outlier_trunc,
> ```

may we add `const` for `depth_outlier_trunc`, `depth_huber_delta` and `intensity_huber_delta` ? Same for rest of the PR.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobianImpl.h, line 47 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZQwi7x5Tu-b3BvMw-_:-MZQwi7x5Tu-b3BvMw-a:b-6e8z46) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobianImpl.h#L47)):*
> ```objc
> #endif
> 
> inline OPEN3D_HOST_DEVICE float HuberDeriv(float r, float delta) {
> ```

Later, we might want to expose this outside, and pass it inside as lambda? 
Maybe inside `t::pipeline::odometry`? [To enable users to define there own loss function]. 
___
*[cpp/open3d/t/pipelines/kernel/TransformationConverter.h, line 58 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZQxKGLAcoT_H4Q0dti:-MZQxKGLAcoT_H4Q0dtj:bpcnj7d) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/kernel/TransformationConverter.h#L58)):*
> ```objc
> /// \param delta 6d
> /// tensor for a se3 tangent vector. \param residual 1d tensor.
> void DecodeAndSolve6x6(const core::Tensor &A_reduction,
> ```

May I remove this, in my PR for registration update? I will also be using the other overloaded function.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp, line 218 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZQzs8yCelV15RKukC_:-MZQzs8z4qGB9R25v_WB:bsnb48h) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp#L218)):*
> ```cpp
>             core::Tensor delta_source_to_target = result.transformation_;
>             trans = delta_source_to_target.Matmul(trans).Contiguous();
>             utility::LogDebug("level {}, iter {}: rmse = {}, fitness = {}", i,
> ```

This is a good design, I tried to use this design in the Registration refactoring PR earlier. I think Registration and Odometry should be consistent with this part. 
In registration, the current design is:
```
Get Correspondences and RegistrationResult
     Registration Loop:
           Print( Iteration, Inlier RMSE, Inlier Fitness)
           ComputeTransform
           Update
           Get Correspondences and RegistrationResult
           Check termination criteria
```
Disadvantage:
   - So, for N iterations of ICP, we do N + 1, NNS. 
   - We reduce squared distance from NNS, as inlier rmse, instead of using residual.
   - We need an inlier count, based on NNS result, before going to TransformationEstimation functions. [Thus we are not using the kernel's inlier residual and count, performing 2 extra reductions]. 

Advantage:
  - If the difference in fitness and rmse, is less than the criteria, the loop can end in its first iteration itself. Therefore we are using one less `ComputeTransform`[cheap compared to NNS]. 


Would you suggest, that I adapt this flow for registration as well?
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp, line 440 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZR17zA8USjvBv03UJs:-MZR17zA8USjvBv03UJt:b-rwsklm) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp#L440)):*
> ```cpp
> }
> 
> OdometryResult ComputePosePointToPlane(
> ```

Do we want to change the function name? Maybe to `ComputeOdometryResultPointToPlane`? 

One alternative may be, ComputeTransformPointToPlane and pass inlier_residual and inlier_count as parameters to get output.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp, line 464 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZR2EXB26XOgXNPnN-x:-MZR2EXB26XOgXNPnN-y:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp#L464)):*
> ```cpp
> }
> 
> OdometryResult ComputePoseIntensity(const core::Tensor& source_depth,
> ```

same.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp, line 492 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZR2Fqu6oDpQ7FhMn4t:-MZR2Fqu6oDpQ7FhMn4u:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp#L492)):*
> ```cpp
> }
> 
> OdometryResult ComputePoseHybrid(const core::Tensor& source_depth,
> ```

same.
___
*[cpp/tests/t/geometry/Image.cpp, line 896 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZR2ePi-r32sjYz-JFW:-MZR2ePj1_zk6gWVWs-E:b7gvuqm) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/tests/t/geometry/Image.cpp#L896)):*
> ```cpp
> }
> 
> TEST_P(ImagePermuteDevices, DISABLED_CreateNormalMap_Visual) {
> ```

why are implemented tests DISABLED in this file?


<!-- Sent from Reviewable.io -->

2021-04-29 06:56 UTC, reyanshsolis requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3323)* status: all files reviewed, 9 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp, line 218 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZQzs8yCelV15RKukC_:-MZRPKkY6N8dTatmaLVm:b-ptmlxf) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp#L218)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

This is a good design, I tried to use this design in the Registration refactoring PR earlier. I think Registration and Odometry should be consistent with this part. 
In registration, the current design is:
```
Get Correspondences and RegistrationResult
     Registration Loop:
           Print( Iteration, Inlier RMSE, Inlier Fitness)
           ComputeTransform
           Update
           Get Correspondences and RegistrationResult
           Check termination criteria
```
Disadvantage:
   - So, for N iterations of ICP, we do N + 1, NNS. 
   - We reduce squared distance from NNS, as inlier rmse, instead of using residual.
   - We need an inlier count, based on NNS result, before going to TransformationEstimation functions. [Thus we are not using the kernel's inlier residual and count, performing 2 extra reductions]. 

Advantage:
  - If the difference in fitness and rmse, is less than the criteria, the loop can end in its first iteration itself. Therefore we are using one less `ComputeTransform`[cheap compared to NNS]. 


Would you suggest, that I adapt this flow for registration as well?
</blockquote></details>

*one more `ComputeTransform` [instead of one less].


<!-- Sent from Reviewable.io -->

2021-04-29 08:16 UTC, reyanshsolis commented
Also, if you think it's better,
I would suggest to add `max_iterations` in `OdometryConvergenceCriteria` like `ICPConvergenceCriteria`, and remove `iterations` parameter from the function.

Currently, the `RegistrationMultiScaleICP` looks like this:
```
/// \param source The source point cloud.
/// \param target The target point cloud.
/// \param voxel_sizes VectorDouble of voxel scales of type double.
/// \param criterias Vector of ICPConvergenceCriteria objects for each scale.
/// \param max_correspondence_distances VectorDouble of maximum correspondence
/// points-pair distances of type double, for each iteration. Must be of same
/// length as voxel_sizes and criterias.
/// \param init Initial transformation estimation of type Float64 on CPU.
/// \param estimation Estimation method.
RegistrationResult RegistrationMultiScaleICP(
        const geometry::PointCloud &source,
        const geometry::PointCloud &target,
        const std::vector<double> &voxel_sizes,
        const std::vector<ICPConvergenceCriteria> &criterias,
        const std::vector<double> &max_correspondence_distances,
        const core::Tensor &init = core::Tensor::Eye(4,
                                                     core::Dtype::Float64,
                                                     core::Device("CPU:0")),
        const TransformationEstimation &estimation =
                TransformationEstimationPointToPoint());
```

2021-04-29 08:19 UTC, reyanshsolis requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3323)* status: all files reviewed, 10 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 48 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZRhEvHA_4FkdE_N5Kb:-MZRhEvHA_4FkdE_N5Kc:b-t2qti7) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L48)):*
> ```objc
> };
> 
> class OdometryConvergenceCriteria {
> ```

Also, if you think it's better,
I would suggest adding `max_iterations` in `OdometryConvergenceCriteria` like `ICPConvergenceCriteria`, and remove the `iterations` parameter from the function.

Currently, the `RegistrationMultiScaleICP` looks like this:
```
/// \param source The source point cloud.
/// \param target The target point cloud.
/// \param voxel_sizes VectorDouble of voxel scales of type double.
/// \param criterias Vector of ICPConvergenceCriteria objects for each scale.
/// \param max_correspondence_distances VectorDouble of maximum correspondence
/// points-pair distances of type double, for each iteration. Must be of same
/// length as voxel_sizes and criterias.
/// \param init Initial transformation estimation of type Float64 on CPU.
/// \param estimation Estimation method.
RegistrationResult RegistrationMultiScaleICP(
        const geometry::PointCloud &source,
        const geometry::PointCloud &target,
        const std::vector<double> &voxel_sizes,
        const std::vector<ICPConvergenceCriteria> &criterias,
        const std::vector<double> &max_correspondence_distances,
        const core::Tensor &init = core::Tensor::Eye(4,
                                                     core::Dtype::Float64,
                                                     core::Device("CPU:0")),
        const TransformationEstimation &estimation =
                TransformationEstimationPointToPoint());
```


<!-- Sent from Reviewable.io -->

2021-04-29 09:54 UTC, reyanshsolis requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3323)* status: all files reviewed, 11 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 85 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS1ttdEKCLcaJ32tKA:-MZS1tteA3_w4YeF2dlf:b-khvvin) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L85)):*
> ```objc
> };
> 
> class OdometryLossParams {
> ```

May we add `docstring` with `OdometryLossParams`?


<!-- Sent from Reviewable.io -->

2021-04-29 10:26 UTC, reyanshsolis requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3323)* status: all files reviewed, 19 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 119 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS8I-S8ax7S1SIMcOK:-MZS8I-S8ax7S1SIMcOL:bbnrjnx) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L119)):*
> ```objc
> /// \param source Source RGBD image.
> /// \param target Target RGBD image.
> /// \param intrinsics (3, 3) intrinsic matrix for projection.
> ```

please add Dtype to docstring for `intrinsics``init_source_to_target` `transformation`, also in rest of this file.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 134 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS6BwE4QYA6zgL0k3U:-MZS6BwE4QYA6zgL0k3V:b7qq5p9) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L134)):*
> ```objc
>         const core::Tensor& init_source_to_target = core::Tensor::Eye(
>                 4, core::Dtype::Float64, core::Device("CPU:0")),
>         float depth_scale = 1000.0f,
> ```

Is this modified by the algorithm? 
If not can we make `depth_scale` and `depth_max` as `const`?
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 142 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS9HUnCjJvSQWmESqQ:-MZS9HUnCjJvSQWmESqR:b-twuc4u) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L142)):*
> ```objc
>                 OdometryConvergenceCriteria());
> 
> /// \brief Estimates the 4x4 rigid transformation T from source to target.
> ```

Change the return from the transformation matrix to `OdometryResult`. Also for the rest of this file.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 162 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS8oBH76AQpoMU45PG:-MZS8oBH76AQpoMU45PH:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L162)):*
> ```objc
> /// source to target.
> /// \param depth_outlier_trunc Depth difference threshold used to filter
> /// projective associations. \return (4, 4) optimized transformation matrix from
> ```

same.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 173 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS9KVF1Wa9aAuyo4BM:-MZS9KVF1Wa9aAuyo4BN:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L173)):*
> ```objc
>         float depth_huber_delta);
> 
> /// \brief Estimates the 4x4 rigid transformation T from source to target.
> ```

same.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 200 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS9Nza9j1dO6_Z70wb:-MZS9Nza9j1dO6_Z70wc:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L200)):*
> ```objc
> /// source to target.
> /// \param depth_outlier_trunc Depth difference threshold used to filter
> /// projective associations. \return (4, 4) optimized transformation matrix from
> ```

same.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 214 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS9QlADQJtD-DSC_sw:-MZS9QlADQJtD-DSC_sx:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L214)):*
> ```objc
>                                     float intensity_huber_delta);
> 
> /// \brief Estimates the 4x4 rigid transformation T from source to target.
> ```

same.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 247 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS9TEY19msdk9EPdZM:-MZS9TEY19msdk9EPdZN:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L247)):*
> ```objc
> /// source to target.
> /// \param depth_outlier_trunc Depth difference threshold used to filter
> /// projective associations. \return (4, 4) optimized transformation matrix from
> ```

same.


<!-- Sent from Reviewable.io -->

2021-04-29 12:16 UTC, reyanshsolis requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3323)* status: all files reviewed, 20 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 249 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZSYQpD6inMml4CJOnQ:-MZSYQpD6inMml4CJOnR:b-i1su80) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L249)):*
> ```objc
> /// projective associations. \return (4, 4) optimized transformation matrix from
> /// source to target.
> OdometryResult ComputePoseHybrid(const core::Tensor& source_depth,
> ```

Is `source_depth`, `target_depth` same as `source_depth_map` and `target_depth_map` ? 
If so, may you please change the same in the function argument as well as in the docstring? 


<!-- Sent from Reviewable.io -->

2021-04-29 12:19 UTC, reyanshsolis requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3323)* status: all files reviewed, 21 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 261 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZSZB4c4GZvPpkPYuh4:-MZSZB4c4GZvPpkPYuh5:b-mwxqn9) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L261)):*
> ```objc
>                                  const core::Tensor& init_source_to_target,
>                                  float depth_outlier_trunc,
>                                  float depth_huber_delta,
> ```

docstring missing for `depth_huber_delta` and `intensity_huber_delta`, for `Hybrid` and `Intensity` and `PointToPlane`. 


<!-- Sent from Reviewable.io -->

2021-04-29 12:58 UTC, reyanshsolis requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3323)* status: all files reviewed, 21 unresolved discussions (waiting on @ssheorey and @theNded)

___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 261 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZSZB4c4GZvPpkPYuh4:-MZSh6_b-_X9nZq4DHIZ:b-irwbcj) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L261)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

docstring missing for `depth_huber_delta` and `intensity_huber_delta`, for `Hybrid` and `Intensity` and `PointToPlane`. 
</blockquote></details>

Oh, I guess, `OdometryLossParams` is to be passed in ~`ComputePose...`~ `ComputeOdometryResult...` functions. 


<!-- Sent from Reviewable.io -->

2021-04-29 20:48 UTC, theNded reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3323)* status: all files reviewed, 20 unresolved discussions (waiting on @reyanshsolis and @ssheorey)

___
*[cpp/open3d/t/geometry/Image.h, line 242 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZQsxl187Vgn2BDxKDW:-MZU5vuZBn4cTfbX2YnS:bj0826i) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/geometry/Image.h#L242)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

May we want to add the `\brief` and `\return` keywords, in docstring? 
Same for the rest of this PR.
</blockquote></details>

We can move these comments to the timage PR.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp, line 95 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZQumxL4IMvnqYUuQMm:-MZU5zWS3CBvRobchms8:bf2h2jb) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp#L95)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

So this is like `Robust Kernel: weight`?
Do we want to add a custom option later too, like in Legacy Registration, to pass any outlier rejection method / loss function? 
</blockquote></details>

Yes, this could be in a future PR.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryImpl.h, line 46 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZQwCAk18TUjhieTjbQ:-MZU6iRT5DpkhaaAku-n:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/kernel/RGBDOdometryImpl.h#L46)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

may we add `const` for `depth_outlier_trunc`, `depth_huber_delta` and `intensity_huber_delta` ? Same for rest of the PR.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobianImpl.h, line 47 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZQwi7x5Tu-b3BvMw-_:-MZU7eGu7xVbVs8XyVUz:b-rt43sr) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobianImpl.h#L47)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Later, we might want to expose this outside, and pass it inside as lambda? 
Maybe inside `t::pipeline::odometry`? [To enable users to define there own loss function]. 
</blockquote></details>

We would support options, but not user-defined functions. Lambda as an argument cannot be directly passed to CUDA kernels easily.
___
*[cpp/open3d/t/pipelines/kernel/TransformationConverter.h, line 58 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZQxKGLAcoT_H4Q0dti:-MZU7tqg2_vIfzd3Z9PS:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/kernel/TransformationConverter.h#L58)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

May I remove this, in my PR for registration update? I will also be using the other overloaded function.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 48 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZRhEvHA_4FkdE_N5Kb:-MZU7zFK3NLy79lsxs_6:bm7wna7) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L48)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Also, if you think it's better,
I would suggest adding `max_iterations` in `OdometryConvergenceCriteria` like `ICPConvergenceCriteria`, and remove the `iterations` parameter from the function.

Currently, the `RegistrationMultiScaleICP` looks like this:
```
/// \param source The source point cloud.
/// \param target The target point cloud.
/// \param voxel_sizes VectorDouble of voxel scales of type double.
/// \param criterias Vector of ICPConvergenceCriteria objects for each scale.
/// \param max_correspondence_distances VectorDouble of maximum correspondence
/// points-pair distances of type double, for each iteration. Must be of same
/// length as voxel_sizes and criterias.
/// \param init Initial transformation estimation of type Float64 on CPU.
/// \param estimation Estimation method.
RegistrationResult RegistrationMultiScaleICP(
        const geometry::PointCloud &source,
        const geometry::PointCloud &target,
        const std::vector<double> &voxel_sizes,
        const std::vector<ICPConvergenceCriteria> &criterias,
        const std::vector<double> &max_correspondence_distances,
        const core::Tensor &init = core::Tensor::Eye(4,
                                                     core::Dtype::Float64,
                                                     core::Device("CPU:0")),
        const TransformationEstimation &estimation =
                TransformationEstimationPointToPoint());
```
</blockquote></details>

This is chunky: {OdometryConvergeceCriteria(10), OdometryConvergenceCriteria(5), OdometryConvergenceCriteria(3)}.
I think users would prefer {10, 5, 3} when they play with iterations. They will less likely touch relative_rmse.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 85 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS1ttdEKCLcaJ32tKA:-MZU8cYW0bMYu4k2frY9:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L85)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

May we add `docstring` with `OdometryLossParams`?
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 119 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS8I-S8ax7S1SIMcOK:-MZU9z6x87XckXz-nFtT:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L119)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

please add Dtype to docstring for `intrinsics``init_source_to_target` `transformation`, also in rest of this file.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 134 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS6BwE4QYA6zgL0k3U:-MZUB0j_DPE94pQLIjQk:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L134)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Is this modified by the algorithm? 
If not can we make `depth_scale` and `depth_max` as `const`?
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 142 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS9HUnCjJvSQWmESqQ:-MZUELKRBSs0S3cwIW3H:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L142)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Change the return from the transformation matrix to `OdometryResult`. Also for the rest of this file.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 162 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZS8oBH76AQpoMU45PG:-MZUENw3EYHK-Qx09ALT:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L162)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

same.
</blockquote></details>

 [...]

2021-04-29 21:14 UTC, reyanshsolis requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3323)* status: 46 of 64 files reviewed, 13 unresolved discussions (waiting on @reyanshsolis, @ssheorey, and @theNded)

___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp, line 76 at r6](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZUQmK-Ch5fcs-D_J7p:-MZUQmK-Ch5fcs-D_J7q:blbtio4) ([raw file](https://github.com/intel-isl/open3d/blob/863c89dd8d60da954929da69fe0cf336aa3459ce/cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp#L76)):*
> ```cpp
>     core::Device::DeviceType device_type = device.GetType();
>     if (device_type == core::Device::DeviceType::CPU) {
>         ComputeOdometryResultPointToPlaneCPU(
> ```

This was for RegistrationICP. Please revert changes in this file.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 44 at r6](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZUQzv245aYoyV1F0Qu:-MZUQzv245aYoyV1F0Qv:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/863c89dd8d60da954929da69fe0cf336aa3459ce/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L44)):*
> ```cpp
> namespace kernel {
> 
> void ComputeOdometryResultPointToPlaneCPU(const float *source_points_ptr,
> ```

same.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu, line 37 at r6](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZUR1m-BO4rUKvgLI7U:-MZUR1m-BO4rUKvgLI7V:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/863c89dd8d60da954929da69fe0cf336aa3459ce/cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu#L37)):*
> ```Cuda
> namespace kernel {
> 
> void ComputeOdometryResultPointToPlaneCUDA(const float *source_points_ptr,
> ```

same.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformImpl.h, line 38 at r6](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZUR55W3R_9XiTiEgcN:-MZUR55W3R_9XiTiEgcO:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/863c89dd8d60da954929da69fe0cf336aa3459ce/cpp/open3d/t/pipelines/kernel/ComputeTransformImpl.h#L38)):*
> ```objc
> namespace kernel {
> 
> void ComputeOdometryResultPointToPlaneCPU(const float *source_points_ptr,
> ```

same.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformImpl.h, line 49 at r6](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZUR64B4eZd-dcGzAHp:-MZUR64B4eZd-dcGzAHq:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/863c89dd8d60da954929da69fe0cf336aa3459ce/cpp/open3d/t/pipelines/kernel/ComputeTransformImpl.h#L49)):*
> ```objc
> 
> #ifdef BUILD_CUDA_MODULE
> void ComputeOdometryResultPointToPlaneCUDA(
> ```

same.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 261 at r5](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZSZB4c4GZvPpkPYuh4:-MZUTQVV6FQ7n1NgLbU5:b-fpv7ry) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L261)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Would it be preferable to directly use `OdometryLossParams` instead of passing `depth_outlier_trunc`, `depth_huber_delta` and `intensity_huber_delta`, for `Hybrid` and `Intensity` and `PointToPlane` ?
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 45 at r6](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZURagX3OglhBjMVJ4z:-MZURagX3OglhBjMVJ5-:bubeenj) ([raw file](https://github.com/intel-isl/open3d/blob/863c89dd8d60da954929da69fe0cf336aa3459ce/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L45)):*
> ```objc
>     PointToPlane,  // Implemented and commented in
>                    // ComputeOdometryResultPointToPlane
>     Intensity,     // Implemented and commented in ComputePoseIntensity
> ```

*ComputeOdometryResult for `Intensity` and `Hybrid`.


<!-- Sent from Reviewable.io -->

2021-04-29 21:35 UTC, reyanshsolis approved these changes
LGTM after reverting `ComputeOdometry` in `Registration` back to `ComputePose`. 

> Reviewed 4 of 18 files at r6.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3323#-:-MZUYGYR59G8GYLjRGjN:b-pz538t)* status: 48 of 64 files reviewed, 12 unresolved discussions (waiting on @reyanshsolis, @ssheorey, and @theNded)

___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.h, line 44 at r6](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZUV5-c7Bc6WWDhAMS6:-MZUV5-c7Bc6WWDhAMS7:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/10d127ae444bb3c6332c8293094bb018b97d8a05/cpp/open3d/t/pipelines/kernel/ComputeTransform.h#L44)):*
> ```objc
> /// `/cpp/open3d/t/pipelines/registration/TransformationEstimation.h`].
> /// \return Pose [X Y Z alpha beta gamma], a shape {6} tensor of dtype Float32.
> core::Tensor ComputePosePointToPlane(
> ```

same.
___
*[cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp, line 132 at r6](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZUUy5CEpGsfjdqYzzH:-MZUUy5CEpGsfjdqYzzI:b-7jl271) ([raw file](https://github.com/intel-isl/open3d/blob/10d127ae444bb3c6332c8293094bb018b97d8a05/cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp#L132)):*
> ```cpp
>     // Get pose {6} of type Float64 from correspondences indexed source and
>     // target point cloud.
>     core::Tensor pose = pipelines::kernel::ComputePosePointToPlane(
> ```

same.


<!-- Sent from Reviewable.io -->

2021-05-03 06:25 UTC, ssheorey approved these changes
That speedup is pretty impressive!

Looks good to me. Some comments about adding more documentation to some of the classes and also to the examples.

Do we have Python bindings (perhaps in a separate PR)?

> Reviewed 1 of 53 files at r1, 2 of 48 files at r5, 6 of 18 files at r6, 10 of 14 files at r7.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3323#-:-MZkr2br3kPGUHiiEgz0:b-wxdq7e)* status: 60 of 64 files reviewed, 33 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.h, line 43 at r7](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZkgLeo-tQLQDSF6KTh:-MZkgLeo-tQLQDSF6KTi:b65jvq7) ([raw file](https://github.com/intel-isl/open3d/blob/c63480d7d9ce6d7303dc5d5667ea1e4715661f6b/cpp/open3d/t/pipelines/kernel/ComputeTransform.h#L43)):*
Define:
> ```
> alpha beta gamma
> ```
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp, line 103 at r7](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZkkB084dmfFXJL_LGA:-MZkkB084dmfFXJL_LGB:b-na58y) ([raw file](https://github.com/intel-isl/open3d/blob/c63480d7d9ce6d7303dc5d5667ea1e4715661f6b/cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp#L103)):*
> ```cpp
>     } else if (device.GetType() == core::Device::DeviceType::CUDA) {
> #ifdef BUILD_CUDA_MODULE
>         ComputeOdometryResultIntensityCUDA(
> ```

Can use `CUDA_CALL` macro to simplify this.
___
*[cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp, line 72 at r7](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZkkxFZ5sl2Oc4h2Q0r:-MZkkxFZ5sl2Oc4h2Q0s:bwzxyk9) ([raw file](https://github.com/intel-isl/open3d/blob/c63480d7d9ce6d7303dc5d5667ea1e4715661f6b/cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp#L72)):*
> ```cpp
>     std::vector<float> A_1x29(29, 0.0);
> 
> #ifdef _WIN32
> ```

Use `_MSC_VER` macro to check for MSVC. `_WIN32` will be defined even for GNU / Clang  toolchains (e.g. MinGW) on Windows which do have proper OpenMP support.
___
*[cpp/open3d/t/pipelines/kernel/TransformationConverter.h, line 46 at r7](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZkgzSt5wr48vfWjPD0:-MZkgzSt5wr48vfWjPD1:b-payhy6) ([raw file](https://github.com/intel-isl/open3d/blob/c63480d7d9ce6d7303dc5d5667ea1e4715661f6b/cpp/open3d/t/pipelines/kernel/TransformationConverter.h#L46)):*
> ```objc
> /// \brief Convert pose to the transformation matrix.
> ///
> /// \param pose Pose [alpha, beta, gamma, tx, ty, tz], a tensor of
> ```

Format of pose vector is inconsistent. In [cpp/open3d/t/pipelines/kernel/ComputeTransform.h:43](https://github.com/intel-isl/open3d/blob/c63480d7d9ce6d7303dc5d5667ea1e4715661f6b/cpp/open3d/t/pipelines/kernel/ComputeTransform.h#L43) it is [X, Y, Z, alpha, beta, gamma].
Also define [alpha, beta, gamma]. If they are Euler angles, specify convention used.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 55 at r7](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZkZMnN9ZDjEQNShOVO:-MZkZMnN9ZDjEQNShOVP:b-k65zff) ([raw file](https://github.com/intel-isl/open3d/blob/c63480d7d9ce6d7303dc5d5667ea1e4715661f6b/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L55)):*
> ```objc
>     ///
>     /// \param relative_rmse Relative rmse threshold where we stop iterations.
>     /// \param relative_fitness Relative fitness threshold where we stop
> ```

Can you define `relative_fitness`?
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 72 at r7](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZkZ0rrDE8IA2BOrpTU:-MZkZ0rrDE8IA2BOrpTV:b1tuj51) ([raw file](https://github.com/intel-isl/open3d/blob/c63480d7d9ce6d7303dc5d5667ea1e4715661f6b/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L72)):*
> ```
>     /// \brief Constructor for the odometry result.
>     ///
> ```
We can skip "obvious" comments to keep the documentation from getting unnecessarily verbose.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 97 at r7](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZkZZMxBrDdX-VxwDHi:-MZkZZMxBrDdX-VxwDHj:b63aofg) ([raw file](https://github.com/intel-isl/open3d/blob/c63480d7d9ce6d7303dc5d5667ea1e4715661f6b/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L97)):*
> ```
>     /// \brief Constructor for the odometry loss function.
>     ///
> ```
"Obvious". OK to skip.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 148 at r7](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZkbWL47Mpgm4ILk356:-MZkbWL47Mpgm4ILk357:bnjd61p) ([raw file](https://github.com/intel-isl/open3d/blob/c63480d7d9ce6d7303dc5d5667ea1e4715661f6b/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L148)):*
> ```objc
> /// \param method Method used to apply RGBD odometry.
> /// \param params Parameters used in loss function, including outlier rejection
> /// threshold and huber norm parameters.
> ```

**H**uber
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 178 at r7](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZkbuhP5cUjRPT5g7hR:-MZkbuhP5cUjRPT5g7hS:bo4447r) ([raw file](https://github.com/intel-isl/open3d/blob/c63480d7d9ce6d7303dc5d5667ea1e4715661f6b/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L178)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> /// \param source_vertex_map (H, W, 3) Float32 source vertex image obtained by
> /// CreateVertexMap before calling this function.
> /// \param target_vertex_map (H, W, 3) Float32 target vertex image obtained by
> /// CreateVertexMap before calling this function.
> /// \param target_normal_map (H, W, 3) Float32 target normal image obtained by
> ```
</details>

(H,W,3) -> (rows, cols, channels=3) for consistency.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 212 at r7](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZkcUufCL9NF_eF1vSO:-MZkcUufCL9NF_eF1vSP:bne7tvf) ([raw file](https://github.com/intel-isl/open3d/blob/c63480d7d9ce6d7303dc5d5667ea1e4715661f6b/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L212)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> /// \param source_depth (H, W, 1) Float32 source depth image obtained by
> /// PreprocessDepth before calling this function.
> /// \param target_depth (H, W, 1) Float32 target depth image obtained by
> /// PreprocessDepth before calling this function.
> /// \param source_intensity (H, W, 1) Float32 source intensity image obtained by
> /// RGBToGray before calling this function.
> ```
</details>

(H,W,1) -> (rows, cols, channels=1) for consistency.
___
*[cpp/open3d/t/pipelines/odometry/RGBDOdometry.h, line 270 at r7](https://reviewable.io/reviews/intel-isl/open3d/3323#-MZkd1h5Dh5vNK91ePZr:-MZkd1h5Dh5vNK91ePZs:b-cnjl8b) ([raw file](https://github.com/intel-isl/open3d/blob/c63480d7d9ce6d7303dc5d5667ea1e4715661f6b/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L270)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
> /// \param source_depth (H, W, 1) Float32 source depth image obtained by
> /// PreprocessDepth before calling this function.
> /// \param target_depth (H, W, 1) Float32 target depth image obtained by
> /// PreprocessDepth before calling this function.
> /// \param source_intensity (H, W, 1) Float32 source intensity image obtained by
> /// RGBToGray before calling this function.
> /// \param target_intensity (H, W, 1) Float32 target intensity image obtained by
> /// RGBToGray before calling this function.
> /// \param source_depth_dx (H, W, 1) Float32 source depth gradient image
> /// at x-axis obtained by FilterSobel before calling this function.
> /// \param source_depth_dy (H, W, 1) Float32 source depth gradient image
> /// at y-axis obtained by FilterSobel before calling this function.
> /// \param source_intensity_dx (H, W, 1) Float32 source intensity gradient image
> /// at x-axis obtained by FilterSobel before calling this function.
> /// \param source_intensity_dy (H, W, 1) Float32 source intensity gradient image
> /// at y-axis obtained by FilterSobel before calling this function.
> /// \param target_v [...]

2021-05-03 07:16 UTC, reyanshsolis commented
@ssheorey I have added the pybinds in a separate PR #3359.

2021-05-06 00:05 UTC, merged