[WebRTC] WebRTC library build scripts
intel-isl/Open3D pull request #3349
Opened 2021-04-27 23:23 UTC by yxlao

- By default, we download the pre-compiled WebRTC binary.
- `3rdparty/webrtc/Dockerfile.webrtc` is used for building the binary release.

2021-04-28 11:27 UTC, stotko reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3349)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @ssheorey and @yxlao)

___
*[CMakeLists.txt, line 12 at r2](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZNCToK4gJrpTHQBbeM:-MZNCToK4gJrpTHQBbeN:btfgr72) ([raw file](https://github.com/intel-isl/open3d/blob/ab05a95ae0d19f24d3956271f732d40f38fc0ca1/CMakeLists.txt#L12)):*
> ```CMake
>     "Minimum OS X deployment version" FORCE)
> endif()
> set(CMAKE_CXX_STANDARD 14)
> ```

Is that needed? It sets the C++ standard for this directory (and all subdirectories) to C++14 in a non-transitive way. However, the standard is also set on a per-target basis in `open3d_set_global_properties` which is a public and transitive property, and the modern way to define this requirement.


<!-- Sent from Reviewable.io -->

2021-04-28 16:55 UTC, yxlao reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3349)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @ssheorey and @stotko)

___
*[CMakeLists.txt, line 12 at r2](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZNCToK4gJrpTHQBbeM:-MZOP3uRBgRcgCe8vPhN:b-8d4tc6) ([raw file](https://github.com/intel-isl/open3d/blob/ab05a95ae0d19f24d3956271f732d40f38fc0ca1/CMakeLists.txt#L12)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Is that needed? It sets the C++ standard for this directory (and all subdirectories) to C++14 in a non-transitive way. However, the standard is also set on a per-target basis in `open3d_set_global_properties` which is a public and transitive property, and the modern way to define this requirement.
</blockquote></details>

good point, removed


<!-- Sent from Reviewable.io -->

2021-04-28 18:58 UTC, ssheorey requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3349)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @stotko and @yxlao)

___
*[CMakeLists.txt, line 13 at r3](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZOi49O4MHRw4LrCt4O:-MZOi49O4MHRw4LrCt4P:boy60aq) ([raw file](https://github.com/intel-isl/open3d/blob/f0ed1e245b8ca885212cb3ffb6a773d04379ad92/CMakeLists.txt#L13)):*
> ```CMake
> endif()
> 
> if(UNIX AND NOT APPLE)
> ```

Can we replace this check with
`if(CMAKE_SYSTEM_NAME STREQUAL "Linux")` for clarity?
Also, we can define `set(LINUX TRUE CACHE BOOL "")` for future use. This may be better addressed in a separate PR, though.
___
*[CMakeLists.txt, line 16 at r3](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZOh12Z5U2Ioy7MOWnO:-MZOh12Z5U2Ioy7MOWnP:b-2f90vc) ([raw file](https://github.com/intel-isl/open3d/blob/f0ed1e245b8ca885212cb3ffb6a773d04379ad92/CMakeLists.txt#L16)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     execute_process(COMMAND uname -p
>         OUTPUT_VARIABLE PROCESSOR_ARCH
>         OUTPUT_STRIP_TRAILING_WHITESPACE
>     )
> ```
</details>

Is this needed? `CMAKE_HOST_SYSTEM_PROCESSOR` provides this information, as used below.
___
*[CMakeLists.txt, line 48 at r3](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZOk_Z46CoY6B8HW9Ic:-MZOk_Z46CoY6B8HW9Id:b-1l9ne5) ([raw file](https://github.com/intel-isl/open3d/blob/f0ed1e245b8ca885212cb3ffb6a773d04379ad92/CMakeLists.txt#L48)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> if(UNIX AND NOT APPLE AND NOT LINUX_AARCH64)
>     option(BUILD_WEBRTC           "Build WebRTC visualizer"                  ON )
> else()
>     option(BUILD_WEBRTC           "Build WebRTC visualizer"                  OFF)
> endif()
> option(BUILD_JUPYTER_EXTENSION    "Build Jupyter, requires BUILD_WEBRTC=ON"  OFF)
> ```
</details>

`CMakeDependentOption` can simplify this. e.g.:
> `cmake_dependent_option(USE_FOO "Use Foo" ON
>                      "USE_BAR;NOT USE_ZOT" OFF)`
___
*[3rdparty/civetweb/civetweb.cmake, line 8 at r3](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZOlYBc4fXMlFB8H8AV:-MZOlYBc4fXMlFB8H8AW:b-i5wi3a) ([raw file](https://github.com/intel-isl/open3d/blob/f0ed1e245b8ca885212cb3ffb6a773d04379ad92/3rdparty/civetweb/civetweb.cmake#L8)):*
> ```
>     GIT_REPOSITORY https://github.com/civetweb/civetweb.git
>     GIT_TAG v1.14
>     GIT_SHALLOW ON
> ```
(Optional) Can we use the URL zip download method instead, since we are not patching this? That will let us cache this download. It's not too big though (3MB).
___
*[3rdparty/webrtc/webrtc_common.cmake, line 33 at r3](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZOo8lA-b_y7VgqTRFx:-MZOo8lA-b_y7VgqTRFy:b-edvkug) ([raw file](https://github.com/intel-isl/open3d/blob/f0ed1e245b8ca885212cb3ffb6a773d04379ad92/3rdparty/webrtc/webrtc_common.cmake#L33)):*
> ```
>     # Don't use libstdc++ (Clang), use libc++ (GNU)
>     # https://stackoverflow.com/a/47384787/1255535
> ```
Do you mean   `# Don't use libstdc++ (GNU), use libc++ (Clang)`?


<!-- Sent from Reviewable.io -->

2021-04-28 19:14 UTC, ssheorey requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3349)* status: 0 of 12 files reviewed, 7 unresolved discussions (waiting on @stotko and @yxlao)

___
*[3rdparty/webrtc/webrtc_common.cmake, line 1 at r3](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZOrI143stv0D9mRxeW:-MZOrI143stv0D9mRxeX:b-krfc81) ([raw file](https://github.com/intel-isl/open3d/blob/f0ed1e245b8ca885212cb3ffb6a773d04379ad92/3rdparty/webrtc/webrtc_common.cmake#L1)):*
> ```
> # Common configs for building WebRTC from source. Used in both native build
> # and building inside docker.
> ```
This may be a good place for setting security options for either the docker or native (with Open3D) builds of WebRTC. This is more important for WebRTC since networking is involved. Can we add these compiler options:

 ```
add_compile_definitions(_FORTIFY_SOURCE=2)     # Buffer overflow detection
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
```
clang:
```
    set(HARDENING_CFLAGS
        -fstack-protector               # Stack-based buffer overrun detection
        -Wformat -Wformat-security      # Format string vulnerability
        -O2
        CACHE STRING "Compiler flags for security hardening")
    set(HARDENING_LDFLAGS
        -fsanitize=safe-stack       # Stack execution protection
        -Wl,-z,relro,-z,now         # Data relocation protection
         -S                           # Strip debug symbols
        CACHE STRING "Linker flags for security hardening")
```
gcc:
```
    set(HARDENING_CFLAGS
        -fstack-protector-strong    # Stack-based buffer overrun detection
        -Wformat -Wformat-security  # Format string vulnerability
        -O2
        CACHE STRING "Compiler flags for security hardening")
    set(HARDENING_LDFLAGS
        -Wl,-z,noexecstack   # Stack execution protection
        -Wl,-z,relro,-z,now  # Data relocation protection
        -strip-debug   # Strip debug symbols
        CACHE STRING "Linker flags for security hardening")
```
We shouldn't need `-pie` since we are only building libraries, not executables.


<!-- Sent from Reviewable.io -->

2021-04-28 21:57 UTC, yxlao reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3349)* status: 0 of 12 files reviewed, 7 unresolved discussions (waiting on @ssheorey and @stotko)

___
*[CMakeLists.txt, line 12 at r2](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZNCToK4gJrpTHQBbeM:-MZPIWXR7NCG6LA16TlO:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/ab05a95ae0d19f24d3956271f732d40f38fc0ca1/CMakeLists.txt#L12)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

good point, removed
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 13 at r3](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZOi49O4MHRw4LrCt4O:-MZPSaG7Dezh16g3pQiM:bfkfakm) ([raw file](https://github.com/intel-isl/open3d/blob/f0ed1e245b8ca885212cb3ffb6a773d04379ad92/CMakeLists.txt#L13)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can we replace this check with
`if(CMAKE_SYSTEM_NAME STREQUAL "Linux")` for clarity?
Also, we can define `set(LINUX TRUE CACHE BOOL "")` for future use. This may be better addressed in a separate PR, though.
</blockquote></details>

Agreed. There are several other `UNIX AND NOT APPLE` in our cmakes. I'll create a new PR to address them together.
___
*[CMakeLists.txt, line 16 at r3](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZOh12Z5U2Ioy7MOWnO:-MZPIvXVCUDxBKZrGoDH:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f0ed1e245b8ca885212cb3ffb6a773d04379ad92/CMakeLists.txt#L16)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>     execute_process(COMMAND uname -p
>         OUTPUT_VARIABLE PROCESSOR_ARCH
>         OUTPUT_STRIP_TRAILING_WHITESPACE
>     )
> ```
Is this needed? `CMAKE_HOST_SYSTEM_PROCESSOR` provides this information, as used below.
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 48 at r3](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZOk_Z46CoY6B8HW9Ic:-MZPM2AW9bepC142HCNq:b-5hf4vl) ([raw file](https://github.com/intel-isl/open3d/blob/f0ed1e245b8ca885212cb3ffb6a773d04379ad92/CMakeLists.txt#L48)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> if(UNIX AND NOT APPLE AND NOT LINUX_AARCH64)
>     option(BUILD_WEBRTC           "Build WebRTC visualizer"                  ON )
> else()
>     option(BUILD_WEBRTC           "Build WebRTC visualizer"                  OFF)
> endif()
> option(BUILD_JUPYTER_EXTENSION    "Build Jupyter, requires BUILD_WEBRTC=ON"  OFF)
> ```
`CMakeDependentOption` can simplify this. e.g.:
> `cmake_dependent_option(USE_FOO "Use Foo" ON
>                      "USE_BAR;NOT USE_ZOT" OFF)`
</blockquote></details>

That's a good point. However, here even when `BUILD_WEBRTC=ON` we still want to set `BUILD_JUPYTER_EXTENSION=OFF` by default, since `BUILD_JUPYTER_EXTENSION` requires additional dependency like `npm` and `yarn`(installed by npm). So it will look something like this:

```
cmake_dependent_option(BUILD_JUPYTER_EXTENSION
    "Build Jupyter, requires BUILD_WEBRTC=ON" OFF
    "BUILD_WEBRTC" OFF)
```
So, we might want simply `option(BUILD_JUPYTER_EXTENSION   "..."  OFF)`.
___
*[3rdparty/civetweb/civetweb.cmake, line 8 at r3](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZOlYBc4fXMlFB8H8AV:-MZPPh-hAWWLkf24sDyp:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f0ed1e245b8ca885212cb3ffb6a773d04379ad92/3rdparty/civetweb/civetweb.cmake#L8)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>     GIT_REPOSITORY https://github.com/civetweb/civetweb.git
>     GIT_TAG v1.14
>     GIT_SHALLOW ON
> ```
(Optional) Can we use the URL zip download method instead, since we are not patching this? That will let us cache this download. It's not too big though (3MB).
</blockquote></details>

Done.
___
*[3rdparty/webrtc/webrtc_common.cmake, line 1 at r3](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZOrI143stv0D9mRxeW:-MZPSldl1FCe76lc9RtQ:b-63vp19) ([raw file](https://github.com/intel-isl/open3d/blob/f0ed1e245b8ca885212cb3ffb6a773d04379ad92/3rdparty/webrtc/webrtc_common.cmake#L1)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> # Common configs for building WebRTC from source. Used in both native build
> # and building inside docker.
> ```
This may be a good place for setting security options for either the docker or native (with Open3D) builds of WebRTC. This is more important for WebRTC since networking is involved. Can we add these compiler options:

 ```
add_compile_definitions(_FORTIFY_SOURCE=2)     # Buffer overflow detection
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
```
clang:
```
    set(HARDENING_CFLAGS
        -fstack-protector               # Stack-based buffer overrun detection
        -Wformat -Wformat-security      # Format string vulnerability
        -O2
        CACHE STRING "Compiler flags for security hardening")
    set(HARDENING_LDFLAGS
        -fsanitize=safe-stack       # Stack execution protection
        -Wl,-z,relro,-z,now         # Data relocation protection
         -S                           # Strip debug symbols
        CACHE STRING "Linker flags for security hardening")
```
gcc:
```
    set(HARDENING_CFLAGS
        -fstack-protector-strong    # Stack-based buffer overrun detection
        -Wformat -Wformat-security  # Format string vulnerability
        -O2
        CACHE STRING "Compiler flags for security hardening")
    set(HARDENING_LDFLAGS
        -Wl,-z,noexecstack   # Stack execution protection
        -Wl,-z,relro,-z,now  # Data relocation protection
        -strip-debug   # Strip debug symbols
        CACHE STRING "Linker flags for security hardening")
```
We shouldn't need `-pie` since we are only building libraries, not executables.

</blockquote></details>

WebRTC uses the `GN` build system, the `set(WEBRTC_ARGS` are setting the available options that they provide. We'll need to patch their build system (like how we patch the CXX11 ABI) to enable additional flags. I would suggest leaving it as future work since it requires changes in the WebRTC code.
___
*[3rdparty/webrtc/webrtc_common.cmake, line 33 at r3](https://reviewable.io/reviews/intel-isl/open3d/3349#-MZOo8lA-b_y7VgqTRFx:-MZPRt_fD6poonKtH3Nc:b-mr68ul) ([raw file](https://github.com/intel-isl/open3d/blob/f0ed1e245b8ca885212cb3ffb6a773d04379ad92/3rdparty/webrtc/webrtc_common.cmake#L33)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>     # Don't use libstdc++ (Clang), use libc++ (GNU)
>     # https://stackoverflow.com/a/47384787/1255535
> ```
Do you mean   `# Don't use libstdc++ (GNU), use libc++ (Clang)`?
</blockquote></details>

Yes, corrected


<!-- Sent from Reviewable.io -->

2021-05-04 23:25 UTC, ssheorey approved these changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3349)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @stotko)



<!-- Sent from Reviewable.io -->

2021-05-04 23:28 UTC, merged