RGBD Odometry Pybinds
intel-isl/Open3D pull request #3359
Opened 2021-04-29 14:41 UTC by reyanshsolis

## Testing.

2021-05-04 00:41 UTC, ssheorey requested changes
> Reviewed 1 of 54 files at r2, 2 of 48 files at r3, 7 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3359)* status: 10 of 67 files reviewed, 11 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[cpp/pybind/t/geometry/tsdf_voxelgrid.cpp, line 36 at r3](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZobspI67VsTVxrK2Xo:-MZobspI67VsTVxrK2Xp:b-uyts1t) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/pybind/t/geometry/tsdf_voxelgrid.cpp#L36)):*
> ```cpp
> namespace t {
> namespace geometry {
> ```

Add documentation (ReST format) for pybinds (including for arguments). Ensure documentation is equivalent to C++. 
___
*[cpp/pybind/t/geometry/tsdf_voxelgrid.cpp, line 81 at r3](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZohTlJAOXMFa-sjWUz:-MZohTlJAOXMFa-sjWV-:bfhr5fo) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/pybind/t/geometry/tsdf_voxelgrid.cpp#L81)):*
> ```cpp
>             "depth_scale"_a, "depth_max"_a);
> 
>     // TODO(wei): expose mask code as a python class
> ```

Is this done already? I can see the docs.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 47 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZoit6kCFvNfzgdiGQU:-MZoit6kCFvNfzgdiGQV:b-g921p1) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L47)):*
> ```cpp
>     py::class_<OdometryConvergenceCriteria> odometry_convergence_criteria(
>             m, "OdometryConvergenceCriteria",
>             "Class that defines the convergence criteria of odometry. "
> ```

~~Class that defines the~~ convergence criteria of odometry.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 74 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZoia9M6S26E_G7juXD:-MZoia9M6S26E_G7juXE:bbt825h) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L74)):*
> ```cpp
>                         "with max_iteration={:d}, relative_rmse={:e}, "
>                         "relative_fitness={:e}.",
>                         c.max_iteration_, c.relative_rmse_,
> ```

Shorten: 
`"ICPConvergenceCriteria[max_iteration={:d}, relative_rmse={:e}, relative_fitness={:e}."]`
Similarly for other `__repr__` output.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 109 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZokQNN8eUYVlVZxkrT:-MZokQNN8eUYVlVZxkrU:bqayyly) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L109)):*
> ```cpp
>     py::class_<OdometryLossParams> odometry_loss_params(
>             m, "OdometryLossParams",
>             "Class that contains the odometry loss parameters.");
> ```

~~Class that contains~~ the odometry loss parameters
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 161 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZoknJN8ROnTUgX7wvL:-MZoknJN8ROnTUgX7wvM:btprpnf) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L161)):*
> ```
>                  "(H, W, 1) Float32 source depth image obtained by "
> ```
switch to (rows,cols, channels=1) here and similarly below.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 164 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZol2aD3u4OMcSQjZgg:-MZol2aD3u4OMcSQjZgh:b669p8s) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L164)):*
> ```
> depth gradient image at x-axis
> ```
at -> along the 
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 208 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZolIV272gmFyf7BUBo:-MZolIV272gmFyf7BUBp:b-baz9l5) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L208)):*
> ```cpp
>                                                         core::Device("CPU:0")),
>           "depth_scale"_a = 1000.0f, "depth_max"_a = 3.0f,
>           "criterias"_a = std::vector<OdometryConvergenceCriteria>({10, 5, 3}),
> ```

criterias -> criteria is plural
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 221 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZolZXa3y-HGSvv_1t0:-MZolZXa3y-HGSvv_1t1:bkfpqp7) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L221)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>           "[(V_p - V_q)^T N_p]^2, where "
>           "V_p  denotes the vertex at pixel p in the source, "
>           "V_q  denotes the vertex at pixel q in the target, "
>           "N_p  denotes the normal at pixel p in the source. "
>           "q is obtained by transforming p with init_source_to_target then "
> ```
</details>

Use `:math:` ReST markup.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 237 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZoljxo5OhihY_iWF1V:-MZoljxo5OhihY_iWF1W:b-ezyl6u) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L237)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>           "(I_p - I_q)^2, where "
>           "I_p  denotes the intensity at pixel p in the source, "
>           "I_q  denotes the intensity at pixel q in the target. "
>           "q is obtained by transforming p with init_source_to_target then "
>           "projecting with intrinsics. "
> ```
</details>

Use `:math:` ReST markup.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 256 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZolnki5oUCjoCoWCfN:-MZolnki5oUCjoCoWCfO:b5m8crs) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L256)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>           "(I_p - I_q)^2 + lambda(D_p - (D_q)')^2, where "
>           "I_p  denotes the intensity at pixel p in the source, "
>           "I_q  denotes the intensity at pixel q in the target. "
>           "D_p  denotes the depth pixel p in the source, "
>           "D_q  denotes the depth pixel q in the target. "
>           "q is obtained by transforming p with init_source_to_target then "
> ```
</details>

Use `:math:` ReST markup.


<!-- Sent from Reviewable.io -->

2021-05-06 04:00 UTC, theNded approved these changes
Reviewable keeps asking me to review 150+ files so use GitHub default...
After minor document changes are resolved we can merge.

2021-05-06 11:18 UTC, reyanshsolis commented on cpp/open3d/t/pipelines/odometry/RGBDOdometry.h
> +/// \param target_depth_dx (rows, cols, channels=1) Float32 target depth
@theNded The `source_*` and `target_*` might have been interchanged in this file. I found them to be opposite in `.cpp`, may you please verify this in the new changes, if they are fixed?

2021-05-06 11:21 UTC, reyanshsolis commented on cpp/pybind/t/pipelines/odometry/odometry.cpp
> +          "Loss function: :math: `[(V_p - V_q)^T N_p]^2`, where "
@ssheorey I tried, but it doesn't seem to work. May you please help me with this. 
I referred to the legacy `odometry` and `trainglemesh` pybinds, but it is still not fixed.

2021-05-06 11:21 UTC, reyanshsolis commented on cpp/open3d/t/pipelines/registration/Registration.h
> +/// Float64 on CPU. \param estimation Estimation method.
Done.

2021-05-06 11:21 UTC, reyanshsolis commented on cpp/open3d/t/pipelines/registration/Registration.h
> +/// Float64 on CPU. \param estimation Estimation method. \param criteria
Done.

2021-05-06 11:21 UTC, reyanshsolis commented on cpp/pybind/t/pipelines/odometry/odometry.cpp
> +                 "(H, W, 1) Float32 source depth image obtained by "
Done.

2021-05-06 11:22 UTC, reyanshsolis commented on cpp/pybind/t/pipelines/odometry/odometry.cpp
> +          "[(V_p - V_q)^T N_p]^2, where "
I found some `:math:` references, but it is still not working as expected. Will try to fix it soon.

2021-05-06 11:24 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3359)* status: 7 of 67 files reviewed, 17 unresolved discussions (waiting on @reyanshsolis, @ssheorey, @theNded, and @yxlao)

___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 47 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZoit6kCFvNfzgdiGQU:-M_0PrHP2OY3VEeEt3Wj:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L47)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

~~Class that defines the~~ convergence criteria of odometry.
</blockquote></details>

Done.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 74 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZoia9M6S26E_G7juXD:-M_0Ps0AC6XDq53a8ZB2:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L74)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Shorten: 
`"ICPConvergenceCriteria[max_iteration={:d}, relative_rmse={:e}, relative_fitness={:e}."]`
Similarly for other `__repr__` output.
</blockquote></details>

Done.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 109 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZokQNN8eUYVlVZxkrT:-M_0PsRi28GEwWRZHP3J:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L109)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

~~Class that contains~~ the odometry loss parameters
</blockquote></details>

Done.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 161 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZoknJN8ROnTUgX7wvL:-M_0Pt0w7dkBMKS6P-t7:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L161)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>                  "(H, W, 1) Float32 source depth image obtained by "
> ```
switch to (rows,cols, channels=1) here and similarly below.
</blockquote></details>

Done.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 164 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZol2aD3u4OMcSQjZgg:-M_0PtN3DgdLfvbeNXdo:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L164)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> depth gradient image at x-axis
> ```
at -> along the 
</blockquote></details>

Done.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 208 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZolIV272gmFyf7BUBo:-M_0PtzBD4nV2CEZGE1S:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L208)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

criterias -> criteria is plural
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-07 02:07 UTC, reyanshsolis commented on cpp/pybind/t/pipelines/odometry/odometry.cpp
> +          "Loss function: :math: `[(V_p - V_q)^T N_p]^2`, where "
Done.

2021-05-07 02:08 UTC, reyanshsolis commented on cpp/pybind/t/pipelines/odometry/odometry.cpp
> +          "[(V_p - V_q)^T N_p]^2, where "
Done.

2021-05-07 02:09 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3359)* status: 7 of 68 files reviewed, 16 unresolved discussions (waiting on @reyanshsolis, @ssheorey, @theNded, and @yxlao)

___
*[cpp/pybind/t/geometry/tsdf_voxelgrid.cpp, line 36 at r3](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZobspI67VsTVxrK2Xo:-M_3_QbS9HIhmrj0diPw:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/pybind/t/geometry/tsdf_voxelgrid.cpp#L36)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add documentation (ReST format) for pybinds (including for arguments). Ensure documentation is equivalent to C++. 
</blockquote></details>

Done.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 221 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZolZXa3y-HGSvv_1t0:-M_3_W9mC3SZUp_RpZzE:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L221)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>           "[(V_p - V_q)^T N_p]^2, where "
>           "V_p  denotes the vertex at pixel p in the source, "
>           "V_q  denotes the vertex at pixel q in the target, "
>           "N_p  denotes the normal at pixel p in the source. "
>           "q is obtained by transforming p with init_source_to_target then "
> ```
Use `:math:` ReST markup.
</blockquote></details>

Done.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 237 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZoljxo5OhihY_iWF1V:-M_3_Wmx-bJZjPGJ3l6R:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L237)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>           "(I_p - I_q)^2, where "
>           "I_p  denotes the intensity at pixel p in the source, "
>           "I_q  denotes the intensity at pixel q in the target. "
>           "q is obtained by transforming p with init_source_to_target then "
>           "projecting with intrinsics. "
> ```
Use `:math:` ReST markup.
</blockquote></details>

Done.
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 256 at r9](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZolnki5oUCjoCoWCfN:-M_3_XGOC-ZRe60sXUG0:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a458ddc8f3801e68ba2e28f00b6e16b73ee3689c/cpp/pybind/t/pipelines/odometry/odometry.cpp#L256)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>           "(I_p - I_q)^2 + lambda(D_p - (D_q)')^2, where "
>           "I_p  denotes the intensity at pixel p in the source, "
>           "I_q  denotes the intensity at pixel q in the target. "
>           "D_p  denotes the depth pixel p in the source, "
>           "D_q  denotes the depth pixel q in the target. "
>           "q is obtained by transforming p with init_source_to_target then "
> ```
Use `:math:` ReST markup.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-07 03:52 UTC, theNded approved these changes

2021-05-07 03:55 UTC, theNded approved these changes

2021-05-07 07:38 UTC, reyanshsolis commented on cpp/open3d/t/pipelines/odometry/RGBDOdometry.h
> +/// \param target_depth_dx (rows, cols, channels=1) Float32 target depth
Done.

2021-05-08 05:08 UTC, merged

2021-05-08 05:20 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3359)* status: 4 of 68 files reviewed, 8 unresolved discussions

___
*[cpp/pybind/t/geometry/tsdf_voxelgrid.cpp, line 36 at r3](https://reviewable.io/reviews/intel-isl/open3d/3359#-MZobspI67VsTVxrK2Xo:-M_9Ocbh3wdsuTDg-Ns9:b1by660) ([raw file](https://github.com/intel-isl/open3d/blob/91fb2cbee0b533138a82fe46a66caa4e6997c35c/cpp/pybind/t/geometry/tsdf_voxelgrid.cpp#L36)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Hey, sorry, I thought this file was part of this PR. But this file is missing Python docs, so we should add them in some PR.
</blockquote></details>

Sure, I will do that soon in some other PR. Sorry, I thought it was referring to Odometry `ReST` changes, so I marked it complete. 
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 54 at r14](https://reviewable.io/reviews/intel-isl/open3d/3359#-M_7dVICAtRvR82S_EAV:-M_9PZCW7tyqPmC7auPB:b-etnjrt) ([raw file](https://github.com/intel-isl/open3d/blob/43a6055cee4956a8cdeb296d1100516012de92b3/cpp/pybind/t/pipelines/odometry/odometry.cpp#L54)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> def(py::init
> ```
Add ClassMethodDocInject for `__init__` functions of all classes.
</blockquote></details>

Sorry, I missed the comment before merging, I will add it along with one of my other PR. 
___
*[cpp/pybind/t/pipelines/odometry/odometry.cpp, line 194 at r14](https://reviewable.io/reviews/intel-isl/open3d/3359#-M_7dkDWBjdIjSYa0rdv:-M_9P12_3p1Yo01UkrVA:bnt6dhh) ([raw file](https://github.com/intel-isl/open3d/blob/43a6055cee4956a8cdeb296d1100516012de92b3/cpp/pybind/t/pipelines/odometry/odometry.cpp#L194)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can we release GIL here (and in other odometry methods) to enable Python multithreading parallelism? This looks like a long running compute bound function. [Also @thended ] I don't believe we use any Python interpreter functionality inside.
</blockquote></details>

I am unfamiliar with GIL, it would be great, if you may share some references. I will try to apply that in `Odometry` and `Registration` as well in a separate PR.  


<!-- Sent from Reviewable.io -->