torch RaggedTensor class and batch support for SparseConv
intel-isl/Open3D pull request #3572
Opened 2021-06-11 14:45 UTC by sanskar107

Added a container for RaggedTensor for torch and enable batch support in `fixed_radius_search`, `SparseConv` and `SparseConvTranspose`.

2021-06-15 05:38 UTC, benjaminum requested changes
Seems like adding a python wrapper is the only way to workaround the limitations for now.

Can you add some simple python unit tests that test creation and backprop (maybe for addition of two ragged tensors)

> Reviewed 3 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3572#-:-McD6oaV4e0lsW--UNIZ:b-dx0cib)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @sanskar107)

___
*[cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.h, line 49 at r2](https://reviewable.io/reviews/intel-isl/open3d/3572#-McD1bV67b1JXnFVpGAQ:-McD1bV76C8wDaALf3uV:bpm255m) ([raw file](https://github.com/intel-isl/open3d/blob/7a1e2f02092a7a0e0a8662b3bbd2c1f867d8361a/cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.h#L49)):*
> ```objc
>     ///
>     /// The returned `RaggedTensor` corresponds with the python list defined by:
>     /// ```python
> ```

Does this work in doxygen or should it be```\code{.py} ... \endcode```
___
*[cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.cpp, line 33 at r2](https://reviewable.io/reviews/intel-isl/open3d/3572#-McD3EDDAlmmuFXEBuFz:-McD3EDDAlmmuFXEBuG-:brcc1n2) ([raw file](https://github.com/intel-isl/open3d/blob/7a1e2f02092a7a0e0a8662b3bbd2c1f867d8361a/cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.cpp#L33)):*
> ```cpp
> 
> c10::intrusive_ptr<RaggedTensor> RaggedTensor::FromRowSplits(
>         torch::Tensor values, torch::Tensor row_splits) const {
> ```

Tensorflow has a ```validate=True``` argument. Can we add this argument and skip the expensive "monotonically increasing" check for validate=False?


<!-- Sent from Reviewable.io -->

2021-06-17 10:54 UTC, sanskar107 reviewed
I've added python wrapper and unit tests.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3572#-:-McOaVX3-PNlBM5BhfNG:b-7172ir)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @benjaminum)

___
*[cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.h, line 49 at r2](https://reviewable.io/reviews/intel-isl/open3d/3572#-McD1bV67b1JXnFVpGAQ:-McOaavc6v3dim8PcFU5:b-ha5j47) ([raw file](https://github.com/intel-isl/open3d/blob/7a1e2f02092a7a0e0a8662b3bbd2c1f867d8361a/cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.h#L49)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Does this work in doxygen or should it be```\code{.py} ... \endcode```
</blockquote></details>

I took this format from our `core::Tensor` which seems to look fine in the C++ doxygen documentation.
___
*[cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.cpp, line 33 at r2](https://reviewable.io/reviews/intel-isl/open3d/3572#-McD3EDDAlmmuFXEBuFz:-McOao8dBiOODQZYtf4H:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7a1e2f02092a7a0e0a8662b3bbd2c1f867d8361a/cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.cpp#L33)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Tensorflow has a ```validate=True``` argument. Can we add this argument and skip the expensive "monotonically increasing" check for validate=False?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-18 09:27 UTC, benjaminum requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3572)* status: 1 of 11 files reviewed, 7 unresolved discussions (waiting on @benjaminum and @sanskar107)

___
*[cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.cpp, line 80 at r3](https://reviewable.io/reviews/intel-isl/open3d/3572#-McTL32e6RmiUsUA-d4h:-McTL32e6RmiUsUA-d4i:b-2ccyd1) ([raw file](https://github.com/intel-isl/open3d/blob/86c14125b0ae871ea2501f12d8c7c5a214739dd9/cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.cpp#L80)):*
> ```cpp
> }
> 
> c10::intrusive_ptr<RaggedTensor> RaggedTensor::Concat(
> ```

Do we use this function at the moment? It seems unfinished and is not exposed in python. We can deactivate it for now (throw unimplemented exception)
___
*[python/open3d/ml/torch/classes/ragged_tensor.py, line 182 at r3](https://reviewable.io/reviews/intel-isl/open3d/3572#-McTMXQm4w6Tx_nuBZVD:-McTMXQm4w6Tx_nuBZVE:b-b91gax) ([raw file](https://github.com/intel-isl/open3d/blob/86c14125b0ae871ea2501f12d8c7c5a214739dd9/python/open3d/ml/torch/classes/ragged_tensor.py#L182)):*
> ```Python
>         return self
> 
>     def __div__(self, other):
> ```

do we need __div__? I don't see it in the python3 docs
___
*[python/open3d/ml/torch/classes/ragged_tensor.py, line 189 at r3](https://reviewable.io/reviews/intel-isl/open3d/3572#-McTNGSpAjm2yyB--pwP:-McTNGSpAjm2yyB--pwQ:bvno60x) ([raw file](https://github.com/intel-isl/open3d/blob/86c14125b0ae871ea2501f12d8c7c5a214739dd9/python/open3d/ml/torch/classes/ragged_tensor.py#L189)):*
> ```Python
>         return self
> 
>     def __truediv__(self, other):
> ```

floordiv and truediv have the same implementation
___
*[python/open3d/ml/torch/python/layers/convolutions.py, line 756 at r3](https://reviewable.io/reviews/intel-isl/open3d/3572#-McTNVvN6WkgBw0DNQKd:-McTNVvN6WkgBw0DNQKe:b-u5htow) ([raw file](https://github.com/intel-isl/open3d/blob/86c14125b0ae871ea2501f12d8c7c5a214739dd9/python/open3d/ml/torch/python/layers/convolutions.py#L756)):*
> ```Python
> 
>         if out_positions_split is not None:
>             out_features = classes.RaggedTensor.from_row_splits(
> ```

we can make use of the shallow copy for torch
___
*[python/test/ml_ops/test_ragged_tensor.py, line 42 at r3](https://reviewable.io/reviews/intel-isl/open3d/3572#-McTPk9f3_yFV_C-eTOg:-McTPk9f3_yFV_C-eTOh:bb3bs1n) ([raw file](https://github.com/intel-isl/open3d/blob/86c14125b0ae871ea2501f12d8c7c5a214739dd9/python/test/ml_ops/test_ragged_tensor.py#L42)):*
> ```Python
> 
> # this op is only available for torch
> ```

Please add tests for the operators. Maybe copy and adapt from here
https://github.com/intel-isl/Open3D/blob/master/python/test/core/test_core.py#L347


<!-- Sent from Reviewable.io -->

2021-06-18 14:55 UTC, sanskar107 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3572)* status: 1 of 11 files reviewed, 7 unresolved discussions (waiting on @benjaminum)

___
*[cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.cpp, line 80 at r3](https://reviewable.io/reviews/intel-isl/open3d/3572#-McTL32e6RmiUsUA-d4h:-McUbO757LA4L8oY6Pu-:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/86c14125b0ae871ea2501f12d8c7c5a214739dd9/cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.cpp#L80)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Do we use this function at the moment? It seems unfinished and is not exposed in python. We can deactivate it for now (throw unimplemented exception)
</blockquote></details>

Done.
___
*[python/open3d/ml/torch/classes/ragged_tensor.py, line 182 at r3](https://reviewable.io/reviews/intel-isl/open3d/3572#-McTMXQm4w6Tx_nuBZVD:-McUbOy88zEt9pdaekHx:b-42azex) ([raw file](https://github.com/intel-isl/open3d/blob/86c14125b0ae871ea2501f12d8c7c5a214739dd9/python/open3d/ml/torch/classes/ragged_tensor.py#L182)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

do we need __div__? I don't see it in the python3 docs
</blockquote></details>

Removed `div` and `idiv`
___
*[python/open3d/ml/torch/classes/ragged_tensor.py, line 189 at r3](https://reviewable.io/reviews/intel-isl/open3d/3572#-McTNGSpAjm2yyB--pwP:-McUbTbk91Tb6_uxCWcw:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/86c14125b0ae871ea2501f12d8c7c5a214739dd9/python/open3d/ml/torch/classes/ragged_tensor.py#L189)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

floordiv and truediv have the same implementation
</blockquote></details>

Done.
___
*[python/open3d/ml/torch/python/layers/convolutions.py, line 756 at r3](https://reviewable.io/reviews/intel-isl/open3d/3572#-McTNVvN6WkgBw0DNQKd:-McUbUUiAgs-U9iCfBMn:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/86c14125b0ae871ea2501f12d8c7c5a214739dd9/python/open3d/ml/torch/python/layers/convolutions.py#L756)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

we can make use of the shallow copy for torch
</blockquote></details>

Done.
___
*[python/test/ml_ops/test_ragged_tensor.py, line 42 at r3](https://reviewable.io/reviews/intel-isl/open3d/3572#-McTPk9f3_yFV_C-eTOg:-McUbV536YwuVhDDJlEF:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/86c14125b0ae871ea2501f12d8c7c5a214739dd9/python/test/ml_ops/test_ragged_tensor.py#L42)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Please add tests for the operators. Maybe copy and adapt from here
https://github.com/intel-isl/Open3D/blob/master/python/test/core/test_core.py#L347

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-20 06:51 UTC, benjaminum requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3572)* status: 1 of 11 files reviewed, 9 unresolved discussions (waiting on @benjaminum and @sanskar107)

___
*[cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.h, line 85 at r4](https://reviewable.io/reviews/intel-isl/open3d/3572#-Mcc9JtoDNBNdD4ZEe36:-Mcc9JtoDNBNdD4ZEe37:b-mxb4fd) ([raw file](https://github.com/intel-isl/open3d/blob/a6d675ccdea57fb850f34de1c6a223e501ce259e/cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.h#L85)):*
> ```objc
> 
>     template <typename T>
>     c10::intrusive_ptr<RaggedTensor> Add(T value) const {
> ```

If both operand are ragged tensors the element-wise operations will work even for incompatible  tensors. For instance `[ [1], [2,3] ] + [ [1,2], [3] ] = [ [2], [4,6] ]` will work but should throw an exception.
Seems like we need a specialized function for RaggedTensor args.
___
*[python/test/ml_ops/test_ragged_tensor.py, line 43 at r4](https://reviewable.io/reviews/intel-isl/open3d/3572#-MccAeWA5VPkUo9Gl_AC:-MccAeWA5VPkUo9Gl_AD:b-pi9qd3) ([raw file](https://github.com/intel-isl/open3d/blob/a6d675ccdea57fb850f34de1c6a223e501ce259e/python/test/ml_ops/test_ragged_tensor.py#L43)):*
> ```Python
> # this op is only available for torch
> ```

Please add tests checking some failure cases with incompatible tensors.


<!-- Sent from Reviewable.io -->

2021-06-22 08:41 UTC, sanskar107 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3572)* status: 1 of 11 files reviewed, 9 unresolved discussions (waiting on @benjaminum)

___
*[cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.h, line 85 at r4](https://reviewable.io/reviews/intel-isl/open3d/3572#-Mcc9JtoDNBNdD4ZEe36:-McmqhKoDCu-6M7Cy_rO:b-ag11jm) ([raw file](https://github.com/intel-isl/open3d/blob/a6d675ccdea57fb850f34de1c6a223e501ce259e/cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.h#L85)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

If both operand are ragged tensors the element-wise operations will work even for incompatible  tensors. For instance `[ [1], [2,3] ] + [ [1,2], [3] ] = [ [2], [4,6] ]` will work but should throw an exception.
Seems like we need a specialized function for RaggedTensor args.

</blockquote></details>

I meant to add these binary ops only for `torch::Tensor` and Scalar values in C++ API and add support for RaggedTensor through Python wrapper. I've added shape checking for incompatible RaggedTensors in python wrapper. We can add everything in C++ API once we migrate to torch 1.9.
___
*[python/test/ml_ops/test_ragged_tensor.py, line 43 at r4](https://reviewable.io/reviews/intel-isl/open3d/3572#-MccAeWA5VPkUo9Gl_AC:-McmsQp98VU46VhtDQW8:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/a6d675ccdea57fb850f34de1c6a223e501ce259e/python/test/ml_ops/test_ragged_tensor.py#L43)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Please add tests checking some failure cases with incompatible tensors.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-22 12:36 UTC, benjaminum requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3572)* status: 1 of 11 files reviewed, 11 unresolved discussions (waiting on @benjaminum and @sanskar107)

___
*[python/open3d/ml/torch/classes/ragged_tensor.py, line 196 at r5](https://reviewable.io/reviews/intel-isl/open3d/3572#-McnhtWx6KFISqX48-_3:-McnhtWx6KFISqX48-_4:b541c2c) ([raw file](https://github.com/intel-isl/open3d/blob/28035017ea49d52c152aad9ae7d359030112fbd0/python/open3d/ml/torch/classes/ragged_tensor.py#L196)):*
> ```Python
>         return self
> 
>     def convert_to_tensor(self, value):
> ```

Just a suggestion, maybe hide this function it seems to be meant for internal use.
___
*[python/open3d/ml/torch/classes/ragged_tensor.py, line 208 at r5](https://reviewable.io/reviews/intel-isl/open3d/3572#-Mcni0KnAysTIxwxt0qh:-Mcni0KnAysTIxwxt0qi:b-9rzjo8) ([raw file](https://github.com/intel-isl/open3d/blob/28035017ea49d52c152aad9ae7d359030112fbd0/python/open3d/ml/torch/classes/ragged_tensor.py#L208)):*
> ```Python
>             return value
>         elif isinstance(value, (int, float, bool)):
>             return torch.full(self.values.shape, value)
> ```

Is there no broadcasting on the cpp side?


<!-- Sent from Reviewable.io -->

2021-06-22 13:08 UTC, sanskar107 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3572)* status: 1 of 11 files reviewed, 11 unresolved discussions (waiting on @benjaminum)

___
*[python/open3d/ml/torch/classes/ragged_tensor.py, line 196 at r5](https://reviewable.io/reviews/intel-isl/open3d/3572#-McnhtWx6KFISqX48-_3:-McnpOS09YKe8yeL3fO0:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/28035017ea49d52c152aad9ae7d359030112fbd0/python/open3d/ml/torch/classes/ragged_tensor.py#L196)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Just a suggestion, maybe hide this function it seems to be meant for internal use.
</blockquote></details>

Done.
___
*[python/open3d/ml/torch/classes/ragged_tensor.py, line 208 at r5](https://reviewable.io/reviews/intel-isl/open3d/3572#-Mcni0KnAysTIxwxt0qh:-McnpP3UDeSSpUwcMwWQ:bnlp9wa) ([raw file](https://github.com/intel-isl/open3d/blob/28035017ea49d52c152aad9ae7d359030112fbd0/python/open3d/ml/torch/classes/ragged_tensor.py#L208)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Is there no broadcasting on the cpp side?
</blockquote></details>

Yes, there is. Modified it.


<!-- Sent from Reviewable.io -->

2021-06-22 13:34 UTC, benjaminum approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3572#-:-McnvT6G2SFulOaLRejt:bnfp4nl)* status: 1 of 11 files reviewed, 11 unresolved discussions (waiting on @benjaminum)



<!-- Sent from Reviewable.io -->

2021-07-01 05:35 UTC, yxlao commented on cpp/open3d/ml/pytorch/CMakeLists.txt
> +ragged_tensor/RaggedTensor.cpp)
indentation

2021-07-01 05:38 UTC, yxlao commented on cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.h
> +#include "torch/custom_class.h"
`<>` for 3rd-party headers

2021-07-08 12:53 UTC, sanskar107 commented on cpp/open3d/ml/pytorch/CMakeLists.txt
> +ragged_tensor/RaggedTensor.cpp)
Done

2021-07-08 12:53 UTC, sanskar107 commented on cpp/open3d/ml/pytorch/ragged_tensor/RaggedTensor.h
> +#include "torch/custom_class.h"
Done

2021-07-22 11:20 UTC, merged