Exposed NeighbourCounts as return from HybridSearch
intel-isl/Open3D pull request #3588
Opened 2021-06-15 17:57 UTC by reyanshsolis

2021-06-22 07:20 UTC, yxlao requested changes
> Reviewed 9 of 15 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3588)* status: 16 of 17 files reviewed, 4 unresolved discussions (waiting on @junha-l, @reyanshsolis, and @yxlao)

___
*[cpp/open3d/core/nns/FaissIndex.h, line 92 at r2](https://reviewable.io/reviews/intel-isl/open3d/3588#-Mcm_-hE4O4KhNgQvXxd:-Mcm_-hE4O4KhNgQvXxe:b-b09qbs) ([raw file](https://github.com/intel-isl/open3d/blob/43de9a85e9337f1fbf5ce5958c03b1aca8d42c79/cpp/open3d/core/nns/FaissIndex.h#L92)):*
> ```objc
>     /// - distances: Tensor of shape {total_num_neighbors,}, same dtype with
>     /// dataset_points.
>     /// - num_neighbors: Tensor of shape {n,}, dtype Int64.
> ```

Here it is called `num_neighbors`. It is called `neighbour_counts` in other locations. Could we standardized them to `num_neighbors` in both code and comments?
___
*[cpp/open3d/core/nns/FaissIndex.cpp, line 152 at r2](https://reviewable.io/reviews/intel-isl/open3d/3588#-McmZ5eN8Q3zwI5ALJ7j:-McmZ5eOCa45FdJXG_Xv:b-m7l89z) ([raw file](https://github.com/intel-isl/open3d/blob/43de9a85e9337f1fbf5ce5958c03b1aca8d42c79/cpp/open3d/core/nns/FaissIndex.cpp#L152)):*
> ```cpp
> 
>     Tensor neighbour_counts =
>             invalid.To(core::Dtype::Int64).Sum({0}).Neg().Add(max_knn);
> ```

This should work:`max_knn - invalid.To(core::Dtype::Int64).Sum({0})`, since we've overloaded the operator. We can save one operation.
___
*[cpp/open3d/core/nns/FaissIndex.cpp, line 162 at r2](https://reviewable.io/reviews/intel-isl/open3d/3588#-McmZPHd4kO1UfIxZgOi:-McmZPHd4kO1UfIxZgOj:b6heewl) ([raw file](https://github.com/intel-isl/open3d/blob/43de9a85e9337f1fbf5ce5958c03b1aca8d42c79/cpp/open3d/core/nns/FaissIndex.cpp#L162)):*
> ```cpp
>     distances.SetItem(TensorKey::IndexTensor(invalid), invalid_distances);
> 
>     return std::make_tuple(indices, distances, neighbour_counts);
> ```

Future work: we can have a PR to standardize the spellings, e.g. for `neighbor(u)r` and `optimiz(s)ation`. It is fine for now.
___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 126 at r2](https://reviewable.io/reviews/intel-isl/open3d/3588#-Mcm_XqR3paExxkvCeQC:-Mcm_XqR3paExxkvCeQD:bydq41r) ([raw file](https://github.com/intel-isl/open3d/blob/43de9a85e9337f1fbf5ce5958c03b1aca8d42c79/cpp/open3d/core/nns/FixedRadiusIndex.h#L126)):*
> ```objc
> 
>     void AllocCounts(int64_t** ptr, size_t num) {
>         distances_ = Tensor::Empty({int64_t(num)}, Dtype::Int64, device_);
> ```

it's called `AllocConunts`, why are we writing to `distances_`?


<!-- Sent from Reviewable.io -->

2021-06-22 08:14 UTC, benjaminum reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3588)* status: 16 of 17 files reviewed, 4 unresolved discussions (waiting on @junha-l, @reyanshsolis, and @yxlao)

___
*[cpp/open3d/core/nns/FaissIndex.h, line 92 at r2](https://reviewable.io/reviews/intel-isl/open3d/3588#-Mcm_-hE4O4KhNgQvXxd:-McmkbFcCGDe-DA5Pxuk:b-ef0ibc) ([raw file](https://github.com/intel-isl/open3d/blob/43de9a85e9337f1fbf5ce5958c03b1aca8d42c79/cpp/open3d/core/nns/FaissIndex.h#L92)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Here it is called `num_neighbors`. It is called `neighbour_counts` in other locations. Could we standardized them to `num_neighbors` in both code and comments?
</blockquote></details>

Just naming it `counts` would work for the docstrings too because everything is about the neighbors.
In the code I think `neighbors_count` makes sense because we have `neighbors_index`,  `neighbors_distance`, `neighbors_row_splits` in some other locations. 


<!-- Sent from Reviewable.io -->

2021-06-24 09:29 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3588)* status: 0 of 17 files reviewed, 4 unresolved discussions (waiting on @junha-l and @yxlao)

___
*[cpp/open3d/core/nns/FaissIndex.h, line 92 at r2](https://reviewable.io/reviews/intel-isl/open3d/3588#-Mcm_-hE4O4KhNgQvXxd:-McxLMYY-mKBoyGkVccQ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/43de9a85e9337f1fbf5ce5958c03b1aca8d42c79/cpp/open3d/core/nns/FaissIndex.h#L92)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Just naming it `counts` would work for the docstrings too because everything is about the neighbors.
In the code I think `neighbors_count` makes sense because we have `neighbors_index`,  `neighbors_distance`, `neighbors_row_splits` in some other locations. 
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/FaissIndex.cpp, line 152 at r2](https://reviewable.io/reviews/intel-isl/open3d/3588#-McmZ5eN8Q3zwI5ALJ7j:-McxLNMn-61DDASWz2qj:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/43de9a85e9337f1fbf5ce5958c03b1aca8d42c79/cpp/open3d/core/nns/FaissIndex.cpp#L152)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

This should work:`max_knn - invalid.To(core::Dtype::Int64).Sum({0})`, since we've overloaded the operator. We can save one operation.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/FaissIndex.cpp, line 162 at r2](https://reviewable.io/reviews/intel-isl/open3d/3588#-McmZPHd4kO1UfIxZgOi:-McxLOA5AFyaL8vdtOP_:brfi6w5) ([raw file](https://github.com/intel-isl/open3d/blob/43de9a85e9337f1fbf5ce5958c03b1aca8d42c79/cpp/open3d/core/nns/FaissIndex.cpp#L162)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Future work: we can have a PR to standardize the spellings, e.g. for `neighbor(u)r` and `optimiz(s)ation`. It is fine for now.
</blockquote></details>

Sure, I will do that. 
___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 126 at r2](https://reviewable.io/reviews/intel-isl/open3d/3588#-Mcm_XqR3paExxkvCeQC:-McxLSeACPZrRt55fcPB:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/43de9a85e9337f1fbf5ce5958c03b1aca8d42c79/cpp/open3d/core/nns/FixedRadiusIndex.h#L126)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

it's called `AllocConunts`, why are we writing to `distances_`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-02 22:18 UTC, yxlao approved these changes

2021-07-02 22:18 UTC, merged