Introduce memory manager statistics
intel-isl/Open3D pull request #3639
Opened 2021-06-24 13:28 UTC by stotko

Features:
- Thread-safe `MemoryManagerStatistic` instance implemented as a singleton
- Per `Device` logging of memory allocations and frees
- Configurable print modes: `All`, `Unbalanced`, `None`
- Automatic print at the end of the program, defaults to `Unbalanced` to minimize noise

Detected memory leaks in unit tests:
- Skipped `Free` in LU decomposition when the operation fails

2021-06-24 14:33 UTC, theNded requested changes
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3639)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @stotko)

___
*[cpp/open3d/core/MemoryManager.cpp, line 42 at r1](https://reviewable.io/reviews/intel-isl/open3d/3639#-McyQsXSAAR6KtD-WIDu:-McyQsXSAAR6KtD-WIDv:b-he9fv5) ([raw file](https://github.com/intel-isl/open3d/blob/d3b21eb2541565fe7e0681bc7bef56d3ce3331e8/cpp/open3d/core/MemoryManager.cpp#L42)):*
> ```cpp
> 
> void* MemoryManager::Malloc(size_t byte_size, const Device& device) {
>     MemoryManagerStatistic::getInstance().IncrementCountMalloc(device);
> ```

Shall we count byte_size as well? That might be helpful for more advanced checks.
___
*[cpp/open3d/core/MemoryManagerStatistic.cpp, line 36 at r1](https://reviewable.io/reviews/intel-isl/open3d/3639#-McyQIe8AD6Ml3SQY2Um:-McyQIe8AD6Ml3SQY2Un:b-uhxqk5) ([raw file](https://github.com/intel-isl/open3d/blob/d3b21eb2541565fe7e0681bc7bef56d3ce3331e8/cpp/open3d/core/MemoryManagerStatistic.cpp#L36)):*
> ```cpp
> namespace core {
> 
> MemoryManagerStatistic& MemoryManagerStatistic::getInstance() {
> ```

Should we use `GetInstance` to keep consistency?


<!-- Sent from Reviewable.io -->

2021-06-24 15:54 UTC, stotko reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3639)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @theNded)

___
*[cpp/open3d/core/MemoryManager.cpp, line 42 at r1](https://reviewable.io/reviews/intel-isl/open3d/3639#-McyQsXSAAR6KtD-WIDu:-Mcyij-aCQHA68_qzcvZ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d3b21eb2541565fe7e0681bc7bef56d3ce3331e8/cpp/open3d/core/MemoryManager.cpp#L42)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Shall we count byte_size as well? That might be helpful for more advanced checks.
</blockquote></details>

Done.
___
*[cpp/open3d/core/MemoryManagerStatistic.cpp, line 36 at r1](https://reviewable.io/reviews/intel-isl/open3d/3639#-McyQIe8AD6Ml3SQY2Um:-McyikeU8W--9hEwD4Q6:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d3b21eb2541565fe7e0681bc7bef56d3ce3331e8/cpp/open3d/core/MemoryManagerStatistic.cpp#L36)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Should we use `GetInstance` to keep consistency?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-24 16:25 UTC, theNded approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3639)* status: all files reviewed, 2 unresolved discussions (waiting on @theNded)



<!-- Sent from Reviewable.io -->

2021-06-25 01:04 UTC, yxlao reviewed
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3639)* status: all files reviewed, 4 unresolved discussions (waiting on @stotko and @theNded)

___
*[cpp/open3d/core/MemoryManager.cpp, line 50 at r2](https://reviewable.io/reviews/intel-isl/open3d/3639#-Md-cp1B6uFJu5TxgnaM:-Md-cp1B6uFJu5TxgnaN:bgp36io) ([raw file](https://github.com/intel-isl/open3d/blob/37b0deb5ec0b91e9562520825e77bf349809898c/cpp/open3d/core/MemoryManager.cpp#L50)):*
> ```cpp
> void MemoryManager::Free(void* ptr, const Device& device) {
>     GetDeviceMemoryManager(device)->Free(ptr, device);
>     MemoryManagerStatistic::GetInstance().IncrementCountFree(device, ptr);
> ```

nit: shall we change the order to be consistent with `MemoryManager::Free(ptr, device)`?
i.e.
```cpp
// We have:
MemoryManager::Free(ptr, device);
// Change IncrementCountFree to:
IncrementCountFree(ptr, device);
```

Similarly for `IncrementCountMalloc`:

```cpp
// We have:
MemoryManager::Malloc(byte_size, device);
// Change IncrementCountMalloc to:
IncrementCountMalloc(ptr, byte_size, device);
```
___
*[cpp/open3d/core/MemoryManagerStatistic.h, line 76 at r2](https://reviewable.io/reviews/intel-isl/open3d/3639#-Md-eMXc5-wjPpSLJUa8:-Md-eMXc5-wjPpSLJUa9:baiy7cq) ([raw file](https://github.com/intel-isl/open3d/blob/37b0deb5ec0b91e9562520825e77bf349809898c/cpp/open3d/core/MemoryManagerStatistic.h#L76)):*
> ```objc
>     };
> 
>     struct DeviceComparator {
> ```

This could be useful on other occasions if we'd like to use `Device` as the key in a map/unordered_map.

Shall we consider moving this to the `Device` class itself? For the `unordered_map` version, this would look like:

```cpp
class Device {
public:
    struct Hash {
        std::size_t operator()(const open3d::core::Device& device) const {
            return std::hash<std::string>{}(device.ToString());
        }
    };
};
```

and, we can use the `unordered_map` as:
```cpp
static std::unordered_map<Device, MemoryStatistics, Device::Hash>;
```


<!-- Sent from Reviewable.io -->

2021-06-25 07:51 UTC, stotko reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3639)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/MemoryManager.cpp, line 50 at r2](https://reviewable.io/reviews/intel-isl/open3d/3639#-Md-cp1B6uFJu5TxgnaM:-Md18AyF1IingmHKLkMP:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/37b0deb5ec0b91e9562520825e77bf349809898c/cpp/open3d/core/MemoryManager.cpp#L50)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: shall we change the order to be consistent with `MemoryManager::Free(ptr, device)`?
i.e.
```cpp
// We have:
MemoryManager::Free(ptr, device);
// Change IncrementCountFree to:
IncrementCountFree(ptr, device);
```

Similarly for `IncrementCountMalloc`:

```cpp
// We have:
MemoryManager::Malloc(byte_size, device);
// Change IncrementCountMalloc to:
IncrementCountMalloc(ptr, byte_size, device);
```
</blockquote></details>

Done.
___
*[cpp/open3d/core/MemoryManagerStatistic.h, line 76 at r2](https://reviewable.io/reviews/intel-isl/open3d/3639#-Md-eMXc5-wjPpSLJUa8:-Md18Dgx47_GjBeHOyfT:bl2293) ([raw file](https://github.com/intel-isl/open3d/blob/37b0deb5ec0b91e9562520825e77bf349809898c/cpp/open3d/core/MemoryManagerStatistic.h#L76)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

This could be useful on other occasions if we'd like to use `Device` as the key in a map/unordered_map.

Shall we consider moving this to the `Device` class itself? For the `unordered_map` version, this would look like:

```cpp
class Device {
public:
    struct Hash {
        std::size_t operator()(const open3d::core::Device& device) const {
            return std::hash<std::string>{}(device.ToString());
        }
    };
};
```

and, we can use the `unordered_map` as:
```cpp
static std::unordered_map<Device, MemoryStatistics, Device::Hash>;
```
</blockquote></details>

Done. FYI I used `std::map<Device, MemoryStatistics>` to have a consistent ordering during `Print()`.


<!-- Sent from Reviewable.io -->

2021-06-25 09:35 UTC, merged