F64 and Robust Kernel Support in RegistrationICP
intel-isl/Open3D pull request #3690
Opened 2021-07-06 02:38 UTC by reyanshsolis

2021-07-13 11:01 UTC, stotko requested changes
> Reviewed 16 of 22 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3690)* status: all files reviewed, 20 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 57 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUPqD6Ae67or6IB4U4:-MeUPqD6Ae67or6IB4U5:b-pypdtr) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L57)):*
> ```objc
> 
> #define OPEN3D_ATOMIC_ADD(X, Y) atomicAdd(X, Y)
> #define OPEN3D_ABS(X) abs(X)
> ```

Could you comment on why these macros are needed? Would it be possible to use `abs` (without `std::` namespace qualification) instead? There are also floating-point overloads defined that are prefixed with `f`, i.e. `fabs`. Would that work here?

Otherwise, I would recommend to define a set of `OPEN3D_HOST_DEVICE` annotated functions for all of these macros (except `OPEN3D_ATOMIC_ADD`.
___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 74 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUQuxN4IP1m8kwIpXJ:-MeUQuxN4IP1m8kwIpXK:b-vvk1gd) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L74)):*
> ```objc
> 
> template <typename scalar_t>
> OPEN3D_HOST_DEVICE bool OPEN3D_IS_CLOSE(const scalar_t &X,
> ```

Put into `open3d` namespace and rename to `IsClose`, i.e. `OPEN3D_IS_CLOSE(...)` -> `open3d::IsClose(...)`. 
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.h, line 42 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeURPGP5_ZqFtPpJtnU:-MeURPGP5_ZqFtPpJtnV:bku9cq9) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransform.h#L42)):*
> ```objc
> /// \param target_points target points indexed according to correspondences.
> /// \param target_normals target normals indexed according to correspondences.
> /// \param correspondence_indices TODO.
> ```

Please add documentation for the `TODO` part.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.h, line 55 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeURT7G0Ke9oNEYsSj2:-MeURT7H4u2pXSMhnzed:b-q64pkt) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransform.h#L55)):*
> ```objc
> /// \param source_points source points indexed according to correspondences.
> /// \param target_points target points indexed according to correspondences.
> /// \param correspondence_indices TODO.
> ```

See above.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 47 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeURpuP2J-KcfWDCB8d:-MeURpuP2J-KcfWDCB8e:b-caklnn) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L47)):*
> ```cpp
> namespace kernel {
> 
> template <typename scalar_t, typename funct_t>
> ```

Perhaps `function_t` or `func_t`? `CPULauncher` etc. use the latter, so I would recommend that version.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 83 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUSRcI0WQo1teXi6b1:-MeUSRcI0WQo1teXi6b2:bxipqbi) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L83)):*
> ```cpp
> 
>                     scalar_t w = GetWeightFromRobustKernel(r);
>                     // printf(" residual: %f, weight: %f", (float)r, (float)w);
> ```

Is this a leftover from debugging? If it is not needed, then please remove that line.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 178 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTOmB7KhZBBePeVEr:-MeUTOmB7KhZBBePeVEs:b-ursfag) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L178)):*
> ```cpp
>                                   const core::Device &device,
>                                   core::Tensor &Sxy,
>                                   core::Tensor &mean_t,
> ```

`source_mean` and `target_mean` to avoid ambiguity for `mean_t` which looks similar to `scalar_t`.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 183 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTAJzBhig6NUsx1d-:-MeUTAJzBhig6NUsx1d0:bryunsg) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L183)):*
> ```cpp
>     // Calculating mean_s and mean_t, which are mean(x, y, z) of source and
>     // target points respectively.
>     std::vector<double> mean_1x7(7, 0.0);
> ```

Why `double`? Would `scalar_t` also work here?
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 220 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUSuWjEugP8PFcuDw_:-MeUSuWjEugP8PFcuDwa:b-s3has6) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L220)):*
> ```cpp
>             });
> 
>     for (int i = 0; i < 6; i++) {
> ```

nit: Prefer `++i` over `i++`. The former is, in theory, faster than the latter as it avoids one temporary copy.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 221 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUSjlh4CnIBWCysWY7:-MeUSjlh4CnIBWCysWY8:bvunx6n) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L221)):*
> ```cpp
> 
>     for (int i = 0; i < 6; i++) {
>         mean_1x7[i] = mean_1x7[i] / mean_1x7[6];
> ```

Check if `mean_1x7[6]` is `0` to avoid division-by-zero failures.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 277 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTbid62Y5hcmZaPQQ:-MeUTbid62Y5hcmZaPQR:bd4yku3) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L277)):*
> ```cpp
>     for (int i = 0, j = 0; j < 3; j++) {
>         for (int k = 0; k < 3; k++) {
>             sxy_ptr[j * 3 + k] = sxy_1x9[i++] / mean_1x7[6];
> ```

Check division. See comment above.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu, line 45 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUThPxDs_fALp5glVk:-MeUThPxDs_fALp5glVl:b-q64pkt) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu#L45)):*
> ```Cuda
> const int kThread1DUnit = 256;
> 
> template <typename scalar_t, typename funct_t>
> ```

See above.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu, line 79 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTs9j26h73iHA0CDy:-MeUTs9j26h73iHA0CDz:b-5gp5mm) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu#L79)):*
> ```Cuda
>     if (valid) {
>         // Dump J, r into JtJ and Jtr
>         reduction[0] += J_ij[0] * w * J_ij[0];
> ```

Is there any performance improvement when manually unrolling this loop? If not, the loops are easier to read and understand.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformImpl.h, line 85 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUUdPX-WCyQgn8g_CJ:-MeUUdPX-WCyQgn8g_CK:bxd8rl3) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformImpl.h#L85)):*
> ```objc
> }
> 
> template <>
> ```

We could ena [...]

2021-07-15 07:31 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3690)* status: all files reviewed, 18 unresolved discussions (waiting on @stotko and @yxlao)

___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 57 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUPqD6Ae67or6IB4U4:-MeczuuS5fdny4sjC0Hf:bqejsik) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L57)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Could you comment on why these macros are needed? Would it be possible to use `abs` (without `std::` namespace qualification) instead? There are also floating-point overloads defined that are prefixed with `f`, i.e. `fabs`. Would that work here?

Otherwise, I would recommend to define a set of `OPEN3D_HOST_DEVICE` annotated functions for all of these macros (except `OPEN3D_ATOMIC_ADD`.
</blockquote></details>

Done. Replaces Max, Min, Abs, Pow, Exp by fmax, fmin, fabs, pow, exp from `cmath`.
___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 74 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUQuxN4IP1m8kwIpXJ:-Med-IJb5sUUMcaT4bsc:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L74)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Put into `open3d` namespace and rename to `IsClose`, i.e. `OPEN3D_IS_CLOSE(...)` -> `open3d::IsClose(...)`. 
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.h, line 42 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeURPGP5_ZqFtPpJtnU:-Med-JFtEHsVBrsABq4Y:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransform.h#L42)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Please add documentation for the `TODO` part.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.h, line 55 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeURT7G0Ke9oNEYsSj2:-Med-JhV3z_H6D74hqav:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransform.h#L55)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 47 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeURpuP2J-KcfWDCB8d:-Med-KKf9nPYqBGJGwDv:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L47)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Perhaps `function_t` or `func_t`? `CPULauncher` etc. use the latter, so I would recommend that version.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 83 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUSRcI0WQo1teXi6b1:-Med-KyJ9JTdRV9qqOBi:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L83)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Is this a leftover from debugging? If it is not needed, then please remove that line.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 178 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTOmB7KhZBBePeVEr:-Med-LNg9dC2jE-VVTHu:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L178)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`source_mean` and `target_mean` to avoid ambiguity for `mean_t` which looks similar to `scalar_t`.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 183 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTAJzBhig6NUsx1d-:-Med-M9v2Oa7onCFNuoG:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L183)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Why `double`? Would `scalar_t` also work here?
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 220 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUSuWjEugP8PFcuDw_:-Med-RAHBT_1JUlU5cjV:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L220)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

nit: Prefer `++i` over `i++`. The former is, in theory, faster than the latter as it avoids one temporary copy.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 221 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUSjlh4CnIBWCysWY7:-Med2XEY18laYSNkBe8I:byjt2bg) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L221)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Check if `mean_1x7[6]` is `0` to avoid division-by-zero failures.
</blockquote></details>

Added check at `ComputeTransform.cpp` function.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 277 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTbid62Y5hcmZaPQQ:-Med2Uts-7Aj_Z9_GlSc:byjt2bg) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L277)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Check division. See comment above.
</blockquote></details>

Added check at `ComputeTransform.cpp` function.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu, line 45 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUThPxDs_fALp5glVk:-Med-UvJ3uPik8-N_qwj:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu#L45)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu, line 79 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTs9j26h73iHA0CDy:-Med2tHRCU7DgBXQBVBx:b-48hyh4) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu#L79)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Is there any performance improvement when manually unrolling this loop? If not, the loops are easier to read and understand.
</blockquote></details>

I previously had it in loop form, but it was not very clear as it fills the triangle matrix, so I unrolled the same for clarity. 

Previously:
```
                        for (int i = 0, j = 0; j < 6; j++) {
                            for (int k = 0; k <= j; k++) {
                                A_reduction[i] += J_ij[j] * w * J_ij[k];
                                i++;
                            }
                            A_reduction[21 + j] += J_I[j] * w * r;
                        }
                        A_reduction[27] [...]

2021-07-19 10:25 UTC, stotko requested changes
> Reviewed 12 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3690)* status: 24 of 25 files reviewed, 9 unresolved discussions (waiting on @reyanshsolis, @stotko, and @yxlao)

___
*[cpp/open3d/core/linalg/kernel/SVD3x3.h, line 808 at r3](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeyCZlE8II4PTyP4O8H:-MeyCZlE8II4PTyP4O8I:b-m55336) ([raw file](https://github.com/intel-isl/open3d/blob/f78dc6e2066865012ad9da680bccdde34ef9e995/cpp/open3d/core/linalg/kernel/SVD3x3.h#L808)):*
> ```objc
> 
>     Stmp5.f = 0.f;
>     Sch.f = __dsub_rn(Stmp5.f, Sa11.f);
> ```

Could you comment on the advantage of using the `__dsub_rn` intrinsic over the plain `-` operator? Will this generate better/faster machine code?
___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 60 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeyDAbD03Ea1pkdkOsN:-MeyDAbD03Ea1pkdkOsO:b5k8b7) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L60)):*
> ```objc
> #define OPEN3D_EXP(X) exp(X)
> #define OPEN3D_POW(X, Y) pow((X), (Y))
> #define ISNAN(X) isnan(X)
> ```

Can the `ISNAN` macro also be replaced like the other macros?
___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 65 at r3](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeyDXrl99aR0bC_z-in:-MeyDXrl99aR0bC_z-io:b2u7cn8) ([raw file](https://github.com/intel-isl/open3d/blob/f78dc6e2066865012ad9da680bccdde34ef9e995/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L65)):*
> ```objc
> namespace open3d {
> template <typename scalar_t, typename T>
> OPEN3D_HOST_DEVICE bool IsClose(const scalar_t &X,
> ```

`X` -> `x`, i.e. lowercase for all variables.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp, line 41 at r3](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeyE60W2L5lZXuzaFew:-MeyE60W2L5lZXuzaFex:bhv5yms) ([raw file](https://github.com/intel-isl/open3d/blob/f78dc6e2066865012ad9da680bccdde34ef9e995/cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp#L41)):*
> ```cpp
>                                      const core::Tensor &correspondence_indices,
>                                      const registration::RobustKernel &kernel) {
>     if (source_points.GetLength() == 0 || target_points.GetLength() == 0) {
> ```

See the discussion below.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 221 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUSjlh4CnIBWCysWY7:-MeyEIka75PmJ8Ov4YSZ:bco67q) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L221)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Added check at `ComputeTransform.cpp` function.
</blockquote></details>

Answering here to keep the discussion at a single place and avoid confusion:

Should we handle empty input point clouds as errors? This is more like a general question to come up with a consistent approach of doing this throughout the library.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu, line 79 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTs9j26h73iHA0CDy:-MeyGGWF24D6ukQgmcGB:b-bzif9h) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu#L79)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

I previously had it in loop form, but it was not very clear as it fills the triangle matrix, so I unrolled the same for clarity. 

Previously:
```
                        for (int i = 0, j = 0; j < 6; j++) {
                            for (int k = 0; k <= j; k++) {
                                A_reduction[i] += J_ij[j] * w * J_ij[k];
                                i++;
                            }
                            A_reduction[21 + j] += J_I[j] * w * r;
                        }
                        A_reduction[27] += r;
                        A_reduction[28] += 1;
                    }
```
Let me know your suggestion, which one you think is more clear?
</blockquote></details>

I think the loop is much easier to read and makes it easier to get the triangular structure. I would suggest to move `int i = 0` out of the `for` loop and define it before that loop.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformImpl.h, line 85 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUUdPX-WCyQgn8g_CJ:-MeyHGlP4A8lun_HlQNr:b-ngqncx) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformImpl.h#L85)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

added template prototype definition for float and double. 
</blockquote></details>

Does this exclude the unsupported types? It looks like that the `float` and `double` variants are just explicitly instantiated and whereas an `int` version could be implicitly instantiated, but will not print an error.


<!-- Sent from Reviewable.io -->

2021-07-20 16:02 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3690)* status: 20 of 26 files reviewed, 9 unresolved discussions (waiting on @stotko, @theNded, and @yxlao)

___
*[cpp/open3d/core/linalg/kernel/SVD3x3.h, line 808 at r3](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeyCZlE8II4PTyP4O8H:-Mf34YQd8Na-M6TXVRYM:b-ykahlj) ([raw file](https://github.com/intel-isl/open3d/blob/f78dc6e2066865012ad9da680bccdde34ef9e995/cpp/open3d/core/linalg/kernel/SVD3x3.h#L808)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Could you comment on the advantage of using the `__dsub_rn` intrinsic over the plain `-` operator? Will this generate better/faster machine code?
</blockquote></details>

well, it's a round-off operation. @thended used this implementation for SLAC, I just exposed the same, added support for double, and used this to add a device solver function, which will also be used in ColoredICP PR. So, he might be able to comment on this better.
___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 60 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeyDAbD03Ea1pkdkOsN:-Mf34DCu4dudEySf5daj:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L60)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Can the `ISNAN` macro also be replaced like the other macros?
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/GeometryMacros.h, line 65 at r3](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeyDXrl99aR0bC_z-in:-Mf34CRC-wZ3yBWz4evE:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f78dc6e2066865012ad9da680bccdde34ef9e995/cpp/open3d/t/geometry/kernel/GeometryMacros.h#L65)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`X` -> `x`, i.e. lowercase for all variables.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp, line 41 at r3](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeyE60W2L5lZXuzaFew:-Mf33rgm-m8_1grqZZ2O:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/f78dc6e2066865012ad9da680bccdde34ef9e995/cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp#L41)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See the discussion below.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 221 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUSjlh4CnIBWCysWY7:-Mf33Zc56xRg6wpHJLwm:bqehd56) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L221)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Answering here to keep the discussion at a single place and avoid confusion:

Should we handle empty input point clouds as errors? This is more like a general question to come up with a consistent approach of doing this throughout the library.
</blockquote></details>

Well, if we don't throw an error here, the error of `0 correspondences` will be thrown anyways. So, for ICP at least an empty point cloud must be treated as an error, imo.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu, line 79 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTs9j26h73iHA0CDy:-Mf33Vbf5gg1Bh93iHZU:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu#L79)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

I think the loop is much easier to read and makes it easier to get the triangular structure. I would suggest to move `int i = 0` out of the `for` loop and define it before that loop.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformImpl.h, line 85 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUUdPX-WCyQgn8g_CJ:-Mf2oY16-ypNXU_Vo4y1:b-cs2af8) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformImpl.h#L85)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Does this exclude the unsupported types? It looks like that the `float` and `double` variants are just explicitly instantiated and whereas an `int` version could be implicitly instantiated, but will not print an error.
</blockquote></details>

Added checks at `kernel/ComputeTransform.cpp` and there are also checks at`RegistrationICP`. 


<!-- Sent from Reviewable.io -->

2021-07-21 12:40 UTC, stotko approved these changes
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3690)* status: all files reviewed, 10 unresolved discussions (waiting on @reyanshsolis, @theNded, and @yxlao)

___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp, line 53 at r4](https://reviewable.io/reviews/intel-isl/open3d/3690#-Mf82ESa4NsvZgdXPUgZ:-Mf82ESb6hNgIQoPvoSW:b-g6586x) ([raw file](https://github.com/intel-isl/open3d/blob/1a541ef3e4b9bad908669385ce8636dabf9adff1/cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp#L53)):*
> ```cpp
> 
>     if (source_points.GetLength() == 0 || target_points.GetLength() == 0) {
>         utility::LogError("PointCloud is Empty.");
> ```

nit: `"Source and/or target point cloud is empty."`
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp, line 56 at r4](https://reviewable.io/reviews/intel-isl/open3d/3690#-Mf82JiP3QgPqeHI2F53:-Mf82JiP3QgPqeHI2F54:b-t0aq11) ([raw file](https://github.com/intel-isl/open3d/blob/1a541ef3e4b9bad908669385ce8636dabf9adff1/cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp#L56)):*
> ```cpp
>     }
>     if (correspondence_indices.GetLength() == 0) {
>         utility::LogError("0 correspondence present.");
> ```

nit: `"No correspondences present."`
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp, line 102 at r4](https://reviewable.io/reviews/intel-isl/open3d/3690#-Mf82mO-4LFLbPn1phGD:-Mf82mO-4LFLbPn1phGE:b-q64pkt) ([raw file](https://github.com/intel-isl/open3d/blob/1a541ef3e4b9bad908669385ce8636dabf9adff1/cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp#L102)):*
> ```cpp
> 
>     if (source_points.GetLength() == 0 || target_points.GetLength() == 0) {
>         utility::LogError("PointCloud is Empty.");
> ```

See above.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp, line 105 at r4](https://reviewable.io/reviews/intel-isl/open3d/3690#-Mf82nGP5EjkfJbeQl2Z:-Mf82nGP5EjkfJbeQl2_:b-q64pkt) ([raw file](https://github.com/intel-isl/open3d/blob/1a541ef3e4b9bad908669385ce8636dabf9adff1/cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp#L105)):*
> ```cpp
>     }
>     if (correspondence_indices.GetLength() == 0) {
>         utility::LogError("0 correspondence present.");
> ```

See above.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 221 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUSjlh4CnIBWCysWY7:-Mf838Uu63rjJVYVqret:buxy0nt) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L221)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Well, if we don't throw an error here, the error of `0 correspondences` will be thrown anyways. So, for ICP at least an empty point cloud must be treated as an error, imo.
</blockquote></details>

In that case, we could add a comment here stating that division-by-zero cannot happen here as the sizes are already checked.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 277 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTbid62Y5hcmZaPQQ:-Mf83fm6A3xcC6TGjsvw:b-q64pkt) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L277)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Added check at `ComputeTransform.cpp` function.
</blockquote></details>

See above.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 88 at r4](https://reviewable.io/reviews/intel-isl/open3d/3690#-Mf82q8jEnhcSvunknV4:-Mf82q8jEnhcSvunknV5:b-93c3el) ([raw file](https://github.com/intel-isl/open3d/blob/1a541ef3e4b9bad908669385ce8636dabf9adff1/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L88)):*
> ```cpp
>                         // Dump J, r into JtJ and Jtr
>                         int i = 0;
>                         for (int j = 0; j < 6; j++) {
> ```

`++j` instead of `j++` (same for `k`)
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 91 at r4](https://reviewable.io/reviews/intel-isl/open3d/3690#-Mf82wL0Es7gPqfo18CZ:-Mf82wL0Es7gPqfo18C_:b-umihfx) ([raw file](https://github.com/intel-isl/open3d/blob/1a541ef3e4b9bad908669385ce8636dabf9adff1/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L91)):*
> ```cpp
>                             for (int k = 0; k <= j; k++) {
>                                 A_reduction[i] += J_ij[j] * w * J_ij[k];
>                                 i++;
> ```

`++i;`
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu, line 79 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTs9j26h73iHA0CDy:-Mf83o8g3VNmW8ADnxA2:b-xp5all) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu#L79)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

See comments in `ComputeTransformCPU.cpp`


<!-- Sent from Reviewable.io -->

2021-07-21 18:23 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3690)* status: 13 of 26 files reviewed, 8 unresolved discussions (waiting on @stotko, @theNded, and @yxlao)

___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp, line 53 at r4](https://reviewable.io/reviews/intel-isl/open3d/3690#-Mf82ESa4NsvZgdXPUgZ:-Mf9I-NHC0w_IZ9uqZf2:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1a541ef3e4b9bad908669385ce8636dabf9adff1/cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp#L53)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

nit: `"Source and/or target point cloud is empty."`
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp, line 56 at r4](https://reviewable.io/reviews/intel-isl/open3d/3690#-Mf82JiP3QgPqeHI2F53:-Mf9I0Mz7hUz7rNqoQ84:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1a541ef3e4b9bad908669385ce8636dabf9adff1/cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp#L56)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

nit: `"No correspondences present."`
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp, line 102 at r4](https://reviewable.io/reviews/intel-isl/open3d/3690#-Mf82mO-4LFLbPn1phGD:-Mf9I2qsB5aAzotdh9t5:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1a541ef3e4b9bad908669385ce8636dabf9adff1/cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp#L102)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp, line 105 at r4](https://reviewable.io/reviews/intel-isl/open3d/3690#-Mf82nGP5EjkfJbeQl2Z:-Mf9I4VT6DbxV996_cXh:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1a541ef3e4b9bad908669385ce8636dabf9adff1/cpp/open3d/t/pipelines/kernel/ComputeTransform.cpp#L105)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 221 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUSjlh4CnIBWCysWY7:-Mf9I8zf2IZLBoncN0Ew:b-ilfmqn) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L221)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

In that case, we could add a comment here stating that division-by-zero cannot happen here as the sizes are already checked.
</blockquote></details>

Added Check. (the prev. check was not sufficient, as for the case where all correspondences is -1 was not covered).
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 277 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTbid62Y5hcmZaPQQ:-Mf9IhL05MwmZt1CcE5U:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L277)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 88 at r4](https://reviewable.io/reviews/intel-isl/open3d/3690#-Mf82q8jEnhcSvunknV4:-Mf9I7O101fL6BcP6rYB:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1a541ef3e4b9bad908669385ce8636dabf9adff1/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L88)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`++j` instead of `j++` (same for `k`)
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp, line 91 at r4](https://reviewable.io/reviews/intel-isl/open3d/3690#-Mf82wL0Es7gPqfo18CZ:-Mf9I7jXD-alhRewxRx0:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/1a541ef3e4b9bad908669385ce8636dabf9adff1/cpp/open3d/t/pipelines/kernel/ComputeTransformCPU.cpp#L91)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`++i;`
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu, line 79 at r2](https://reviewable.io/reviews/intel-isl/open3d/3690#-MeUTs9j26h73iHA0CDy:-Mf9IjNU8L6djxVKIoWd:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/610f2518fc3a52e370bac20796057a71585a2e58/cpp/open3d/t/pipelines/kernel/ComputeTransformCUDA.cu#L79)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See comments in `ComputeTransformCPU.cpp`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-22 07:09 UTC, merged