Introduce CUDAScopedStream class for Multi-Stream Support
intel-isl/Open3D pull request #3732
Opened 2021-07-12 17:52 UTC by stotko

Highlights:
- Add `CUDAScopedStream` class for setting the global internal per-thread stream state. Preliminary Multi-Device Support is also included by making use of `CUDADeviceSwitcher`.
- Add `cuda::{Get,Set}Stream` functions to access the global state. These functions are used to implement `CUDAScopedStream`.
- Add `cuda::{Get,Set}Device` to mirror the stream API. This makes `CUDADeviceSwitcher`'s implementation look similar to `CUDAScopedStream`. It further allows to hide the implementation detail that CUDA is already capable of managing the device state internally.
- Make all of Open3D's kernel calls aware of the current stream.
- Add unit tests to check thread locality.

Future work:
- Unify stream usage in ML ops to take advantage of `CUDAScopedStream`.

2021-07-14 05:26 UTC, yxlao approved these changes
> Reviewed 12 of 17 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3732)* status: all files reviewed, 3 unresolved discussions (waiting on @benjaminum, @ssheorey, and @stotko)

___
*[cpp/open3d/core/CUDAState.cuh, line 137 at r2](https://reviewable.io/reviews/intel-isl/open3d/3732#-MeYP4j9DtdnLZtBcUas:-MeYP4j9DtdnLZtBcUat:bzhv38f) ([raw file](https://github.com/intel-isl/open3d/blob/d7430fa95ad66d845244ab654073c6f4f8ea0aa1/cpp/open3d/core/CUDAState.cuh#L137)):*
> ```Cuda
>     ~CUDAScopedStream() { cuda::SetStream(prev_stream_); }
> 
>     CUDAScopedStream(CUDAScopedStream const&) = delete;
> ```

nit: `const CUDAScopedStream &` to be consistent with the rest.
___
*[cpp/open3d/core/CUDAUtils.cpp, line 93 at r2](https://reviewable.io/reviews/intel-isl/open3d/3732#-MeYNPhl82jY8gH6bY4e:-MeYNPhl82jY8gH6bY4f:b-bqsoqw) ([raw file](https://github.com/intel-isl/open3d/blob/d7430fa95ad66d845244ab654073c6f4f8ea0aa1/cpp/open3d/core/CUDAUtils.cpp#L93)):*
> ```cpp
>     void Set(cudaStream_t stream) { stream_ = stream; }
> 
>     static cudaStream_t Default() { return (cudaStream_t)0; }
> ```

nit: `static_cast<cudaStream_t>`
___
*[cpp/open3d/ml/Helper.h, line 108 at r2](https://reviewable.io/reviews/intel-isl/open3d/3732#-MeYTICO7nreMbl1DiAE:-MeYTICO7nreMbl1DiAF:b-tb3yme) ([raw file](https://github.com/intel-isl/open3d/blob/d7430fa95ad66d845244ab654073c6f4f8ea0aa1/cpp/open3d/ml/Helper.h#L108)):*
> ```objc
> 
>         if (err_get_string == CUDA_SUCCESS) {
>             fprintf(stderr, "%s:%d CUDA driver error: %s", file, line,
> ```

Possible to convert this to `utility::Logxxx()`? Previously the ML Ops is independent from `libOpen3D`, but now`libOpen3D` is linked into the ML Ops library.


<!-- Sent from Reviewable.io -->

2021-07-14 09:41 UTC, stotko reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3732)* status: 8 of 33 files reviewed, 1 unresolved discussion (waiting on @benjaminum, @ssheorey, and @yxlao)

___
*[cpp/open3d/core/CUDAState.cuh, line 137 at r2](https://reviewable.io/reviews/intel-isl/open3d/3732#-MeYP4j9DtdnLZtBcUas:-MeZNkSZ-2_FOOu_-xQH:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d7430fa95ad66d845244ab654073c6f4f8ea0aa1/cpp/open3d/core/CUDAState.cuh#L137)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: `const CUDAScopedStream &` to be consistent with the rest.
</blockquote></details>

Done.
___
*[cpp/open3d/core/CUDAUtils.cpp, line 93 at r2](https://reviewable.io/reviews/intel-isl/open3d/3732#-MeYNPhl82jY8gH6bY4e:-MeZNnj12saMfvogb-zZ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/d7430fa95ad66d845244ab654073c6f4f8ea0aa1/cpp/open3d/core/CUDAUtils.cpp#L93)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: `static_cast<cudaStream_t>`
</blockquote></details>

Done.
___
*[cpp/open3d/ml/Helper.h, line 108 at r2](https://reviewable.io/reviews/intel-isl/open3d/3732#-MeYTICO7nreMbl1DiAE:-MeZNs8f9XjynWtf0_Pm:b-hevbm4) ([raw file](https://github.com/intel-isl/open3d/blob/d7430fa95ad66d845244ab654073c6f4f8ea0aa1/cpp/open3d/ml/Helper.h#L108)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Possible to convert this to `utility::Logxxx()`? Previously the ML Ops is independent from `libOpen3D`, but now`libOpen3D` is linked into the ML Ops library.
</blockquote></details>

Done. I also applied some additional cleanups in `Helper.h`, `CUDAUtils.h`and `CUDAState.cuh`.


<!-- Sent from Reviewable.io -->

2021-07-14 13:04 UTC, benjaminum requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3732)* status: 8 of 33 files reviewed, 3 unresolved discussions (waiting on @ssheorey, @stotko, and @yxlao)

___
*[cpp/open3d/ml/Helper.h, line 101 at r4](https://reviewable.io/reviews/intel-isl/open3d/3732#-Me_6MFN1ie9n0DNHutV:-Me_6MFO3t6aP7uNKX_x:b-dr5iye) ([raw file](https://github.com/intel-isl/open3d/blob/9e434b303c58bde56caf80174e3989626e7b78ec/cpp/open3d/ml/Helper.h#L101)):*
> ```objc
> }
> 
> class CUDAScopedDeviceStream {
> ```

Where is this used? Is this the only file where we need the driver API?
___
*[cpp/open3d/ml/contrib/Nms.cu, line 168 at r4](https://reviewable.io/reviews/intel-isl/open3d/3732#-Me_5uXoALrRChwAqRSH:-Me_5uXoALrRChwAqRSI:b-d71rxr) ([raw file](https://github.com/intel-isl/open3d/blob/9e434b303c58bde56caf80174e3989626e7b78ec/cpp/open3d/ml/contrib/Nms.cu#L168)):*
> ```Cuda
>                 utility::DivUp(n, NMS_BLOCK_SIZE));
>     dim3 threads(NMS_BLOCK_SIZE);
>     NmsKernel<<<blocks, threads, 0, core::cuda::GetStream()>>>(
> ```

The Nms op should get the stream from tensorflow or pytorch. Looks like we did not pass this information from the op wrappers to here.


<!-- Sent from Reviewable.io -->

2021-07-14 14:24 UTC, stotko commented
Re-requesting reviews as I decided to to merge further changes into this PR:
- Rename `CUDADeviceSwitcher` to `CUDAScopedDevice`
- Add support for stream-based allocation (introduced in CUDA 11.2) and copy functions in CUDAMemoryManager.

2021-07-14 14:54 UTC, benjaminum requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3732)* status: 8 of 39 files reviewed, 3 unresolved discussions (waiting on @ssheorey, @stotko, and @yxlao)

___
*[cpp/open3d/ml/Helper.h, line 101 at r4](https://reviewable.io/reviews/intel-isl/open3d/3732#-Me_6MFN1ie9n0DNHutV:-Me_SrND0BL2WT71aLz3:b9zl6fu) ([raw file](https://github.com/intel-isl/open3d/blob/9e434b303c58bde56caf80174e3989626e7b78ec/cpp/open3d/ml/Helper.h#L101)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

This is a combination of `CUDAScopedDevice` and `CUDAScopedStream` where the device information is inferred from the stream via the CUDA driver API. Since we cannot directly put this into the core library, due to linking issues, this class is only exposed in the ML ops. It is currently not used, but may be useful in the future.

Is this combined functionality helpful in the context of the ML ops or are the individual wrappers enough to handle all use cases?
</blockquote></details>

I think the scoped stream is the most important class. It will allow us to use our Tensor library within the ops.
I assume that the current device is already set by tf/torch when an operator is called. I agree that having a way to infer the device could become handy but I am not sure if there are implications with linking the driver api.
___
*[cpp/open3d/ml/contrib/Nms.cu, line 168 at r4](https://reviewable.io/reviews/intel-isl/open3d/3732#-Me_5uXoALrRChwAqRSH:-Me_VGSj3HsZ-sDPDLBA:b-jb4cqv) ([raw file](https://github.com/intel-isl/open3d/blob/9e434b303c58bde56caf80174e3989626e7b78ec/cpp/open3d/ml/contrib/Nms.cu#L168)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Could you provide some pointers on how to approach this? I tried

TensorFlow: `auto device = context->eigen_gpu_device();` Then use`device.stream()`.
PyTorch: `auto stream = at::cuda::getCurrentCUDAStream();`

but they only seem to be available in `.cu` files and I get some strange compiler errors instead. Is there some difference in the design of the Nms op compared to the others?
</blockquote></details>

Yes, we need to split the op up in multiple compilation units similar to the other ops. For tensorflow we already have the right structure but for torch it is missing.


<!-- Sent from Reviewable.io -->

2021-07-14 17:37 UTC, stotko reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3732)* status: 6 of 40 files reviewed, 3 unresolved discussions (waiting on @benjaminum, @ssheorey, and @yxlao)

___
*[cpp/open3d/ml/Helper.h, line 101 at r4](https://reviewable.io/reviews/intel-isl/open3d/3732#-Me_6MFN1ie9n0DNHutV:-Mea3hDD8Vq0VQ5Rp5cQ:b-pkt42s) ([raw file](https://github.com/intel-isl/open3d/blob/9e434b303c58bde56caf80174e3989626e7b78ec/cpp/open3d/ml/Helper.h#L101)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

I think the scoped stream is the most important class. It will allow us to use our Tensor library within the ops.
I assume that the current device is already set by tf/torch when an operator is called. I agree that having a way to infer the device could become handy but I am not sure if there are implications with linking the driver api.
</blockquote></details>

Yes, as long as this assumption holds, `CUDAScopedStream` should be enough. Unfortunately, there is no corresponding API in the runtime library to infer the device, so we must use the driver API. If this may lead to any blockers in the future, we can remove `CUDAScopedDeviceStream` for now and consider adding it at a later point in time if we observe that we need it. Any preference on how we should proceed?
___
*[cpp/open3d/ml/contrib/Nms.cu, line 168 at r4](https://reviewable.io/reviews/intel-isl/open3d/3732#-Me_5uXoALrRChwAqRSH:-Mea36lN76Pk3BvKF2E2:bi6jie5) ([raw file](https://github.com/intel-isl/open3d/blob/9e434b303c58bde56caf80174e3989626e7b78ec/cpp/open3d/ml/contrib/Nms.cu#L168)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Yes, we need to split the op up in multiple compilation units similar to the other ops. For tensorflow we already have the right structure but for torch it is missing.
</blockquote></details>

Reverted all applications of `cuda::GetStream()` in the ML ops. I would like to unblock this PR and suggest to improve Nms and any other affected op in a separate PR.


<!-- Sent from Reviewable.io -->

2021-07-14 17:45 UTC, benjaminum approved these changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3732)* status: 6 of 40 files reviewed, 3 unresolved discussions (waiting on @ssheorey, @stotko, and @yxlao)

___
*[cpp/open3d/ml/Helper.h, line 101 at r4](https://reviewable.io/reviews/intel-isl/open3d/3732#-Me_6MFN1ie9n0DNHutV:-Mea6SWoBfqQw7xsyXkA:bpmbe25) ([raw file](https://github.com/intel-isl/open3d/blob/9e434b303c58bde56caf80174e3989626e7b78ec/cpp/open3d/ml/Helper.h#L101)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Yes, as long as this assumption holds, `CUDAScopedStream` should be enough. Unfortunately, there is no corresponding API in the runtime library to infer the device, so we must use the driver API. If this may lead to any blockers in the future, we can remove `CUDAScopedDeviceStream` for now and consider adding it at a later point in time if we observe that we need it. Any preference on how we should proceed?
</blockquote></details>

It is just a header file. I don't mind keeping it.
___
*[cpp/open3d/ml/contrib/Nms.cu, line 168 at r4](https://reviewable.io/reviews/intel-isl/open3d/3732#-Me_5uXoALrRChwAqRSH:-Mea6CEE4Ue4PCk-vfwg:b-pqov82) ([raw file](https://github.com/intel-isl/open3d/blob/9e434b303c58bde56caf80174e3989626e7b78ec/cpp/open3d/ml/contrib/Nms.cu#L168)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Reverted all applications of `cuda::GetStream()` in the ML ops. I would like to unblock this PR and suggest to improve Nms and any other affected op in a separate PR.
</blockquote></details>

makes sense


<!-- Sent from Reviewable.io -->

2021-07-14 21:43 UTC, ssheorey reviewed
Can we add stream support to the NPP image processing operations as well?
eg: Current NPP calls:
https://github.com/intel-isl/Open3D/blob/e0a6201554fa7a8e8c0038181dd68b76929a7203/cpp/open3d/t/geometry/kernel/NPPImage.cpp#L101

NPP>=v10.1 introduces a new API for application managed stream context that we should use. The function calls are now `*_Ctx()` and take an extra argument that can be added to the NPP_ARGS macro.

The older API was easier to use with a `npp{Get,Set}Stream()`.

OK to do in another PR.

> Reviewed 1 of 8 files at r2, 1 of 25 files at r3, 1 of 1 files at r4, 4 of 9 files at r5, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3732#-:-MeavZD8D9R2SBinl8r3:b-625aid)* status: 13 of 40 files reviewed, 8 unresolved discussions (waiting on @stotko and @yxlao)

___
*[cpp/benchmarks/core/MemoryManager.cpp, line 72 at r6](https://reviewable.io/reviews/intel-isl/open3d/3732#-Meakstl7gjUd-sXe3Or:-Meakstl7gjUd-sXe3Os:buin21y) ([raw file](https://github.com/intel-isl/open3d/blob/58097fbaecaac7459e97c3ec8f5c8d8a231675da/cpp/benchmarks/core/MemoryManager.cpp#L72)):*
> ```
> Synchronize(
> ```
nit: `static`
___
*[cpp/open3d/core/CUDAState.cuh, line 114 at r6](https://reviewable.io/reviews/intel-isl/open3d/3732#-MeapUn32wnxvdP4_9LF:-MeapUn32wnxvdP4_9LG:b-o3shh6) ([raw file](https://github.com/intel-isl/open3d/blob/58097fbaecaac7459e97c3ec8f5c8d8a231675da/cpp/open3d/core/CUDAState.cuh#L114)):*
> ```Cuda
> class CUDAScopedStream {
> public:
>     explicit CUDAScopedStream(cudaStream_t stream)
> ```

We can simplify usage by making `stream` optional. If stream is not provided we create a new stream in the ctor. The user doesn't need to track streams for simple code.
___
*[cpp/open3d/core/CUDAUtils.h, line 103 at r6](https://reviewable.io/reviews/intel-isl/open3d/3732#-MeariV9DPh19ew0GnAQ:-MeariV9DPh19ew0GnAR:b-wuwkv) ([raw file](https://github.com/intel-isl/open3d/blob/58097fbaecaac7459e97c3ec8f5c8d8a231675da/cpp/open3d/core/CUDAUtils.h#L103)):*
> ```objc
> 
> #ifdef BUILD_CUDA_MODULE
> ```

I would suggest only providing the `cudaScoped{Device,Stream}` APIs and not providing these additional `Set` APIs. Two ways of doing the same thing can cause user confusion. `Get` APIs are still useful.
___
*[cpp/open3d/core/CUDAUtils.cpp, line 97 at r6](https://reviewable.io/reviews/intel-isl/open3d/3732#-MeasjDg69XBI64cqhcp:-MeasjDg69XBI64cqhcq:b-iwweoe) ([raw file](https://github.com/intel-isl/open3d/blob/58097fbaecaac7459e97c3ec8f5c8d8a231675da/cpp/open3d/core/CUDAUtils.cpp#L97)):*
> ```cpp
>     return device;
> }
> ```

Consider not providing the `Set` APIs (see above).
___
*[cpp/tests/core/CUDAState.cpp, line 79 at r6](https://reviewable.io/reviews/intel-isl/open3d/3732#-MeaoeygBuHg7nRNzZvo:-MeaoeygBuHg7nRNzZvp:b-vdtc2) ([raw file](https://github.com/intel-isl/open3d/blob/58097fbaecaac7459e97c3ec8f5c8d8a231675da/cpp/tests/core/CUDAState.cpp#L79)):*
> ```cpp
>     std::vector<std::thread> threads;
> 
>     const int kIterations = 100000;
> ```

Can you comment on why we need a large `kIterations`?


<!-- Sent from Reviewable.io -->

2021-07-14 21:52 UTC, ssheorey reviewed
Also, Python bindings will be useful if a user wants to build their own pipeline in Python with Open3D components.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3732#-:-Meb--qW5C_j9ZTzM0Ve:b-1625k0)* status: 13 of 40 files reviewed, 8 unresolved discussions (waiting on @stotko and @yxlao)



<!-- Sent from Reviewable.io -->

2021-07-14 21:53 UTC, ssheorey reviewed
NPP stream context: https://docs.nvidia.com/cuda/npp/index.html#application_managed_stream_context

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3732#-:-Meb-XuU53QSysua70AR:b-zfqmhp)* status: 13 of 40 files reviewed, 8 unresolved discussions (waiting on @stotko and @yxlao)



<!-- Sent from Reviewable.io -->

2021-07-15 07:43 UTC, yxlao approved these changes
> Reviewed 19 of 25 files at r3, 1 of 1 files at r4, 8 of 9 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3732)* status: all files reviewed, 7 unresolved discussions (waiting on @stotko)



<!-- Sent from Reviewable.io -->

2021-07-16 09:17 UTC, yxlao commented
Merging #3732 for now, and @stotko will address @ssheorey 's remaining comments in a separate PR.

2021-07-16 09:18 UTC, merged